### ISSUE TITLE
Can not remove added identifier first option

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14598] opened 2022-08-07 16:18 UTC
**Describe the issue:**
Can not remove added identifier first option in  console

**How to reproduce:**
1. Login to console
2. Create application
3. Navigate to application edit ->Sign in method
4. Select one of the option and navigate to the sign-in methods edit page
5. Click add authenticator and add identifier first
6. Click remove button to remove the identifier option

Identifier option should be removed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by IsuraD** [comment] 2022-08-07 17:18
This is reproducible. This could happens due to some validations we are doing to check the authenticators in the second step. For example, if MagicLink is there in the second step, we shouldn't be able to remove the Identifier First from the first step. 

However, we can use the **Revert to default** option as an alternative.

**Comment by brionmario** [comment] 2022-08-08 06:04
A NPE was hitting in a validation when deleting the identifier first handler.


<img width="758" alt="Screenshot 2022-08-08 at 11 12 08" src="https://user-images.githubusercontent.com/25959096/183347224-783c02e4-73f3-40b8-a27a-6e25d0f36a89.png">

Fixed with https://github.com/wso2/identity-apps/pull/3308

**Closed** 2022-08-08 06:36 UTC
Labels: ui, Priority/Highest, Severity/Critical, bug, console, UI Component/Application Management, QA-Reported, 6.0.0-rc-testing
