### ISSUE TITLE
When a google account gets provisioned “username” is internally derived by trimming from the email received

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#18129] opened 2023-11-28 07:13 UTC
**Describe the issue:**
$subject

<img width="617" alt="Screenshot 2023-11-28 at 12 42 32" src="https://github.com/wso2/product-is/assets/25428696/7582cb84-b880-4ca0-859b-840f15a4980a">

**Expected behavior:**
username should be mapped to the username claim

**Comment by aaujayasena** [comment] 2023-11-30 06:10
Shall we update the status. @mpmadhavig

**Comment by mpmadhavig** [comment] 2023-11-30 06:14
The fix is yet to be finalized.

**Comment by ayshsandu** [comment] 2023-12-01 04:50
Same issue is faced with SAML federated IdP flow as well.

**Comment by mpmadhavig** [comment] 2023-12-01 04:55
The root cause for this behavior is when email as username flag is not enabled, when generating the local user's  username using the subject value sent by the IDP, if there is a part after the @ sign, it will be removed assuming it is the tenant domain of the user. This can be avoided by the below fixes.

1. Fix this particular issue by checking if the user is federated and using the IDP sent username as it is for the local username. https://github.com/wso2/carbon-identity-framework/pull/5237
    - Problem with this issue is, then there will be users in the system whose username is an email and flows like recovery will break for these users.
2. Enable email as Username by default.

**Comment by ayshsandu** [comment] 2023-12-01 13:35
> * Problem with this issue is, then there will be users in the system whose username is an email and flows like recovery will break for these users.
@mpmadhavig can you please elaborate on how these flows get broken? 

> 2\. Enable email as Username by default.
This will not be an option, there are cases where the username can be of any format including @ in the username value but not necessary to mandate all the usernames in the system to email format.

**Comment by mpmadhavig** [comment] 2023-12-02 03:55
> > * Problem with this issue is, then there will be users in the system whose username is an email and flows like recovery will break for these users.
> 
> @mpmadhavig can you please elaborate on how these flows get broken?
> 
When the email as username flag is disabled, as we assume the username of the user will be non-email type, everywhere we execute getTenantAwareUsername it will try to identify the user with the username part of the email assuming email provider part is the tenant domain.

**Comment by mpmadhavig** [comment] 2023-12-09 08:23
After furthermore analysis, the following cases need to addressed in JIT provisioning flow.

- Prompt for username, password and consent
    - Username input field doesn't take an email address as the username.
    - Provisions successfully when a compatible username is added.
- Prompt for password and consent
    - Username is been taken as the username part of email.
    - Provisions successfully with invalid username.
- Prompt for consent
    - Username is been taken as the username part of email.
    - Provisions successfully with invalid username.
- Provision silently
    - Username is been taken as the username part of email.
    - Provisions successfully with invalid username.

**Comment by mpmadhavig** [comment] 2023-12-11 15:00
Tested all the above mentioned flows. Issue will get fixed with the below PRs.
- https://github.com/wso2/carbon-identity-framework/pull/5237
- https://github.com/wso2/identity-apps/pull/5029

**Closed** 2023-12-14 13:43 UTC
Labels: Severity/Blocker, bug, backend, U2, Affected/7.0.0-beta2
