### ISSUE TITLE
Error at  role permission

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18040] opened 2023-11-22 08:47 UTC
**Describe the issue:**
Error at role permission.

<img width="928" alt="Screenshot 2023-11-22 at 14 02 10" src="https://github.com/wso2/product-is/assets/39077751/e20d9cf4-43e4-4117-ba44-2243d581b431">

https://github.com/wso2/product-is/assets/39077751/7d90ff10-0cb7-498d-840f-2d4ba09582ed

**How to reproduce:**
1. Login to console
2. Navigate to API resource
3. Create API resource and assign permission
4. Create application
5. Navigate to API resource section and add API resource. 
6. Navigate to the application role tab and create  role
7. Assign permission to role
8. Navigate to the role section and click edit on created role
9. Navigate to permission tab

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment] 2023-11-22 09:11
I could observe the error if I try to go to the permissions tab immediately after creating the role. But after a little while, error is no longer visible.

**Comment by SujanSanjula96** [comment] 2023-11-22 09:30
This can be reproduced when going to permission section for the first time in new window. Should be an issue related to initial state.

**Comment by pavinduLakshan** [comment] 2023-11-29 11:30
Duplicate of https://github.com/wso2/product-is/issues/18039

**Closed** 2023-11-29 11:30 UTC
Labels: ui, Priority/Highest, Resolution/Duplicate, Severity/Critical, bug, QA-Reported, Application Roles, Affected/7.0.0-beta
