### ISSUE TITLE
Error Saving / Updating an Entitlement (XACML) policy that uses the “equals-with-regexp-match" or “greater-than-and-less-than"

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/product-is#7232] opened 2020-01-07 09:36 UTC
**Issue:** Saving / Updating an Entitlement (XACML) policy that uses the “equals-with-regexp-match" or “greater-than-and-less-than" condition option will result in an error.

**Environment:** WSO2 Identity Server 5.8.0 and 5.9.0 using https://github.com/wso2/docker-is

**Using “equals-with-regexp-match" condition option:**
![image](https://user-images.githubusercontent.com/8591787/71884774-e8812800-3173-11ea-9478-b6bd7d1ee986.png)

_Error:_

![image](https://user-images.githubusercontent.com/8591787/71884825-0189d900-3174-11ea-9ea3-dadf707c8462.png)

_Error Log:_ 
```
ERROR {org.wso2.carbon.identity.entitlement.EntitlementUtil} -  XACML policy is not valid according to the schema :cvc-complex-type.2.4.b: The content of element 'Condition' is not complete. One of '{"urn:oasis:names:tc:xacml:3.0:core:schema:wd-17":Expression}' is expected.
```
 
**Using “greater-than-and-less-than" condition option:**

![image](https://user-images.githubusercontent.com/8591787/71884883-21b99800-3174-11ea-8ba6-1dd221365492.png)

_Error_

![image](https://user-images.githubusercontent.com/8591787/71884910-2e3df080-3174-11ea-8b4e-bb7eced0bf2a.png)
  
_Error log_
No error log

**Comment by emswbandara** [comment] 2020-01-30 05:27
We have tested the above two functions locally and please find the analysis below.

1. equals-with-regexp-match
This expects a java regexp and the regexp expression should be embedded inside curly brackets {} as per [1].

Ex :
{ ^([a-zA-Z0-9_.-])+@wso2.com }

2. greater-than-and-less-than
For this there should be two values. And the two values should be separated by comma [1].

When we give the values in expected format it is working as expected. Since this is not a bug in our product, we will close this issue. Please raise if you have any concerns. 

[1] https://is.docs.wso2.com/en/next/learn/creating-a-xacml-policy/

**Closed by emswbandara** 2020-01-30 05:27 UTC
Labels: Priority/Normal, Severity/Critical, Type/Bug, WUM
