### ISSUE TITLE
Webauthn(fido2)Doesn't work with ff

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7229] opened 2020-01-06 22:38 UTC
I tried to register a webauthn credential in ff and it failed with an error.
Product Version: IS 5.10-alpha
FF version: 71.0 (64-bit)
Error: [2020-01-06 14:28:54,086] [11c2a8c6-801f-463e-abc5-a67541744c07] ERROR {org.wso2.carbon.identity.application.authenticator.fido2.endpoint.impl.FinishRegistrationApiServiceImpl} - Unexpected server exception while finishing FIDO2 device registration with challenge response: {"credential":{"id":"AAhM5l06a8_PSpm135O7XhjYv2y9G8b7BGGrMgdDqMAHQL8gZfJDIxptxHKBE5cZrgFnfFTuETM_5_bzVagwCjZ73FLrTFssNtGmgosWtPIm7ZrOdJeImjyazAyZDpOtWvrnCo610JfeIJcykgXdpqARUZEINLw5jEW0tT1nwE9zfIdfTeunQxTh45sofYTJaiGvLoYY15pbHgdOg5Glw8_7","response":{"attestationObject":"o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEYwRAIgQolBkuj_VBz6zkkE4uVBC9oC_twA4KhlbXPMvr-8cTICIG1aUumXN1NEyGWfsHyZ4Ikti5_6-I6RJRPRU-2VhG2WY3g1Y4FZATUwggExMIHZoAMCAQICBQCniWpjMAoGCCqGSM49BAMCMCExHzAdBgNVBAMTFkZpcmVmb3ggVTJGIFNvZnQgVG9rZW4wHhcNMjAwMTA1MjIyODUzWhcNMjAwMTA3MjIyODUzWjAhMR8wHQYDVQQDExZGaXJlZm94IFUyRiBTb2Z0IFRva2VuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERhUHhzu_VXyJzxHUjwNGPPlhUDWnCPk3tluH602-iuUQ4rZcnxa-qQN4w8oGKfmwssUwA-MN1Z7ZZXd4DcY_PDAKBggqhkjOPQQDAgNHADBEAiATd6_Q7L3vxTttbDhcBwWpm6ti1Tm-_x8jYnqm6JV_oQIgf3taJK7vtAo69kMQP-e7yuIYkg-CpoMtAU_8dCWGNmRoYXV0aERhdGFZASZJlg3liA6MaHQ0Fw9kdmBbj-SuuaKGMseZXPO6gx2XY0EAAAAAAAAAAAAAAAAAAAAAAAAAAACiAAhM5l06a8_PSpm135O7XhjYv2y9G8b7BGGrMgdDqMAHQL8gZfJDIxptxHKBE5cZrgFnfFTuETM_5_bzVagwCjZ73FLrTFssNtGmgosWtPIm7ZrOdJeImjyazAyZDpOtWvrnCo610JfeIJcykgXdpqARUZEINLw5jEW0tT1nwE9zfIdfTeunQxTh45sofYTJaiGvLoYY15pbHgdOg5Glw8_7pQECAyYgASFYII3Xgd6LBFpwUZzQwUrC8pm0vIi8BbgmAKXxg-dN5R4gIlggm1UzaSLP8BNiQv_O4naCKb6S9OLywoj5sAgptfQAeQg","clientDataJSON":"eyJjaGFsbGVuZ2UiOiJMb0hKODVFeDVtMFc2TFQtN2R0TnZkN2JRc0NiZXF4dGRkOWdqMUgzQUlVIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6OTQ0MyIsInR5cGUiOiJ3ZWJhdXRobi5jcmVhdGUifQ"},"clientExtensionResults":{},"type":"public-key"},"requestId":"8MBdr81vqLrYxN7JKXYHpAi4EzelCvnB7Y5L89zVf2E"} org.wso2.carbon.identity.application.authenticator.fido2.exception.FIDO2AuthenticatorServerException: Server error occurred while adding FIDO2 device registration for username: admin@carbon.super
	at org.wso2.carbon.identity.application.authenticator.fido2.dao.FIDO2DeviceStoreDAO.addFIDO2RegistrationByUsername(FIDO2DeviceStoreDAO.java:324)
	at org.wso2.carbon.identity.application.authenticator.fido2.core.WebAuthnService.addFIDO2Registration(WebAuthnService.java:631)
	at org.wso2.carbon.identity.application.authenticator.fido2.core.WebAuthnService.finishFIDO2Registration(WebAuthnService.java:318)
	at org.wso2.carbon.identity.application.authenticator.fido2.endpoint.impl.FinishRegistrationApiServiceImpl.finishRegistrationPost(FinishRegistrationApiServiceImpl.java:47)
	at org.wso2.carbon.identity.application.authenticator.fido2.endpoint.FinishRegistrationApi.finishRegistrationPost(FinishRegistrationApi.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:93)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column """CREDENTIAL_ID"" VARCHAR(200) NOT NULL": "'AAhM5l06a8/PSpm135O7XhjYv2y9G8b7BGGrMgdDqMAHQL8gZfJDIxptxHKBE5cZrgFnfFTuETM/5/bzVagwCjZ73FLrTFssNtGmgosWtPIm7ZrOdJeImjyazAyZDpO... (216)"; SQL statement:
INSERT INTO FIDO2_DEVICE_STORE (TENANT_ID, DOMAIN_NAME, USER_NAME, TIME_REGISTERED, USER_HANDLE, CREDENTIAL_ID, PUBLIC_KEY_COSE, SIGNATURE_COUNT, USER_IDENTITY ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:441)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:824)
	at org.h2.command.dml.Insert.insertRows(Insert.java:175)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:250)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy53.execute(Unknown Source)
	at org.wso2.carbon.identity.application.authenticator.fido2.dao.FIDO2DeviceStoreDAO.addFIDO2RegistrationByUsername(FIDO2DeviceStoreDAO.java:319)
	... 57 more

**Comment by ajanthan** [comment] 2020-01-07 21:25
I have used ff software token for the testing.

**Comment by sachiniWettasinghe** [comment] 2020-01-23 06:07
@ajanthan, I have tested registering a webauthn credential with the same firefox version as mentioned above (71.0 (64-bit)) and I could not reproduce this issue. Could you please mention the steps followed to reproduce this issue? Were there any special steps followed in this use case?

**Comment by ajanthan** [comment] 2020-01-24 19:25
@sachiniWettasinghe I haven't used a hardware token instead I have used "firefox softtoken" as mentioned [here](https://stackoverflow.com/a/54093137)

**Comment by IsuraD** [comment] 2022-08-02 05:30
The flow works fine with Fido2 hardware tokens. Hence closing the issue.

**Closed by IsuraD** 2022-08-02 05:30 UTC
Labels: Priority/Normal, bug, 6.0.0-bug-fixing
