### ISSUE TITLE
No consent asked for requested user attributes in the login flow (tested with SAML SP)

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4741] opened 2019-03-24 03:28 UTC
1. Create an SP (SAML) - with no requested attributes
2. Login.
3. Update the SP and add Email as a requested attribute.
4. No consent prompted for the Email during the login flow.

**Comment by malithie** [comment] 2019-04-02 02:21
@nilasini , This should be due to pre-consented requested claims. Can you confirm.

**Comment by nilasini** [comment] 2019-04-02 03:53
@malithie Yes this issue is due to pre-consented requested claims. According to the implementation, this is expected behavior. 
Please refer \[1] for more details on this.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Comment by nilasini** [comment] 2019-04-09 04:54
This issue will be tracked with the doc issue \[1] hence closing the issue.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Closed by nilasini** 2019-04-09 04:54 UTC
Labels: Affected/5.8.0-Alpha2, Complexity/High, Component/Consent, Priority/High, Severity/Critical, Type/Bug
