### ISSUE TITLE
Unable to configure tenant-wise EmailOTP notifications

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#13030] opened 2022-01-24 22:37 UTC
**Describe the issue:**
As per [1], it is possible to have tenant-based event adapter configurations and as per [2], is it possible to have tenant-based authenticator configurations. With those both features enabled you could have one tenant sending emails with Gmail API, another with SendGrid and another one with a SMTP server.

This works as expected for event based notifications such as account confirmation, account (un)locked, password reset, etc. but it does not work for EmailOTP notifications even when the EmailOTP Authenticator has been configured to use event based notifications, i.e:
```
<AuthenticatorConfig name="EmailOTP" enabled="true">
    ...
    <Parameter name="useEventHandlerBasedEmailSender">true</Parameter>
    ...
</AuthenticatorConfig>
```
On this case IS return an authentication error, and on the wso2carbon.log we can see an exception like the next one:
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Authentication failed exception!
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Authentication Failed: Authenticator Properties may be null
...
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error while getting the SMTP configuration
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.sendOTP(EmailOTPAuthenticator.java:1909)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.checkEmailOTPBehaviour(EmailOTPAuthenticator.java:511)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.processEmailOTPFlow(EmailOTPAuthenticator.java:909)
	... 67 more
```
It seem to be that during the authentication flow, IS is reading the authenticator configuration from the application-authentication.xml file on the filesystem and not from the application-authentication.xml uploaded to tenant's registry [3].

**How to reproduce:**

1. Configure EmailOTP email template type and email template following the steps on [2] (_Configure WSO2 IS as the email OTP provider - step # 4_).
2. Restart WSO2 IS to apply changes.
3. Create a tenant and log in to management console using tenant's admin credentials.
4. Create an Email OTP federated Identity Provider.
5. Create a service provider and configure local and outbound authentication to use "EmailOTP" as a second step.
6. Create a user.
7. Configure <IS_HOME>/repository/tenants/<tenant-id>/eventpublishers/EmailPublisher.xml file following the steps on [1].
8. Create a copy of the <IS_HOME>/repository/conf/identity/application-authentication.xml and configure EmailOTP authenticator following the steps on [2] (_Configure WSO2 IS as the email OTP provider - step # 6_).
9. Upload this new application-authentication.xml file into the registry at /_system/governance/EmailOTP (you'll have to create the EmailOTP collection beforehand) [2] (_Configure WSO2 IS as the email OTP provider - step # 6_).
10. Log in to the service provider using the credentials of the user you've created on the above steps.

**Expected behavior:**

- The user should receive an email with the OTP code instead of an authentication error, and
- The user should receive an email with the OTP code from the adapter configured on tenant's EmailPublisher.xml file instead of the SMTP server configured on the axis2.xml file or the adapter configured on the output-event-adapter.xml file.

**Environment information:**
 - Product Version: IS 5.8.0

---

[1] https://docs.wso2.com/display/IS580/Sending+Tenant-Wise+Emails
[2] https://docs.wso2.com/display/IS580/Configuring+Email+OTP
[3] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/256002fb4b86890ab0a559bb5fe6816f1be0b709/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L894

**Comment by piraveena** [comment] 2022-04-08 14:02
Could not reproduce this issue locally in the latest IS-5.12.0-alpha19 snapshot pack. Tested with the default pack (H2 DB) using the doc provided [here](https://is.docs.wso2.com/en/5.12.0/learn/tenant-wise-email-sender-configuration) . 

Also in IS 5.12.0, we have introduced this REST API to configure notification senders tenant-wise](https://is.docs.wso2.com/en/5.12.0/develop/notification-sender-rest-api)I[1]. This makes the life easy

[1]https://anuradha-15.medium.com/tenant-wise-email-and-sms-notification-senders-in-wso2-identity-server-43554e1a5afe

Closing this issue since this is not reproducible in the latest  IS-5.12.0-alpha19 snapshot 

Related issue:
https://github.com/wso2/product-is/issues/8544

**Closed by piraveena** 2022-04-08 14:02 UTC
Labels: Severity/Critical, bug, 5.12.0-bug-fixing
