### ISSUE TITLE
The given contact email in the branding section doesnt get update in the email sent

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17611] opened 2023-11-07 05:18 UTC
**Describe the issue:**

The given contact email in the branding section doesnt get update in the email.
<img width="1085" alt="Screenshot 2023-11-07 at 10 37 17" src="https://github.com/wso2/product-is/assets/40081059/944a3736-f8fe-493f-8be5-647a692e9aff">

<img width="848" alt="Screenshot 2023-11-07 at 10 38 32" src="https://github.com/wso2/product-is/assets/40081059/132d15bc-e8d5-4a78-a2a3-58bed2cf1c8e">

**How to reproduce:**

1.Login to the console
2.Visit branding =>styles and texts 
3.Go to General
4.Update the contact email and save

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment] 2023-11-09 04:15
Could not reproduce with the Alpha 2.
<img width="689" alt="image" src="https://github.com/wso2/product-is/assets/1332991/d8d011b2-1b2f-4251-aa39-3a58d1677d61">

**Comment by madurangasiriwardena** [comment] 2023-11-09 05:06
Closing the issue since it cannot be reproduced. Feel free to re-open if you still can reproduce the issue.

**Closed** 2023-11-09 05:06 UTC
Labels: Priority/Highest, Resolution/Cannot Reproduce, Severity/Critical, bug, Affected/7.0.0-Alpha

**Comment by melanisilva** [comment] 2023-11-09 05:28
Yes @madurangasiriwardena This issue seems to be fixed in Alpha 2
<img width="1079" alt="Screenshot 2023-11-09 at 10 57 50" src="https://github.com/wso2/product-is/assets/41188245/c0708568-d883-4633-a69d-99ea3795efcf">
