### ISSUE TITLE
Console Application Role Mappings drop down section having 2 colurs with 2 sections as grey and white in the UI

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13445] opened 2022-04-11 07:28 UTC
1. Access console
2. Develop > Applications > Console (preview)
3. Go to User Attributes tab
4. Check drop down for Role attribute
5. Check Role Mappings section

This UI section for Role Mappings needs improvements. It has 2 colurs in the drop down which is not matching 

![b](https://user-images.githubusercontent.com/31848014/162686156-61d16996-c2fa-46f6-ade3-247f77f08288.png)

Check Myaccount application too

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

**Comment by ShanikaWickramasinghe** [comment] 2022-04-11 07:32
Also observing duplicate entries as below
![Screenshot from 2022-04-11 13-01-55](https://user-images.githubusercontent.com/31848014/162686919-9f58e5b8-738b-4717-a85d-b1d8f9d3f105.png)
![Screenshot from 2022-04-11 13-02-03](https://user-images.githubusercontent.com/31848014/162686932-47b21f7e-0491-4913-9e73-a19cf0350da7.png)

**Comment by JayaShakthi97** [comment] 2022-04-15 11:29
Not reproducible with ```IS 5.12.0 alpha 19```

![Screenshot from 2022-04-15 16-36-35](https://user-images.githubusercontent.com/37938529/163565538-f5b3f268-bb56-4186-a645-79c130d096df.png)

Does not allow duplicate entries.

![Screenshot from 2022-04-15 16-36-59](https://user-images.githubusercontent.com/37938529/163565649-08b16723-3c27-4ea3-b3c4-726166c7e22d.png)

**Comment by nilasini** [comment] 2022-04-15 16:46
@ShanikaWickramasinghe Please verify and close the issue of the issue is not reproducible

**Comment by ShanikaWickramasinghe** [comment] 2022-04-18 08:37
Still observing the issue in IS 5.12.0 alpha 19 pack. Attaching a video for the steps

https://user-images.githubusercontent.com/31848014/163781674-6a8b355a-743a-4507-b4f9-4997ab3ab97a.mp4

**Comment by ShanikaWickramasinghe** [comment] 2022-05-10 11:25
Still observing the issue in 5.12.0 beta 2 pack
![Screenshot from 2022-05-10 16-53-59](https://user-images.githubusercontent.com/31848014/167617870-9f251694-f387-4101-b360-71cfeb20e11b.png)

My Linux machine resolution 

![Screenshot from 2022-05-10 16-55-09](https://user-images.githubusercontent.com/31848014/167617975-25d6a736-4d44-4e83-89c4-d829df68f3d5.png)

**Comment by savindi7** [comment] 2022-05-10 19:23
Further clarification - In order to reproduce this issue, the application must be in read only mode. The following comment made earlier shows that the application was not in read only mode and hence why it was not reproducible. 

> Not reproducible with `IS 5.12.0 alpha 19`
> 
> ![Screenshot from 2022-04-15 16-36-35](https://user-images.githubusercontent.com/37938529/163565538-f5b3f268-bb56-4186-a645-79c130d096df.png)
> 
> Does not allow duplicate entries.
> 
> ![Screenshot from 2022-04-15 16-36-59](https://user-images.githubusercontent.com/37938529/163565649-08b16723-3c27-4ea3-b3c4-726166c7e22d.png)

**Closed** 2022-05-11 03:43 UTC
Labels: ui, Priority/Highest, Severity/Major, bug, console, 5.12.0-bug-fixing, Affected-5.12.0, QA-Reported
