### ISSUE TITLE
Outbound Provisioning to Google Not Working via Console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18856] opened 2024-01-09 10:00 UTC
**Describe the issue:**
When attempting to configure outbound provisioning to Google via the console, user provisioning is not functioning as expected. However, when configured through the management console, user provisioning is successful.

**How to reproduce:**

**Expected behavior:**
User provisioning to Google should be successful when configured via the console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database:H2
 - Userstore: [e.g., LDAP, JDBC]

**Comment by DMHP** [comment] 2024-01-09 10:05
As this is working in the Management Console, this should be fixed from the FE.

**Comment by NipuniBhagya** [comment] 2024-01-11 04:49
Hi @NilukaSripalim, could you please provide the steps to reproduce this?

**Comment by NipuniBhagya** [comment] 2024-01-16 12:10
We may have to bring the provisioning configuration to the Console there seems to be an issue with the application level provisioning configuration. It logs the following error in the server logs.

```
[2024-01-16 17:26:35,227] [314a74dc-0cb0-42f5-a22a-6408f171ec6d] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity se01nipuni@gmail.com For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating user: se01nipuni@gmail.com
	at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.createUser(GoogleProvisioningConnector.java:205)
	at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.provision(GoogleProvisioningConnector.java:133)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:85)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:34)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid Input: primary_user_email",
    "reason" : "invalid"
  } ],
  "message" : "Invalid Input: primary_user_email"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.createUser(GoogleProvisioningConnector.java:201)
```

**Comment by UdeshAthukorala** [comment] 2024-01-19 13:55
- I have setup the outbound provisioning in the IS pack and tried out the flow and couldn't able to reproduce the above mentioned error.
- Then further checked with the @NipuniBhagya 's setup and found that the `Application Name` property in her google IDP is incorect and this error was occured due to that. 
- Since this error occurred due to a configuration issue we can ignore this issue.

But when doing the testing found following two issues.
1. Can not update Google Outbound provisioning configurations through in the IDP and got the following error in backend.

      ```
      ERROR {org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService} - errorCode: IDP-65034 | message: Error occurred while updating Identity Provider information  for tenant -1234
      ```
2. When the outbound provisioning is enabled via mangemnt console and when a user is self registering to and application, there are two outbound provisioning requests are getting fired and due to that can see below error in backend.

      ```
      ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity suyama@gmail.com For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating user: suyama@gmail.com
	      at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.createUser(GoogleProvisioningConnector.java:205)
	      at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.provision(GoogleProvisioningConnector.java:133)
	      at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:85)
	      at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:34)
	      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	      at java.base/java.lang.Thread.run(Thread.java:829)
      Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
      {
        "code" : 409,
        "errors" : [ {
          "domain" : "global",
          "message" : "Entity already exists.",
          "reason" : "duplicate"
        } ],
        "message" : "Entity already exists."
      }
	      at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	      at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	      at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	      at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	      at org.wso2.carbon.identity.provisioning.connector.google.GoogleProvisioningConnector.createUser(GoogleProvisioningConnector.java:201)
	      ... 7 more
      
      ```
Will create seperate 

cc: @DMHP & @NipuniBhagya

**Comment by UdeshAthukorala** [comment] 2024-01-22 13:03
This will be fixed with:
- https://github.com/wso2/carbon-identity-framework/pull/5408

**Closed** 2024-01-22 16:41 UTC
Labels: Priority/Highest, Severity/Blocker, bug, backend, QA-Reported
