### ISSUE TITLE
Cancel button is not working in SAML config page

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5376] opened 2019-06-05 06:00 UTC
Moved from: https://wso2.org/jira/browse/IDENTITY-7111

The cancel button doesn't work from "Metadata File Configuration" and "URL Configuration" section.

![Screenshot from 2017-12-11 13-38-06](https://user-images.githubusercontent.com/12288369/58933624-8992a500-8785-11e9-90a9-b0d8dd7ebf45.png)

**Comment by deshankoswatte** [comment] 2020-02-06 11:54
Hi @IsurangaPerera,

This is a duplicate of https://github.com/wso2/product-is/issues/1894 and has been fixed by https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/261.

Hence closing this issue.

**Closed** 2020-02-10 08:02 UTC
