### ISSUE TITLE
[5.6.0] Username pattern is validated and the failures are not logged during authenticating through a JDBC user store manager.

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#4470] opened 2019-02-21 06:54 UTC
1) We need to check whether the validation is really needed.

2) If it is needed, the validation failures should be logged for troubleshooting purposes.

**Comment by hauntingEcho** [comment] 2019-02-25 20:27
I would argue against validating at authentication - if a user has somehow already been created which violates the validation (e.g. because they were created before the validation was changed) they should still be able to authenticate.

**Comment by rushmin** [comment] 2019-02-25 23:57
@hauntingEcho I totally agree with you. But I'm not aware of the history of this behaviour. If we don't solve any problem here we can immediately get rid of it. Else, we should check the possibilities of addressing the original problem.

@isharak @darshanasbg what's your take on this?

**Comment by madurangasiriwardena** [comment] 2019-05-14 14:00
IMO we should not validate the pattern at login time. 

And in the same time, if we are going to keep the behavior, I don't think we need to log in error level since this is a problem with user input, not a server error.

**Comment by mefarazath** [comment] 2020-03-06 10:06
Related to https://github.com/wso2/product-ei/issues/4777

@madurangasiriwardena seems like the issue is already fixed with https://github.com/wso2/carbon-kernel/pull/2355/files so should be available in 5.10.0 as well.

**Closed** 2020-11-16 13:52 UTC
Labels: Affected/5.6.0, Component/User Mgt, Priority/Normal, Severity/Major, question
