### ISSUE TITLE
IDENTITY-6571 - Additonal tasks created when assigning a role for a workflow available to update user roles

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5683] opened 2019-06-12 11:35 UTC
Steps to recreate the issue
1. Create a workflow to change the role of the user (Update_Roles_Of_User)
2. Select an existing user and go to 'Assign Role' view
3. Then add an existing role and click 'Update'
4. Then finish the process by selecting the 'Finish' button

![image](https://user-images.githubusercontent.com/29881881/59348190-1f08d880-8d34-11e9-8fa5-0bc601887d4e.png)
![image](https://user-images.githubusercontent.com/29881881/59348201-26c87d00-8d34-11e9-8bfc-57bfd6c13c97.png)
![image](https://user-images.githubusercontent.com/29881881/59348207-2def8b00-8d34-11e9-922e-d0cbdae390e0.png)
![image](https://user-images.githubusercontent.com/29881881/59348213-32b43f00-8d34-11e9-9f84-042083fd99e6.png)

**Comment by madurangasiriwardena** [comment] 2019-06-12 11:37
Duplicate of https://github.com/wso2/product-is/issues/5680

**Closed by madurangasiriwardena** 2019-06-12 11:37 UTC
