### ISSUE TITLE
Department field in the user profile is not editable even for the Admin

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2482] opened 2018-02-19 11:25 UTC
According to GDPR users should be able to edit their own information

![2](https://user-images.githubusercontent.com/1845370/36375396-21ec7ad8-1595-11e8-8ac2-351f87f5c46b.png)

**Comment by hasinthaindrajee** [comment] 2018-03-01 10:24
Within an organization there are some information that users will not be able to change through user portal (ie dashboard). For an example Department may be something which a user cannot edit. Also you you need to be able to edit, you can make it editable by changing claim config to "read write" from admin console. Please refer [1] also for more information.

[1] https://github.com/wso2/product-is/issues/2601

**Comment by dilinisg** [comment] 2018-03-02 13:41
@hasinthaindrajee -  This property is not editable even from the management console for the super admin. Having a field that cannot be edited by default even by the admin is meaningless. Therefore, can't we make the field editable by default? Reopening the issue

**Comment by darshanasbg** [comment] 2018-03-02 13:49
@dilinisg 

Please refer @hasinthaindrajee's above comment.
" you can make it editable by changing claim config to "read write" from admin console. Please refer [1] also for more information."

Since this is the expected behaviour, closing the issue.

**Comment by dilinisg** [comment] 2018-03-02 14:02
@darshanasbg  - I understand that this property can be changed to "read write" from the admin console. My point is why do we have such property uneditable even by the admin at the first place? According to this behaviour, we are asking the user to do an additional configuration which is not relevant IMO.
Do we have a reason for having this property disabled by default?

**Comment by darshanasbg** [comment] 2018-03-02 14:14
@dilinisg There are some fields that should now have the ability to modify to avoid unintended changes..

Departement field is such field showcase that ability..

And the claim metadata effects all the users uniformly for user's profile.. Even admin should adhere to those policies..

Hope you have understood the fundamentals around this..

**Closed by darshanasbg** 2018-03-02 14:14 UTC
Labels: Affected/5.5.0-Alpha, Priority/Highest, Resolution/Invalid, Severity/Major, Type/Bug
