### ISSUE TITLE
Observing warning as line 135: warning: command substitution: ignored null byte in input when starting the server with ubuntu 20

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12959] opened 2022-01-11 05:21 UTC
**Describe the issue:**
as per subject $

**How to reproduce:**
1. Setup postgres 11.5 as the primary db
2. User store store configured for database_unique_id
3. Up the server with sh wso2server.sh

Observing the below warning 

`wso2server.sh: line 135: warning: command substitution: ignored null byte in input`
**Note**
Not observing this warning when run the server with default configs ( H2 default pack) on the same environment

![Screenshot from 2022-01-11 10-38-31](https://user-images.githubusercontent.com/31848014/148885636-a559ee10-af2a-4524-9bd5-8e0fb48fdb6e.png)

**Environment information**
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by piraveena** [comment] 2022-08-02 10:31
@ShanikaWickramasinghe is this issue reproducible now?

**Comment by piraveena** [comment] 2022-08-02 11:19
closing the issue based on above comment

**Comment by ShanikaWickramasinghe** [comment] 2022-08-05 10:49
Observed this again against the shared kernel testing pack https://drive.google.com/file/d/1wZVqkCT1GZNr_mjYbowH9q3MIq195tAm/view?usp=sharing

THis was observed during the second start up of the pack. During the 1st start up it was not observed

1. Start the pack
2. Stop the pack
3. Start the pack again

H2/default
Linux ubuntu 20
Oracle JDK 11
![Screenshot from 2022-08-05 16-16-44](https://user-images.githubusercontent.com/31848014/183062219-88fda255-476f-4130-849d-582b4663377f.png)

**Comment by piraveena** [comment] 2022-08-05 10:58
Could not reproduce this issue in the 2nd server startup in Mac OS

```
piraveena@piraveena-2 bin % 
piraveena@piraveena-2 bin % sh wso2server.sh
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/piraveena/Documents/kernel/wso2is-6.0.0-beta2-SNAPSHOT
Using Java memory options: -Xms256m -Xmx1024m

[2022-08-05 16:27:03,004] []  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
[2022-08-05 16:27:03,300] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Starting WSO2 Carbon...
[2022-08-05 16:27:03,301] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Operating System : Mac OS X 10.15.7, x86_64
[2022-08-05 16:27:03,302] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Home        : /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home
[2022-08-05 16:27:03,302] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Version     : 11.0.12
[2022-08-05 16:27:03,302] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java VM          : Java HotSpot(TM) 64-Bit Server VM 11.0.12+8-LTS-237,Oracle Corporation
[2022-08-05 16:27:03,303] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Carbon Home      : /Users/piraveena/Documents/kernel/wso2is-6.0.0-beta2-SNAPSHOT
[2022-08-05 16:27:03,303] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Temp Dir    : /Users/piraveena/Documents/kernel/wso2is-6.0.0-beta2-SNAPSHOT/tmp
[2022-08-05 16:27:03,303] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - User             : piraveena, en-LK, Asia/Colombo
[2022-08-05 16:27:03,703] []  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} - Successfully deployed the Kafka output event adaptor service
[2022-08-05 16:27:04,347] []  INFO {org.wso2.carbon.identity.hash.provider.pbkdf2.internal.PBKDF2HashServiceComponent} - PBKDF2 bundle activated successfully.
[2022-08-05 16:27:04,438] []  INFO {org.wso2.carbon.identity.oauth.uma.grant.internal.UMA2GrantServiceComponent} - Policy evaluator registered successfully: DefaultPolicyEvaluator
[2022-08-05 16:27:04,439] []  INFO {org.wso2.carbon.identity.oauth.uma.grant.internal.UMA2GrantServiceComponent} - UMA Grant component activated successfully.

```

**Comment by isharak** [comment] 2024-11-07 05:00
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 05:00 UTC
Labels: Priority/High, Severity/Major, Type/Bug, 6.0.0-bug-fixing, Affected-6.0.0, QA-Reported, IceBox
