### ISSUE TITLE
SMS OTP, Email OTP, TOTP, Magic Link, passkey  quick start guide navigate to shared access tab of myaccount instead of signin methods tab

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18251] opened 2023-11-30 14:12 UTC
**Describe the issue:**
1. Go to connections >SMS OTP/ Email OTP
2. Go to the Quick Start tab
3. Click on the applications link there, select my account application
4. It will navigate the user to the shared access tab of the my account application

https://github.com/wso2/product-is/assets/25483865/00cc542b-50c9-4f31-9515-5bba890a94b1

**Comment by brionmario** [comment] 2023-12-09 06:16
Duplicate of https://github.com/wso2/product-is/issues/18226

**Closed** 2024-01-02 09:47 UTC
Labels: ui, Priority/Normal, Severity/Critical, bug, frontend, Affected/7.0.0-beta2
