### ISSUE TITLE
Issues with password validation configurations

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19044] opened 2024-01-21 10:11 UTC
**Describe the issue:**
The are two places the password validation can be configured and it is unclear which takes precedence. Password validation can be configured through the configuration available in the console called Password Validation[1] also a password validation regex can be configured through the user-mgt.xml(via deployment.toml) config for the PRIMARY userstore and also when onboarding secondary userstores. It is unclear to which user stores(or globally) the Password Validation configuration in the console applies to.

I could notice while the user-mgt password pattern had a minimum char length as 5 (`<Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>`) the UI had enforced a minimum length of 8.

<img width="596" alt="Screenshot 2024-01-21 at 15 37 27" src="https://github.com/wso2/product-is/assets/11583571/05dcea3f-6624-442f-8cad-2ccc9bd8a93c">

It should be cleared out what configuration honoured. And if there are unused configurations then references to them should be removed clearing any confusions.

[1] - https://is.docs.wso2.com/en/next/guides/account-configurations/login-security/password-validation/

**Comment by Thumimku** [comment] 2024-01-22 05:40
Hi @janakamarasena ,

With [this](https://github.com/wso2/product-is/issues/16323) feature, we introduced organisation wide password validation mechanism where the admin can configure password validation rules which is common for all userstores.

Regarding the user store wise password validation feature, the xml files and logics were there to preserve backward compatibility for any migrated users. But we are not promoting for new users. In our IS 7 doc space we don't mention about userstore level password validation.

Regarding the precedence, when the password input validation listener is enabled(current approach) user store level  password validation won't work.

Hence, this is not a bug rather than a issue related to documentation for migration.

For migrated users user store level password validation can be provided by following configuration based on my quick research (not tested the flow in console),

### Disable input validation listener.
[event.default_listener.validation]
enable = "false"

### Enable password policy handler.
[identity_mgt.password_policy.password_policy_validation_handler]
enable=true

**Comment by DMHP** [comment] 2024-01-22 06:00
+ 1 to add this to migration documents.

**Comment by Thumimku** [comment] 2024-01-22 06:44
I am closing this issue cause the migration issue tracked with https://github.com/wso2/product-is/issues/19068
CC: @DMHP @janakamarasena

**Closed by Thumimku** 2024-01-22 06:44 UTC
Labels: docs, Severity/Critical, Component/Migration, Type/Docs, 7.0.0-migration
