### ISSUE TITLE
UI feature for delete me feature

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#8918] opened 2020-07-20 13:28 UTC
**Is your feature request related to a problem? Please describe.**
User should able to delete him/her self

**Comment by madurangasiriwardena** [comment] 2020-07-22 05:26
Duplicate of https://github.com/wso2/product-is/issues/8466

**Comment by AnuradhaSK** [comment] 2020-10-12 04:23
Reopened to track the UI implementation.

**Comment by isharak** [comment] 2024-11-06 04:58
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 04:58 UTC
Labels: Type/NewFeature, Resolution/Duplicate, consumer-exp, IceBox
