### ISSUE TITLE
Unable to start K8s cluster after update

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#19852] opened 2024-02-26 18:56 UTC
**Describe the issue:**
After updating to the latest U2 level the server couldn't start the cluster due to a `NoClassDefFoundError` error:
```
[2024-02-23 23:40:33,734] [] ERROR {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - Cannot initialize cluster java.lang.NoClassDefFoundError: org/wso2/carbon/core/clustering/hazelcast/HazelcastMembershipScheme
	...
	at org.wso2.carbon.hazelcast.HazelcastClusteringAgent.initiateCustomMembershipScheme(HazelcastClusteringAgent.java:617)
	at org.wso2.carbon.hazelcast.HazelcastClusteringAgent.configureMembershipScheme(HazelcastClusteringAgent.java:604)
	at org.wso2.carbon.hazelcast.HazelcastClusteringAgent.createConfigForAxis2Mode(HazelcastClusteringAgent.java:396)
	at org.wso2.carbon.hazelcast.HazelcastClusteringAgent.loadHazelcastConfig(HazelcastClusteringAgent.java:442)
	at org.wso2.carbon.hazelcast.HazelcastClusteringAgent.init(HazelcastClusteringAgent.java:177)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.enableClustering(StartupFinalizerServiceComponent.java:295)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:183)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309)
	...
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.core.clustering.hazelcast.HazelcastMembershipScheme cannot be found by kubernetes_membership_scheme_1.0.11_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 64 more
```

Class `org.wso2.carbon.core.clustering.hazelcast.HazelcastMembershipScheme` was renamed to `org.wso2.carbon.hazelcast.HazelcastMembershipScheme` according to [1] but it was not updated accordingly on the `kubernetes-membership-scheme` extension [2].

**How to reproduce:**
- Update from U2 level 216 (or below) to U2 level 271 (or above)

**Expected behavior:**
Kubernetes clusters should start seamlessly after taking updates.

**Environment information:**
 - Product Version: IS-KM 5.10.0

---
[1] https://github.com/wso2/api-manager/issues/514
[2] https://github.com/wso2/kubernetes-common/blob/master/kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java#L28-L30

**Comment by RushanNanayakkara** [comment] 2024-03-26 04:48
Closing as the update is released for the identified product and the public fix is not needed since the issue is not present in the public branch.

**Closed by RushanNanayakkara** 2024-03-26 04:48 UTC
Labels: bug, regression
