### ISSUE TITLE
[Feature] Provide write operations for groups over REST APIs (Preferably SCIM)

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16368] opened 2023-08-03 07:27 UTC
**Description:**
At the moment IS does not support all CRUD operations over groups of all types of remote user store through SCIM support. Hence this feature should provide flexibility to plug any user store with groups with or without group-id and perform CRUD operations on groups.

Related tasks:

-  Finalizing interfaces for the unique group ID feature: https://github.com/wso2/product-is/issues/7365
-  AD and LDAP implementation for unique id for groups: https://github.com/wso2/product-is/issues/7913
-  JDBC implementation for unique id for groups: https://github.com/wso2/product-is/issues/7914
-  Integrate the user core group implementation with SCIM 2.0: https://github.com/wso2/product-is/issues/7915

**Comment by UdeshAthukorala** [comment] 2024-02-14 11:43
Duplicate of: https://github.com/wso2/product-is/issues/7912

**Closed** 2024-02-27 10:08 UTC
