### ISSUE TITLE
When there is a password policy violation, the error message is not properly handled [Console][MC]

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10289] opened 2020-11-03 10:23 UTC
**Describe the issue:**
When there is a password policy violation, the error message is not properly handled.
In the console app, if the password policy violated, then no errors showing during user addition but once add the user notification bar contains the error message.
![1](https://user-images.githubusercontent.com/20336761/97973608-57f39280-1dec-11eb-9842-7606809985f0.png)

![2](https://user-images.githubusercontent.com/20336761/97973589-51fdb180-1dec-11eb-9f77-3f8d122b2e24.png)

IN the management console nothing is prompted in the UI, only back end error is thrown.

**How to reproduce:**
1. Create a secondary user store and configure password policy as [0-9._\-|//]{3,30}$
2. Create a user with console app/MC with password as *#789231323Jk*#
3. You will observe the behaviors mentioned in the description.

**Expected behavior:**
Proper error handling

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by NipuniBhagya** [comment] 2020-11-12 21:30
@nilasini We followed the steps that you have mentioned in the issue and set the **javascript regex** to [0-9._-|//]{3,30}$ in a JDBC user store and tried to create a user with the password #789231323Jk# but we couldn't reproduce the issue with both 5.11.0-beta4 and 5.11.0-beta6-SNAPSHOT packs.

![image](https://user-images.githubusercontent.com/30111554/98998491-37e67080-255c-11eb-9eea-3ff297d4db42.png)

Please verify and close the issue.

**Comment by nilasini** [comment] 2020-11-13 04:01
@NipuniBhagya this is reproducible when we only set java regex

**Comment by isharak** [comment] 2024-11-06 05:08
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 05:08 UTC
Labels: ui, Priority/High, Severity/Major, Type/Bug, Affected/5.11.0-Beta, IceBox
