### ISSUE TITLE
Ask Password claim value not honoured when creating user with SCIM2

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9646] opened 2020-10-02 07:36 UTC
**Describe the issue:**
Ask Password claim value not honored when creating a user with SCIM2

**How to reproduce:**
Setup Identity server for user creation with ask password option[1].
Create a user with the following curl with askPassword set to **false** as shown below.
```
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Tharaka","givenName":"Wijekoon"},"userName":"Tharaka","password":"password","emails":[{"primary":true,"value":"tharakawijekoon2@gmail.com"}],"EnterpriseUser":{askPassword:"false"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users
```
An email will be sent to the user even though ask password is set to false.

**Expected behavior:**
If askPassword is set to false email should not be sent to the user. In the code, we only check whether the askPassword claim URI is present not the value[2].

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.7.0]

[1]https://docs.wso2.com/display/IS570/Creating+Users+Using+the+Ask+Password+Option
[2]https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java#L160

**Comment by dewniMW** [comment] 2020-10-20 03:14
This issue is a duplicate of: https://github.com/wso2/product-is/issues/9458

**Closed** 2020-10-21 06:19 UTC
Labels: Resolution/Duplicate, bug
