### ISSUE TITLE
Invited Users from Parent Org Not Showing Up in Users > Invitation Tab, Immediately after inviting a user.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18177] opened 2023-11-29 07:30 UTC
**Describe the issue:**
In A  Sub organization after inviting a user from the parent organization, the user will not be listed and visualized as a pending invited user in the list Users Page > Invitation Tab.

https://github.com/wso2/product-is/assets/41188245/d0ef1aff-546b-470a-a9d9-a8d3cd7f4123

**How to reproduce:**

1. Create a User 
2. Create an Organization
3. switch to that Org and Navigate to Users page
4. invite a user from Add users dropdown button and select Invite a user from parent organization option.
5. Invite the user 
6. find that the invited user is not listed in the invited Users list.

Also, if a user is invited, it should display the invitation tab, else it should display the Users list.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Beta 2
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment] 2023-11-29 08:27
Duplicate of https://github.com/wso2/product-is/issues/18158

**Closed** 2023-11-29 08:28 UTC
Labels: ui, Priority/Normal, Severity/Major, bug, frontend, Affected/7.0.0-beta2
