### ISSUE TITLE
Email OTP options ask for the email address as the input, but it works only for the username

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17869] opened 2023-11-17 07:08 UTC
**Describe the issue:**
$subject

![image](https://github.com/wso2/product-is/assets/5061791/05db7702-8a64-4a5e-b547-ae6779e40e3e)

**How to reproduce:**
Try email user OTP as first factor

**Expected behavior:**
Ask for the correct value 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-11-17 13:12
Duplicate of https://github.com/wso2/product-is/issues/17578

**Closed** 2023-11-17 13:12 UTC
Labels: ui, Priority/Highest, Resolution/Duplicate, Severity/Critical, bug, Affected/7.0.0-Alpha
