### ISSUE TITLE
Error when adding new workflow.- Workflow defenition

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7272] opened 2020-01-14 05:04 UTC
Affected version: wso2is-5.10.0-alpha2
user store type : read_write_ldap_unique_id
DB: H2
java version "11.0.5"

**Issue when filling all the fields,** 
- the issue is occurring when adding over 100 letters for  Workflow Description and Task Detail(Approval task description)(should fill both)

![image](https://user-images.githubusercontent.com/39120228/72315663-9d0dd300-36b9-11ea-9848-1cc5add7a90c.png)

ERROR {org.wso2.carbon.identity.workflow.mgt.WorkflowManagementAdminService} - Server error when adding workflow WorkflowNewwww org.wso2.carbon.identity.workflow.mgt.exception.InternalWorkflowException: Error when executing the SQL query 
	at org.wso2.carbon.identity.workflow.mgt.dao.WorkflowDAO.addWorkflow(WorkflowDAO.java:68)
	at org.wso2.carbon.identity.workflow.mgt.WorkflowManagementServiceImpl.addWorkflow(WorkflowManagementServiceImpl.java:365)
	at org.wso2.carbon.identity.workflow.mgt.WorkflowManagementAdminService.addWorkflow(WorkflowManagementAdminService.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170)
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82)
	at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45)
	at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.identity.workflow.mgt.stub.WorkflowAdminServiceStub.addWorkflow(WorkflowAdminServiceStub.java:470)
	at org.wso2.carbon.identity.workflow.mgt.ui.WorkflowAdminServiceClient.addWorkflow(WorkflowAdminServiceClient.java:150)
	at org.apache.jsp.workflow_002dmgt.finish_002dwf_002dwizard_002dajaxprocessor_jsp._jspService(finish_002dwf_002dwizard_002dajaxprocessor_jsp.java:197)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column """DESCRIPTION"" VARCHAR(255)": "'A set of claims are identified as a dialect. Different dialects represents the same piece of information with different claim U... (346)"; SQL statement:
INSERT INTO WF_WORKFLOW(ID, WF_NAME, DESCRIPTION, TEMPLATE_ID, IMPL_ID, TENANT_ID) VALUES (?,?, ?, ?, ?, ?) [22001-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:441)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:824)
	at org.h2.command.dml.Insert.insertRows(Insert.java:175)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy58.executeUpdate(Unknown Source)
	at org.wso2.carbon.identity.workflow.mgt.dao.WorkflowDAO.addWorkflow(WorkflowDAO.java:64)
	... 81 more

===========================
ERROR {org.apache.ode.bpel.compiler.bom.BpelObjectFactory$BOMSAXErrorHandler} - null:file:///Users/niluka/WSO2/5_10_Release/alpha/alpa22/default/wso2is-5.10.0-alpha2/repository/bpel/-1234/WorkflowNewwww-2/WorkflowNewwww.bpel:51:17:cvc-complex-type.2.4.a: Invalid content was found starting with element 'extensions'. One of '{"http://docs.oasis-open.org/wsbpel/2.0/process/executable":import, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":partnerLinks, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":messageExchanges, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":variables, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":correlationSets, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":faultHandlers, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":eventHandlers, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":assign, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":compensate, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":compensateScope, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":empty, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":exit, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":extensionActivity, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":flow, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":forEach, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":if, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":invoke, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":pick, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":receive, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":repeatUntil, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":reply, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":rethrow, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":scope, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":sequence, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":throw, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":validate, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":wait, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":while}' is expected.
[2020-01-14 10:13:40,468] [] ERROR {org.apache.ode.bpel.compiler.bom.BpelObjectFactory$BOMSAXErrorHandler} - null:file:///Users/niluka/WSO2/5_10_Release/alpha/alpa22/default/wso2is-5.10.0-alpha2/repository/bpel/-1234/WorkflowNewwww-2/WorkflowNewwww.bpel:304:84:cvc-elt.4.2: Cannot resolve 'p:tExpression' to a type definition for element 'p:searchBy'.
[2020-01-14 10:13:40,473] []  WARN {org.apache.ode.bpel.compiler.bom.BpelObjectFactory} - Validation errors during parsing, continuing due to -Dorg.apache.ode.compiler.failOnValidationErrors=false switch
[2020-01-14 10:13:40,473] []  INFO {org.apache.ode.bpel.compiler.BpelC} - info: [CompilingProcess] Compiling BPEL process.

**Comment by wijith7** [comment] 2020-01-17 09:31
This issue is reproduced only if we use more than 255 characters and it is an expected behaviour.
Hence we can close this issue

**Comment by IsuraD** [comment] 2020-01-17 09:37
@wijith7 , We have to throw a correct message to the UI.

**Comment by isharak** [comment] 2024-11-06 00:11
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 00:11 UTC
Labels: Priority/High, Severity/Major, Type/Bug, Affected/5.10.0-Alpha2, IceBox
