### ISSUE TITLE
The  sub sections in the Server sections shows empty content 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21648] opened 2024-11-08 07:05 UTC
**Describe the issue:**

In the console,   the below subsections in the Server sections show empty content  when clicked

1.Admin Advisory Banner
2.Remote Log Publishing

https://github.com/user-attachments/assets/84a51e72-aa79-4c60-bc11-32ca36cd6c5e

**How to reproduce:**

1. Login to the console
2. Go to the server section
3. Click on any of the below sub-sections
- Admin Advisory Banner
- Remote Log Publishing

**Expected behavior:**

Must show the relevant content when clicked

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.1 M4]
 - OS: [ Mac]
 - Database: [H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduR** [comment] 2024-12-16 06:24
Duplicate of https://github.com/wso2/product-is/issues/22000

**Closed by ThaminduR** 2024-12-16 06:24 UTC
Labels: Priority/Highest, Severity/Blocker, Type/Bug, QA-Reported, Team/Identity Server Core, Affected/7.1.0-m4
