### ISSUE TITLE
Users email domain is removed at the time JIT provisioning

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18234] opened 2023-11-30 12:00 UTC
**Describe the issue:**
As a workaround
**How to reproduce:**
Follow the steps in  https://github.com/wso2/product-is/issues/18233
First, you will face this issue when setting up JIT provisioning - https://github.com/wso2/product-is/issues/18233
As a workaround update the userstore to JIT provision from the UI and update
Make sure attribute mappings are properly in place and the username/subject coming from the federated side is an email.
After successful federated login the newly JIT provisioned username has the email domain removed from it.
![image](https://github.com/wso2/product-is/assets/5061791/9066b7a9-1058-4cdb-8251-96fbfcd68fe7)

**Expected behavior:**
Username should not be altered without respective configuration options.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mpmadhavig** [comment] 2023-12-01 04:35
Duplicate of https://github.com/wso2/product-is/issues/18129

**Closed by mpmadhavig** 2023-12-01 04:35 UTC
Labels: Severity/Blocker, bug, Affected/7.0.0-beta2
