### ISSUE TITLE
Clicking Console Settings -> admin user lands on a "something went wrong" page

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18350] opened 2023-12-03 03:54 UTC
**Describe the issue:**
$ subject
<img width="1217" alt="Screenshot 2023-12-03 at 9 20 10 AM" src="https://github.com/wso2/product-is/assets/4951983/a293d4a5-eedd-4eea-8637-1f2c617048d2">

In browser console below error is visible
``` Error: useUserManagement must be used within a UserManagementProvider
    at se (87892.90b6b8e9.chunk.js:1:18277)
    at ce (87892.90b6b8e9.chunk.js:1:19602)
    at ko (vendor.b1ea42f3.js:205:5080825)
    at ks (vendor.b1ea42f3.js:205:5137680)
    at gl (vendor.b1ea42f3.js:205:5126832)
    at pl (vendor.b1ea42f3.js:205:5126760)
    at ml (vendor.b1ea42f3.js:205:5126623)
    at al (vendor.b1ea42f3.js:205:5123764)
    at Pr (vendor.b1ea42f3.js:205:5064666)
    at vendor.b1ea42f3.js:205:5121367
```

**How to reproduce:**
1. Login to console
2. Go to console settings
3. Click on the admin user
4. Note the something went wrong page

**Expected behavior:**
Should be able to view profile of the admin user and update user settings

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 RC SNAPSHOT build on 02/12/2023

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by GoushiRam** [comment] 2023-12-03 04:55
Duplicate of https://github.com/wso2/product-is/issues/18288.

**Closed** 2023-12-03 05:22 UTC
Labels: Severity/Blocker, bug
