### ISSUE TITLE
Getting into something went wrong error page when deleting a user in a sub organization

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17066] opened 2023-10-19 09:49 UTC
**Describe the issue:**

Getting into something went wrong error page when deleting a user in a sub organization

https://github.com/wso2/product-is/assets/40081059/049f6fe3-6383-4c47-8ddb-21bb9fd8eecb

**How to reproduce:**

1.Login in to console
2.Create a sub organization
3.Navigate to the sub org and create a user in the sub org
4.Then delete a created user in the sub organization
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-10-22 11:09
Duplicate of https://github.com/wso2/product-is/issues/17037

**Closed by pavinduLakshan** 2023-10-22 11:09 UTC
Labels: Priority/Highest, Resolution/Duplicate, Severity/Blocker, bug
