### ISSUE TITLE
Expiration of public certificate in SAML2 supported federated IDP does not get validated

### ISSUE THREAD

**Issue by YogyaGamage** [wso2/product-is#13778] opened 2022-05-31 04:59 UTC
**Describe the issue:**

Expiration of public certificate in SAML2 supported federated IDP does not get validated.

**How to reproduce:**

- Configure a federated IDP
- Enable include public certificate

<img width="905" alt="Screenshot 2022-05-31 at 10 03 14" src="https://user-images.githubusercontent.com/47789154/171093549-01aee8cd-a701-4a6c-9b12-214c70583e1f.png">

- Add an expired certificate as the public certificate

<img width="938" alt="Screenshot 2022-05-31 at 10 04 34" src="https://user-images.githubusercontent.com/47789154/171093587-87d787fa-91f5-4eda-b9d5-eaedc3ba8ecc.png">

- SSO with identity federation will work without an error

**Expected behavior:**

- An error should be shown indicating that the public certificate has expired.

**Environment information:**
 - Product Version: IS 6.0.0
 - OS:  Mac
 - Database:  H2

---

**Comment by piyarathnalakmali** [comment] 2022-06-22 06:49
I have tested a SAML federated IDP with a expired certificate and signature validation does not fail if the certificate is expired.
 
Following are the steps followed (Using a secondary IS as the IDP)

- Create a SAML federated IDP and enable authentication response signing
- Create a SP and configure federated authentication with the IDP configured in the above step
- Create a SAML SP in the secondary IS and enable response signing
- Get the secondary IS to sign the SAML response with a private key having a expired cert by 
  - Updating the wso2carbon entry in the key store with a private key having a expired public certificate
  - Updating the wso2carbon entry in the trust store with the expired certificate
  - Restarting to apply the key store changes
- Choose the `Upload IDP certificate` option for `Choose IDP certificate type` and upload the expired public certificate into the `Identity Provider Public Certificate` section in the SAML federated IDP
- Try logging into the SP configured with federated authentication

Authentication will be successful even though the uploaded IDP certificate is expired. 

SAML response signature validation is done in the [DefaultSAML2SSOManager](https://github.com/wso2-extensions/identity-outbound-auth-samlsso/blob/1972c8887db430626ebe5d775d29881b0f87eea2/components/org.wso2.carbon.identity.application.authenticator.samlsso/src/main/java/org/wso2/carbon/identity/application/authenticator/samlsso/manager/DefaultSAML2SSOManager.java#L1204) class using the opensaml xmlsec library and it does not fail the signature validation upon certificate expiry.

**Comment by rksk** [comment] 2022-06-29 19:47
Related https://github.com/wso2/product-is/issues/5944

**Comment by Avarjana** [comment] 2022-08-02 09:35
The expired certificate provided by a federated IdP cannot be challenged by the developer who's using WSO2 IS. Therefore, this will not be addressed ATM.

**Comment by Avarjana** [comment] 2022-08-02 09:40
Duplicate of https://github.com/wso2/product-is/issues/5944

**Closed by Avarjana** 2022-08-02 09:40 UTC
Labels: Priority/Low, Severity/Minor, bug, Affected-6.0.0, IS-6.0.0-Test-Hackathon
