### ISSUE TITLE
Loading issues in the protocol tab in application settings page

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#17781] opened 2023-11-14 09:53 UTC
**Describe the issue:**
When navigated to the `Protocol` tab in the settings page of a particular application, the content does not get loaded. 

https://github.com/wso2/product-is/assets/27700915/07494ad0-7df5-48a9-8314-56930ca57d79

**How to reproduce:**
1. Log into the console.
2. Create an application (ex:SPA)
3. Go to the settings page of the application.
4. Click in the `Protocol` tab.

**Expected behavior:**
Content of the protocol tab should be loaded.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta-SNAPSHOT

**Comment by pavinduLakshan** [comment] 2023-11-15 10:10
Duplicate of https://github.com/wso2/product-is/issues/17607

**Closed by pavinduLakshan** 2023-11-15 10:10 UTC
Labels: ui, Priority/Highest, Resolution/Duplicate, Severity/Critical, bug, Affected/7.0.0-Alpha
