### ISSUE TITLE
U2F UserHandle validation failure when a single user has multiple devices registered

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16443] opened 2023-08-11 15:46 UTC
**Describe the issue:**
When multiple fido devices are registered, authentication with non-discoverable credentials (FIDO U2F) are failing.

**How to reproduce:**
Register multiple fido devices and try to login with one of non-discoverable credential.
Reproduced the issue with older mackbooks (MacBook Pro 2015 and 2020) which does not have touch ID.

**Analysis:**
When devices are getting registered, it always add random values for userHandle into the credentialRepository (FIDO2_DEVICE_STORE table). But during the authentication flow, the device sends DeviceHandle as null [ref](https://www.w3.org/TR/webauthn/#sctn-conforming-authenticators-u2f:~:text=2.2.1.%20Backwards%20Compatibility%20with%20FIDO%20U2F), so it invokes credentialRepository.[getUserHandleForUsername](https://github.com/wso2-extensions/identity-local-auth-fido/blob/3d544a3bba22922edf8b18ed37f4b9bf6a30331e/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java#L116).

When there are multiple devices registered for the same user, [getUserHandleForUsername](https://github.com/wso2-extensions/identity-local-auth-fido/blob/3d544a3bba22922edf8b18ed37f4b9bf6a30331e/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java#L116) returns one of them from the credentialRepository, the credential [lookup](https://github.com/wso2-extensions/identity-local-auth-fido/blob/3d544a3bba22922edf8b18ed37f4b9bf6a30331e/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/dao/FIDO2DeviceStoreDAO.java#L190) [ref](https://github.com/Yubico/java-webauthn-server/blob/1.12.1/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java#L204) returns empty when that returned userHandle does not match with the credentialId and that's the reason for other device for not being able to login at all.

**Expected behavior:**
The UserHandle should be unique for a given user. When a user is registering the second device, it should use the existing value instead of generating a new value.

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
https://github.com/Yubico/java-webauthn-server/issues/313

**Comment by rksk** [comment] 2023-08-11 16:02
Diff for 5.11
```
Index: components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java b/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java
--- a/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java	(revision 2d70bc147c30fbfb2c3494c5e7ff5a065720c0cb)
+++ b/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java	(date 1691767078003)
@@ -181,8 +181,7 @@
         user.setTenantDomain(CarbonContext.getThreadLocalCarbonContext().getTenantDomain());
 
         PublicKeyCredentialCreationOptions credentialCreationOptions =
-                relyingParty.startRegistration(StartRegistrationOptions.builder().user(UserIdentity.builder()
-                        .name(user.toString()).displayName(user.getUserName()).id(generateRandom()).build())
+                relyingParty.startRegistration(StartRegistrationOptions.builder().user(buildUserIdentity(user))
                         .authenticatorSelection(AuthenticatorSelectionCriteria.builder()
                                 .requireResidentKey(true).build()).build());
 
@@ -697,8 +696,10 @@
 
     private UserIdentity buildUserIdentity(User user) {
 
+        ByteArray userHandle = FIDO2DeviceStoreDAO.getInstance().getUserHandleForUsername(user.toString())
+                .orElseGet(WebAuthnService::generateRandom);
         return UserIdentity.builder().name(user.toString()).displayName(user.getUserName())
-                .id(generateRandom()).build();
+                .id(userHandle).build();
     }
 
     private User getPrivilegedUser() {

```

**Comment by lashinijay** [comment] 2023-09-13 04:48
Closing this issue as the issue is now fixed in the master branch

**Closed by lashinijay** 2023-09-13 04:48 UTC
Labels: bug, U2
