### ISSUE TITLE
DB_Script Error- Postgres 11.6

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9306] opened 2020-08-26 06:26 UTC
While executing oracle.sql queries in /
wso2is-5.11.0-m33-SNAPSHOT/dbscripts/identity/postgresql.sql

Getting below-mentioned errors:
ERROR:  syntax error at or near "AUTO_INCREMENT"
LINE 4:     ID                INT           NOT NULL AUTO_INCREMENT,
                                                     ^. (Line 1264)

The Query :  CREATE TABLE IF NOT EXISTS IDN_CORS_ORIGIN (
    ID                INT           NOT NULL AUTO_INCREMENT,
    TENANT_ID         INT           NOT NULL,
    ORIGIN            VARCHAR(2048) NOT NULL,
    UUID              CHAR(36)      NOT NULL,

    PRIMARY KEY (ID),
    UNIQUE (TENANT_ID, ORIGIN),
    UNIQUE (UUID)
);

2. ERROR:  relation "idn_cors_origin" does not exist. (Line 1277)

Query : ALTER TABLE IDN_CORS_ASSOCIATION
    ADD CONSTRAINT ID_IDN_CORS_ORIGIN_ID_FOREIGN_CONSTRAINT
        FOREIGN KEY (IDN_CORS_ORIGIN_ID)
        REFERENCES IDN_CORS_ORIGIN (ID)
        ON DELETE CASCADE
        ON UPDATE RESTRICT;

**Comment by nilasini** [comment] 2020-09-28 07:12
while adding the applicaiton with allowedOrigins throwing following exception.

ng/Updating OAuth2/OpenIDConnect configuration. CMS-65004 org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: CMS-65004
	at org.wso2.carbon.identity.cors.mgt.core.internal.util.ErrorUtils.handleServerException(ErrorUtils.java:35)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSOriginDAOImpl.setCORSOrigins(CORSOriginDAOImpl.java:202)
	at org.wso2.carbon.identity.cors.mgt.core.internal.impl.CORSManagementServiceImpl.setCORSOrigins(CORSManagementServiceImpl.java:97)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.functions.application.inbound.oauth2.OAuthInboundFunctions.updateCorsOrigins(OAuthInboundFunctions.java:242)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.ServerApplicationManagementService.createApplication(ServerApplicationManagementService.java:327)
	at org.wso2.carbon.identity.api.server.application.management.v1.impl.ApplicationsApiServiceImpl.createApplication(ApplicationsApiServiceImpl.java:82)
	at org.wso2.carbon.identity.api.server.application.management.v1.ApplicationsApi.createApplication(ApplicationsApi.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: column "id" does not exist
  Position: 96
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy55.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:208)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSOriginDAOImpl.setCORSOrigins(CORSOriginDAOImpl.java:195)
	... 57 more

**Comment by nilasini** [comment] 2020-09-28 07:16
After adding an application with allowed origin couldn't able to retrieve the particular application through cors/origins/<origin_id>/applications. Always get an error saying not a valid CORS origin ID. The reason is while adding the UUID some extra spaces added in the database.

ERROR {org.wso2.carbon.identity.api.server.cors.v1.core.CORSService} - errorCode: CRS-65001 | message: Server encountered an error while retrieving the CORS origins. org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceClientException: 3d96d4b707964e7aa1a6ef961e2c07e3 is not a valid CORS origin ID.
	at org.wso2.carbon.identity.api.server.cors.v1.core.CORSService.getAssociatedAppsByCORSOrigin(CORSService.java:68)
	at org.wso2.carbon.identity.api.server.cors.v1.impl.CorsApiServiceImpl.getAssociatedAppsByCORSOrigin(CorsApiServiceImpl.java:36)
	at org.wso2.carbon.identity.api.server.cors.v1.CorsApi.getAssociatedAppsByCORSOrigin(CorsApi.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)

**Comment by nilasini** [comment] 2020-09-29 11:19
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3105

**Closed by nilasini** 2020-09-29 11:19 UTC
Labels: Priority/High, Severity/Blocker, affected/5.11.0-m33, bug
