### ISSUE TITLE
Experiencing "Something Went Wrong" Error When Attempting Self-Registration After Changing Hostname.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19408] opened 2024-02-06 10:06 UTC
**Describe the issue:**
Getting Something went wrong when trying Self-registration with the hostname changed.

```
[2024-02-06 12:48:04,325] [21862112-b2d0-4f98-9b97-9f5353d5cea3] ERROR {org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint} - Cannot find AuthenticationResult from the cache
[2024-02-06 12:48:53,934] [0e810af7-a8f0-4de8-ae8d-81fb157d16ca] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/accountrecoveryendpoint].[register.do]} - Servlet.service() for servlet [register.do] in context with path [/accountrecoveryendpoint] threw exception [An exception occurred processing [/self-registration-username-request.jsp] at line [322]

319:     Claim emailPII =
320:         uniquePIIs.get(IdentityManagementEndpointConstants.ClaimURIs.EMAIL_CLAIM);
321:     Boolean isAlphanumericUsernameEnabled = false;
322:     if (usernameConfig.has("alphanumericFormatValidator")) {
323:         isAlphanumericUsernameEnabled = (Boolean) usernameConfig.get("alphanumericFormatValidator");
324:     }
325:


Stacktrace:] with root cause java.lang.NullPointerException
	at org.apache.jsp.self_002dregistration_002dusername_002drequest_jsp._jspService(self_002dregistration_002dusername_002drequest_jsp.java:1668)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.tomcat.ext.filter.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:211)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**How to reproduce:**

1. Download IS7 pack
2. Change the hostname (Followed Option 1) - https://is.docs.wso2.com/en/next/deploy/change-the-hostname/
3. Navigate to login and registration and enable self-registration
4. From the My Account app try to self-register 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 Beta 7
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment] 2024-02-09 06:45
Could not able to reproduce this with the IS-7.0.0-beta7 release pack.
We changing the cert I used following keytool command to compatible with PKCS12

1. Keytool command under option 1

> keytool -genkey -alias newcert -keyalg RSA -keysize 2048 -keystore newkeystore.p12 -deststoretype PKCS12 -dname "CN=is.dev.wso2.com, OU=Is,O=Wso2,L=SL,S=WS,C=LK" -storepass mypassword -keypass mypassword -ext SAN=dns:localhost

2. For step 3

> keytool -export -alias newcert -keystore newkeystore.p12 -file pkn.pem

3. For step 4
keytool -import -alias newcert -file pkn.pem -keystore client-truststore.p12 -storepass wso2carbon

Can you try with this command @melanisilva

**Comment by Thisara-Welmilla** [comment] 2024-02-09 06:46
Additional Note: In code line[1] if any error occurred when trying get password or username config, instead of handing the error or setting to default values, we set to them to null object. In such cases, this we get null pointer exception. Is this the correct behavior.
@brionmario @NipuniBhagya @Thumimku 

[1]. https://github.com/wso2/identity-apps/blame/4fc35edd26a5a0fbf9a8054b20de30b81b58dd00/identity-apps-core/apps/recovery-portal/src/main/webapp/self-registration-username-request.jsp#L142

**Comment by brionmario** [comment] 2024-02-09 07:03
+1. Need to habdle null properly.

Even JS code blocks will throw errors when `null` is assigned.

ex: 
```
if (passwordConfig.minLength> 0 || passwordConfig.maxLength > 0) {
```

**Comment by Thisara-Welmilla** [comment] 2024-02-09 08:53
Will close the issue and open new issue to track the UI improvement.

> +1. Need to handle null properly.
> 
> Even JS code blocks will throw errors when `null` is assigned.
> 
> ex:
> 
> ```js
> if (passwordConfig.minLength> 0 || passwordConfig.maxLength > 0) {
> ```
> 
> cc:/ @kayathiri4

**Closed by Thisara-Welmilla** 2024-02-09 08:53 UTC
Labels: Priority/Highest, Severity/Blocker, bug, backend, QA-Reported, Affected/7.0.0-beta7

**Comment by melanisilva** [comment] 2024-02-09 09:22
> Could not able to reproduce this with the IS-7.0.0-beta7 release pack. We changing the cert I used following keytool command to compatible with PKCS12
> 
> 1. Keytool command under option 1
> 
> > keytool -genkey -alias newcert -keyalg RSA -keysize 2048 -keystore newkeystore.p12 -deststoretype PKCS12 -dname "CN=is.dev.wso2.com, OU=Is,O=Wso2,L=SL,S=WS,C=LK" -storepass mypassword -keypass mypassword -ext SAN=dns:localhost
> 
> 2. For step 3
> 
> > keytool -export -alias newcert -keystore newkeystore.p12 -file pkn.pem
> 
> 3. For step 4
> 
> > keytool -import -alias newcert -file pkn.pem -keystore client-truststore.p12 -storepass wso2carbon
> 
> Can you try with this command @melanisilva
> 
> Doc update will be tracked with #19303

Tried the flow with the mentioned commands and the flow works as expected.
