### ISSUE TITLE
No server info logs of the error when authorization request fails due to an expired JWT

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/product-is#13934] opened 2022-06-15 05:07 UTC
**Describe the issue:**

Authorization requests fail when trying to make an authorization call with an expired JWT (the exp attribute having a past date) in the request object. Yes it is true that the request needs to fail in these types of scenarios as the JWT is expired. But the issue that we come across here is that there are no server info logs that could be found in such instances which makes the user completely unaware of why the request failed unless debug logs are enabled. The reason for it is because only debug logs are added when handling the exception. In the code snippet [1] it can be found where the exception is being thrown and in the code snippet [2] it can be found where the errors are being logged just when debugging is enabled.

**Expected behavior:**

Therefore if we could change the implementation in [2] to either add additional server info logs mentioning the reason for the error to occur when handling the exception or if we could remove the *isDebugEnabled()* condition check and log the exception anyway, then it would give more clarity to the user of the error that occurred in order to rectify it. If we are to use the option of adding additional server info logs then it should mention the error as *Expired JWT* when handling the exception. The purpose of implementing one of the aforementioned solutions  is because ideally the end user must be aware of the error occurring without even having debug enabled. 

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/RequestObjectValidatorUtil.java#L153

[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/tree/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L1967

**Comment by ThumulaPerera** [comment] 2022-06-22 10:42
Expired JWT is an error from the client side. As a practice, such client side errors are not logged as info logs on the server side. 
However, an appropriate response is sent to the client (in this case `error=invalid_request_object`) which should enable the client to detect the error from their end. In addition, as mentioned in the issue description as well, server side debug logs can be used to identify the error if required. 

Closing the issue as this is the intended behaviour.

**Closed by ThumulaPerera** 2022-06-22 10:42 UTC
Labels: bug, good first issue
