### ISSUE TITLE
Default WSO2 IS 5.9.0 installation errors on Admin console

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#7137] opened 2019-12-18 12:29 UTC
I have a default installation of WSO2IS 5.9.0 and I  have noticed GET errors in the pages from the administration console when looking at the user profile:
    <script type="text/javascript" src="../carbon/admin/js/breadcrumbs.js"></script>
    <script type="text/javascript" src="../carbon/admin/js/cookies.js"></script>
    <script type="text/javascript" src="../carbon/admin/js/main.js"></script>
![image](https://user-images.githubusercontent.com/45126217/71086409-8d769980-21a2-11ea-940e-f7e5f0774279.png)
The URL contains an extra carbon. The behaviour is also on other pages. 

Thanks

**Comment by senthalan** [comment] 2019-12-18 13:22
Already a similar issue has been reported with https://github.com/wso2/product-is/issues/5346

**Comment by madurangasiriwardena** [comment] 2020-01-22 10:18
Duplicate of https://github.com/wso2/product-is/issues/5346

**Closed by madurangasiriwardena** 2020-01-22 10:18 UTC
