### ISSUE TITLE
Wrong concatenation of passwordReset parameter to the callback url when create users using the Ask Password and Email Verification options

### ISSUE THREAD

**Issue by lochanaEdirisinghe** [wso2/product-is#12787] opened 2021-11-16 11:36 UTC
**Describe the issue:**
In the Ask Password flow, a parameter is appended as &passwordReset=true to the redirect url as follows,

https://localhost:9443/myaccount&passwordReset=true

After adding the new password and click the proceed button, user gets 405 Method Not Allowed error in normal browser window. But in incognito window user is redirected to the management console instead of myaccount.

**How to reproduce:**
Create a user by Ask Password and Email Verification Option.
Change the password through the link that comes via email and click on proceed.

**Environment information** 
 - Product Version: IS 5.11.0

**Workaround for now**
Setting the redirect url along with an opaque parameter and set that url as "redirect_uri" at the end of create password url in the Ask Password email template as follows,

{{carbon.product-url}}/accountrecoveryendpoint/confirmrecovery.do?confirmation={{confirmation-code}}&amp;userstoredomain={{userstore-domain}}&amp;username={{url:user-name}}&amp;tenantdomain={{tenant-domain}}&amp;redirect_uri=https://localhost:9443/myaccount?temp=test"

There're three places where this redirect_uri should be set in email template.

---

### Optional Fields

**Related issues:**

https://github.com/wso2/product-is/issues/12306

**Comment by nilasini** [comment] 2022-01-18 04:21
@minolih can we close this issue? Isn't this issue reproducible in latest release?

**Comment by minolih** [comment] 2022-01-18 18:19
@nilasini I will reproduce this issue. It was on hold due to a blocker to test.

**Comment by nilasini** [comment] 2022-02-08 05:41
@minolih could you able to check on this?

**Comment by minolih** [comment] 2022-02-08 05:53
@nilasini This issue is already fixed.

**Closed by minolih** 2022-02-08 05:53 UTC
Labels: bug

**Comment by BrunoSuwin** [comment] 2022-02-11 11:55
@minolih can i redirect to any other url, i tired but after that url i am getting an extra parameter along with the url  (&passwordReset=true )   https://example.com&passwordReset=true

**Comment by minolih** [comment] 2022-02-14 05:35
@BrunoSuwin What is the version of WSO2 Identity Server you are using?

**Comment by BrunoSuwin** [comment] 2022-02-14 05:50
5.11

**Comment by minolih** [comment] 2022-02-14 06:32
@BrunoSuwin The fix for this issue is not available in the public release of WSO2 IS 5.11.
However, the fix for WSO2 IS 5.11.0 can be applied via a U2 update. In order to get the U2 update you need to have a subscription to WSO2 Identoty Server.

**Comment by BrunoSuwin** [comment] 2022-02-14 07:43
Ok , Thanyou so much for your time 👍
