### ISSUE TITLE
SQL Error: ORA-01408: such column list already indexed while sourcing Oracle DB Script

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6981] opened 2019-12-02 07:03 UTC
Suggested Labels
Affected/ IS 5.10.0 M8 Snapshot
Type/ Bug
Priority/ High
Severity / Major

**Steps to Reproduce**

1. Source the following Oracle DB Scripts against oracle 12 c
<IS-HOME>/dbscripts/oracle.sql

**Observation**

Observed the below ERROR logs while sourcing the above script

```
Error starting at line 40 in command:
CREATE INDEX REG_PATH_IND_BY_PATH_VALUE ON REG_PATH(REG_PATH_VALUE, REG_TENANT_ID)
Error at Command Line:40 Column:53
Error report:
SQL Error: ORA-01408: such column list already indexed
01408. 00000 -  "such column list already indexed"
*Cause:    
*Action:
index REG_PATH_IND_BY_PARENT_ID created.

```

```
Error starting at line 784 in command:
CREATE INDEX SYSTEM_ROLE_IND_BY_RN_TI ON UM_SYSTEM_ROLE(UM_ROLE_NAME, UM_TENANT_ID)
Error at Command Line:784 Column:57
Error report:
SQL Error: ORA-01408: such column list already indexed
01408. 00000 -  "such column list already indexed"
*Cause:    
*Action:
TRIGGER UM_SYSTEM_ROLE_TRIGGER compiled
```

**Comment by madurangasiriwardena** [comment] 2020-01-16 09:17
Duplicate of https://github.com/wso2/product-is/issues/6981

**Closed by madurangasiriwardena** 2020-01-16 09:17 UTC
Labels: Priority/Highest, Severity/Blocker, Type/Bug
