### ISSUE TITLE
Missing close button icon in pop up windows.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#15340] opened 2023-01-10 13:18 UTC
**Describe the issue:**
The close button icon in pop up windows are missing.

![Screenshot 2023-01-10 at 17 29 51](https://user-images.githubusercontent.com/41188245/211562024-3f4654da-db7d-4e4d-8a71-18ddbc5ae313.png)
![Screenshot 2023-01-10 at 17 46 01](https://user-images.githubusercontent.com/41188245/211562053-4bc478ab-7ccb-46b3-9fa8-3f575b3bda85.png)

**How to reproduce:**

Try to create a new user and the pop up comes after that doesn't include a close icon.

https://user-images.githubusercontent.com/41188245/211717147-f9fd9693-639c-4b73-87a6-11b711fd9614.mov

**Expected behavior:**
All the pop up windows should have a close button with close icon.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Comment by chamathns** [comment] 2023-01-11 18:38
will be fixed with https://github.com/wso2/carbon-kernel/pull/3390

**Comment by chamathns** [comment] 2023-01-11 18:38
Duplicate of https://github.com/wso2/product-is/issues/14615

**Closed** 2023-01-12 04:59 UTC
Labels: ui, Severity/Critical, bug, 6.1.0-bug-fixing
