### ISSUE TITLE
Test Connection Button Does Not Return Correct Status Despite Proper Configuration

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19317] opened 2024-01-31 12:20 UTC
**Describe the issue:**
When adding a database as a secondary user store, initially, the test connection button accurately reflects the connection status. However, after creating the connection, the button consistently prompts an error message stating "Something went wrong."

This is because the password is empty and the field is not editable.

**Initially, it gives the correct status.** 

<img width="836" alt="Screenshot 2024-01-31 at 16 32 37" src="https://github.com/wso2/product-is/assets/41188245/05469d96-0a2f-4931-b2cc-ff12fa54a8a9">

https://github.com/wso2/product-is/assets/41188245/d697d8d6-27eb-4da4-8203-875e33b89a00

**How to reproduce:**

1. Navigate to Userstores page
2. Create New Userstore
3. Select `Database` option
4. Input the mandatory properties and try `TestConnection` button

**Expected behavior:**
Should reflect the correct status.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 Beta6
 - OS: Mac
 - Database:  MySQL
 - Userstore: MySQL Database as secondary.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by rksk** [comment] 2024-10-25 09:33
duplicate of https://github.com/wso2/product-is/issues/18747

**Closed by rksk** 2024-10-25 09:33 UTC
Labels: Priority/High, Severity/Major, Type/Bug, Affected/7.0.0-beta6
