### ISSUE TITLE
Authentication fails for secondary userstores when one userstore fails

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#20136] opened 2024-04-02 21:27 UTC
**Describe the issue:**

Overall authentication failure for secondary userstores when one userstore fails.

**How to reproduce:**

- Create two or more secondary userstores
- Connect the faulty userstore as the secondary userstore 
- Move up the faulty userstore in userstore order by redeploying others
- Try to authenticate to user in secondary userstore (this userstore should be in after the faulty userstore in userstore order)
- User authentication will fail

**Expected behavior:**

User should be able to authenticate even though other userstores are failed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 6.1.0]
 - OS: [ Mac]
 - Database: [H2]
 - Userstore: [LDAP, JDBC]

---
When authenticating, if the user is not found in the primary userstore, it will iterate the authentication with secondary userstore[1]. If the userstore fails, it will throw UserStoreException, hence result in exiting the authentication flow with authentication failure error without proceeding to search within subsequent userstores.
[1] https://github.com/wso2/carbon-kernel/blob/v4.9.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L11331-L11342
### Optional Fields
**Related issues:**

https://github.com/wso2/product-is/issues/8535

**Comment by rksk** [comment] 2024-07-01 03:42
Duplicate of https://github.com/wso2/product-is/issues/8535

**Closed by rksk** 2024-07-01 03:42 UTC
Labels: bug
