### ISSUE TITLE
Missing files or directories should be explained in docs which is included in <Tool>/conf directory

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2743] opened 2018-03-02 11:18 UTC
Missing files or directories should be explained in docs which is included in <Tool>/conf directory in this [1] doc

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

 config.json 
 datasources 
 log4j.properties -missing. Explain what is the use of this and whether we can configure this
 log-config  
 product-config -missing
 sql 
 streams - missing

**Comment by ruwanta** [comment] 2018-03-05 02:29
This is not related to IS 5.5.0. Please move to appropriate project.

**Comment by Nashaath** [comment] 2018-03-23 04:50
closing since this is a duplicate of [1].
[1] https://github.com/wso2/identity-anonymization-tool/issues/68

**Closed by Nashaath** 2018-03-23 04:50 UTC
Labels: Priority/Normal, Resolution/Duplicate, Type/Docs
