### ISSUE TITLE
Mismatch of user id when calling the session management API for the linked accounts in federated log in

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#12169] opened 2021-07-22 22:26 UTC
**Describe the issue:**
For the federated users, session-related information is persisted under a different user id. So, when we try to retrieve the sessions (GET /users/v1/{user_id}/sessions) [1] using the user id in the user profile it won't return any results.

In the IDN_AUTH_USER and IDN_AUTH_USER_SESSION_MAPPING tables, it's maintaining a different user id, not the one in user profile.

**How to reproduce:**
- Get updated IS-5.10.0 pack (1626794272501)
- Configure an identity provider, service provider and add Federated Authentication for the local and outbound authentication (with jit provisioning enabled).
- Login to the service provider using federated login.
- Get the provisioned user id from user profile and retrieve the sessions using session management API [1].
`request: GET /users/v1/{user_id}/sessions`

**Expected behavior:**
It's not returning the sessions, instead returning an empty array. The API should respond with active session for the user.

**Environment information** **:**
 - Product Version: [IS 5.10.0]
 - Database: [H2]
 - Userstore: [LDAP]

**Related issues:**
https://github.com/wso2/product-is/issues/7725

[1] - https://is.docs.wso2.com/en/5.10.0/develop/session-mgt-rest-api/#/

**Comment by dewniMW** [comment] 2022-04-10 06:33
@vihanga-liyanage @Yasara-Y is this issue addressed in master as well? If the issue is not there in master, shall we close this?

**Comment by ThaminduDilshan** [comment] 2022-07-22 04:47
Wasn't able to reproduce this in public according to the steps.

![Screenshot from 2022-07-22 10-12-34](https://user-images.githubusercontent.com/35653110/180364556-c7e775ce-ad7d-45bb-9cf1-8f72b524271b.png)

![Screenshot from 2022-07-22 10-13-32](https://user-images.githubusercontent.com/35653110/180364586-600f4f54-dc4e-4618-a4c4-bcd3a2131f03.png)

**Comment by ThaminduDilshan** [comment] 2022-08-22 04:03
We need to provide [PR](https://github.com/wso2/identity-api-user/pull/155) as a u2 update for 6.0.0

**Comment by ThaminduDilshan** [comment] 2023-04-07 10:47
Closing as completed

**Closed by ThaminduDilshan** 2023-04-07 10:47 UTC
Labels: bug, WUM
