### ISSUE TITLE
Script Library Management REST API parses certain characters incorrectly

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#18731] opened 2023-12-21 12:37 UTC
**Describe the issue:**

When converting the script content to a string, the Script Library Management REST API [1] POST and UPDATE requests remove double slash characters.

Due to this, it is not possible to add comments to the Javascript code, and any URLs specified are also broken as a result (i.e. _//this is a comment -> /this is a comment & https://example.com -> https:/example.com_).

Therefore, due to these syntax errors, it is not possible to utilize the function library that is added via the REST API.

The same behavior can be reproduced in both v6.1.0 and v5.11.0 with both JDK 8 and JDK 11 and the POST and UPDATE methods of the _/script-libraries_ endpoint. When debugging further, it was observed that the conversion of the above-mentioned double slash to a single slash is caused by the _IOUtils.toString_ method invocation present in [2] and [3].

**How to reproduce:**

Invoke the POST or UPDATE _/script-libraries_ endpoint as mentioned in [1].
_Navigate to the carbon management console > Function Libraries > List the libraries > Click "Edit" on the added function library_ and observe that double slashes have been converted to a single slash, causing syntax errors.

[1] - https://is.docs.wso2.com/en/latest/apis/script-library-rest-api
[2] - https://github.com/wso2/identity-api-server/blob/v1.2.23/components/org.wso2.carbon.identity.api.server.script.library/org.wso2.carbon.identity.api.server.script.library.v1/src/main/java/org/wso2/carbon/identity/api/server/script/library/v1/core/ServerScriptLibrariesService.java#L154
[3] - https://github.com/wso2/identity-api-server/blob/v1.2.23/components/org.wso2.carbon.identity.api.server.script.library/org.wso2.carbon.identity.api.server.script.library.v1/src/main/java/org/wso2/carbon/identity/api/server/script/library/v1/core/ServerScriptLibrariesService.java#L196

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: v6.1.0

**Comment by AmshikaH** [comment] 2024-01-22 07:28
This issue is caused by storing the file content as the file pathname in [1] and [2], not due to the use of `IOUtils.toString`. This will be fixed by https://github.com/wso2/identity-api-server/pull/577.

[1] - https://github.com/wso2/identity-api-server/blob/v1.2.23/components/org.wso2.carbon.identity.api.server.script.library/org.wso2.carbon.identity.api.server.script.library.v1/src/main/java/org/wso2/carbon/identity/api/server/script/library/v1/core/ServerScriptLibrariesService.java#L154
[2] - https://github.com/wso2/identity-api-server/blob/v1.2.23/components/org.wso2.carbon.identity.api.server.script.library/org.wso2.carbon.identity.api.server.script.library.v1/src/main/java/org/wso2/carbon/identity/api/server/script/library/v1/core/ServerScriptLibrariesService.java#L196

**Closed** 2024-01-24 06:57 UTC
Labels: bug, U2
