### ISSUE TITLE
[Doc] Outbound Provisioning with Salesforce document images are not visible

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4812] opened 2019-03-25 13:43 UTC
Affected: 5.8.0-Alpha2
Severity: Minor
Priority: Normal
Component: Outbound Prov
Type: Docs

Some of the images are not display in the page, Outbound Provisioning with Salesforce  [1]  

[1] https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce

**Comment by sherenewso2** [comment] 2019-04-08 09:29
Hi,

Closing this as since it seems to be fixed now [1]. Please re-open if the issue is still there. 

[1] https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce

**Closed by sherenewso2** 2019-04-08 09:29 UTC
Labels: Affected/5.8.0-Alpha2, Complexity/Low, Priority/High, Severity/Blocker, Type/Docs
