### ISSUE TITLE
Invalid error related to callback url at OIDC web application creation

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#10421] opened 2020-11-09 16:22 UTC
**Describe the issue:**
Observed following error related to callback url at OIDC web application creation
Issue is not reproduced for 'https://example.com' type.

![image](https://user-images.githubusercontent.com/39077751/98567219-afef3500-22d5-11eb-897e-e213db841dd7.png)

**Comment by brionmario** [comment] 2020-11-10 08:45
Can't reproduce with the latest codebase `identity.apps - v1.0.525`. Needs to validate this with the next release pack.

<img width="1099" alt="Screen Shot 2020-11-10 at 2 13 53 PM" src="https://user-images.githubusercontent.com/25959096/98650571-13717500-235f-11eb-83f3-538340359b6e.png">

**Comment by NipuniBhagya** [comment] 2020-11-11 06:08
@aaujayasena Closing this issue as it is not reproduced in the latest identity-apps version please reopen it if you are able to reproduce it in an IS pack with the latest identity-apps version.

**Closed by NipuniBhagya** 2020-11-11 06:08 UTC
Labels: Complexity/High, Priority/High, Severity/Major, bug, revalidation-required, ux
