### ISSUE TITLE
Error during migration from 5.2.0 to 5.6.0 when InternalKeyStore is specified

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-is#3896] opened 2018-11-01 16:00 UTC
The following stack trace is encountered when running the IS migration client from 5.2.0 to 5.6.0.

TID: [-1234] [] [2018-10-22 16:42:20,149]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.3.0, Migration Step : UserStorePasswordMigrator starting...........................  {org.wso2.carbon.is.migration.VersionMigration}
TID: [-1234] [] [2018-10-22 16:42:20,149]  INFO {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator} -   WSO2 Product Migration Service Task : Migration starting on Secondary User Stores {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator}
TID: [-1234] [] [2018-10-22 16:42:20,152]  INFO {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator} -  Migrating password in: /apps/wso2am-2.5.0/repository/tenants/1/userstores/wrbts.xml {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator}
TID: [-1234] [] [2018-10-22 16:42:20,390] ERROR {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator} -  Error while updating secondary user store password for tenant {org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator}
org.wso2.carbon.core.util.CryptoException: Error during encryption
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:184)
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:198)
	at org.wso2.carbon.core.util.CryptoUtil.encryptAndBase64Encode(CryptoUtil.java:227)
	at org.wso2.carbon.is.migration.service.v530.util.EncryptionUtil.getNewEncryptedValue(EncryptionUtil.java:29)
	at org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator.updatePassword(UserStorePasswordMigrator.java:124)
	at org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator.updateTenantConfigs(UserStorePasswordMigrator.java:70)
	at org.wso2.carbon.is.migration.service.v530.migrator.UserStorePasswordMigrator.migrate(UserStorePasswordMigrator.java:55)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:41)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:74)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: too much data for RSA block
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:177)
	... 69 more

**Comment by coffeeburrito** [comment] 2019-03-20 18:47
@tharikaGitHub Did you ever identify the root cause or solution?

**Comment by coffeeburrito** [comment] 2019-03-20 20:06
The keystore used for password encryption was changed, so it wasn't able to read the old passwords. I assume it's trying to encrypt a stack trace or some other error as the new password, and that's "too much data".

**Comment by isharak** [comment] 2021-04-09 10:46
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 10:46 UTC
