### ISSUE TITLE
Support multiple login names in userstores (JDBC/LDAP/AD)

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#5071] opened 2019-04-17 07:22 UTC
We need to improve all user stores. 
For, LDAP, we need a way to define the attribute set which is being searched for the user name.
For, JDBC, we need to improve the query to include a list of attributes in sub-query or something alike.

Furthermore, we need to treat subjectId, userId and user-name separately.

**Comment by rksk** [comment] 2021-05-06 13:55
Seems like a duplicate of https://github.com/wso2/product-is/issues/8899

**Comment by isharak** [comment] 2024-11-05 20:23
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-05 20:23 UTC
Labels: Type/NewFeature, commitment, IceBox
