### ISSUE TITLE
Unable to decrypt the SAML2 Assertion with AESxxx-GCM encryptions 

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15351] opened 2023-01-13 04:58 UTC
**Describe the issue:**
When a SAML app is configured with one of AESxxx-GCM encryption alogorithms, IS throws an error saying unable to decrypt.

**How to reproduce:**
1. Create a SAML app
2. In the inbound authentication configurations, changes the encryption algorithm to aes192-gcm and save.
3. Try login to the app

<img width="901" alt="Screenshot 2023-01-13 at 10 26 16" src="https://user-images.githubusercontent.com/47152272/212240768-0425d48f-6b86-4cb2-b3bb-1cc36b03961a.png">

**Expected behavior:**
Succesfully Login.

**Environment information**
 - Product Version: IS 6.1.0
 - OS: Mac
 - Database: Postgres
 - Userstore: jdbc
 - App: travelocity
 - Tomcat version: 8

**Comment by ashensw** [comment] 2023-01-24 14:33
The error can be seen in the sample application side in the tomcat logs as below,

`[org.apache.xml.security.algorithms.JCEMapper] : Request for URI http://www.w3.org/2009/xmlenc11#aes192-gcm
[org.apache.xml.security.encryption.XMLCipher] : JCE Algorithm = AES/GCM/NoPadding
[org.opensaml.xmlsec.encryption.support.Decrypter] : Error decrypting the encrypted data element
org.apache.xml.security.encryption.XMLEncryptionException: AlgorithmParameterSpec not of GCMParameterSpec
Original Exception was java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not of GCMParameterSpec
	at org.apache.xml.security.encryption.XMLCipher.decryptToByteArray(XMLCipher.java:1758)
Caused by: java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not of GCMParameterSpec
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineInit(GaloisCounterMode.java:281)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1442)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1375)
	at org.apache.xml.security.encryption.XMLCipher.decryptToByteArray(XMLCipher.java:1754)`

The encrypted SAML response is sent successfully from IS to the sample app. But the sample app is unable to decrypt it and complete the login as per the above error. The sample app is hosted in Tomcat 8, which is based on Java and Java Cryptography Extension (JCE), does not include support for the http://www.w3.org/2009/xmlenc11#aes192-gcm encryption algorithm out of the box. Therefore the limitation in tomcat and the sample app causing the above issue. Hence closing the issue since it's not a bug in the IS.

**Closed by ashensw** 2023-01-24 14:33 UTC
Labels: Priority/High, Severity/Blocker, bug, 6.1.0-bug-fixing
