### ISSUE TITLE
SMSOTP 404 Error after Doing first factor Auth

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7286] opened 2020-01-16 03:58 UTC
Pack: wso2is-5.9.0-1579140055660
It is a WUM updated pack. After entering username & password it lands on 404 error.

<img width="1436" alt="Screen Shot 2020-01-15 at 6 21 55 PM" src="https://user-images.githubusercontent.com/525801/72492044-bfdedb00-37d0-11ea-8d71-a35ccb84e644.png">

It seems the smsotpauthenticationendpoint.war is having an issue. There is a folder `smsotpauthenticationendpoint` inside the exploded directory.

../repository/deployment/server/webapps/smsotpauthenticationendpoint
├── META-INF
│   └── war-tracker
└── `smsotpauthenticationendpoint`
    ├── META-INF
    │   ├── MANIFEST.MF
    │   ├── maven
    │   │   └── org.wso2.carbon.extension.identity.authenticator.outbound.smsotp
    │   │       └── org.wso2.carbon.extension.identity.authenticator.smsotp.endpoint
    │   │           ├── pom.properties
    │   │           └── pom.xml
    │   └── war-tracker
    ├── WEB-INF
    │   ├── classes
    │   │   └── META-INF
    │   │       ├── DEPENDENCIES
    │   │       ├── LICENSE
    │   │       └── NOTICE
    │   └── web.xml
    ├── assets
    │   └── js
    │       └── jquery-3.4.1.min.js
    ├── bootstrap.min.css
    ├── css
    │   ├── Roboto.css
    │   └── custom-common.css
    ├── images
    │   ├── favicon.png
    │   ├── loading.gif
    │   └── logo-inverse.svg
    ├── js
    │   └── scripts.js
    ├── libs
    │   ├── bootstrap_3.4.1
    │   │   ├── css
    │   │   │   └── bootstrap.min.css
    │   │   └── js
    │   │       └── bootstrap.min.js
    │   └── jquery_3.4.1
    │       └── jquery-3.4.1.js
    ├── localstyles.css
    ├── mobile.jsp
    ├── smsotp.jsp
    └── smsotpError.jsp

**Comment by ajanthan** [comment] 2020-01-16 04:20
OS: 

> lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.3 LTS
> Release:	18.04
> Codename:	bionic

I have used inplace wum update.

**Comment by madurangasiriwardena** [comment] 2020-01-16 09:45
@ajanthan can you see any errors in the backend logs (at startup or during using this functionality)

**Comment by ajanthan** [comment] 2020-01-17 18:42
No error logs during the start-up or while getting 404.
BTW It is reproducible in MacOS as well. It is happening with "in place updated" pack.

**Comment by pulasthi7** [comment] 2020-10-14 04:22
Since this is not an issue with the public released dist, we'll track this outside the release. @vihanga-liyanage please do the needful as discussed offline

**Comment by vihanga-liyanage** [comment] 2020-10-14 11:54
This has been fixed with a WUM Update and cannot reproduce in the latest 5.9.0 WUM pack. @ajanthan can we close this?

**Comment by ajanthan** [comment] 2020-10-15 22:49
+1

**Closed** 2020-10-29 23:16 UTC
Labels: Priority/High, Severity/Critical, WUM
