### ISSUE TITLE
Username is not available once user logged into console

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14329] opened 2022-07-20 13:53 UTC
**Describe the issue:**
With the organization management feature, once the admin user logged in to the console, then clicks on the user avatar dropdown, it doesn't show the username.
<img width="1440" alt="Screenshot 2022-07-20 at 6 52 05 PM" src="https://user-images.githubusercontent.com/13362482/179999107-d32de3ec-c628-4522-90d4-771f731ee165.png">
 
**How to reproduce:**

- Login to the console (https://localhost:9443/console)
-  Click on the user avatar dropdown and check the username

**Expected behavior:**
The username should be available once logged in to the console

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by thivi** [comment] 2022-07-20 20:52
Since we are using the ID token to get the user information, we need the `username` attribute to be present in the ID token payload to obtain the username in the frontend. To do this, we need the `profile` scope, which is requested by the Console app by default during authentication. However, the IS should also share the `username` attribute with the Console app. We need to share this claim by default.

Is there a way by which we can get this done @AnuradhaSK @dewniMW?
![image](https://user-images.githubusercontent.com/20745428/180079742-3e8d2ff1-0926-49a9-a18e-16e7044276ed.png)

**Comment by ShanikaWickramasinghe** [comment] 2022-07-25 06:42
Observed the same issue.
pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/
Mysql 8.0.29, oracle jdk 17.0.3.1 
![Screenshot from 2022-07-25 12-10-05](https://user-images.githubusercontent.com/31848014/180714405-e2f9d5f5-d2a4-4897-a77a-2cf529fd155b.png)

**Comment by Maliesha** [comment] 2022-08-01 08:37
Closing the issue since this is not reproducable in IS 6.0.0 Beta.
<img width="1438" alt="Screenshot 2022-08-01 at 1 59 28 PM" src="https://user-images.githubusercontent.com/47919820/182107336-f180b1ee-ae98-42e6-b7e7-3cdf0579abed.png">

**Closed by Maliesha** 2022-08-01 08:37 UTC
Labels: ui, Severity/Blocker, bug, QA-Reported, IS-6.0.0-Test-Hackathon, Organization Management
