### ISSUE TITLE
Unable to login to User portal/ management console with users who added via Bulk import

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7640] opened 2020-02-16 04:59 UTC
**Description:**
Unable to log in to Management console/User portal users who added via Bulk import with the credentials which are provided in CSV   **with Tenant flow** 

Tested Environment:
Cluster setup ubuntu 16.4
Firefox browser

Step to reproduce:
1. Management Console -> Main menu, click Users and Roles.
2. Click Users
3. Click Bulk Import Users.
4. Finish 
5. Try to log in to management console with any user, and credentials which provided in CSV

**Comment by ShanikaWickramasinghe** [comment] 2020-02-21 08:14
Observing the same issue against default IS 5.10.0 beta4 snapshot pack as well in super tenant flow as well. Created bulk user is assigned with admin permissions. But when tries to log in to the management console login fails with the below-console log.

`[2020-02-21 13:41:03,420] [99b28756-2d19-46d5-84ec-4cce9c57ae25]  WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'JackDoe[-1234]' at [2020-02-21 13:41:03,420+0530]
`

**Comment by IsuraD** [comment] 2020-02-25 05:31
Tried the same thing in super tenant and tenant flows and could login to the MC as expected. 
Note: We need to assign login permission to the user to login to the MC

**Comment by IsuraD** [comment] 2020-02-25 06:10
Close the issue since it is not reproducing. Please reopen if the issue occurs again.

**Closed by IsuraD** 2020-02-25 06:10 UTC
Labels: Affected/5.10.0-Beta2, Priority/Highest, Severity/Critical, Type/Bug
