### ISSUE TITLE
The WSO2 Identity Server fails to start on JDK 11.0.20

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#16315] opened 2023-07-25 06:46 UTC
**Describe the issue:**
On both products IS-5.10.0.237, IS-5.11.0.255 and IS-6.1.0 tested, when the JDK version updates to 11.0.20 minor, the server fails to start with errors. (tested locally with OpenJDK 64-Bit Server VM 11.0.20+0,Homebrew)

```
ERROR {org.osgi.framework.FrameworkEvent} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.application.authenticator.requestpath.oauth [266]
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.oauth2.dto; version="[6.2.18,7.0.0)"
    -> Export-Package: org.wso2.carbon.identity.oauth2.dto; bundle-symbolic-name="org.wso2.carbon.identity.oauth"; bundle-version="6.4.2.99"; version="6.4.2.99"; uses:="javax.servlet.http,org.wso2.carbon.identity.application.authentication.framework.model,org.wso2.carbon.identity.oauth2,org.wso2.carbon.identity.oauth2.bean,org.wso2.carbon.identity.oauth2.model,org.wso2.carbon.identity.oauth2.token.bindings,org.wso2.carbon.identity.openidconnect.model"
       org.wso2.carbon.identity.oauth [335]
         Unresolved requirement: Import-Package: waffle.util; version="[1.6.0,2.0.0)"
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.oauth2; version="[6.2.18,7.0.0)"
    -> Export-Package: org.wso2.carbon.identity.oauth2; bundle-symbolic-name="org.wso2.carbon.identity.oauth"; bundle-version="6.4.2.99"; version="6.4.2.99"; uses:="org.wso2.carbon.core,org.wso2.carbon.identity.application.authentication.framework.exception,org.wso2.carbon.identity.base,org.wso2.carbon.identity.oauth.dto,org.wso2.carbon.identity.oauth2.bean,org.wso2.carbon.identity.oauth2.dto,org.wso2.carbon.identity.oauth2.model,org.wso2.carbon.identity.oauth2.token.bindings,org.wso2.carbon.user.api"

	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2023-07-25 12:03:29,237] [] ERROR {org.osgi.framework.FrameworkEvent} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.auth.service [275]
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.oauth2; version="[6.2.18,7.0.0)"
    -> Export-Package: org.wso2.carbon.identity.oauth2; bundle-symbolic-name="org.wso2.carbon.identity.oauth"; bundle-version="6.4.2.99"; version="6.4.2.99"; uses:="org.wso2.carbon.core,org.wso2.carbon.identity.application.authentication.framework.exception,org.wso2.carbon.identity.base,org.wso2.carbon.identity.oauth.dto,org.wso2.carbon.identity.oauth2.bean,org.wso2.carbon.identity.oauth2.dto,org.wso2.carbon.identity.oauth2.model,org.wso2.carbon.identity.oauth2.token.bindings,org.wso2.carbon.user.api"
       org.wso2.carbon.identity.oauth [335]
         Unresolved requirement: Import-Package: waffle.util; version="[1.6.0,2.0.0)"
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.oauth2.dto; version="[6.2.18,7.0.0)"
    -> Export-Package: org.wso2.carbon.identity.oauth2.dto; bundle-symbolic-name="org.wso2.carbon.identity.oauth"; bundle-version="6.4.2.99"; version="6.4.2.99"; uses:="javax.servlet.http,org.wso2.carbon.identity.application.authentication.framework.model,org.wso2.carbon.identity.oauth2,org.wso2.carbon.identity.oauth2.bean,org.wso2.carbon.identity.oauth2.model,org.wso2.carbon.identity.oauth2.token.bindings,org.wso2.carbon.identity.openidconnect.model"

	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**How to reproduce:**
1. Change JDK version to 11.0.20
2. Try to start the identity server
3. Server start fails with above errors.

**Expected behavior:**
Server should be able to start without any errors.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: e.g., IS 5.10.0 IS 5.11.0, IS6.0.0, IS 6.1.0, IS 6.2.0-alpha3
 - OS:LInux

**Comment by vfraga** [comment] 2023-08-14 23:20
Hi all,

The root cause for this issue was reported in the Jira for the `maven-bundle-plugin` [1], which is due to faulty behaviour in the bnd library [2]:
```ZIP extra fields are structured binary data. See section 4.5 of the ZIP File Format Specification. Bnd had incorrectly assumed the ZIP extra field could be treated as a UTF-8 encoded string. However, the structured binary data of a ZIP extra field cannot be safely decoded as UTF-8 data into a String and then re-encoded into UTF-8 data when writing a ZIP file. This resulted in corrupting the ZIP extra fields when wrapping a jar.```

This was fixed in `maven-bundle-plugin` version 5.1.5, so we need to update the plugin version in our fork of `waffle-jna` [3]. (I'm unsure if this needs to be propagated to all components or just this fork, hopefully just the former will suffice)

[1] https://issues.apache.org/jira/browse/FELIX-6622
[2] https://github.com/bndtools/bnd/issues/4507#issuecomment-771925051
[3] https://github.com/wso2/orbit/blob/master/waffle/1.6.wso2v6/pom.xml#L67

**Comment by NteCHourSHOcu** [comment] 2023-08-15 08:12
I see the fix is currently in review, when can we expect it on the wso2 update channel?

**Comment by isharak** [comment] 2024-11-07 05:54
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 05:54 UTC
Labels: Type/Bug, IceBox
