### ISSUE TITLE
Federation authentication with requesting claims only prompt the IDP side consent page.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7686] opened 2020-02-18 06:51 UTC
**Environment**:

DB:  Mssql 2019
userStore: Primary/UniqueID read and write Ldap

Federation authentication with requesting claims only prompt the IDP side consent page. Form the SP side also consent page should prompt. 

Steps to recreate:
01. Get two IS servers and configure one IS as the federated IDP  (Secondary IS) [1]
02. Configure the other IS as the SP which request do the federated authentication (Primary IS) [1]
03. Create user at secondary IS and add profile details
04. Add the claim configuration at secondary ID SP
![image](https://user-images.githubusercontent.com/39077751/74710578-fe403d80-5247-11ea-9f36-ae7cfef15430.png)
05. Add the federate authentication and at primary IS service provider and configure requested claims as well.

![image](https://user-images.githubusercontent.com/39077751/74710714-524b2200-5248-11ea-8685-30c1cdc3f173.png)

05. Login to the application for the first time with created user.

After 5th steps current behavior is its prompt the secondary IS consent page and continue the login without prompt consent page of the primary IS.

[1] https://is.docs.wso2.com/en/latest/learn/log-in-to-the-identity-server-using-another-identity-server-saml2/

**Comment by janakamarasena** [comment] 2020-02-18 14:35
Cannot reproduce. Hence closing.

**Comment by aaujayasena** [comment] 2020-02-24 09:13
This is reproduce only at mssql DB. For h2 and mysql this is working as expected. Therefor reopen the issue.

**Comment by isharak** [comment] 2024-11-06 03:07
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 03:07 UTC
Labels: Priority/High, Severity/Major, Type/Bug, Affected/5.10.0-Beta2, IceBox
