### ISSUE TITLE
[Consent][SSO] OIDC flow should get user consent before share any user attribute via IDToken.

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2428] opened 2018-02-16 13:56 UTC
OIDC flow should get user consent before share any user attribute via IDToken.  This behaviour should be consistent when some one call UserInfo endpoint as well that is UserInfo should only return user attributes if the consent is present only, if there is no consent or current consent is revoked IS should not share user any user attributes.

**Comment by mefarazath** [comment] 2018-03-07 08:26
Duplicate of https://github.com/wso2/product-is/issues/2400

**Closed by mefarazath** 2018-03-07 08:26 UTC
Labels: Affected/5.5.0-Alpha, Priority/Highest, Severity/Blocker, Type/Improvement
