### ISSUE TITLE
[ISSUE] Application template API throws server internal error

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7989] opened 2020-03-31 04:12 UTC
**Describe the issue:**

In the following condition application templates, API is creating a server internal error
1. If the configuration store is not enabled and try to get the template in the get request

```
ERROR {org.wso2.carbon.identity.api.server.application.management.v1.core.functions.Utils} - errorCode: TMM_00017 | message: Error occurred while retrieving templates of type APPLICATION_TEMPLATE of the tenant: carbon.super from the database. org.wso2.carbon.identity.template.mgt.exception.TemplateManagementServerException: Error occurred while retrieving templates of type APPLICATION_TEMPLATE of the tenant: carbon.super from the database.....
Caused by: org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementClientException: Configuration management feature is not enabled

```

2. After enabling the configuration store if we don't create a template and try to get the template list

```
org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementClientException: Resource type with the name: APPLICATION_TEMPLATE does not exists.
```

**How to reproduce:**
#### scenario 1
1. Start the fresh pack an try  to send **GET** request to `api/server/v1/applications/templates`

#### scenario 2
1. [Enable the configuration management](https://is.docs.wso2.com/en/next/develop/using-the-configuration-management-rest-apis/#). and restart the server.
2. Now send **GET** request to `api/server/v1/applications/templates`

**Comment by mefarazath** [comment] 2021-01-11 13:26
Verified with IS 5.12.0-M5 SNAPSHOT, the issue is not reproducible.

This has been fixed with https://github.com/wso2/product-is/issues/7989 where we enable the configuration store by default by adding the required tables and also add the APPLICATION_TEMPLATES resource through the DB script.

**Closed by mefarazath** 2021-01-11 13:26 UTC
Labels: 5.12.0-bug-fixing, Affected/5.11.0-m12, Severity/Major, bug, checked, to-be-reviewed
