### ISSUE TITLE
Null entry in the permission tree

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#6270] opened 2019-08-31 06:31 UTC
![image](https://user-images.githubusercontent.com/11584828/64060200-0bf4fe80-cbe7-11e9-8f3c-93bcd899f2f2.png)

**Comment by ayshsandu** [comment] 2019-09-23 06:38
Duplicate of https://github.com/wso2/product-is/issues/6049

**Closed by ayshsandu** 2019-09-23 06:38 UTC
Labels: Affected/5.9.0-Alpha
