### ISSUE TITLE
Access Token Not Revoked Due to Disabled Autocommit in deployment.toml Configuration

### ISSUE THREAD

**Issue by leonardorobertolopez** [wso2/product-is#21804] opened 2024-11-22 23:25 UTC
**Describe the issue:**
The issue occurs in the authentication flow when the configuration for the identity database in the deployment.toml file is set to defaultAutoCommit = "false". In this case, a second insert into the IDN_OAUTH2_TOKEN_BINDING table is not being committed properly, resulting in the absence of the DEFAULT token binding record. The insert only commits the sso-session record, and as a result, the Access Token (AT) is not revoked after executing a DELETE api/users/v1/me/sessions request. This prevents the AT from being invalidated after session deletion, which should occur to prevent further use of the AT.

The root cause is that the insert operation lacks proper transaction handling, causing it to fail when the defaultAutoCommit is set to false. As a result, the AT is not revoked, and the flow exits prematurely without processing the token revocation logic.

**How to reproduce:**
1. Set up an OAuth2.0/OpenID Connect-based application with the following characteristics:
- Grant type: Code
- Redirect URL: a valid URL for your application
- Token Binding Type: sso-session
- Enable the option to revoke tokens upon user logout.

2. Configure the identity database with the defaultAutoCommit = "false" setting in the deployment.toml file.

3. Implement a custom federated authenticator to handle authentication in the flow.

4. Use an adaptive script to bypass the username/password prompt during login.

5. Test the login flow and ensure that the second insert into the IDN_OAUTH2_TOKEN_BINDING table only includes the sso-session record, without the DEFAULT entry.

6. Try making a DELETE request to api/users/v1/me/sessions to delete the user's sessions.

**Expected behavior:**
The insert should commit both the sso-session and DEFAULT records to the IDN_OAUTH2_TOKEN_BINDING table. After the DELETE api/users/v1/me/sessions request is made, the Access Token (AT) should be revoked and the related records should reflect this revocation.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: IS 7.0
OS: Windows
Database: MySQL 8.0.35
Userstore: JDBC

---

### Optional Fields

**Related issues:**
N/A

**Suggested labels:**

**Comment by RushanNanayakkara** [comment] 2024-12-04 04:36
This issue was caused by having both `rollbackOnReturn` and `commitOnReturn` configurations enabled on the identity database pool configurations. The issue was resolved after removing `rollbackOnReturn` configuration. 

Since this is not a bug and need no fix, I'm closing the issue.

**Closed by RushanNanayakkara** 2024-12-04 04:36 UTC
Labels: Type/Bug, U2
