### ISSUE TITLE
Only Username is shown under Attributes section for a SPA Application and observing something went wrong

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14561] opened 2022-08-06 07:31 UTC
**Describe the issue:**
1. Create a SPA
2. Go to Attributes Tab
3. Try to edit and add a new attribute

Only Username is displayed as the attribute in the attribute list

Observed a something went wrong too intermittently .

Attaching video

https://user-images.githubusercontent.com/31848014/183239357-7a53074b-d0a5-46b3-a78f-1f3d6b25350d.mp4

**Env**
Pack https://drive.google.com/file/d/1h3ynCA_1kLKPovRahbDtrtGvFYxXkbvs/view
H2 default

**Comment by piraveena** [comment] 2022-08-06 10:01
Calling a wrong API
 
```
curl 'https://localhost:9443/api/server/v1/claim-dialects/%7B%7D/claims' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Access-Control-Allow-Origin: https://localhost:9443' -H 'Authorization: Bearer e9cd4d04-c421-3263-8560-e6125eac430b' -H 'Connection: keep-alive' -H 'Cookie: menuPanel=visible; menuPanelType=main; JSESSIONID=F343628DB921B97F22061343B915695D; atbv=492eb4e9-5cf2-4adb-80df-77c81e4f853e; current-breadcrumb=; requestedURI=../../carbon/admin/index.jsp; MSG16596118471050.0706825729849534=true; MSG16596118624330.7537068765946476=true; MSG16596118785040.7749237820961196=true; MSG16596118985490.877019379946138=true; MSG16596119129010.7647916899344912=true; MSG16596119999430.8156992988530211=true; MSG16596138531730.29097706227261433=true; MSG16596138841350.6163266218630801=true; MSG16596143641490.7039235775637004=true; MSG16596144038730.07760969951706365=true; MSG16596180182980.4507268516291716=true; MSG16596180283850.9893186009847007=true; MSG16596635549020.612514011522885=true; commonAuthId=d88ad8d1-ce98-444d-84cb-d62bc5c24cda; opbs=e6d60d55-817c-4a9a-af96-019699ed52a5' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin'
```

**Comment by VivekVinushanth** [comment] 2022-08-07 07:02
Closing since it is tracked with https://github.com/wso2/product-is/issues/14589

**Comment by VivekVinushanth** [comment] 2022-08-07 18:56
Regression due to: 
- https://github.com/wso2/identity-apps/pull/3291

**Comment by VivekVinushanth** [comment] 2022-08-08 17:19
Closing the issue, since the 400 (something went wrong issue) is fixed with the PR (version:1.4.8)

https://user-images.githubusercontent.com/32198547/183475950-940fa0c8-c7d7-44d4-b947-3412cbeeb482.mp4

**Comment by VivekVinushanth** [comment] 2022-08-08 17:22
Username shown issue is tracked with 
- https://github.com/wso2/product-is/issues/14589

**Comment by NilukaSripalim** [comment] 2022-08-09 14:13
https://github.com/wso2/product-is/issues/14678

**Comment by ShanikaWickramasinghe** [comment] 2022-08-09 14:20
@VivekVinushanth can we check this

**Comment by VivekVinushanth** [comment] 2022-08-10 05:09
We checked and closed this. Can you confirm with latest pack and update the status?

**Comment by VivekVinushanth** [comment] 2022-08-10 05:15
And the reason is not because of attributes, is it? THis particular issue is for attribute related 404. The BE logs you have attached says roles. @NilukaSripalim ? Why you just reopened this issue if you care to clarify?

**Comment by NilukaSripalim** [comment] 2022-08-10 05:55
I didn't change any thing , Just took fresh pack and create a new application

**Comment by VivekVinushanth** [comment] 2022-08-10 05:56
Tested and it was specific to roles (role mapping) and not attribute related.

**Comment by NilukaSripalim** [comment] 2022-08-10 05:59
[Screen Recording 2022-08-10 at 11.22.35.zip](https://github.com/wso2/product-is/files/9297161/Screen.Recording.2022-08-10.at.11.22.35.zip)

**Comment by NilukaSripalim** [comment] 2022-08-10 06:03
We can refer this issue : https://github.com/wso2/product-is/issues/14678

**Closed** 2022-08-10 06:33 UTC
Labels: ui, Priority/Highest, Severity/Blocker, bug, console, Affected-6.0.0, QA-Reported, 6.0.0-rc-testing
