### ISSUE TITLE
Email OTP Does Not Redirects To The Authentication Page

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#6431] opened 2019-09-12 13:06 UTC
**Steps to Reproduce:**

1. Configure basic auth as the first step and the Email OTP as the second step for a service provider, with OAuth2 as the inbound authentication protocol.
2. Try to log in to the application.
3. Once you are successfully authenticated with the basic auth, you will be redirected to the Email OTP authentication page with the redirected URL having the **oauth2** path parameter appended.
![Screenshot from 2019-09-12 18-19-21](https://user-images.githubusercontent.com/22551445/64785468-11106100-d58a-11e9-84d3-1c591da6ecbe.png)
4. Clearing this parameter manually resolves the issue.
![Screenshot from 2019-09-12 18-19-29](https://user-images.githubusercontent.com/22551445/64785490-208faa00-d58a-11e9-90ae-c38c90597bf9.png)
(If the error does not reproduce, try using an adaptive authentication script in the flow)

**Possible Cause:**
The issue occurs when the [servlet is trying to resolve the path to the login page](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/7770196749780c9affcc6c9939281ec9922d36c4/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L808)[1], with the relative path provided in the application-authentication.xml for the Email OTP.

**Workaround to avoid the Issue:**
Change the relative path in `<Parameter name="EMAILOTPAuthenticationEndpointURL">emailotpauthenticationendpoint/emailotp.jsp` parameter under Email OTP configuration in the `<IS_HOME>/repository/conf/identity/application-authentication.xml`, to the absolute path `<Parameter name="EMAILOTPAuthenticationEndpointURL">https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp`

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/7770196749780c9affcc6c9939281ec9922d36c4/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L808

**Comment by madurangasiriwardena** [comment] 2020-03-03 12:02
Duplicate of https://github.com/wso2/product-is/issues/6451

**Closed by madurangasiriwardena** 2020-03-03 12:02 UTC
Labels: Affected/5.8.0, Affected/5.9.0-Alpha2, Priority/High, Severity/Major, Type/Bug
