### ISSUE TITLE
Not able to add Backchannel logout URL via management console

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7107] opened 2019-12-16 09:48 UTC
Affected in 5.8.0
Steps to reproduce:

- Add a service provider in IS 5.8.0
- Go to Inbound Authentication Configuration > OAuth/OpenID Connect Configuration.
- Enable OIDC Backchannel Logout
- Add Backchannel Logout Url 
- Update the Service Provider
- Go to Edit and Again check the Service provider config
- Enable OIDC Backchannel Logout and add Backchannel Logout Url  are not visible in the UI

**Comment by piraveena** [comment] 2019-12-16 10:02
Fixed in IS 5.9.0 with this PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1150

**Comment by madurangasiriwardena** [comment] 2020-01-22 10:08
Closing since the issue cannot be reproduced in 5.10.0 Alpha2.

**Comment by Dinithi-Hasanika** [comment] 2023-04-05 09:43
This issue is still there in the identity server 5.8. This has not been fixed in the identity server 5.8. Hence can not configure the OIDC Backchannel logout

**Comment by mpmadhavig** [comment] 2023-04-07 11:13
Getting fixed with: https://github.com/wso2-support/identity-inbound-auth-oauth/pull/1353

**Closed** 2023-04-12 05:08 UTC
