### ISSUE TITLE
Content Missing on the HYPR Connection " Settings " Page and therefore the connection is uneditable. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16998] opened 2023-10-17 05:10 UTC
**Describe the issue:**
The Settings page on the HYPR connections page has an empty page with a Button.

<img width="1511" alt="Screenshot 2023-10-17 at 10 30 19" src="https://github.com/wso2/product-is/assets/41188245/68dc8a4c-c453-493c-9511-34a062961570">

**How to reproduce:**

1. Configure HYPR connection
2. Try to edit the Connector using the React console settings page.

**Expected behavior:**
The page should contain the relevant settings options.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Identity Server-7.0.0-m4-SNAPSHOT
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnjanaSamindraPerera** [comment] 2023-11-23 06:04
Closing this issue since it's not reproducible with the wso2is-7.0.00-beta pack.

**Comment by melanisilva** [comment] 2023-11-23 06:05
Verified in the Beta pack 
<img width="1211" alt="Screenshot 2023-11-23 at 11 33 38" src="https://github.com/wso2/product-is/assets/41188245/5efb175d-16b4-42a9-86fd-a59ad81c6524">

**Closed by AnjanaSamindraPerera** 2023-11-23 06:04 UTC
Labels: Priority/Highest, Severity/Critical, bug, Component/Connectors
