### ISSUE TITLE
Error in starting the server with Email Notification Handler v5.1.1 connector

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#13892] opened 2022-06-09 07:32 UTC
**Describe the issue:**
When starting the IS with the [Email Notification Handler v5.1.1 connector](https://store.wso2.com/store/assets/isconnector/details/959b792a-efce-4b12-af9b-4744c650f6b2) included, the following error is logged in the terminal.

```
[2022-06-09 12:49:17,412] [] ERROR {org.wso2.carbon.identity.notification.mgt} - [SCR] Error while trying to bind reference Reference[name = ldap.tenant.manager.listener.service, interface = org.wso2.carbon.identity.notification.mgt.NotificationSendingModule, policy = dynamic, cardinality = 0..n, target = null, bind = addNotificationSendingModule, unbind = removeNotificationSendingModule]
	Details:
	Problematic reference = Reference[name = ldap.tenant.manager.listener.service, interface = org.wso2.carbon.identity.notification.mgt.NotificationSendingModule, policy = dynamic, cardinality = 0..n, target = null, bind = addNotificationSendingModule, unbind = removeNotificationSendingModule]
	of service component = carbon.identity.notification.mgt
	component implementation class = org.wso2.carbon.identity.notification.mgt.internal.NotificationManagementServiceComponent
	located in bundle with symbolic name = org.wso2.carbon.identity.notification.mgt
	bundle location = reference:file:../plugins/org.wso2.carbon.identity.notification.mgt_5.20.399.jar java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444)
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.identity.notification.mgt.email.internal.EmailMessageSendingServiceComponent.activate(EmailMessageSendingServiceComponent.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.notification.mgt.email.EmailSendingModule.init(EmailSendingModule.java:162)
	at org.wso2.carbon.identity.notification.mgt.internal.NotificationManagementServiceComponent.addNotificationSendingModule(NotificationManagementServiceComponent.java:147)
	... 35 more
```

**How to reproduce:**
1. Download the connector org.wso2.carbon.identity.notification.mgt.email-5.1.1 from the [WSO2 Store](https://store.wso2.com/store/assets/isconnector/details/959b792a-efce-4b12-af9b-4744c650f6b2) and place it the `<IS_HOME>/repository/components/dropins` directory.
2. Start the IS.
3. Observe the terminal.

**Environment information :**
 - Product Version: IS 6.0.0 - m1
 - OS: Mac OS 12.3.1
 - Database: Oracle 12c
 - Userstore: JDBC

**Comment by asha15** [comment] 2022-09-02 06:30
The error could not reproduce in IS 6.0.0. Hence closing this issue.

Please fellow the steps specified in the documentation: https://is.docs.wso2.com/en/latest/guides/tenants/user-operation-notifications

**Closed by asha15** 2022-09-02 06:30 UTC
Labels: bug, IS-6.0.0-Test-Hackathon
