### ISSUE TITLE
When click "Sign-In" from Self-registration get redirected to user-portal

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9338] opened 2020-08-28 11:32 UTC
**Describe the issue:**
If a user wants to quit self-registration and login to the system, in the middle of a self-registration flow, redirected to broken page.

**How to reproduce:**
1. Enable self-registration for a tenant
2. Access `myaccount` app and click `Create account`
3. Pick a username and proceed to self-register
4. Cancel by clicking `Sign in` in  `Already have an account? Sign in`
![image](https://user-images.githubusercontent.com/5061791/91556414-4efbc600-e950-11ea-84f8-66149aafd831.png)

5. user is redirected to `https://localhost:9443/user-portal` which is not an existing page/app

**Expected behavior:**
- Redirected to myaccount loin page.

**Comment by brionmario** [comment] 2020-08-28 11:41
Duplicate of #9328 and was fixed by wso2/carbon-identity-framework#3086.

**Closed by brionmario** 2020-08-28 11:41 UTC
Labels: Priority/Highest, Severity/Critical, bug
