### ISSUE TITLE
Issue when sending SMSOTP

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6713] opened 2019-10-24 07:25 UTC
The following exception is printed when trying to send a SMSOTP

```
[2019-10-23 20:26:39,477] [f9cd11d4-4c33-4699-a854-c360a621378d] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NoClassDefFoundError: org/apache/catalina/util/URLEncoder
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.sendRESTCall(SMSOTPAuthenticator.java:1114)
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:557)
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.initiateAuthenticationRequest(SMSOTPAuthenticator.java:171)
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.process(SMSOTPAuthenticator.java:113)
at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:502)
at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:267)
at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)
at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:155)
at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:239)
at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
```

**Comment by danijelt** [comment] 2019-11-14 09:29
Is there any fix available for 5.9.0 for this issue? Identity Server is useless to me without SMSOTP.

**Comment by danijelt** [comment] 2019-11-15 06:27
I fixed it myself. I removed org.apache.catalina.util.URLEncoder dependency because it's not needed in my case.

**Comment by lpastor74** [comment] 2019-12-15 06:46
Is this still open issue? Do we have any ETA? It is blocker.

**Comment by darshanasbg** [comment] 2019-12-15 14:51
> Is this still open issue? Do we have any ETA? It is blocker.

I have reproduced the issue in wso2is-5.10.0-m9. We probably will get this fixed by 5.10.0 alpha which likely to be release in the upcoming week.

**Comment by lpastor74** [comment] 2019-12-15 15:38
Is there any fix around for this? It looks the issue is caused but some
reference lib .

NoClassDefFoundError: org/apache/catalina/util/*URLEncoder*
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.sendRESTCall(SMSOTPAuthenticator.java:1114)
at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:557)

I have a demo tomorrow? Should I remove this completely from the
presentation ?

**Comment by darshanasbg** [comment] 2019-12-15 15:54
> Is there any fix around for this? It looks the issue is caused but some reference lib . NoClassDefFoundError: org/apache/catalina/util/*URLEncoder* at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.sendRESTCall(SMSOTPAuthenticator.java:1114) at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:557) I have a demo tomorrow? Should I remove this completely from the presentation ?

As you are blocked on tasks related to WSO2 Internals please use proper channels get expected outcome. I guess team already was on touch with you.

Please use public channels for pure community aspects, so any requests raised through those channels are considered as community requests and giving maximum priority within it limits..

Right now, im working on fixing this and will be available in the next public release as I mentioned above. KIT on any status updates.

**Comment by danijelt** [comment] 2019-12-15 16:19
@lpastor74 You can replace the Apache URLEncoder with Java's standard one, compile the authenticator and replace the one bundled in IS. It's used for rewriting URL if your SMS endpoint uses receives message in GET request. If you don't send any special characters in the payload or if you use POST, then this change is safe.

**Comment by darshanasbg** [comment] 2019-12-15 17:04
> @lpastor74 You can replace the Apache URLEncoder with Java's standard one, compile the authenticator and replace the one bundled in IS. It's used for rewriting URL if your SMS endpoint uses receives message in GET request. If you don't send any special characters in the payload or if you use POST, then this change is safe.

@danijelt Done the fix as you mentioned. Please add review comments, if you have any.

**Comment by darshanasbg** [comment] 2019-12-15 17:34
Reported related doc issue with: https://github.com/wso2/docs-is/issues/981

**Closed** 2019-12-15 17:42 UTC
Labels: Priority/High, Severity/Blocker, Type/Bug

**Comment by janakamarasena** [comment] 2020-09-23 15:57
This jar should contain the fix https://maven.wso2.org/nexus/content/repositories/public/org/wso2/carbon/extension/identity/authenticator/outbound/smsotp/org.wso2.carbon.extension.identity.authenticator.smsotp.connector/2.0.30/org.wso2.carbon.extension.identity.authenticator.smsotp.connector-2.0.30.jar

Can add it to the distribution by removing the existing `org.wso2.carbon.extension.identity.authenticator.smsotp.connector` jar from `/repository/components/dropins` and add the jar from the above link
