### ISSUE TITLE
Identify if the SMS Service Provider API responded successfully or not when using HTTP Event Adapter

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15788] opened 2023-04-25 17:19 UTC
**Describe the issue:**
In the SMS OTP Authenticator, we can set the `HTTP Response Code` value in UI to check if the SMS Service Provider accepted the request successfully or not [1].

However, if the SMS OTP was sent via an HTTP Output event adapter [2], there is no mechanism to identify if the SMS Service Provider accepted the request properly or not because the HTTP Event Adapter fire and forget the http request [3].

It is required to improve HTTP output event adapter to configure the successful HTTP response codes and log if it receives something else similar to [4].

**How to reproduce:**

1. Configure SMS OTP [5] without adding the SMS service provider URL (the authenticator will pass the HTTP request to the output event adapter [2]).
2. Configure HTTP output event adapter to send SMS notifications as in [6].
3. Set an invalid SMS service provider URL in the event adapter.
4. Configure MFA for a service provider and try the flow.
5. There is no way to identify if the SMS service provider received the request or not.

**Expected behavior:**

- Successful HTTP error codes should be configurable.
- An error should be logged if the response code is different from the configured successful HTTP codes.

**Environment information:**
 - Product Version: IS 5.11.0

---

[1] - https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/eb528805a350bf1473a67059ea4a987d8854dbbc/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1301-L1312
[2] - https://github.com/wso2/product-is/issues/13394
[3] - https://github.com/wso2/carbon-analytics-common/blob/bfda1eaf41ea5c6df8f5878e616dbee4c8378c7a/components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapter.java#L154
[4] - https://github.com/wso2/product-is/issues/14846
[5] - https://is.docs.wso2.com/en/5.11.0/learn/configuring-sms-otp/#add-disable-smsotp-option-for-users
[6] - https://is.docs.wso2.com/en/5.11.0/develop/enable-verification-for-updated-mobile-number/#step-01-add-an-event-publisher-to-send-sms

**Comment by asha15** [comment] 2023-05-11 05:35
The issue is fixed in update level 240.

**Closed by asha15** 2023-05-11 05:35 UTC
Labels: bug, WUM

**Comment by asha15** [comment] 2023-05-18 08:23
This is fixed in 5.11 and latest releases as well (IS 6.0.0 and IS 6.1.0)
