### ISSUE TITLE
Hello,The file path specified "<IS_HOME>/repository/conf/identity/deployment.toml" in section 14 does not exist on my machine.The 

### ISSUE THREAD

**Issue by KwadwoObeng** [wso2/product-is#10542] opened 2020-11-18 16:48 UTC
Location : https://is.docs.wso2.com/en/latest/learn/configuring-email-otp/

**Comment by omindu** [comment] 2020-11-19 06:50
Duplicate of https://github.com/wso2/product-is/issues/10543

**Closed by omindu** 2020-11-19 06:50 UTC
Labels: Resolution/Duplicate, docs
