### ISSUE TITLE
Support pagination for groups

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#8919] opened 2020-07-20 13:29 UTC
### Requirement

Currently, when we list the Users from the UI and via SCIM, we have the option to paginate the user listing. If we do the same to the groups, we don't have the option to paginate the groups listing.

#### Related Issues
- https://github.com/wso2/product-is/issues/7664

**Comment by madurangasiriwardena** [comment] 2020-07-22 11:29
Duplicate of https://github.com/wso2/product-is/issues/7662

**Closed by madurangasiriwardena** 2020-07-22 11:29 UTC
Labels: consumer-exp, feature
