### ISSUE TITLE
"Organization Administrators" page provided console link is based on managent console not the console url

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16960] opened 2023-10-14 10:21 UTC
$subject
![Administrators](https://github.com/wso2/product-is/assets/39120228/6ae4196d-df24-47c4-b851-18c44afb94a9)

1. Login to console
2. Go to Organizational Settings
3. Click on Organization Administrators

**Comment by pavinduLakshan** [comment] 2023-10-16 05:44
Duplicate of https://github.com/wso2/product-is/issues/16892

**Closed by pavinduLakshan** 2023-10-16 05:44 UTC
Labels: ui, Priority/Highest, Severity/Major, bug, affected - 7.0.0 m4
