### ISSUE TITLE
Add templateId attribute to IDP REST API

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#11023] opened 2021-01-20 14:45 UTC
**Is your feature request related to a problem? Please describe.**
We need to do $subject similar to applications. templateId is required to show some details pulled from the template in the UI. Once the attribute is added, it should be returned in, 

1. GET IDP by ID response
2. IDP listing REST API response

**Comment by AnuradhaSK** [comment] 2021-01-21 14:27
1st part of the issue is resolved by PRs: https://github.com/wso2/carbon-identity-framework/pull/3343, https://github.com/wso2/identity-api-server/pull/256

2nd part of the issue is not resolving atm due to the same reason (related to IDP and IDP_METADATA  tables) as mentioned in https://github.com/wso2/product-is/issues/10681#issuecomment-764413536.

**Closed** 2021-02-02 06:21 UTC
Labels: Component/Identity REST APIs, Severity/Blocker, feature, ui
