### ISSUE TITLE
Getting an Error log while updating group in console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10422] opened 2020-11-09 16:49 UTC
**Describe the issue:**
Try to update create a group  by adding a role, then getting an Error log in carbon log

```
[63cf4d9e-447c-4910-b4cc-069001da2db1] ERROR {org.wso2.carbon.user.mgt.UserRealmProxy} - UI permissions of Admin is not allowed to change
```

**How to reproduce:**
Create a group via console without adding user/ role
Create a role via console without adding user/ group
Try to update the created group by adding the created role to the group

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta6 SNAPSHOT
 - OS: Mac
 - Database: Postgres12.4Oracle19c
 - Userstore: JDBC

---

**Comment by janakamarasena** [comment] 2020-11-10 06:28
could not reproduce

**Comment by piraveena** [comment] 2020-11-10 07:51
@NilukaSripalim Could not reproduce this issue. Hence closing this issue.

**Closed by piraveena** 2020-11-10 07:51 UTC
Labels: Affected/5.11.0-Beta, Priority/Highest, Severity/Critical, bug
