### ISSUE TITLE
SAML back channel SLO not working

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9985] opened 2020-10-21 05:58 UTC
**Describe the issue:**
1. Configured SAML back channel SLO using the doc [1]
2. Once logout form one application other application doesn't get logged out.
3. Getting following errors in the console.
```
[2020-10-21 11:16:55,811] [24186cc2-8c3c-4ad9-966a-c7ea318b08ad]  INFO {org.wso2.carbon.identity.sso.saml.logout.LogoutRequestSender} - Sending single log out request again with retry count 1 after waiting for 60000 milli seconds to https://localhost:9443/identity/saml/slo
[2020-10-21 11:16:55,818] [24186cc2-8c3c-4ad9-966a-c7ea318b08ad]  WARN {org.wso2.carbon.identity.sso.saml.logout.LogoutRequestSender} - Failed single logout response from https://localhost:9443/identity/saml/slo with status code Internal Server Error

```

[1] https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**How to reproduce:**
1. Configured SAML back channel SLO using the doc [1]
2. Once logout form one application other application doesn't get logged out.
3. Getting following errors in the console.
```
[2020-10-21 11:16:55,811] [24186cc2-8c3c-4ad9-966a-c7ea318b08ad]  INFO {org.wso2.carbon.identity.sso.saml.logout.LogoutRequestSender} - Sending single log out request again with retry count 1 after waiting for 60000 milli seconds to https://localhost:9443/identity/saml/slo
[2020-10-21 11:16:55,818] [24186cc2-8c3c-4ad9-966a-c7ea318b08ad]  WARN {org.wso2.carbon.identity.sso.saml.logout.LogoutRequestSender} - Failed single logout response from https://localhost:9443/identity/saml/slo with status code Internal Server Error

```

**Expected behavior:**
First application should automatically logged out

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by sachiniWettasinghe** [comment] 2020-10-26 05:36
@nilasini Were you trying SAML backchannel SLO or SAML SLO with Federated Identity Providers as pointed in [1]?

[1] https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Comment by sachiniWettasinghe** [comment] 2020-11-04 04:38
Could not reproduce the above issue by configuring SAML SLO with a federated Identity provider as mentioned in [1] with a set up of wso2is-5.11.0-beta4-SNAPSHOT. Hence closing the issue. 

[1] https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Closed by sachiniWettasinghe** 2020-11-04 04:38 UTC
Labels: Priority/Highest, Severity/Critical, bug
