### ISSUE TITLE
db2 script error while creating UM_UUID_DOMAIN_MAPPER table

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7391] opened 2020-01-27 10:03 UTC
Getting following error when executing the db2 script

```
SQL Error [42831]: The column named "UM_USER_ID" cannot be a column of a primary key or unique key constraint because it can contain null values.. SQLCODE=-542, SQLSTATE=42831, DRIVER=4.23.42
  The column named "UM_USER_ID" cannot be a column of a primary key or unique key constraint because it can contain null values.. SQLCODE=-542, SQLSTATE=42831, DRIVER=4.23.42

```

**Comment by ShanikaWickramasinghe** [comment] 2020-01-27 11:27
Duplicate of https://github.com/wso2/product-is/issues/7337

**Comment by janakamarasena** [comment] 2020-01-28 13:14
Fixed in https://github.com/wso2/carbon-kernel/pull/2539

**Closed by janakamarasena** 2020-01-28 13:14 UTC
Labels: Affected/5.10.0-Alpha2, Priority/Highest, Severity/Blocker
