### ISSUE TITLE
NPE on DefaultServiceURLBuilder when authentication endpoint is hosted externally

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#16751] opened 2023-09-21 08:07 UTC
**Describe the issue:**
When the authentication portal is externally hosted, when the webapp tries to use the DefaultServiceURLBuilder method, it throws a NullPointerException as the app cannot access the configs packed inside the product. These configs need to be either be added to the webapp through web.xml or should find another mechanism to retrieve the configs to the webapp.

```
21-Sep-2023 10:11:44.703 SEVERE [https-jsse-nio-8443-exec-4] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet [oauth2_login.do] threw exception
	java.lang.NullPointerException
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.fetchPort(DefaultServiceURLBuilder.java:318)
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.build(DefaultServiceURLBuilder.java:90)
		at org.apache.jsp.login_jsp._jspService(login_jsp.java:3172)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthenticationEndpointFilter.doFilter(AuthenticationEndpointFilter.java:87)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
		at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthenticationEndpointFilter.doFilter(AuthenticationEndpointFilter.java:188)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
21-Sep-2023 10:11:44.704 SEVERE [https-jsse-nio-8443-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/authenticationendpoint] threw exception [An exception occurred processing [basicauth.jsp] at line [530]

527:             }
528: 
529:             // For self sign-up build the normal callback URL.
530:             String srURI = ServiceURLBuilder.create().addPath(AUTHENTICATION_ENDPOINT_LOGIN).build().getAbsolutePublicURL();
531:             String srprmstr = URLDecoder.decode(((String) request.getAttribute(JAVAX_SERVLET_FORWARD_QUERY_STRING)), UTF_8);
532:             String srURLWithoutEncoding = srURI + "?" + srprmstr;
533:             srURLEncodedURL= URLEncoder.encode(srURLWithoutEncoding, UTF_8);


Stacktrace:] with root cause
	java.lang.NullPointerException
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.fetchPort(DefaultServiceURLBuilder.java:318)
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.build(DefaultServiceURLBuilder.java:90)
		at org.apache.jsp.login_jsp._jspService(login_jsp.java:3172)
```
For this particular bug setting the config AUTHENTICATION_ENDPOINT_LOGIN in the web.xml and trying to retrieve it from there first will solve the issue. But adding the config in the web.xml for everytime might not be a scalable solution.

**How to reproduce:**
1. [Externally host the authentication portal ](https://is.docs.wso2.com/en/latest/references/extend/host-authentication-endpoint-on-a-different-server/) and try to login.
2. Check the <TOMCAT_HOME>/logs/localhost.<current date>.log file for the logs. The above error should appear.

**Expected behavior:**
- No errors in the log file and a succesful login attempt.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: latest
 - OS: Mac
 - Database: h2
 - Userstore: jdbc

**Comment by pavinduLakshan** [comment] 2023-09-21 08:42
Duplicate of https://github.com/wso2/product-is/issues/16640

**Comment by mpmadhavig** [comment] 2023-09-21 08:45
> Duplicate of #16640

That is a separate issue. The issue occurs in basicauth.jsp in this one.

**Closed** 2023-12-08 08:56 UTC
Labels: Severity/Critical, bug, backend
