### ISSUE TITLE
List of users not loading in console when a user's email address is updated to begin with a special character

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10148] opened 2020-10-28 13:39 UTC
**Describe the issue:**
The users from the primary user store are not loading in the console when a user's email address is updated to start with a special character (eg: /an@wso2.com). Email address as the username was enabled when the issue occurred. While the list of users **was** loaded in the management console, the user profile of the updated user could not be accessed or deleted. 

**How to reproduce:**
1. Enable email address as the username according to the doc[1].
2. Login to the console as admin and create a new user (eg: alan@wso2.com)
3. Login to My Account using the created user
4. Go to My Account > Personal Info and edit the email address to start with a special character and save (eg: /an@wso2.com)
5. Logout from my account and login as admin to the console
6. Go to Console > Manage > Users

Note: Restart the IS and repeat step 6 if the exception isn't thrown

[1] - https://is.docs.wso2.com/en/5.11.0/learn/using-email-address-as-the-username/

**Observation:**
An error message was displayed and an exception was thrown at step 6. The list of users was not displayed.
It's still possible to login from the other users.

**Exception:**
```
[2020-10-28 15:15:47,286] [a64f571d-497e-4203-b8d2-82428ebc48f6] ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while getting the users list for domain: PRIMARY org.wso2.charon3.core.exceptions.CharonException: Error while retrieving users for the domain: PRIMARY with limit: 10 and offset: 1.
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsernames(SCIMUserManager.java:1519)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersFromMultipleDomains(SCIMUserManager.java:1388)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsernamesAcrossAllDomains(SCIMUserManager.java:675)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsers(SCIMUserManager.java:499)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:453)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:347)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.carbon.user.core.UserStoreException: Invalid Domain Name
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreInternal(AbstractUserStoreManager.java:7223)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.lambda$getUserStore$10(AbstractUserStoreManager.java:7160)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStore(AbstractUserStoreManager.java:7160)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserIDFromUserName(AbstractUserStoreManager.java:12185)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUser(AbstractUserStoreManager.java:12116)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager.doGetUserListWithID(UniqueIDReadOnlyLDAPUserStoreManager.java:1456)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:14776)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsernames(SCIMUserManager.java:1494)
	... 66 more
```

**Environment information:**
 - Product Version: IS 5.11.0-Beta3
 - OS: Mac
 - Database: MySQL
 - Userstore: LDAP

**Related issues:**
https://github.com/wso2/product-is/issues/10110

**Suggested labels:**
console

**Comment by piraveena** [comment] 2020-11-02 11:00
Could not edit the emailaddress when email is used as username. Always getting error in the UI level when modifying the email address

- According to the use-case, the email address modified when email as username is configured.  If we modify email, then username attribute also modified. This is not a possible scenario since we can't modify username in IS. 

When I'm trying to modify the emailaddress, I could get the below error.

```
Message ID : 4
    Modify Request
        Object : 'mail=piraveena@wso2.com,ou=Users,dc=wso2,dc=org'
            Modification[0]
                Operation :  replace
                Modification
mail: /piraveena@wso2.com            Modification[1]
                Operation :  replace
                Modification
lastModifiedDate: 2020-11-02T08:45:42.174Zorg.apache.directory.api.ldap.model.message.ModifyRequestImpl@3e377377    ManageDsaITImpl Control
        Type OID    : '2.16.840.1.113730.3.4.2'
        Criticality : 'false'
'
: ERR_62 Entry mail=piraveena@wso2.com,ou=Users,dc=wso2,dc=org does not have the mail attributeType, which is part of the RDN";]; remaining name 'mail=piraveena@wso2.com'
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3185)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
	at com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1408)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:257)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:167)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:156)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager.doSetUserAttributesWithID(UniqueIDReadWriteLDAPUserStoreManager.java:1063)
	... 65 more
```

It is mentioned that this issue is an intermittent one
> Note: Restart the IS and repeat step 6 if the exception isn't thrown

But locally could not able to reproduce the issue. According to the logs, the error is coming from this line and it is trying to get secondaryuserstore when the domain name is PRIMARY https://github.com/wso2/carbon-kernel/blob/v4.6.1-beta/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L7216
 .https://github.com/wso2/carbon-kernel/blob/v4.6.1-beta/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L7223

`[2020-10-28 15:15:47,286] [a64f571d-497e-4203-b8d2-82428ebc48f6] ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while getting the users list for domain: PRIMARY org.wso2.charon3.core.exceptions.CharonException: Error while retrieving users for the domain: PRIMARY with limit: 10 and offset: 1.`

**Comment by piraveena** [comment] 2020-11-02 11:41
Hence closing this git issue based on the above comment

**Closed by piraveena** 2020-11-02 11:41 UTC
Labels: Affected/5.11.0-Beta, Severity/Critical, bug
