### ISSUE TITLE
User name not exists in the My account dropdown

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17802] opened 2023-11-15 08:50 UTC
**Describe the issue:**
User name not exists in the My account dropdown
<img width="1305" alt="image" src="https://github.com/wso2/product-is/assets/39077751/2d9cbd3f-1929-41eb-a424-c225428c0381">

**How to reproduce:**
1. Login to console
2. SSO to My account

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment] 2023-11-15 09:05
Duplicate of https://github.com/wso2/product-is/issues/17463

Hence closing the issue.

**Closed by Achintha444** 2023-11-15 09:05 UTC
Labels: ui, bug, ux, Affected/7.0.0-Alpha
