### ISSUE TITLE
5.9.0 Missing Logging functionality

### ISSUE THREAD

**Issue by L0rDPSYCH0** [wso2/product-is#6468] opened 2019-09-19 10:29 UTC
Hi! 

We are using WSO2 5.8 as of now but planning on migrating to 5.9. 

After downloading and installing the latest version (5.9 Alpha 3), from the monitor section we are missing the Application Logs and System logs.  I could not find any place where these have moved, and I can't think of a reason for them to be removed. 

We have admin users who are using these pages to monitor the health of the application. They do not have access to source code and so on and here was the only way they could check different logs. 

Is there a way to bring back these logs - as far as I can see both System and Application logs pages are missing. I am not talking about configuring the logging (from the Configure-Logging section) I am reffering only to the pages where logs can be seen. 

Is there another way of seeing these logs without leaving the application?
I have attached the new Monitor page vs the Old one to see differences

![image](https://user-images.githubusercontent.com/12871744/65236469-57f9db80-dae1-11e9-9cb9-2781d993dd0d.png)
![image](https://user-images.githubusercontent.com/12871744/65236492-65af6100-dae1-11e9-958a-f57c86627cec.png)

**Comment by senthalan** [comment] 2019-09-23 04:48
Duplicate of https://github.com/wso2/product-is/issues/6462

**Closed by senthalan** 2019-09-23 04:48 UTC
