### ISSUE TITLE
Failed login attempts increasing with userstore order number when userstore domain is not prepended

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16625] opened 2023-09-11 22:49 UTC
**Description :**

With WSO2 Identity Server 5.11.0.256 onwards, the failed login attempts will increase for secondary userstores with the userstore order number when userstore domain is not prepended.

It seems to fail due to the fix added for [1] where the authenticate method has been changed to authenticateWithID which will in turn utilize authenticateInternalIterationWithID method which will iterate through the userstores and will trigger post authentication event listeners for each userstore.

If there are 3 secondary userstores and if the user reside in the 3rd secondary userstore in order, then upon authentication failure the http://wso2.org/claims/identity/failedLoginAttempts will increase by 3 folds.

**Steps to reproduce:**

setup one or many secondary userstores,
invoke password grant without prepending the userstore domain,
check the login attempts value,

**Expected behavior:**
The authentication should not fail for users who exist in the non unique id user store.

**Environment information (Please complete the following information; remove any unnecessary fields) :**
Product Version: 5.11.0
Tested update levels: IS 5.11.0.256 onward to latest 279.
OS: Mac Os
Database: MySQL
Userstore: JDBC and UIDJDBC

[1] https://github.com/wso2/product-is/issues/16149

Thanks,
Isuru.

**Comment by hwupathum** [comment] 2023-09-13 11:59
Duplicate of https://github.com/wso2/product-is/issues/12154

**Closed** 2023-09-13 12:44 UTC
Labels: bug
