### ISSUE TITLE
Document how to support unicode on WSO2 IS.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#10352] opened 2020-11-05 15:40 UTC
**Description:**
Need to document how we can add support for UTF-8 characters in WSO2 Identity Server.

e.g. DB script modifications needed and various regex pattern configuration changes that are needed to support unicode.

**Comment by abhi4u1947** [comment] 2020-12-09 08:47
Duplicate of https://github.com/wso2/product-is/issues/2491

**Comment by isharak** [comment] 2024-11-06 05:07
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 05:07 UTC
Labels: Priority/Highest, Type/Docs, Severity/Major, Type/Bug, Complexity/Medium, Affected/5.11.0, IceBox
