### ISSUE TITLE
UI issues of Password Expiry feature in Console

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16099] opened 2023-06-21 05:33 UTC
**Describe the issue:**
After enabling the Password Expiry feature console UI is not displayed properly.

**How to reproduce:**
1. Enable Password Expiry as in https://is.docs.wso2.com/en/6.0.0/guides/password-mgt/password-policies/#configure-password-expiry
2. Navigate to Manage -> Password Policies in Console.
3. Following UI issue can be observed. 

![Screenshot 2023-06-21 at 11 00 53](https://github.com/wso2/product-is/assets/25563417/a40d5945-6bb3-45c7-8977-28debe86544c)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by chamathns** [comment] 2023-06-21 07:09
Tested this with IS 6.2.0 alpha3 SNAPSHOT and it wasn't reproducible
<img width="2560" alt="Screenshot 2023-06-21 at 12 39 17" src="https://github.com/wso2/product-is/assets/25428696/8b7e0975-22d9-4e84-bef8-27c46817d0dc">

**Comment by chamathns** [comment] 2023-11-22 04:42
closing since it's not reproducible

**Closed by chamathns** 2023-11-22 04:42 UTC
Labels: bug
