### ISSUE TITLE
IDP property name mismatch while updating through REST API and SOAP API

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#17661] opened 2023-11-08 05:30 UTC
**Describe the issue:**

If I need to encrypt IDP SAML assertion, I have to enable assertion encryption in the IDP configurations.  However when I do this update from carbon console the property name which is getting stored is IsAssertionEncrypted. If I update the same using REST APIs (ie new concole), the property that is being stored is IsEnableAssetionEncription.

However the underlying runtime logic seem to be honouring to IsAssertionEncrypted. This makes it's impossible to get the encryption flow working through new console. This is specially affecting B2B cases as there is no other way to update the IDP. 

Also UI also seems to be inconsistent. Even if we update this property either from new console or carbon console, it doesn't show as updated from new console.

**How to reproduce:**

Configure a SAML IDP with Assertion Encryption enabled from new console. It's not working as expected with the federated SAML IDP if it sends an encrypted assertion. If you look at the DB the stored attribute is IsEnableAssetionEncription.

**Comment by pavinduLakshan** [comment] 2023-11-08 06:20
Duplicate of https://github.com/wso2/product-is/issues/17622

**Closed by pavinduLakshan** 2023-11-08 06:20 UTC
Labels: Priority/High, Resolution/Duplicate, bug, Affected/7.0.0-Alpha
