### ISSUE TITLE
Make SCIM user retrieval INFO log to a debug log 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7777] opened 2020-02-27 05:55 UTC
The following log is printed unnecessarily in the wso2carbon logs.

`[2020-02-27 11:20:53,471] [a596f0a4-0176-4148-ac99-69a938110261]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - User: ayesha is retrieved through SCIM.`

**Comment by darshanasbg** [comment] 2020-02-27 05:56
Duplicate of: https://github.com/wso2/product-is/issues/6053

**Closed by darshanasbg** 2020-02-27 05:56 UTC
Labels: Affected/5.10.0-beta3, Priority/Highest
