### ISSUE TITLE
[SCIM/kernel] Error while updating user identity claims via SCIM in a Unique ID Read Only User Store

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#7341] opened 2020-01-22 08:53 UTC
### Description

Error with status 500 is returned when trying to update a user via SCIM in a Read Only (Unique ID) user store.

### Root Cause

`getUserClaimValuesWithID(String userID, String[] claims, String profileName)` [1] returns incorrect value for the "http://wso2.org/claims/location" claim. (i.e. the userId at the end of the location URI is different from the correct userId.)

### Example

**userId:** 87a56c4c-b01e-4483-b637-ad5800a761ac
**location:** https://localhost:9853/scim2/Users/1c712359-2950-4cb2-ae26-2c51b1b82467

### Steps to reproduce

1. Create a user via SCIM in a Unique ID Read Write LDAP User Store. (Don't do any PATCH/PUT operations).
2. Restart the server after pointing to the same user store as above, **but as a Unique ID Read Only User Store**.
3. Perform a PATCH/PIUT operation to update an identity claim of the user created in Step 1. (ex: verifyEmail claim)
4. Evaluate the values returned by [1].

### Post Actions

- Enable the test [2] after fixing this issue and #7342 

[1] https://github.com/wso2/carbon-kernel/blob/802996ae1c8b731aff815f6075db84c92de2b4fd/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L11090
[2] https://github.com/wso2/product-is/blob/6593b883b0f5c0531c6c84f275a345cf91e419b2/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/scim2/rest/api/SCIMUserUpdateReadOnlyTest.java#L112

**Comment by ayshsandu** [comment] 2020-11-16 13:01
Need to verify in the latest version.

**Comment by emswbandara** [comment] 2021-01-13 17:11
Unable to reproduce the said issue in 5.12.0-m5-Snapshot version. However its not updating identity claims even in unique ID read write ldap userstore as well. 

Following was the request used.

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"replace","value":{"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":false}}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/62e60c54-dd36-4af8-8c3a-54d5c9c19cf7`

**Comment by emswbandara** [comment] 2021-01-19 18:30
This works as expected for any other identity claim such as "emailVerified"

"verifyEmail" is a special case which undergoes multiple checks in UserEmailVerificationHandler and gets removed from claims map if required conditions are not map. Hence the above behavior was observed.

We can close this issue since it works correctly for a general identity claim. 

https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java#L208

**Closed by emswbandara** 2021-01-19 18:30 UTC
Labels: 5.12.0-bug-fixing, Component/Kernel, Component/SCIM, Priority/Highest, Severity/Major, a_commit
