### ISSUE TITLE
Keeping the console open for a while being idle and accessing again pops up error dialogs

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18914] opened 2024-01-13 09:55 UTC
**Describe the issue:**
$subject
<img width="492" alt="Screenshot 2024-01-12 at 4 49 02 PM" src="https://github.com/wso2/product-is/assets/4951983/55b65f3b-3b85-4f77-825f-230fd75cf27e">

**How to reproduce:**
1. Keep the console idle for like an hour and try to access. You will see the popup that says 'you have been inactive for a long time'
2. Try to list some apps, or list connections etc.
3. Note the errors coming up
4. If you refreshed the screen things will start working again

**Expected behavior:**
After the popup, the console should reinitiate the session and things should work properly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment] 2024-01-16 04:40
Duplicate of https://github.com/wso2/product-is/issues/18764

**Closed by brionmario** 2024-01-16 04:40 UTC
Labels: ui, Severity/Critical, bug, Affected/7.0.0 beta5
