### ISSUE TITLE
List Headers are not consistent throughout the IS Product

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17804] opened 2023-11-15 09:26 UTC
**Describe the issue:**
The "Users", "Groups" pages do not have the list headers consistent  throughout the IS console. 

Users List:
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/ec276643-7de6-46d9-8ce2-9a368b967267">

Groups List:
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/e5b05b96-ff4f-401f-bfec-7ecadeb64dab">

Roles:
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/2149d8cf-0043-4893-b9f9-58e9b929b8db">

**How to reproduce:**
1. Navigate to Users page > Verify the headers
2. Navigate to Groups page > Verify the headers

**Expected behavior:**
The headers of Lists should have consistent pattern throughout the product

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment] 2023-11-20 10:36
This issue is fixed in the latest identity-server hence closing the issue.
<img width="1800" alt="Screenshot 2023-11-20 at 16 04 54" src="https://github.com/wso2/product-is/assets/46097917/4f4a4a99-44b6-45bd-935e-f58d939312d8">

**Comment by brionmario** [comment] 2023-11-21 09:38
This is the expected behavior and not a consistency issue.

User entity is usually displayed as a circular avatar while other resources are shown as squared or in a different shape.
This is the convention in the industry.

*Auth0*

- Users

<img width="1051" alt="Screenshot 2023-11-21 at 15 06 51" src="https://github.com/wso2/product-is/assets/25959096/0c933422-1846-4ba8-9092-90b2b1c9b7d0">

- Other Resources

<img width="1091" alt="Screenshot 2023-11-21 at 15 07 37" src="https://github.com/wso2/product-is/assets/25959096/99573c14-43b3-4e28-972f-706030885bc0">

*Clerks*

- Users

<img width="1117" alt="Screenshot 2023-11-21 at 10 27 44" src="https://github.com/wso2/product-is/assets/25959096/c2f7e9c3-e1b7-4f23-a316-efcbb9dae212">

- Other Resources

<img width="1069" alt="Screenshot 2023-11-21 at 10 27 47" src="https://github.com/wso2/product-is/assets/25959096/ddd38ea3-b974-4e64-bfca-0a25193902c1">


@Achintha444 @GoushiRam Let's revert this change before Beta 2.

**Comment by GoushiRam** [comment] 2023-11-21 09:56
As discussed with @brionmario there should be a consistency in the "display of headers" for the list views. As such, Users should have the headers, to explain what is populated in each of the list columns. The discussed action items are:

1. Revert https://github.com/wso2/identity-apps/pull/4666
2. Bring a consistency in the list headers between IS and Asgardeo 


@Achintha444 @aaujayasena

**Comment by isharak** [comment] 2024-11-07 06:04
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 06:04 UTC
Labels: ui, Priority/Low, Severity/Minor, Type/Bug, Type/UX, IceBox
