### ISSUE TITLE
[Console] Incorrect placeholder value for "Scope" field in facebook IdP configuration page

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10716] opened 2020-12-09 09:32 UTC
**Describe the issue:**
Facebook IdP configuration page Scope field display incorrect placeholder value as "email"

<img width="600" alt="Screenshot 2020-12-09 at 14 48 02" src="https://user-images.githubusercontent.com/40847371/101611226-43c83400-3a2f-11eb-9265-4fc44144674b.png">

**How to reproduce:**

1. Log in to the Console and click on Develop tab
2. Click on "Identity Providers"
3. Click on "New Identity Provider" and select "Facebook"
4. Add "General settings" and click Next

**Expected behavior:**
Placeholder values should not be display

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL-5.7

**Comment by DimalChandrasiri** [comment] 2020-12-10 10:29
The `email` placeholder is coming from the meta endpoint and this bug is reproducible in the management console as well. Will need to fix from the api side.

**Comment by DimalChandrasiri** [comment] 2020-12-14 06:43
Since this is a placeholder default value, and making it an actual value will result in unwanted scopes added to the idp. Hence will close this issue.

**Closed by DimalChandrasiri** 2020-12-14 06:43 UTC
Labels: bug, ux
