### ISSUE TITLE
UI issue in `Script Based Authentication > Templates`

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#14244] opened 2022-07-15 05:23 UTC
**Describe the issue:**
The `+` icon is out of place. This happens only in Chrome, works fine in Firefox.

![ui-issue-IS](https://user-images.githubusercontent.com/84217321/179156097-45f8a89c-0ca1-41cb-945c-9749051a3a23.png)

**How to reproduce:**

For IS 6; Shut down the IS, run the `enableauthentication.sh` script, and start the IS.

1. On the management console, go to **Main** > **Identity** > **Service Providers** > **List**.
2. Click **Edit** on any service provider.
3. Expand the **Local and Outbound Authentication Configuration** section and click **Advanced Configuration**.
4. You will be redirected to **Advanced Configuration**, expand **Script Based Conditional Authentication**.
5. Expand the **Templates** section.

**Expected behavior:**
The `+` icon should be in line with the script name.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 alpha 2
 - OS: Linux
 - Browser: Chrome

**Comment by piraveena** [comment] 2022-08-02 08:55
Could not reproduce this issue with chrome in the latest IS 6.0.0-beta pack. Hence closing this
<img width="356" alt="Screenshot 2022-08-02 at 14 24 29" src="https://user-images.githubusercontent.com/17597293/182334913-63d82eb5-c36b-4c5c-a411-3feaa6c01d94.png">

**Closed by piraveena** 2022-08-02 08:55 UTC
Labels: ui, Severity/Major, bug
