### ISSUE TITLE
Implement a mechanism to track federated users when persisting/caching users in OAuth flows

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4879] opened 2019-04-01 05:30 UTC
Currently in OAuth2 flows, in order to track whether a user is federated or not , we have introduced a new userstore domain called "FEDERATED:idp_name". This approach causes problems when the idp name contains colon. Therefore as a proper fix for this, we can include another column to IDN_OAUTH2_ACCESS_TOKEN and IDN_OAUTH2_AUTHORIZATION_CODE tables to persist the IDP name of federated users. 

Furthermore, currently in OAuth caches, we do not store the federated property in the cache keys for authorized user. We need a mechanism to differentiate local users and federated users in caches.

**Comment by emswbandara** [comment] 2019-04-11 09:23
reducing the severity since this is a major improvement to the code-base.

**Comment by malithie** [comment] 2019-05-10 11:04
Resolving as the issue is fixed

**Closed by malithie** 2019-05-10 11:04 UTC
Labels: Complexity/High, Component/OAuth, Priority/High, Resolution/Fixed, Severity/Major, Type/Improvement
