### ISSUE TITLE
SCIM2 Filtering with required attributes not working

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5090] opened 2019-04-17 16:23 UTC
**Environment**
Ubuntu, H2 DB, Embedded LDAP userstore

**Steps to reproduce**
Create multiple users in SCIM2
Now try to filter user using filter attribute 
e.g
`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?filter=userName+eq+vindula`
This will work as expected giving a single result.
Try to retrieve required attributes using 'attributes' param.
e.g.
`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?attributes=emails.value,emails.type`
This will also list only the requested attributes of all users.

If we try to use both query params together, it does not filter and retrieve all users.
e.g. 
`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?attributes=emails.value,emails.type&filter=userName+Eq+vindula`

**Comment by malithie** [comment] 2019-04-18 02:20
Changing the severity for further review

**Comment by malithie** [comment] 2019-04-18 12:17
@emswbandara , Can we mention in which user store type this was observed

**Comment by somindatommy** [comment] 2019-04-22 10:35
Cannot reproduce.

**Comment by somindatommy** [comment] 2019-04-22 15:05
Works for primary LDAP

**Comment by malithie** [comment] 2019-04-23 03:58
@somindatommy , @emswbandara , can we resolve this issue. Is this observant

**Comment by emswbandara** [comment] 2019-04-23 04:24
I have tested the following cases

`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?filter=userName+eq+vindula&attributes=emails.home`

`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?filter=userName+eq+vindula&attributes=emails`

`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?filter=userName+eq+vindula&attributes=emails.type`

but in all those cases, it filters the result but does not give only the requested attribute (result contains displayName which is not a meta attribute of user 'vindula')

**Comment by emswbandara** [comment] 2019-04-23 04:28
Same observation was there for a single attribute as well

request
`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?filter=displayName+eq+test&attributes=displayName`

response
`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"work","value":"vindula_work.com"},{"type":"home","value":"vindula_home.com"}],"meta":{"created":"2019-04-17T15:55:35Z","location":"https://localhost:9443/scim2/Users/472177e5-38ec-4e19-84b1-f135d42d69fb","lastModified":"2019-04-23T09:52:05Z","resourceType":"User"},"displayName":"test","name":{"givenName":"vindula","familyName":"jayawardana"},"id":"472177e5-38ec-4e19-84b1-f135d42d69fb","userName":"vindula"}]}`

**Comment by IsurangaPerera** [comment] 2019-04-24 09:58
'&' is a special symbol used in the terminal. Therefore the curl request should be corrected as follows.

`curl -v -k -u admin:admin https://localhost:9443/scim2/Users?attributes=emails.value,emails.type\&filter=userName+Eq+kim`

**Comment by malithie** [comment] 2019-04-24 10:05
Resolving as per comment above

**Closed by malithie** 2019-04-24 10:05 UTC
Labels: Affected/5.8.0-Beta, Complexity/Medium, Component/SCIM, Priority/Highest, Severity/Major, Type/Bug
