### ISSUE TITLE
[ConsoleApp]Can't create identity provider using google as IDP

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9877] opened 2020-10-15 09:03 UTC
**Describe the issue:**
When trying to create a google IDP through console app, once enter the idp name and click next empty page is redirected.
![1](https://user-images.githubusercontent.com/20336761/96101364-ffb72800-0ef2-11eb-81aa-786db7cd6991.png)
![2](https://user-images.githubusercontent.com/20336761/96101401-0a71bd00-0ef3-11eb-934a-7590185c960b.png)

**How to reproduce:**
1. Login to console app using secondary user store user which resides in a tenant.
2. Click identity provider->google->give idp name and click next

**Expected behavior:**
Successfully navigate to provisioning configuration

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta2-snapshot
 - OS:LInux
 - Database:POSGRE
 - Userstore: JDBC

---

**Comment by Sathiyakugan** [comment] 2020-10-19 10:05
Please test for other authenticators as well when you test it. Because it gave the error for Twitter as well.

**Comment by thivi** [comment] 2020-10-29 07:26
I am unable to reproduce this issue in 5.11.0-Beta3-SNAPSHOT. Please verify this issue and close it if it is fixed.

**Comment by Sathiyakugan** [comment] 2020-10-29 07:32
This has been fixed somehow in beta3. since close this issue.

**Closed** 2020-10-29 08:34 UTC
Labels: Priority/Highest, Severity/Blocker, bug, console, ux
