### ISSUE TITLE
Add support to retrieve IDP details at sub organization level through the IdentityProviderDataRetrievalClient

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#17591] opened 2023-11-06 09:56 UTC
**Is your suggestion related to an experience ? Please describe.**
We need to improve the `IdentityProviderDataRetrievalClient` to support resolving IDP details on the sub-organization level. Specifically need a similar util to [1] in order to resolve the IDP image of an IDP created on the sub organization level. 

Sample API path:

`/t/test.com/o/org_id/api/server/v1/identity-providers/idp_id`

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/IdentityProviderDataRetrievalClient.java#L76

**Comment by dhaura** [comment] 2023-11-07 06:03
### Analysis
- In [1], even though the tenant domain is passed when building the url, the org id is resolved using Thread Local Carbon Context [2] and the url is built in the format: `/t/test.com/o/org_id/api/server/v1/identity-providers/idp_id`. Therefore, there is **NO** need for a new util to resolve the IDP image of an IDP created on the sub organization level.
- Even with the `o/org_id` path, the response that we get in [3] is a `404` because currently, the IdP API doesn't support `o/` paths with `basic auth` authentication. Thus, in order to retrieve IdP properties, the following request should be sent with an `access token` belonging to the sub organization.
```
GET https://test.com/t/carbon.super/o/api/server/v1/identity-providers?filter=name+eq+Google
```
- In the above request, sub organization is resolved by determining the organization associated with the sent access token.

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/IdentityProviderDataRetrievalClient.java#L76
[2] - https://github.com/wso2/carbon-identity-framework/blob/3ea41c3dd329063065edfb0b6b44544418641f30/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/DefaultServiceURLBuilder.java#L130
[3] - https://github.com/wso2/carbon-identity-framework/blob/b268df100302ac7b5b77618f94c22921cddbfce2/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/IdentityProviderDataRetrievalClient.java#L84

**Comment by sadilchamishka** [comment] 2023-11-22 12:13
This is organization login page where custom IDP and Google IDP is added.
Is this issue looks resolved now.

<img width="410" alt="Screenshot 2023-11-22 at 17 42 20" src="https://github.com/wso2/product-is/assets/35717390/3ef07779-1d1c-4169-9d46-ce80007fbf66">

**Comment by sadilchamishka** [comment] 2023-11-27 14:15
The BE changes related to IDP image retrieval is fixed. When login page is prompted, the IDP image URLs are retrieved.

<img width="382" alt="Screenshot 2023-11-27 at 19 36 57" src="https://github.com/wso2/product-is/assets/35717390/ae014353-92ab-4868-9008-10ddd7de718d">

But there is an UI issue where, the IDP image URL is differently set for two different cases.
When accessing console with port 9443 default mode, when creating an connection (ex- standard based idp), the image URL is set to an absolute path. When accesing the console in developer mode 9001, when creating a connection, the image URL is set to a relative path. Due to this, the logo resolving fails for the connections created for the IDP created by developer mode.

Absolute path
<img width="906" alt="Screenshot 2023-11-27 at 19 41 36" src="https://github.com/wso2/product-is/assets/35717390/10b0897e-98f9-4f3e-93e3-ffbdc3bac57b">


Relative path
<img width="922" alt="Screenshot 2023-11-27 at 19 42 05" src="https://github.com/wso2/product-is/assets/35717390/043eff2e-1d78-4607-938f-ca69025d2490">

The issue for the relative path is, there is no image with the name `enterprise.svg`, but there is `enterprise-idp-illustration.svg`

1 - We will have to define what is the correct way of image URL resolving. For tomcat deployed console & static console deployment, whether relative/absolute or both for each type to be used.
2 - Whether the image file name to be renamed.

**Comment by sadilchamishka** [comment] 2023-11-28 05:18
The remaining part of the issue is outside the scope of the original concern of the issue, hence close this issue and will be tracked with this issue.

**Closed by sadilchamishka** 2023-11-28 05:18 UTC
Labels: improvement, Priority/High, bug, backend, Component/B2B, Affected/7.0.0-beta
