### ISSUE TITLE
Users without permissions can login/SSO to console but getting errors when accessing the items in the left menu

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18191] opened 2023-11-29 16:16 UTC
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/0761545d-c18e-461d-8e46-7641bae9937b)

**How to reproduce:**

1. Create a user without Management permissions or roles
2. Login to console with the new user or login to myaccount and then access console URL

**Expected behavior:**
Users without permissions should not be able to login or after entering the credentials should given a message that the user doesn't have previladges

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-11-30 05:04
Duplicate of https://github.com/wso2/product-is/issues/17209

**Closed by pavinduLakshan** 2023-11-30 05:04 UTC
Labels: ui, Priority/High, Resolution/Duplicate, Severity/Critical, bug, Affected/7.0.0-beta2
