### ISSUE TITLE
Scope are not returned for client credential grant requests 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19225] opened 2024-01-26 16:34 UTC
**Describe the issue:**
1. Create a standard-based oauth app / M2M application
2. Enable client credentials grant
3. Authorize SCIM2 Users API with all scopes
4. Try client credentials grant based token request by requesting scopes related to SCIM2 Users endpoint

```
curl --location 'https://localhost:9443/oauth2/token' \
--header 'Authorization: Basic bHJtUmp0MHUzZFhhMTJadWdLblh3UDZtOGE4YTpGb1lCT3JaX2RWYVBDT2ZwQmw3blN0VEFoOXB3WV9NZTY3ZWxnS29lcTN3YQ==' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scopes=internal_user_mgt_view internal_user_mgt_update internal_user_mgt_list internal_user_mgt_create internal_user_mgt_delete'
```

(replace the authorization header  according to your client id and secret)

The response will be as follows, no scopes returned
```
{
    "access_token": "c8edca93-7fb2-39b6-8d94-0f4f51a5dc5c",
    "token_type": "Bearer",
    "expires_in": 3558
}
```

**Comment by shanggeeth** [comment] 2024-01-27 07:04
The issue is with the curl request. 
`scope` parameter key is incorrectly set as `scopes`.
When requested for the `scope` paramter, scopes are returned as expected in the latest snapshot.
Hence closing this issue with this comment.

**Closed by shanggeeth** 2024-01-27 07:04 UTC
Labels: Priority/Highest, Severity/Blocker, bug, backend, Affected/7.0.0-beta6
