### ISSUE TITLE
Admin user SSO for the console option is missing at My account

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18026] opened 2023-11-22 06:04 UTC
**Describe the issue:**

My account
<img width="1277" alt="image" src="https://github.com/wso2/product-is/assets/39077751/6d85752b-68bc-4332-b2ae-5e99c2ebf36c">

This link is available on Console side. 
Console
<img width="1226" alt="image" src="https://github.com/wso2/product-is/assets/39077751/69a5fcd3-c851-4d4b-9cb9-bdfdda9338f8">

**How to reproduce:**
1. Login to myaccount as admin
2. Find the SSO to Console from right hand conner dropdown

**Expected behavior:**
There should be a option to SSO to my account. 
<img width="1440" alt="image" src="https://github.com/wso2/product-is/assets/39077751/7b53924e-f78e-4946-a651-0e7df15d2cd4">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7.0.0-beta
 - OS: [e.g., Windows, Linux, Mac]
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment] 2023-11-28 06:04
We need to properly analyze the use cases of showing the Console link in My Account. Therefore we are putting this task on hold.

**Comment by brionmario** [comment] 2023-11-30 06:25
This is the intended behavior for now.

Basically, we need to have a different My Account for business users.

Tracker:
- https://github.com/wso2/product-is/issues/17452

Hence, closing this issue...

**Closed by brionmario** 2023-11-30 06:25 UTC
Labels: ui, Priority/Highest, Severity/Critical, bug, on hold, QA-Reported, Affected/7.0.0-beta
