### ISSUE TITLE
Secondary JDBC userstore copied from older packs not visible in the management console.

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#14716] opened 2022-08-15 04:50 UTC
**Describe the issue:**
After the migration, secondary JDBC userstore copied from older pack not visible in the management console.

**How to reproduce:**
1. Setup IS 5.3.0 with PostgreSQL and a secondary JDBC userstore
2. Instructions in [1] were followed for migrating the IS and secondary userstores.

**Expected behavior:**
All secondary userstores should be working and visible in the console.

**Environment information**  **:**
 - Product Version: IS 5.3.0, 6.0.0
 - OS:  Linux
 - Database: PostgreSQL
 - Userstore: JDBC

[1] https://is.docs.wso2.com/en/6.0.0/deploy/migrate/migrate-to-600/#user-stores

**Comment by ashendes** [comment] 2022-08-16 13:42
Duplicate of https://github.com/wso2/product-is/issues/14664

**Closed by ashendes** 2022-08-16 13:42 UTC
Labels: bug, 6.0.0-Migration
