### ISSUE TITLE
SSL peer failed hostname validation for name

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2763] opened 2018-03-05 10:23 UTC
Referring an issue reported in JIRA [1]. The issue is reported by so many people and still not been fixed.

[1] https://wso2.org/jira/browse/IDENTITY-5243

**Comment by Megala21** [comment] 2018-04-27 10:12
Upon further investigation, it was identified that when "is" is acting as client, when calling to the admin services for SAML SSO flow, it uses the hostname configured in the carbon.xml, however this will lead to a problem, if the load balancer is used and the hostname is configured with the load balancer. When the soap call goes from is to load balancer, during the server hello phase, the load balancer will return the default one. Due that this failure happens. This need to be fix this in is side, so that it uses the local transport to call particular soap service. 

This will be blocker when using loadbalancer with multple certificates. As the soap client currently used in IS level, do not support SNI, where we can specify the hostname, the certificate is requested for.

**Comment by kasunbg** [comment] 2018-05-17 08:26
Setting below system property into bin/wso2server.sh worked.

```
-Dorg.opensaml.httpclient.https.disableHostnameVerification=true 
```

**Comment by kasunbg** [comment] 2018-05-17 08:28
You'll need to generate keystores for your IP address if you are not using hostnames like follows:

```
keytool -genkey -alias wso2ob -keyalg RSA -keysize 2048 -keystore wso2ob.jks -keyalg RSA -validity 9999 -dname "EMAILADDRESS=ca@exmaple.com, CN=ob-km.wso2.com, O=Chimps, L=Portland, S=Oregon, C=US, OU=Portland" -ext san=ip:192.168.52.143
```

Notice the `-ext san=ip:192.168.52.143` at the end.

Then, export the public certificate and import into the client-truststore.jks.
```

keytool -export -alias wso2ob -file key.crt -keystore wso2ob.jks

keytool -import -trustcacerts -alias wso2ob -file key.crt -keystore repository/resources/security/client-truststore.jks
```

**Comment by Megala21** [comment] 2018-05-17 08:37
The issue explained in the previous comment is when load balancer have multiple certificates and the host name in the default certificate of load balancer does not match the host name of request url. The above mentioned self signed certificate will not work in that case, if the default certificate of load balancer is not for the given hostname. When having multiple certificates, during the handshake initiation, we need to mention, what is the hostname the certificate is requested for, otherwise the load balancer which is having multiple certificates will return the default one, which may not match the hostname. Please refer [1] for more information on this.

[1] https://support.comodo.com/index.php?/Knowledgebase/Article/View/1120/38/what-is-sni-and-how-it-works

**Comment by M0nikaSharma** [comment] 2018-10-16 07:52
we have configured the wso2 identity server and IS dashboard with the nginx (load balancer) using the below link.
https://docs.wso2.com/display/IS541/Setting+Up+Deployment+Pattern+2#SettingUpDeploymentPattern2-Settingupthedashboard

we have followed the below commands to generate keystores for our IP address:

keytool -genkey -alias wso2carbon -keyalg RSA -keysize 2048 -keystore wso2carbon.jks -dname "CN=idp.wso2.com,OU=Home,O=Home,L=SL,S=WS,C=LK"  -ext san=ip:192.168.52.143
keytool -export -alias wso2carbon -file key.crt -keystore wso2carbon.jks 
Imported the public cert of the new key to trust store
keytool -import -trustcacerts -alias wso2carbon -file key.crt -keystore client-truststore.jks.

Now, we are only able to access the IS using the nginx IP: https:<NGNIX_IP>:443/carbon but we are not able to access the dashboard by using the https:<NGNIX_IP>:443/dashboard.

**Comment by cwichoski** [comment] 2019-06-27 20:11
Hi, 

I got an exception about domain null:

`Caused by: org.mozilla.javascript.JavaScriptException: JavaException: org.jaggeryjs.scriptengine.exceptions.ScriptException: SSL peer failed hostname validation for name: null (/dashboard/controllers/wsUtil.jag#76)
	at org.jaggeryjs.rhino.dashboard.controllers.c0._c_callWSReturnXML_3(/dashboard/controllers/wsUtil.jag:76)
	at org.jaggeryjs.rhino.dashboard.controllers.c0.call(/dashboard/controllers/wsUtil.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.dashboard.controllers.c0._c_callWSReturnJSON_4(/dashboard/controllers/wsUtil.jag:82)
	at org.jaggeryjs.rhino.dashboard.controllers.c0.call(/dashboard/controllers/wsUtil.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at …`

Then added suggested set for disableHostnameVerification, and got a newer exception:

`
2019-06-27 20:03:33,510] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} -  org.mozilla.javascript.JavaScriptException: JavaException: org.jaggeryjs.scriptengine.exceptions.ScriptException: peer not authenticated (/dashboard/controllers/wsUtil.jag#76)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.JavaScriptException: JavaException: org.jaggeryjs.scriptengine.exceptions.ScriptException: peer not authenticated (/dashboard/controllers/wsUtil.jag#76)
`

Im using deployment of kubernetes-is from folder advanced/is-with-analytics, the certificate I installed only in ingress that is a wildcard (*.example.com) for the domain, and configured carbon.xml with one domain for console and other for server like (console.example.com and auth.example.com). Not touched wso2carbon.jks and client-truststore.jks files that comes from kubernetes installation. You see this scenario too?

Best regards
Clóvis

**Comment by iNemesis** [comment] 2019-10-21 12:58
This article solves my problem : 
https://medium.com/@igunawardana/how-to-change-hostname-in-wso2-is-with-self-signed-certificate-ea547605e015

**Comment by isharak** [comment] 2021-04-09 11:47
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 11:47 UTC
Labels: Affected/5.5.0-Alpha3, Priority/High, Severity/Major, bug
