### ISSUE TITLE
Unhanded Internal server error response when calling OIDC userinfo endpoint.

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-is#5186] opened 2019-05-03 17:40 UTC
**Execute the following curl command which passes the JWT token to user info endpoint**

```
curl -X GET \
 https://<hostname>/oauth2/userinfo \
 -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImRpbGVlcGEiLCJpYXQiOjE1MTYyMzkwMjJ9.9RCHh3kt9LIvJJNPE9Sw9lZxBQNw2RtbWPZQcIVw9Sc'
```

It will throw the null pointer exception at the token validation level and return the 500 internal server error as an HTML response.

`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>`

**Comment by omindu** [comment] 2019-05-14 05:07
Duplicate of https://github.com/wso2/product-is/issues/5182

**Closed by omindu** 2019-05-14 05:07 UTC
