### ISSUE TITLE
[OrcleDB] error while listing role 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18631] opened 2023-12-15 12:16 UTC
**Describe the issue:**

```
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while listing roles in tenantDomain: [test.com](http://test.com/)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.getRoles(RoleDAOImpl.java:335)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.getRoles(RoleManagementServiceImpl.java:185)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManagerV2.filterRolesByAttributes(SCIMRoleManagerV2.java:473)
	... 58 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00936: missing expression

https://docs.oracle.com/error-help/db/ora-00936/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1277)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:482)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:259)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1088)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1277)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1207)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1543)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3731)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3835)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1099)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy54.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeQuery(NamedPreparedStatement.java:260)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.buildRolesList(RoleDAOImpl.java:2393)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.processListRolesQuery(RoleDAOImpl.java:2377)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.getRoles(RoleDAOImpl.java:332)
	... 60 more
Caused by: Error : 936, Position : 504, SQL = SELECT UM_ROLE_NAME, UM_UUID, UM_AUDIENCE, UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID FROM (SELECT UM_ROLE_NAME, UM_AUDIENCE, UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID, rownum AS rnum FROM (SELECT UM_ROLE_NAME, UM_AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.UM_AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.UM_ID WHERE UM_ROLE_NAME = :1 AND UM_AUDIENCE_ID = :2 AND  UM_TENANT_ID= :3 ORDER BY UM_HYBRID_ROLE.UM_ID DESC) WHERE AND rownum <=  :4 ) WHERE rnum >  :5 , Original SQL = SELECT UM_ROLE_NAME, UM_UUID, UM_AUDIENCE, UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID FROM (SELECT UM_ROLE_NAME, UM_AUDIENCE, UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID, rownum AS rnum FROM (SELECT UM_ROLE_NAME, UM_AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.UM_AUDIENCE_ID, UM_AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.UM_AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.UM_ID WHERE UM_ROLE_NAME = ?  AND UM_AUDIENCE_ID = ?  AND  UM_TENANT_ID= ?  ORDER BY UM_HYBRID_ROLE.UM_ID DESC) WHERE AND rownum <=  ? ) WHERE rnum >  ? , Error Message = ORA-00936: missing expression

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)
	... 83 more
```

**How to reproduce:**
1. Login to console (tenanted path)
2. Navigate to role
3. Select Application or organization

**Expected behavior:**
No error should be appear

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment] 2023-12-17 14:10
This can be seen when Navigate to Console setting as well.

**Comment by sahandilshan** [comment] 2023-12-18 04:52
This was already fixed with https://github.com/wso2/carbon-identity-framework/pull/5302

**Comment by sahandilshan** [comment] 2023-12-18 04:52
Duplicate of https://github.com/wso2/product-is/issues/18550

**Closed** 2023-12-20 12:10 UTC
Labels: Priority/Highest, Severity/Blocker, bug, QA-Reported, DB/Oracle, Affected/7.0.0-beta4
