### ISSUE TITLE
Unable to edit role permissions in Console Settings

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19040] opened 2024-01-21 06:32 UTC
**Describe the issue:**
We can add roles and assign permissions in the Console Settings. But unable to modify the assigned permissions through the role edit. There is no indication either that these cannot be modified when creating. However, I can see that these can be modified through the role edit in the Roles section of user management. But that has a completely different permission representation than what was seen when creating a role and assigning permissions through Console Settings. 

https://github.com/wso2/product-is/assets/11583571/d38ccb0c-ad05-4c9a-94e9-0816753b9ae6

Additionally in  Console Settings when creating a role; the UI for assigning permissions has a completely different view when going to view the assigned permissions. The view permissions screen doesn't give any mental link to the permissions assigned during the role creation.

Permission view when creating the Role through Console Settings
<img width="833" alt="Screenshot 2024-01-21 at 12 00 21" src="https://github.com/wso2/product-is/assets/11583571/e450fef6-131f-429e-8dcb-5cffa835df97">

Permission view when viewing the permissions of the Role through Console Settings
<img width="1371" alt="Screenshot 2024-01-21 at 12 00 45" src="https://github.com/wso2/product-is/assets/11583571/d4e09d44-4245-4929-93de-77038d82a0ef">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment] 2024-01-21 11:32
Duplicate of https://github.com/wso2/product-is/issues/18071

This is a known limitation in the Console roles. When creating a role, we utilize the `api-resource-collections` meta endpoint to show the set of permissions as feature `View` & `Edit`. But once the role is created, there's no way to map the permissions back to the feature.

Ref: https://github.com/wso2/product-is/issues/18071#issuecomment-1833444026

**Comment by brionmario** [comment] 2024-02-06 13:02
Tried to do a workaround for this as follows.

- Since we have `console:<SCOPE>` for features now, we can cross check the permissions in the role with the set of permissions in the `api-resource-collections` and try to define a mapping. 

However, this fails due to org level feature permissions using the same UI scope.

ex:
Tenant Applications -> `console:applications`
Organization Applications -> `console:applications`

This causes issues when tenant level application permission is given but organization application permission is not given for a user.

https://github.com/wso2/product-is/assets/25959096/461ef4e0-fde2-43e3-9856-326574dca96c

Similarly, the following happens since the console ui scopes are coming from tenant level permissions.
https://github.com/wso2/product-is/assets/25959096/2f6af0b8-794d-4dec-a54e-f49e1165e31e

@DilshanSenarath This issue will affect the overall Console RBAC as well.

IMO, we should use a different scope for org features.

ex: `console:org:applications`

**Comment by DonOmalVindula** [comment] 2024-02-09 11:15
> Tried to do a workaround for this as follows.
> 
> * Since we have `console:<SCOPE>` for features now, we can cross check the permissions in the role with the set of permissions in the `api-resource-collections` and try to define a mapping.
> 
> However, this fails due to org level feature permissions using the same UI scope.
> 
> ex: Tenant Applications -> `console:applications` Organization Applications -> `console:applications`
> 
> This causes issues when tenant level application permission is given but organization application permission is not given for a user.
> 
>  Feb-06-2024.18-25-31.mp4 
> Similarly, the following happens since the console ui scopes are coming from tenant level permissions. https://github.com/wso2/product-is/assets/25959096/2f6af0b8-794d-4dec-a54e-f49e1165e31e
> 
> @DilshanSenarath This issue will affect the overall Console RBAC as well.
> 
> IMO, we should use a different scope for org features.
> 
> ex: `console:org:applications`

This will be implemented with https://github.com/wso2/product-is/issues/19446

**Closed** 2024-02-12 09:10 UTC
Labels: ui, Priority/High, Severity/Blocker, bug, on hold, frontend, Component/ConsoleRBAC
