### ISSUE TITLE
Users not returned in SCIM for JDBC secondary userstores in IS 5.10

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#9480] opened 2020-09-16 20:53 UTC
**Describe the issue:**
When we make the SCIM requests mentioned below, the users in the secondary user store US1 is not included in the response.
```
https://localhost:9443/scim2/Users
https://localhost:9443/scim2/Users?domain=US1
```
The above behavior occurs since the `users` will contain the username prepended with the user store domain (US1/user1) at [1] and hence the same will be applied to the query. However, the username in the table won't contain the user store domain and hence the query will return empty results.

**How to reproduce:**
1. Create a secondary JDBCUserStoreManager (The SCIM will be enabled by default).
   - When creating the database, make sure to use db scripts of a previous IS version (IS 5.9.0) since the new db scripts provided in the 5.10.0 pack only compatible with UniqueIDJDBCUserStoreManager.
2. Add some users.
3. Invoke the above SCIM requests.

**Environment information**
 - Product Version: IS 5.10.0

**Suggested labels:**
Severity/Blocker

[1] https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L3084

**Comment by Sathiyakugan** [comment] 2020-09-18 09:18
Duplicate of https://github.com/wso2/product-is/issues/8623

**Comment by mifrazmurthaja** [comment] 2020-09-18 12:00
@Sathiyakugan,
This is about, the SCIM doesn't return the users of the JDBC secondary user store at all. But #8623 is about including user groups in the response, where it returns the users excluding the groups in the response.
Therefore, this is not the duplicate of #8623.

**Comment by isharak** [comment] 2024-11-06 05:01
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 05:01 UTC
Labels: Type/Bug, WUM, IceBox
