### ISSUE TITLE
[OpenID Connect Discovery] Issuer value returned when invoking discovery endpoint not reflect the value given for ID token the issuer value

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5184] opened 2019-05-03 12:42 UTC
The issue is related to the Identity server 5.3.0 version.

Please follow below steps to reproduce the issue.

1. Updated the value for the  OAuth2/OpenID Connect Configuration Identity Provider Entity Id 
2. Invoke discovery Endpoint 

"curl -v -k --user admin:admin https://mgt.as.wso2.com/oauth2/oidcdiscovery/.well-known/openid-configuration"

3. In the response, it reflects the value given for the  <IDTokenIssuerID> in the identity,xml not the value given for the Identity Provider Entity Id

**Comment by rksk** [comment] 2020-06-11 21:48
Duplicate of https://github.com/wso2/product-is/issues/4277
Fixed in master with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1005

**Comment by isharak** [comment] 2024-11-05 20:27
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-05 20:27 UTC
Labels: WUM, IceBox
