### ISSUE TITLE
Permission assignment for super tenant doesn't work when enable_email_domain enabled

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#18454] opened 2023-12-06 06:17 UTC
**Describe the issue:**
When Email Address as the Username is configured [1], and the super admin login to the console using the new credentials, the logged in user does not get detected as an admin. (Administrator role is not getting listed for the user.)

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/

https://github.com/wso2/product-is/assets/47152272/68b8a209-5892-4341-b59c-d80dceb330c0

The roles assigned for the admin@wso2.com user is listed as below. (Got this info after disabling the feature)

<img width="1193" alt="Screenshot 2023-12-06 at 12 02 40" src="https://github.com/wso2/product-is/assets/47152272/ea76be76-6f40-4f91-8e8f-33ca1faf5622">

**How to reproduce:**
1. Enable  Email Address as the Username[1].
2. Login to console using the new admin credentials as mentioned in the doc[1].

**Expected behavior:**
Logged in user should get detected as the admin.

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/

**Comment by Kanapriya** [comment] 2023-12-14 08:46
Checked this issue in the latest build pack wso2is-7.0.0-beta4-SNAPSHOT and couldn't reproduce the exact case, instead I could see some UI issues and raised a new issue to get that fixed.
Please refer - https://github.com/wso2/product-is/issues/18582

**Comment by mpmadhavig** [comment] 2023-12-15 05:24
The behavior reproduced after enabling the config for an already started pack. Shall we check that and confirm. Apologies for not adding this information earlier.

**Comment by Kanapriya** [comment] 2023-12-15 06:14
> The behavior reproduced after enabling the config for an already started pack. Shall we check that and confirm. Apologies for not adding this information earlier.

Same behaviour occured with the already started pack. Hence close this issue.

**Closed by Kanapriya** 2023-12-15 06:14 UTC
Labels: Severity/Blocker, bug, backend, Affected/7.0.0-beta2
