### ISSUE TITLE
Invalid Response code and Response while creating SCIM 2.0 user 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7509] opened 2020-02-10 10:26 UTC
**Description**
Invalid Response Code and Response while creating SCIM 2.0 user 

Tested environment :
Primary user store - JDBC
Secondary user store - JDBC-Unique
Primary DB - Postgres 11.6
Secondary DB Postgres 11.5

**Re test same scenario and only changed DB type to MSSQL 2017
I got same issue,** 
also issue occurring with primary as well as secondary user store

Step to reproduced:
1. configure deployment.toml
`[user_store]
type = "database"

[database.identity_db]
type = "postgre"
hostname = "localhost"
name = "beta510"
username = "postgres"
password = "wso2carbon"
port = "5432"
[database.identity_db.pool_options]
 maxActive = "80"
 maxWait = "60000"
 minIdle = "5"
 testOnBorrow = true
 validationQuery="SELECT 1; COMMIT"
 validationInterval="30000"
 defaultAutoCommit=false
[database.shared_db]
type = "postgre"
hostname = "localhost"
name = "beta510"
username = "postgres"
password = "wso2carbon"
port = "5432"
[database.shared_db.pool_options]
 maxActive = "80"
 maxWait = "60000"
 minIdle = "5"
 testOnBorrow = true
 validationQuery="SELECT 1; COMMIT"
 validationInterval="30000"
 defaultAutoCommit=false

 [bps_database.config]
url = "jdbc:postgresql://localhost:5432/beta510"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"`

2. SCIM request:

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users
--
Response :
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "scimType": "null",
    "detail": "Error in adding the user: Testusertt to the user store. ",
    "status": "500"
}

Same behavior: for secondary user store

But user is dispalyed in the management console

**Comment by denuwanthi** [comment] 2020-02-11 10:20
This is happening because, when using the primary user store as JDBC, the 'UM_UUID_DOMAIN_MAPPER' table is not added in the DB. (This is only in the 5.10.0 dbscripts.)
When doing the SCIM call for PRIMARY user, it fails due to UM_UUID_DOMAIN_MAPPER is not there.

Then , even if you use a SECONARY as a JDBC-Unique, still from the AbstractUserStoremanager, it checks for the UM_UUID_DOMAIN_MAPPER class, to find the domain name. This table will laways be create din the PRIMARY carbon db. Since you are using dbscripts without UM_UUID_DOMAIN_MAPPER, it fails.

This is a duplicate of https://github.com/wso2/product-is/issues/7424

This need to be addressed during migration.

**Comment by denuwanthi** [comment] 2020-02-11 10:22
Please find the related migration issue at https://github.com/wso2/product-is/issues/7481

**Closed** 2020-02-11 10:24 UTC
Labels: Affected/5.10.0-beta, Component/Migration, Priority/Highest, Severity/Major, Type/Bug
