### ISSUE TITLE
[consoleApp] [Manage] Secondary userstore added via console manage cannot be deleted from the management console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10166] opened 2020-10-29 05:30 UTC
**Describe the issue:**
Secondary userstore added via console cannot be deleted from the management console

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Enable Userstore
6. Update
7. Login to managementconsole 
8. Try to delete the added userstore from management console

**Observation**
Cannot delete the userstore from the management console

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console27](https://user-images.githubusercontent.com/31848014/97529402-d3f96f00-19d5-11eb-9e46-c879fdd73aad.png)

**Comment by nilasini** [comment] 2020-11-06 04:26
Couldn't reproduce this issue with 5.11.0-beta4. Hence closing this issue.

**Closed by nilasini** 2020-11-06 04:26 UTC
Labels: Priority/Highest, Severity/Critical, bug
