### ISSUE TITLE
Application role shows unauthorized permissions in the drop down

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#18237] opened 2023-11-30 12:33 UTC
**Describe the issue:**
$subject

https://github.com/wso2/product-is/assets/61885844/1f8e849f-61c9-4687-8037-32b8171bfd7c

**How to reproduce:**
- Login to console.
- Go to user management -> roles section.
- Go to permissions.
- Click on dropdown.
- Try refreshing the page if not visible. 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment] 2023-11-30 13:07
Duplicate of https://github.com/wso2/product-is/issues/18171

**Closed by dewniMW** 2023-11-30 13:07 UTC
Labels: ui, bug
