### ISSUE TITLE
[UX] No way to add multiple API resources at once 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18181] opened 2023-11-29 09:06 UTC
**Describe the issue:**

<img width="728" alt="Screenshot 2023-11-29 at 14 16 24" src="https://github.com/wso2/product-is/assets/29881881/50e97474-afe0-4f1a-ba77-04d60efb7cea">

Since there are many API resources getting listed but we cannot add them as a set. Due to this we need to add one then add authorized scopes and then finish. Then only we can add the next one. 

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment] 2023-11-29 09:18
Modified the severity level @Buddhimah FYI

**Comment by dewniMW** [comment] 2023-11-30 02:55
Duplicate of https://github.com/wso2/product-is/issues/17454

**Closed** 2023-12-07 07:11 UTC
Labels: ui, Priority/Normal, Severity/Major, bug, consumer-exp, ux, Affected/7.0.0-beta
