### ISSUE TITLE
Observing error logs while executing mysql DB scripts

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16160] opened 2023-06-29 06:01 UTC
**Describe the issue:**
when executing mysql.sql script getting following error logs. 
1. <HOME>/dbscripts
     

> 11:17:41    CREATE INDEX IF NOT EXISTS INDEX_UM_TENANT_ORG_UUID ON UM_TENANT(UM_ORG_UUID)    Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS INDEX_UM_TENANT_ORG_UUID ON UM_TENANT(UM_ORG_UUID)' at line 1    0.00012 sec

3. <HOME>/dbscripts/identity

> 11:18:20    CREATE TABLE IF NOT EXISTS IDN_OAUTH2_TOKEN_BINDING (             TOKEN_ID VARCHAR (255),             TOKEN_BINDING_TYPE VARCHAR (32),             TOKEN_BINDING_REF VARCHAR (32),             TOKEN_BINDING_VALUE VARCHAR (1024),             TENANT_ID INTEGER DEFAULT -1,             UNIQUE (TOKEN_ID,TOKEN_BINDING_TYPE,TOKEN_BINDING_VALUE),             FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE )ENGINE INNODB    Error Code: 1071. Specified key was too long; max key length is 3072 bytes    0.00056 sec

**How to reproduce:**
1. Run mysql.sql scripts in <HOME>/dbscripts and <HOME>/dbscripts/identity in mysql database.

**Expected behavior:**
Scripts should be executed without any errors. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment] 2023-06-30 09:16
Couldn't reproduce on the wso2is-6.2.0-Alpha4-SNAPSHOT

**Comment by DMHP** [comment] 2023-07-24 11:34
While executing /dbscripts did not observe any issue in wso2is-6.2.0-alpha4-SNAPSHOT, but noticed some issues when executing /dbscripts/identity.
<img width="526" alt="image" src="https://github.com/wso2/product-is/assets/12690906/ffe84018-5e34-4b45-adfe-c0f70adf1349">
<img width="484" alt="image" src="https://github.com/wso2/product-is/assets/12690906/1e8e8d41-554b-4bef-9449-8970b5284757">
<img width="582" alt="image" src="https://github.com/wso2/product-is/assets/12690906/ac441e71-f9be-4c21-8bbd-4be7a000c366">
<img width="488" alt="image" src="https://github.com/wso2/product-is/assets/12690906/14610831-c41c-4390-85af-3f548fc0cc0a">
<img width="619" alt="image" src="https://github.com/wso2/product-is/assets/12690906/bac2c7e5-b129-4123-9534-ab92d4419bf0">

**Comment by DMHP** [comment] 2023-07-31 04:23
@Shenali-SJ Please update the issue with your findings.

**Comment by Shenali-SJ** [comment] 2023-07-31 04:52
The first sub-issue has been resolved in Carbon Kernel version 4.9.6, which means it is fixed starting from IS 6.2.0 Alpha 3 and onwards.

**Comment by Shenali-SJ** [comment] 2023-08-09 11:23
MySQL script located in dbscripts/identity has been tested using 5.7.12 MySQL Community Server (GPL) with the updated character set of latin1 and it did not produce any errors.

**Closed** 2023-09-07 06:54 UTC
Labels: bug, 7.0.0-stabilisation
