### ISSUE TITLE
Duplicate Request validation certificate alias

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9963] opened 2020-10-20 02:45 UTC
**Describe the issue:**
![1](https://user-images.githubusercontent.com/20336761/96533804-29ce6880-12ac-11eb-9f9b-3d7325ace413.png)

In console app for a saml sp the Request validation certificate alias has been duplicated.

**How to reproduce:**
Add saml sp through the console and check drop down "Request validation certificate alias"

**Expected behavior:**
No duplication.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by ChamathNS** [comment] 2021-01-15 05:32
This issue is not reproducible in IS-5.12.0-m5 environment.
The default options in the wso2carbon.jks shipped in product does not contain duplicate certificate alias and hence, no duplicates would be listed in the drop down of the "Request validation certificate alias".

This was verified manually by calling the `https://{{server-url}}/t/{{tenant-domain}}/api/server/v1/applications/meta/inbound-protocols/saml` EP which is responsible for populating the options in the drop down field.

In the case of using a custom keystore, the `alias` should be unique as per the documentation [1]. Hence, no duplicate alias should exist in the keystore resulting in unique alias entries in the dropdown list mentioned above.

[1] https://docs.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html

**Comment by nilasini** [comment] 2021-01-15 05:48
@ChamathNS it is reproducible when you create a tenant and login to that tenant, check the field  Request validation certificate alias

**Comment by mefarazath** [comment] 2021-01-15 11:41
Any idea why we need this alias value?
Shouldn't we be using the value stored in the certificate section for request validation?

**Comment by ChamathNS** [comment] 2021-01-18 09:11
> Any idea why we need this alias value?
> Ideally, shouldn't we be using the value stored in the certificate section for request validation?

@mefarazath AFAUI, this alias value will only be used when the JWKS endpoint is provided for the certificate section. If the application certificate is provided then it will be used. If the JWKS EP is provided, this alias value will be used by the Certificate Resolver to pick the key from the key set. The alias is applicable for key rotation scenarios [1].

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/Multiple-keys-support-in-JWKS-endpoint-td159691.html#a159706

**Comment by mefarazath** [comment] 2021-01-18 09:29
For SAML, we usually do not associate the JWKS at all. I initially thought we are using this alias for picking the cert in a certain SAML flow. In prev, versions this was used to pick the public key of the SP for request validation (Before we started storing the cert in the DB).

@inthirakumaaran can your usage of the this alias value in certification rotation scenarios?

**Comment by ChamathNS** [comment] 2021-01-18 10:19
.@nilasini In the default behavior of the drop down element, the selected value should be a child element of the options populated in the drop down list. [1]
In the case you have pointed out, there is only one element in the drop down list. Hence, the selected and the available options will be the same. To remove the duplication of alias entries, the following are the suggested approaches.

1.  In case there is only one option and the field is mandatory, change the input from a `drop down` to a `read-only label` or a similar read-only element where the default value is already set.
2. If the input is not mandatory, add `none` option to the drop down child elements.

As per now, in all of the instances, the drop down selection behaves in the default manner described above where the child elements will be shown in the drop down list even if there is only a single option.

If we are to change the behavior of the drop down selection to be in line with either of the approaches suggested above, we can change the behavior centrally, or else, we can change the behavior in the specific cases such as the requestSigningCertificateAlias selection.
If we are to change the drop down behavior centrally, we need to tread with caution since it might break the working flows where the drop down input is used. 
If we were to only fix this specific case, then it would cause inconsistent behavior in the app. 

@ayshsandu @jeradrutnam 

[1] https://semantic-ui.com/modules/dropdown.html#selection

**Comment by ChamathNS** [comment] 2021-01-19 12:30
Closing this since it is not a blocking issue. Enabling the signature validation certificate alias option via a configuration is is tracked with https://github.com/wso2/product-is/issues/11003.

**Closed by ChamathNS** 2021-01-19 12:30 UTC
Labels: Priority/Highest, Severity/Minor, bug, ui
