### ISSUE TITLE
SMS OTP authenticator does not send the HTTP request payload correctly.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#15807] opened 2023-04-28 09:52 UTC
**Describe the issue:**

The SMS OTP Authenticator does not send the HTTP request payload to the SMS OTP provider properly when the parameter enable_payload_encoding_for_sms_otp is enabled.

**How to reproduce:**

- Create an SMS OTP identity provider with the following payload format with a web hook.
```{"src": "+94565656565", "dst": "$ctx.num", "text": "$ctx.msg" }```
- Configure SMS OTP to the service provider.
- Try out the login flow.
- The request sent from the WSO2 Identity Server would be as follows.
```{"src": "+94565656565", "dst": ""+94153456789"", "text": ""Verification Code: "243071" }```
- Validate the request with https://jsonformatter.curiousconcept.com/#.
- The request is not valid. However, it works when the above said configuration is disabled.

We might need to check whether the encoding process is working fine for these kinds of requests.

**Expected behavior:**

A proper request should be sent to the SMS OTP provider.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

 - Product Version: IS 6.0
 - OS: Ubuntu
 - Database: H2
 - Userstore: JDBC

---

**Comment by Shenali-SJ** [comment] 2023-09-11 07:34
This issue is not reproducible in 7.0.0-m1. The request payload is valid when checked against the said JSON formatter.

<img width="983" alt="Screenshot 2023-09-11 at 13 00 35" src="https://github.com/wso2/product-is/assets/66279520/c6dd9087-76c5-4e73-996d-734b7d84d65a">

**Comment by isuruhettiarachchi** [comment] 2023-09-22 14:14
This issue is happening happening in 6.1.0.

When an `application/json` header is used payload will not be encoded even if the `enable_payload_encoding_for_sms_otp` is configured. However, the following payload will not encoded as a proper json payload.

Configured payload in the IS:

```
{"src": "+94565656565", "dst": "$ctx.num", "text": "$ctx.msg" }
```
Payaload sent from the IS to SMS service provider:
```
{"src": "+94565656565", "dst": ""+94153456789"", "text": ""Verification Code: "243071" }
```
The above payload is not a valid JSON payload.

https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/e72d6ae4f1dd44035d85449e16a3898790197660/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1344-L1361

**Comment by madurangasiriwardena** [comment] 2023-11-22 08:15
Closing the issue as per the comments since the issue is not re-producible in the latest distributions.

**Closed by madurangasiriwardena** 2023-11-22 08:15 UTC
Labels: bug, 7.0.0-stabilisation
