### ISSUE TITLE
Organization and Application audience concept is not clear under the "Roles" config of an applicaition

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17867] opened 2023-11-17 06:54 UTC
**Describe the issue:**
$subject

![image](https://github.com/wso2/product-is/assets/5061791/c9cba473-67bb-476f-9e11-afa58bf07f6f)

**How to reproduce:**

**Expected behavior:**
Imporve the UX and descriptions to clearly denote what each type of role is

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-11-18 15:45
Duplicate of https://github.com/wso2/product-is/issues/17820

**Closed** 2023-11-18 15:45 UTC
Labels: ui, Resolution/Duplicate, Severity/Major, bug, Affected/7.0.0-Alpha, Component/B2B
