### ISSUE TITLE
Enable ask password option not enable the ask password option on user creation

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18242] opened 2023-11-30 13:21 UTC
**Describe the issue:**
Enable ask password  

<img width="628" alt="image" src="https://github.com/wso2/product-is/assets/39077751/b4c1e27a-305f-417f-8c5f-1c69cea4259b">

**How to reproduce:**
1. Login to console
2. Navigate to the login & registration -> Invite User to Set Password
3. Enable user email registration

**Expected results**
Invited the user to set their password should be enable in user creation wizard

 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT-4957
 - OS: [e.g., Windows, Linux, Mac]
 - Database: postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment] 2023-12-01 06:05
Duplicate of https://github.com/wso2/product-is/issues/18248. Hence closing this issue.

**Closed by Thisara-Welmilla** 2023-12-01 06:05 UTC
Labels: Severity/Blocker, bug, Affected/7.0.0-beta2, IS7-Unification Issues, DB/postgres
