### ISSUE TITLE
[consoleApp] [Manage] Cannot assign roles to a tenant user in a secondary userstore by editing the user

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10418] opened 2020-11-09 15:15 UTC
**Describe the issue:**
A role can't be assigned to an already created user that is in the secondary userstore in tenant mode when editing the user. 

**How to reproduce:**
1. Login to console as the admin of a created tenant 
2. Go to Manage > Users and create a user without assigning any roles
3. Go to Manage > Roles and create a new role
4. Go to Manage > Users > Edit user > Roles > Update User Roles and assign a role for the user and press save

**Observation:**
The success message is displayed but the role doesn't get added

**Environment information:**
 - Product Version: IS 5.11.0 Beta6 Snapshot
 - OS: Mac
 - Database: MySQL 8
 - Secondary Userstore: JDBC
 - Tenant mode

**Comment by janakamarasena** [comment] 2020-11-10 08:47
Was not able to reproduce

**Comment by JeethJJ** [comment] 2020-11-11 17:15
This issue was reproduced in the following environment as well. 
 - Product Version: 5.11.0 Beta6 Snapshot
 - OS: Ubuntu 18.04 LTS
 - Database: Maria DB 10.4
 - Userstore: JDBC

After the admin role is added to a user, other roles aren't getting added. Also it was experienced in super admin mode as well.


Request when adding a role after adding admin: 
```
{"failOnErrors":1,"Operations":[{"data":{"schemas":["urn:ietf:params:scim:schemas:core:2.0:Role"],"Operations":[{"op":"add","value":{"users":[{"value":"3632df35-6641-4876-9178-b64654150a4d"}]}}]},"method":"PATCH","path":"/Roles/6dacbf87-a7a5-4775-b2b4-58330f586a2b"},{"data":{"schemas":["urn:ietf:params:scim:schemas:core:2.0:Role"],"Operations":[{"op":"add","value":{"users":[{"value":"3632df35-6641-4876-9178-b64654150a4d"}]}}]},"method":"PATCH","path":"/Roles/a8a6a84c-d955-4ae0-9aeb-0b4ebd97214b"},{"data":{"schemas":["urn:ietf:params:scim:schemas:core:2.0:Role"],"Operations":[{"op":"add","value":{"users":[{"value":"3632df35-6641-4876-9178-b64654150a4d"}]}}]},"method":"PATCH","path":"/Roles/ff602749-8e05-4c4f-b544-c62a30507836"},{"data":{"schemas":["urn:ietf:params:scim:schemas:core:2.0:Role"],"Operations":[{"op":"add","value":{"users":[{"value":"3632df35-6641-4876-9178-b64654150a4d"}]}}]},"method":"PATCH","path":"/Roles/bbd8e574-22bb-47b4-b372-0b959035e144"}],"schemas":["urn:ietf:params:scim:api:messages:2.0:BulkRequest"]}
```

Responce : 
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:BulkResponse"],"Operations":[{"bulkId":"","method":"PATCH","location":"https://localhost:9443/scim2/Roles/6dacbf87-a7a5-4775-b2b4-58330f586a2b","status":{"code":200}},{"bulkId":"","method":"PATCH","location":"https://localhost:9443/scim2/Roles/a8a6a84c-d955-4ae0-9aeb-0b4ebd97214b","status":{"code":200}},{"bulkId":"","method":"PATCH","response":"{\"schemas\":[\"urn:ietf:params:scim:api:messages:2.0:Error\"],\"detail\":\"Error occurred while updating permissions for role: admin\",\"status\":\"500\"}","status":{"code":500}}]}
```

**Comment by janakamarasena** [comment] 2020-11-11 20:31
Resolved with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/308

**Closed by janakamarasena** 2020-11-11 20:31 UTC
Labels: Priority/Highest, Severity/Critical, bug, console
