### ISSUE TITLE
Fix Redirecting to general tab page after changing the default authenticator in the Custom connector

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18435] opened 2023-12-05 07:12 UTC
**Describe the issue:**
In the current behavior, after the default authenticator is changed from the settings page, it redirects to the getting start page.

https://github.com/wso2/product-is/assets/41188245/af90723d-7442-4428-9e5b-32e0cb8850d5

**How to reproduce:**
1. Create a Custom Connector from Connections page
2. From the settings page add around 2 authenticators
3. change the default authenticator.

**Expected behavior:**
It should redirect back to the setting page, not the getting started page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac
 - Database:  MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment] 2024-01-09 05:21
Duplicate of https://github.com/wso2/product-is/issues/18442. (Fix is already available in product)

**Closed by DilshanSenarath** 2024-01-09 05:21 UTC
Labels: ui, Priority/Highest, Severity/Major, bug, Affected/7.0.0-beta2, Component/Custom Connector
