### ISSUE TITLE
In tenant mode, user on-boarding with email verification/new password creation using ask password email, user is redirected to super-tenants user portal authentication endpoint

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#7621] opened 2020-02-15 09:53 UTC
**Description:**
In tenant mode, user on-boarding with email verification/new password creation using ask password email, after email verification/password creation, user is redirected to super-tenants user portal authentication endpoint. 

**OS, DB, other environment details and versions:**    
OS : Ubuntu 18.04
Primary user store : MySQL 8.0.19
Secondary user store : MySQL 8.0.19

**Steps to reproduce:**
Following steps are to reproduce the issue when trying in ask password mode;
1. Create a tenant.
2. [Enable ask password and email verification for user on-boarding](https://is.docs.wso2.com/en/next/learn/creating-users-using-the-ask-password-option/#file-based-config).
3. Create an user for the tenant with ask password option enabled and provide a valid email. 
4. Using the email, create the password for the user. After creating the password user is redirected to a super-tenant user portal authentication endpoint.

**Comment by madurangasiriwardena** [comment] 2020-02-25 08:33
This is because the application registered tenant and user registered tenant are not the same. For example, 

- user tries to user-portal application in a tenant (https://localhost:9443/t/wso2.com/user-portal/)
- in the login page, a user clicks "Create Account" link and register for a different tenant
- after successful account creation, the user is redirected back to the login page for the original tenant and now when the user tries to login with the newly created user account. Now when the user tries to login, authentication will fail since the user is not belonging to the tenant of the application.

Closing the issue since the above described issue is actually not reproduced. We will be improving the login pages to make sure that the user will be registered to the application registered tenant.

**Closed by madurangasiriwardena** 2020-02-25 08:33 UTC
Labels: Affected/5.10.0-Beta2, Priority/Highest, Severity/Blocker
