### ISSUE TITLE
if we send a request object with a wrong signature verification the flow works

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#1708] opened 2017-12-18 13:34 UTC
if we send a request object with a wrong signature verification the flow works

steps
1.pass a sign value which is not in the identity servers client trust store as below. we see the system does not validate the wrong signature 

https://192.168.48.106:8243/AuthorizeAPI/v1.0.0/?response_type=code%20token&client_id=qO1088fx_cqtghF7rNgppn3NVpQa&scope=payments openid&redirect_uri=http://openbanking.staging.wso2.com:9999/playground2&state=YWlzcDozMTQ2&request=eyJraWQiOiJrMmJkYyIsImFsZyI6IlJTMjU2In0.eyJtYXhfYWdlIjo4NjQwMCwic2NvcGUiOiJvcGVuaWQiLCJjbGFpbXMiOnsiaWRfdG9rZW4iOnsiYWNyIjp7ImVzc2VudGlhbCI6dHJ1ZX0sIm9wZW5iYW5raW5nX2ludGVudF9pZCI6eyJ2YWx1ZSI6IjEyMzQ1IiwiZXNzZW50aWFsIjp0cnVlfX0sInVzZXJpbmZvIjp7ImVtYWlsX3ZlcmlmaWVkIjp7ImVzc2VudGlhbCI6dHJ1ZX0sIm5pY2tuYW1lIjpudWxsLCJnaXZlbl9uYW1lIjp7ImVzc2VudGlhbCI6dHJ1ZX0sImVtYWlsIjp7ImVzc2VudGlhbCI6dHJ1ZX0sInBpY3R1cmUiOm51bGx9fSwiaXNzIjoiczZCaGRSa3F0MyIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIGlkX3Rva2VuIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6XC9cL2NsaWVudC5leGFtcGxlLm9yZ1wvY2IiLCJzdGF0ZSI6ImFmMGlmanNsZGtqIiwibm9uY2UiOiJuLTBTNl9XekEyTWoiLCJjbGllbnRfaWQiOiJzNkJoZFJrcXQzIn0.gfNJCTvAmygywRdoB-QcoR4UnyiwNJehhngsBx7IBvEQxBGr7krzqLBLcBrAsdyggKdcGCA9t1L9GU2MjOR-YnPRQhyAg6RqR8fUDAhW8eY7BtclIgtJZD-GrMcZV1oCIzaqMu_d1NPvRPfCDLfEjvzXBPorA6bdgUaK7wJlQMt6lu2-LNSViaKPPIB5N3eAnr7ImkpZgXSmKkNiH9y2MhKDFEneJv9jftGpThF-ekUOPpUSQumAOJ7no8CQnXb6VfKuZ50yIYVQjouKNhEsWvmQSJNRLUWFwi6bpkmUpvD3_y4pAjPbWMJ5XB0EZFAxvKcLvIzdDxd4bPRRhilVjg

**Comment by Buddhimah** [comment] 2019-03-05 13:28
This issue might occur due to the implementation that was used in IS-5.5.0 . This is explained in this [issue](https://github.com/wso2/product-is/issues/2159). But after IS 5.5.0 the implementation is changed so that this issue is no longer can be reproduced. Therefore can we close the issue @malithie

**Comment by malithie** [comment] 2019-03-06 02:43
Closing as the issue is not visible on 5.7.0+ versions

**Closed by malithie** 2019-03-06 02:43 UTC
Labels: Affected/5.5.0, Component/OIDC, Priority/High, Severity/Critical, Type/Bug
