### ISSUE TITLE
Migration related to TOTP authenticator for IS 5.12.0

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11016] opened 2021-01-20 07:12 UTC
There are few affected paths for a user migrating a user from 5.11.0 to 5.12.0. This information needs to be captured in the TOTP docs.

### The connector is no longer added to the dropins folder
The connector is now moved the repository/components/plugins 

### The totpauthethentication endpoint is no longer packed with the product. Users having customized totp pages have two choices.

1. Merge the customziations to the authentication portal app.  
The pages related to TOTP are
```
- enableTOTP.jsp (TOTP enroll page)
- totp.jsp (TOTP login page)
- totpError.jsp (TOTP error page)
```

- The 18n keys are moved to the i18n property file of the authentication portal

2. Use their existing customized TOTP web app. Deploy it to the server and using the deployment.toml point to existing customized pages.
```
[authentication.authenticator.totp.parameters]
TOTPAuthenticationEndpointURL="totpauthenticationendpoint/totp.jsp"
TOTPAuthenticationEndpointErrorPage="totpauthenticationendpoint/totpError.jsp"
TOTPAuthenticationEndpointEnableTOTPPage="totpauthenticationendpoint/enableTOTP.jsp"
```

### The option to send OTP by email as a fallback option has been disabled by default. In order to obtain the behaviour of previous versions add the below config,

```
[authentication.authenticator.totp.parameters]
allow_sending_verification_code_by_email=true
```

**Comment by ashendes** [comment] 2022-03-31 21:46
Duplicate of https://github.com/wso2/product-is/issues/11174

**Closed** 2022-06-21 07:51 UTC
Labels: docs, 6.0.0-Migration, Affected-6.0.0
