### ISSUE TITLE
Login Page is not properly when trying the Passive STS sample

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#9287] opened 2020-08-24 05:30 UTC
**Describe the issue:**
The login page is not properly formatted when trying to get a SAML 2.0 token by using the url given in the official [documentation](https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-wsfed/#try-it-out)[1]

**How to reproduce:**
1. Configure a Passive STS application as given in [documentation](https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-wsfed/#configuring-single-sign-on-using-ws-federation)[2]
2. Access the URL, `http://localhost:8080/PassiveSTSSampleApp?samlv=2-0` to get a SAML 2.0 token
3. The directed login page will be as follows.
![image](https://user-images.githubusercontent.com/12439288/91007109-c0f2a900-e5f8-11ea-9d5c-859e307a6939.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 M31
 - Browser: Chrome and Firefox

---
[1] https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-wsfed/#try-it-out
[2] https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-wsfed/#configuring-single-sign-on-using-ws-federation

**Comment by deshankoswatte** [comment] 2020-09-01 10:03
@pamodaaw I had the same issue before my changes too. This issue is a duplicate of https://github.com/wso2/product-is/issues/8354

**Closed** 2020-10-15 03:50 UTC
Labels: Affected/5.11.0-m31, Priority/High, Severity/Critical, bug, gateway, login-portal, ux
