### ISSUE TITLE
[Intermittently] Session Expiry Issue When Removing More Than Two Users Sequentially from a Group

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18761] opened 2023-12-24 13:53 UTC
**Describe the issue:**
After adding more than two users to a group, attempting to remove more than two users from the group sequentially results in a session expiry.

**How to reproduce:**

1. Add more than two users to a group.
2. Sequentially attempt to remove more than two users from the group.

**Expected behavior:**
The removal of users from the group should not result in a session expiry.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database: DB2
 - Userstore:JDBC

---

[group-session.webm](https://github.com/wso2/product-is/assets/39120228/68af65e7-a6be-479e-9489-ce65bf90eabf)

**Comment by ZiyamSanthosh** [comment] 2024-01-04 07:12
**Analysis**
1. The issue is not related to deleting multiple users deletion. It occurs during an attempt to delete the admin user from an existing group.
2. When the admin user is removed from a group, all the tokens related to the admin user is getting revoked. Hence, the session will get expired and the admin gets logged out from the console.
3. This is an expected behaviour in our current architecture where all tokens related to a user will be revoked after the user gets removed from the group.
https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ae84cb940422ec0b60e1c697cd6f5ddfda3e8348/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthUtil.java#L779

The tokens are being revoked since the tokens will have the scopes mapped to relevant permissions which could have been assigned to the user by adding the user to the specific group. To remove those permissions, all the active tokens are being revoked.

Hence this behaviour is expected, reducing the priority of the issue. Further discussed has to be conducted.

FYI @hasanthiP

**Comment by NilukaSripalim** [comment] 2024-01-05 04:33
<img width="1728" alt="Screenshot 2024-01-05 at 10 02 53" src="https://github.com/wso2/product-is/assets/39120228/f66956b9-cabe-4d6c-b083-4586024b5473">
![Uploading Screenshot 2024-01-05 at 10.03.05.png…]()

**Comment by DMHP** [comment] 2024-01-05 05:01
Ideally, none of the tokens should be invalidated when an admin user is removed from a certain group. However, when a user's groups are updated, all of the tokens are revoked due to the way we have implemented this. It appears that after the user and group roles are separated, the token revocation process is not being handled correctly. We need to fix this with a proper evaluation.

**Comment by isharak** [comment] 2024-11-07 13:43
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 13:43 UTC
Labels: Priority/High, Severity/Major, Type/Bug, QA-Reported, Affected/7.0.0-beta4, IceBox
