### ISSUE TITLE
Audit logs and events for recovery flows

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#10751] opened 2020-12-11 13:13 UTC
The product needs to have audit logs for the below recovery scenarios.

- Welcome Email (Ask password feature)
- Forgot password (Password reset with recovery email feature)
- Admin reset password (Admin forced password reset with recovery email feature)

Some of these flows already have audit logs and events triggered. Below are some of the flows I could capture.
Password reset with recovery email has below events triggered at the time when the recovery email is sent.

```
PRE_SEND_RECOVERY_NOTIFICATION
POST_SEND_RECOVERY_NOTIFICATION
```
And below audit log is printed

```TID: [-1234] [2020-10-13 10:09:00,660] [8c522ea4-3f51-4462-b160-0a4261f832f6]  INFO {AUDIT_LOG} - Initiator : wso2.system.user@carbon.super | Action : Password recovery | Target : user6 | Data : {"UserStoreDomain":"PRIMARY","Notification Channel":"EMAIL"} | Result : Success```

When the user recovers the password, the below events are triggered.

```
PRE_ADD_NEW_PASSWORD
POST_ADD_NEW_PASSWORD
```
Below audit log is printed

```TID: [-1234] [2020-10-13 10:09:51,066] [7e85d4eb-b958-4f5c-b60c-4743e9c986b9]  INFO {AUDIT_LOG} - Initiator : wso2.system.user@carbon.super | Action : Password reset | Target : user6 | Data : {"ServiceProviderName":"User Portal","UserStoreDomain":"PRIMARY"} | Result : Success```

However, the ask password feature does not have such comprehensive logs and events. All the above 3 flows need to be verified for events and audit logs and add them.

**Comment by dewniMW** [comment] 2020-12-16 02:26
Duplicate of https://github.com/wso2/product-is/issues/10365

**Closed by dewniMW** 2020-12-16 02:26 UTC
Labels: improvement
