### ISSUE TITLE
SAML2 grant type with cutom subject attribute throws an error

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15374] opened 2023-01-18 02:22 UTC
**Describe the issue:**
When using SAML2 grant type, when the subject claim is assigned a particular claim (ex: email), the AccessTokenIssuer throws and error saying, `Error occurred while validating grant: User not found in local user store`. 

The guess for the root cause is, with [this](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1855/files) PR, the user ID is being getting from the subject identifier.

**How to reproduce:**
1. Use [this](https://is.docs.wso2.com/en/latest/guides/access-delegation/saml2-bearer-assertion-profile/) guide to configure an app with SAML2 grant type. ([refer this issue when configuring](https://github.com/wso2/product-is/issues/15372))
2. Goto the configured app and add email as the subject claim.
3. Use the self-contained access token and try to retrieve userinfo as mentioned [here](https://is.docs.wso2.com/en/latest/references/concepts/authentication/user-information/#invoke-the-userinfo-endpoint). ([refer this issue when configuring](https://github.com/wso2/product-is/issues/15368))

**Expected behavior:**
Recieve userinfo accoriding to the requested scope and configured requested claims.

**Related Issues**
1. https://github.com/wso2/product-is/issues/15372
2. https://github.com/wso2/product-is/issues/15368

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Mac
 - Database: Postgres
 - Userstore: JDBC

**Comment by ashanthamara** [comment] 2023-12-07 10:14
Closing since this is not reproducing in latest IS-7.0.0-beta2 pack

**Closed by ashanthamara** 2023-12-07 10:14 UTC
Labels: Severity/Critical, bug, backend, 6.1.0-bug-fixing
