### ISSUE TITLE
MyAccount is throwing errors for sub org users

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17945] opened 2023-11-20 06:10 UTC
**Describe the issue:**

**How to reproduce:**
- Create a sub org called `test`
- Switch to it and create a user called `testorguser` on the sub org
- Logout from Console and goto https://localhost:9453/myaccount
- Click on `Sign In with SSO` and provide org name `test`
- Login with `testorguser` credentials
- Now try going to Personal info and security sections

<img width="430" alt="Screenshot 2023-11-20 at 11 39 15 AM" src="https://github.com/wso2/product-is/assets/719073/864ed8e6-ec16-4bba-adf9-72610e18f415">

The APIs are returning multiple errors such as below
```
{
    "code": "UAA-10005",
    "message": "Error while getting associations of user: a0bc981f-b968-4d1b-94ee-838eb99ef273@6aadbb25-bce4-43e9-a4d0-a1319d637e23@6aadbb25-bce4-43e9-a4d0-a1319d637e23",
    "description": "The provided user identifier is invalid",
    "traceId": "6d40887d-69b3-419a-a2cb-7e5478b24d79"
}
```
```
{
    "code": "BCA-15003",
    "message": "Unable to retrieve user backup codes.",
    "description": "Error occurred failed while trying to access userRealm of the user : a0bc981f-b968-4d1b-94ee-838eb99ef273@6aadbb25-bce4-43e9-a4d0-a1319d637e23@6aadbb25-bce4-43e9-a4d0-a1319d637e23",
    "traceId": "f161dfb0-170a-430f-a9d0-707d8dfa12c5"
}
```

**Environment information** 
 - Product Version: IS 7.0 Alpha 2

**Comment by dewniMW** [comment] 2023-11-22 08:07
The issue is not reproducing in the latest pack. Hence closing the issue
https://github.com/wso2/product-is/assets/24982871/c5b8d512-75cc-445b-9c40-8f79e008840c

**Closed by dewniMW** 2023-11-22 08:07 UTC
Labels: bug, Affected/7.0.0-Alpha
