### ISSUE TITLE
Can not add User Store from Management Console

### ISSUE THREAD

**Issue by murathazer** [wso2/product-is#8436] opened 2020-05-31 18:38 UTC
Getting error when trying to add user store from management console;

Error 403 - Forbidden in the browser and the following error in the console;

```
[2020-05-31 21:31:44,527] [fdf3924c-224f-40c7-a5d8-2fdc9874e60b] ERROR {org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve} - Could not handle request: null java.lang.NullPointerException
	at org.wso2.carbon.tomcat.ext.internal.Utils.getTenantDomain(Utils.java:41)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.initCarbonContext(CarbonContextCreatorValve.java:79)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:56)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Environment information** 
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: MySql
 - Userstore: JDBC

**Comment by ruwanta** [comment] 2020-06-01 02:42
Hi @murathazer ,
Can you please provide more details.
e.g What user store configured, the steps you followed, is it super tenant or another tenant, etc,

The provided stack-trace does not carry any traceable information to diagnose, you would understand.

**Comment by gdiamond** [comment] 2020-06-04 01:54
I've run into the same problem but using Postgres.

User Store Manager Class:  org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager

Domain Name:  MYUEN

Connection URL:  jdbc:postgresql://*****:*****/*****?preferQueryMode=simple
Connection Name:  *****
Connection Password:  *******
Driver Name:  org.postgresql.Driver

Error in the browser:
![Screen Shot 2020-06-03 at 7 34 38 PM](https://user-images.githubusercontent.com/8548757/83705641-b533af80-a5d2-11ea-891f-c91adace85e6.png)
Error in wso2carbon.log:
```
TID: [-1] [] [2020-06-03 19:34:36,024] [da79b0a9-42f0-400e-b350-bcce4560d902] ERROR {org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve} - Could not handle request: null java.lang.NullPointerException
	at org.wso2.carbon.tomcat.ext.internal.Utils.getTenantDomain(Utils.java:41)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.initCarbonContext(CarbonContextCreatorValve.java:79)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:56)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I have not investigated further by I have a feeling that the table schemas have changed between 5.4.1 where this works for me and 5.10.0 where it no longer works for me.  
In my case, the tables are implemented as read-only views of user tables from our legacy portal.  I will look into my theory and let you know my results.

@murathazer, Are you connecting to a JDBC database created by IS prior to 5.10.0?  You will likely need to upgrade the schema in the database you are using with your secondary user store.

**Comment by murathazer** [comment] 2020-06-04 19:22
@ruwanta it was clean & fresh Install and we were trying to and mysql backed JDBC user store. And it was single super tenant.

Yes you're right, stack trace doesn't provide any useful information, because of that we couldn't solve the problem and decided to open a GitHub issue.

@gdiamond it was fresh and clean Install.

We switched back to 5.9.0 and everything is ok until now, we continue to development.

**Comment by Navino16** [comment] 2020-08-24 13:09
Hi !

We have exactly the same issue with IS 5.10.0 (version from github release).

Product Version: IS 5.10.0
OS: Debian 10
Database: MySql
Userstore: JDBC

**Comment by gdiamond** [comment] 2020-08-24 15:17
@Navino16 I don't know the exact problem but I was able to get it fixed via a WUM patch.

**Comment by Navino16** [comment] 2020-08-27 08:49
Hi @gdiamond !

As far as I know, WUM patch are provided by taking a subscription with WSO2 wich is actualy not a solution for us.
Thanks for your response 👍

**Comment by dexterfcp** [comment] 2020-09-21 14:52
I have a same problem with same information, and the WUM paths is actualy not a solution for us. 

> 
> 
> Hi !
> 
> We have exactly the same issue with IS 5.10.0 (version from github release).
> 
> Product Version: IS 5.10.0
> OS: Debian 10
> Database: MySql
> Userstore: JDBC

**Comment by darshanasbg** [comment] 2020-10-28 06:36
@murathazer I suspect this is due to the use of `org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager`.

If you are using the default db script like `wso2is-5.10.0/dbscripts/mysql.sql` to create the schema of the user store, with the IS 5.10.0 AFAIK you should use `org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager`.

Even this worked with about change, it should check for possible improvement of the code to provide more details on the error.

**Comment by murathazer** [comment] 2020-10-28 16:47
@darshanasbg we try both options, all produce same exception.

**Comment by sthenusan** [comment] 2020-11-05 06:25
@murathazer I tried to create a secondary user store with WSO2 is 5.10 and I created it successfully. I tried to reproduce the same error that you got to solve that issue. but, still  I am unable to reproduce it. May you tell me the exact steps that you followed to reproduce the error?

**Closed** 2020-11-09 05:32 UTC
Labels: bug
