### ISSUE TITLE
Auto-login after password recovery

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9085] opened 2020-07-28 07:57 UTC
Automatically login the user after password recovery, since the user is already validated when the old password is entered in password recovery.

**Comment by pulasthi7** [comment] 2020-10-29 11:01
Possible duplicate of https://github.com/wso2/product-is/issues/8634

**Comment by isharak** [comment] 2024-11-06 03:14
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 03:14 UTC
Labels: Type/NewFeature, consumer-exp, IceBox
