### ISSUE TITLE
Google one tap dialog box closes after an unauthorized user error pop up cancel button clicked.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16127] opened 2023-06-23 08:06 UTC
**Describe the issue:**
When an unauthorized user tries to log in using Google one tap pops up an error.  After the okay button is clicked the one-tap dialog box closes completely.

https://github.com/wso2/product-is/assets/41188245/c32d17a4-86dd-48d2-a28d-06bb15cdf39a

**How to reproduce:**

1. Create a Google IDP and enable one tap. https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#sign-in-with-google-one-tap
2. Create a service provider and add Google as an authentication step
3. try to log in to the app using google one tap with an unregistered email.
4. Click `OK` in the error pop up

**Expected behavior:**
Google One tap window should pop up after the error message is dismissed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

-  Product Version: [e.g., IS 5.10.0, IS 5.9.0] - IS 6.2.0-alpha
- OS: [e.g., Windows, Linux, Mac] - Mac
- Database: [e.g., MySQL, H2] - H2 / MSSQL
- Userstore: [e.g., LDAP, JDBC]

---

**Comment by DilshanSenarath** [comment] 2023-08-02 04:09
This issue is not reproducible. Check with the latest Alpha-4 IS. Refer the following video.

https://github.com/wso2/product-is/assets/74205483/cb656b45-734f-4794-b491-c39d79092b1d

I have checked this issue with JIT provisioning as well. But couldn't reproduce it.

**Comment by DMHP** [comment] 2023-08-03 04:37
Closing the issue as it can not be reproduced. @melanisilva Please re-open if you have any concerns.

**Closed by DMHP** 2023-08-03 04:37 UTC
Labels: Priority/High, Resolution/Cannot Reproduce, Severity/Major, bug, 6.2.0-stabilisation
