### ISSUE TITLE
User email ID can be updated to have special characters

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10110] opened 2020-10-27 11:41 UTC
**Describe the issue:**
The user's email address can be updated to have special characters (such as *) in the email ID using My Account and Console. This prevents the user from logging in when email address as the username is enabled.

**How to reproduce:**

1. Enable email address as the username according to the documentation[1]
2. Create a new user from the console app
3. Login to My Account using that user
4. Go to My Account > Personal Info
5. Edit the email address with special characters in the email ID and save (eg: jo*hn@wso2.com)
6. If successful, logout and try to login to My Account again

[1] - https://is.docs.wso2.com/en/5.11.0/learn/using-email-address-as-the-username/

**Observation:**
1. The email address gets updated with special characters. Can't login using the updated email address used as the username.
2. Sometimes an error message is displayed preventing the email address from getting updated.

**Environment information:**
 - Product Version: IS 5.11.0-Beta3
 - OS: Mac
 - Database: MySQL
 - Userstore: LDAP

**Comment by piraveena** [comment] 2020-11-02 11:44
Added a comment in this git issue https://github.com/wso2/product-is/issues/10148#issuecomment-720399969

It is not possible to edit the emailaddress when email is used as username.

```
Caused by: javax.naming.directory.SchemaViolationException: [LDAP: error code 67 - NOT_ALLOWED_ON_RDN: failed for MessageType : MODIFY_REQUEST
Message ID : 4
    Modify Request
        Object : 'mail=piraveena@wso2.com,ou=Users,dc=wso2,dc=org'
            Modification[0]
                Operation :  replace
                Modification
mail: **piraveena@wso2.com            Modification[1]
                Operation :  replace
                Modification
lastModifiedDate: 2020-11-02T08:45:10.721Zorg.apache.directory.api.ldap.model.message.ModifyRequestImpl@3e377377    ManageDsaITImpl Control
        Type OID    : '2.16.840.1.113730.3.4.2'
        Criticality : 'false'
'
: ERR_62 Entry mail=piraveena@wso2.com,ou=Users,dc=wso2,dc=org does not have the mail attributeType, which is part of the RDN";]; remaining name 'mail=piraveena@wso2.com'
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3185)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
	at com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1408)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:257)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:167)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:156)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager.doSetUserAttributesWithID(UniqueIDReadWriteLDAPUserStoreManager.java:1063)
	... 65 more
```
This can be due some configuration issues with the email as username.  Hence closing this issue since we couldn't reproduce this issue locally

**Closed by piraveena** 2020-11-02 11:44 UTC
Labels: Priority/High, Severity/Major, bug
