### ISSUE TITLE
Startup errors with workflow profile

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#3238] opened 2018-05-28 17:40 UTC
Following error is observed and the server is not getting started.

```
[2018-05-28 23:06:02,060] ERROR {org.apache.tomcat.util.digester.Digester} -  Begin event threw exception
java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.core.runtime.internal.adaptor.ContextFinder.loadClass(ContextFinder.java:131)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1303)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1595)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:88)
	at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:122)
	at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2018-05-28 23:06:02,062] ERROR {org.wso2.carbon.tomcat.internal.CarbonTomcat} -  error while parsing xml stream
java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2726)
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2758)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1306)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1595)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:88)
	at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:122)
	at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2018-05-28 23:06:02,985]  WARN {org.wso2.carbon.registry.core.config.RegistryConfigurationProcessor} -  Could not find the handler class org.wso2.carbon.identity.entitlement.policy.finder.registry.RegistryPolicyHandler. This handler will not be registered. All handler and filter classes should be in the class path of the Registry.
```

**Comment by hauntingEcho** [comment] 2018-09-18 15:57
This stack trace looks very similar to the first few errors from #3287 - I've had luck just rebuilding (`mvn clean package -DskipTests`), and kinda suspect nondeterminism in the build somewhere - does this work for you?

**Comment by hauntingEcho** [comment] 2018-09-18 19:59
after a bit more inspection - the zipped artifact created by `mvn deploy` has this issue, the artifact created by `mvn package` does not.

**Comment by hauntingEcho** [comment] 2018-09-18 20:04
I've included the full stdout/stderr [here](https://gist.github.com/hauntingEcho/1430620fd2107f4c7c86e09748dc124d)

**Comment by trihoangvo** [comment] 2018-10-22 13:44
Same error:
1. Clone https://github.com/wso2/wso2-wss4j/tree/v1.5.11-wso2v17
2. Without modifying anything, run "mvn clean package -DskipTests" (in wso2-wss4j)
3. Copy target/wss4j_1.5.11.wso2v17.jar to "repository/components/plugins/"
4. Restart wso2 --> ERROR
How come? workaround?

**Comment by DMHP** [comment] 2019-03-25 09:50
Cannot reproduce with the current master. Hence closing. Please re-open with the logs if you still get the same error.

@trihoangvo 
I have tried the same using following steps.

1. Build https://github.com/wso2/wso2-wss4j/tree/v1.5.11-wso2v17
2. Copy the built jar from [1] to patches directory.

[1] https://github.com/wso2/wso2-wss4j/tree/v1.5.11-wso2v17/modules/orbit

This worked without any error

**Closed by DMHP** 2019-03-25 09:50 UTC
Labels: Type/Bug

**Comment by mmnur** [comment] 2020-06-28 23:45
I am seeing the same issue in the 6.4.37 build and 6.4.2 builds.

1. Install WSO2 Identity Server 5.10.0
*****
2. Download the following:
    git clone https://github.com/wso2-extensions/identity-inbound-auth-oauth
3a. Disable checkstyle plugin in
    \identity-inbound-auth-oauth\.pom.xml
3b. Build the jars:
    mvn package -DskipTests
4. Replace \WSO2\Identity Server\5.10.0\repository\components\plugins\org.wso2.carbon.identity.oauth_6.4.2.jar with the newly builtorg.wso2.carbon.identity.oauth-6.4.37-SNAPSHOT.jar
5. Got to C:\Program Files\WSO2\Identity Server\5.10.0\bin run
    wso2server.bat run
6. I see the ClassNotFoundException for org.wso2.carbon.identity.auth.valve.AuthenticationValve.
*****
7. Check out the same version that get installed with 5.10.0.
    git checkout tags/v6.4.2
8a. Disable checkstyle plugin in
    \identity-inbound-auth-oauth\.pom.xml
8b. Build the jars:
    mvn package -DskipTests
9. Replace \WSO2\Identity Server\5.10.0\repository\components\plugins\org.wso2.carbon.identity.oauth_6.4.2.jar with the newly builtorg.wso2.carbon.identity.oauth-6.4.37-SNAPSHOT.jar (for 6.4.37) or org.wso2.carbon.identity.oauth-6.4.2.jar (6.4.2)
10. Got to C:\Program Files\WSO2\Identity Server\5.10.0\bin run
    wso2server.bat run
11. I see the ClassNotFoundException for org.wso2.carbon.identity.auth.valve.AuthenticationValve.

 

[2020-06-28 15:29:23,895] [] ERROR {org.apache.tomcat.util.digester.Digester} - Begin event threw exception java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:104)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1210)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1485)
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:90)
        at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:156)
        at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:40)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2020-06-28 15:29:23,938] [] ERROR {org.wso2.carbon.tomcat.internal.CarbonTomcat} - error while parsing xml stream org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 93; Error at line [38] column [93]: [org.wso2.carbon.identity.auth.valve.AuthenticationValve]
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1892)
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1924)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1213)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1485)
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:90)
        at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:156)
        at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:40)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:104)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1210)
        ... 32 more

**Comment by cr1st1** [comment] 2021-04-05 10:12
Hello,
I am experiencing the same issue while trying to replace org.wso2.carbon.identity.application.authentication.framework_5.14.97.jar
Is there a workaround for this or at least the source of the issue determined?
[2021-04-05 12:43:23,719] [] ERROR {org.apache.tomcat.util.digester.Digester} - Begin event threw exception java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:104)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1173)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1448)
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:90)
        at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:156)
        at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:40)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2021-04-05 12:43:23,728] [] ERROR {org.wso2.carbon.tomcat.internal.CarbonTomcat} - error while parsing xml stream org.xml.sax.SAXParseException; lineNumber: 40; columnNumber: 93; Error at line [40] column [93]: [org.wso2.carbon.identity.auth.valve.AuthenticationValve]
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1855)
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1887)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1176)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1448)
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:90)
        at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:156)
        at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:40)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:104)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1173)
        ... 32 more

**Comment by pdkgamage** [comment] 2022-06-08 06:36
Hi Team,

I am facing this same issue. i just removed few jars which removed from wum update and applied wum diff. These are the jar files removed. Also, if i restore these jars again server start without any issue. 

Remove "jackson-databind-2.9.9.jar" file from <APIM_HOME>/lib/runtimes/cxf3 directory	
   Remove "net.minidev.json-smart_1.3.0.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.api_1.6.1.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.api_1.7.13.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.api_1.7.21.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.log4j12_1.6.1.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.log4j12_1.7.13.jar" from <APIM_HOME>/repository/components/plugins
   Remove "slf4j.log4j12_1.7.21.jar" from <APIM_HOME>/repository/components/plugins
   Remove "commons-codec-1.4.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib 
   Remove "log4j-1.2.17.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib
   Remove "slf4j-api-1.7.25.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib
   Remove "slf4j-log4j12-1.7.25.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib

Any reason?
