### ISSUE TITLE
Sending access_token through /oauth2/userinfo API Body in WSO2 5.7.0

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4403] opened 2019-02-04 05:16 UTC
In IS-5.3.0 we can send "access_token" through API Body for "/oauth2/userinfo" API. But in IS-5.7.0 if we enabled the correlation value as follows then sending access_token through API body will fail.

```
<Valve className="org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve" 
                       headerToCorrelationIdMapping="{'activityid':'Correlation-ID'}" queryToCorrelationIdMapping="{'RelayState':'Correlation-ID'}"/>
```

The reason for this behavior is through correlation valve we are reading the request body\[1] hence when we trying to read the request body again\[2] it is failing because we can only read the request body once.

*Steps to reproduce*
1. Add the following property in catalina-server.xml file.

2. Retrieve access token and invoke user info by sending the access token through request body.

3. You won't get any responses.

4. comment the line "Enumeration<String> parameterNames = httpServletRequest.getParameterNames();" in \[1] and rebuild the jar and tried the same flow.

5. You will get the user info

Hence we could decide that we need to modify the code \[1] in a way that to only read the query parameters and not to read the request body. For example use *request .getQueryParams*. We need to properly test this as well.

\[1] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.tomcat.ext/src/main/java/org/wso2/carbon/tomcat/ext/valves/RequestCorrelationIdValve.java#L224
\[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/user/impl/UserInforRequestDefaultValidator.java#L57-L64

**Comment by malithie** [comment] 2019-03-04 18:49
@DMHP , could you please have a check if this is fixed in kernel already

**Comment by emswbandara** [comment] 2020-11-20 10:04
Can be reproduced in 5.11.0 RC1

@Yasasr1 can you please add your findings here.

**Comment by Yasasr1** [comment] 2020-11-20 11:45
Issued fix no longer works because [1] returns null. In addition to RequestCorrelationIdValve class, some other method is also reading request body before it comes to [2]


[1] - [https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/4df95b068c9cbd97c96baf3f83a06fed0f7bac6e/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/user/impl/UserInforRequestDefaultValidator.java#L48](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/4df95b068c9cbd97c96baf3f83a06fed0f7bac6e/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/user/impl/UserInforRequestDefaultValidator.java#L48)

[2]- [https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/4df95b068c9cbd97c96baf3f83a06fed0f7bac6e/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/user/OpenIDConnectUserEndpoint.java](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/4df95b068c9cbd97c96baf3f83a06fed0f7bac6e/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/user/OpenIDConnectUserEndpoint.java)

**Comment by emswbandara** [comment] 2021-02-01 10:04
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1535

**Closed by emswbandara** 2021-02-01 10:04 UTC
Labels: Affected/5.7.0, Complexity/Medium, Component/Kernel, Priority/Highest, Severity/Critical, WUM, bug
