### ISSUE TITLE
Unable to re-assign admin access to users, which revoked previously

### ISSUE THREAD

**Issue by SulakshanaBandara** [wso2/product-is#16805] opened 2023-09-27 06:22 UTC
**Describe the issue:**
In groups and roles management after removing admin access from a user which had admin access, cant assign admin access for that person again but it gives a pop up as successfully updated, but it won't update.

**How to reproduce:**
1. Created a new user with the admin access.
2. Removed the admin access from that user. 
3. Again tried to give the admin access.

[admin access issue.webm](https://github.com/wso2/product-is/assets/129736390/d4325e47-6e24-4d12-9433-7d83f7270182)

**Expected behavior:**
Update the user with admin access.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0]
 - OS: [Linux,]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment] 2023-10-19 06:30
This issue extends beyond admin role. When creating a role, let's say 'R', and assigning it to a group named 'A', attempting to assign 'R' directly to a user who is already part of group 'A' will encounter this issue. This is the reason we can't re-assign the admin role to a user who already resides in the admin group. This behavior might be rooted in the backend's verification process, which checks if the user is assigned to that role through groups. To address this, we should discuss whether the roles list for a user should display both directly assigned roles and group-assigned roles, or if we should consider fixing the backend to allow the addition of roles directly, even if they are group-assigned roles.

**Comment by madurangasiriwardena** [comment] 2023-10-27 06:06
@SulakshanaBandara in the new console UI, only the new application roles are available now. So there is no way to reproduce this issue now with the console.

However, if I try the same flow with management console, it could not be reproduced.

**Closed by madurangasiriwardena** 2023-10-27 06:06 UTC
Labels: Priority/High, Severity/Major, bug, backend
