### ISSUE TITLE
Issue in JWKS endpoint behavior

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#10493] opened 2020-11-12 10:16 UTC
**Describe the issue:**
I am trying to use the new version 5.11 and I found a problem; the scenario is a service provider Saas which is linked to an application that contacts wso2 via a gateway. 
When I define the jwk in the gateway if I define it as "http://identity-server:9763/oauth2/jwks" wso2 allows me to login as super admin but not as tenant admin,
if instead I define it as "http://identity-server:9763/t/ngdms.com/oauth2/jwks" does not allow me to log in with user nor super admin as tenant admin 
I did a further test, if the service provider is defined directly in the tenant and the jwks is "http://identity-server:9763/t/ngdms.com/oauth2/jwks" then it works. 
Is it a bug, or am I making a mistake? 

in wso2 5.10 it work with "http://identity-server:9763/oauth2/jwks"

**Environment information**
 - Product Version: IS 5.11.0

**Comment by giannaccio** [comment] 2020-11-12 10:36
I have similar problem, and I opened this bug
https://github.com/wso2/product-is/issues/10440

**Comment by giannaccio** [comment] 2020-11-15 16:20
I found a strange configuration for wso2is-5.11

 jwk-set-uri: ${provider.host}/oauth2/jwks

and user-info-uri tenant based

user-info-uri: ${provider.host}/t/test.com/oauth2/userinfo

but it's strange and different from wso2is-5.10

**Comment by IsuraD** [comment] 2020-12-15 18:03
Identity Server is using the Application tenant's private key to sign the ID token by default. Since this is a SAAS application, you can use the user's tenant private key to sign the ID token. You can change this config from deployment.toml as follows.  The issues will be fixed by adding this config. Please let us know if you need further assistance. 

```
[oauth.oidc.id_token]
sign_with_sp_key=false
```

**Closed by IsuraD** 2020-12-15 18:03 UTC
Labels: Priority/High, bug

**Comment by Seregni** [comment] 2021-02-09 14:23
We tried this solution but the problem is the same; tenant admin cannot login

**Comment by giovanni-depalma** [comment] 2021-02-09 15:06
this is the demo project to explain the issue:

https://github.com/giovanni-depalma/spring-gateway-wso2
