### ISSUE TITLE
Inconsistence behaviour with JIT Provisioning 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19265] opened 2024-01-29 12:10 UTC
**Describe the issue:**

During JIT (Just-In-Time) provisioning, if a user attempts to register with a username that already exists without domain (ex: if the email is "abc@gmail.com", user exist as "abc"), an authentication error occurs,Authentication error! Provide user name is already exists. 

<img width="1019" alt="Screenshot 2024-01-29 at 16 34 30" src="https://github.com/wso2/product-is/assets/39077751/9488dbe4-a417-4c60-bf6c-9254cf7876b9">

However, if no user with the specified username (with or without the domain) is found, the user is successfully onboarded with the specified domain. (ex: user onboard as "abc@gmail.com")
 
There is a inconstancy with the behaviour.  

**How to reproduce:**
1. Login to console
2. Create application
3. Create google IDP
4. Enable JIT provisioning on created IDP
5. Configure created application with the google IDP as first factor. 
6. Create user with  the email username and without domain (ex: if your email user name is abc@gmail.com create user with username abc)
7. Authenticate to the application. 
8. Check the behaviour. 
9. Login to console again and delete created user "abc"
10. Authenticate to the application with abc@gmail.com
11. Validate the provisioned user  username. 

**Expected behavior:**
there is a inconstancy of the behaviour in step  8 provisioning should be completed since the existing user,"abc" is different from  "abc@gmail.com"

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment] 2024-01-29 12:11
Related issue fix: https://github.com/wso2/product-is/issues/18234

**Comment by Thumimku** [comment] 2024-01-30 04:01
Adding error log
```
[2024-01-30 09:30:00,833] [0852d6cf-407a-453b-8223-a23349491066] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.JITProvisioningPostAuthenticationHandler} - 80018 - Provided username is already exists.

```

**Comment by madurangasiriwardena** [comment] 2024-02-09 06:25
Duplicate of https://github.com/wso2/product-is/issues/19294

**Closed by madurangasiriwardena** 2024-02-09 06:25 UTC
Labels: Priority/Highest, Severity/Critical, bug, QA-Reported, Affected/7.0.0-beta6
