### ISSUE TITLE
Unable to scan the QR code from the authenticator app to setup TOTP, when TOTP is engaged to an app from the sub org level

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18349] opened 2023-12-03 03:30 UTC
**Describe the issue:**
$subject

**How to reproduce:**
1. Configure a B2B app sharing that app with sub orgs
2. Add a organization and switch to that org
3. For the app add TOTP as the second step
4. Login to the app from a user managed at the organization level
5. Note the TOTP QR code pop up, but that it not possible to be scanned from the authenticator app

**Expected behavior:**
The QR code should be scannable and should be able to enroll TOTP 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 RC SNAPSHOT build on 02/12/2023

**Comment by dewniMW** [comment] 2023-12-03 10:49
Duplicate of https://github.com/wso2/product-is/issues/18120
Confirmed that it is working fine in a pack built on 03/12/2023. Hence closing the issue.

**Closed by dewniMW** 2023-12-03 10:49 UTC
Labels: Severity/Blocker, bug
