### ISSUE TITLE
Consent Management layout is not aligned properly for non-admin users

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2495] opened 2018-02-19 14:02 UTC
Consent Management layout is not aligned properly for non-admin users.

![7](https://user-images.githubusercontent.com/1845370/36381438-9291f7ca-15ab-11e8-9f05-b01a479e6d70.png)

**Comment by thusithak** [comment] 2018-02-20 04:29
duplicate of #2450 
@omindu please close this.

**Closed** 2018-02-20 04:31 UTC
Labels: Affected/5.5.0-Alpha, Priority/Low, Resolution/Duplicate, Severity/Minor, Type/Bug
