### ISSUE TITLE
SCIM is not provisioning users to secondary users store

### ISSUE THREAD

**Issue by shazni** [wso2/product-is#6641] opened 2019-10-14 06:04 UTC
Affected version - 5.8.0 and 5.9.0

- Configure a secondary user store in the IS. For example, MySQL based secondary user store
- Configure resident service provider's inbound provisioning as in below to the secondary user store 
https://docs.wso2.com/display/IS580/Setting+Up+Service+Provider+for+Inbound+Provisioning
- Send a request to add a user without the domain name prefix as in below.

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

- It adds the user to the primary user store instead of the secondary user store. 
- 
- Expected behavior - Add the user to the configured user store

This same behavior could be observed when the inbound provisioning of the SP is configured to the secondary user store as well. In this case, the SCIM request with a token is used. The user is still added to the primary user store instead of the configured user store.

**Comment by sarubi** [comment] 2020-01-23 07:18
Hi @shazni ,

As I observed your curl request, seems like you haven't provided the username with your corresponding domain name. 

"userName":"kim"  should change to "userName":"your-secondary-domain-name/kim"
you can refer the step 4 from "Configuring the Identity Server for provisioning" section from the doc you pointed out, 
https://docs.wso2.com/display/IS580/Setting+Up+Service+Provider+for+Inbound+Provisioning

**Comment by madurangasiriwardena** [comment] 2020-01-23 09:46
@shazni, with the request you have made, this seems to be the expected behavior. Hence we are closing the issue. If you need further clarification, please feel free to reopen the issue.

**Comment by johannnallathamby** [comment] 2020-03-09 06:13
@sarubi @madurangasiriwardena I think @shazni has clearly mentioned that he has configured the secondary user store domain as the inbound provisioning user store in the resident SP configuration. In step 4 of the document @sarubi has pointed also it says if the user store has been configured in resident SP then regardless of what domain you send in the request (or even if you don't send a domain) it should provision to the configured user store.

Also note that @shazni has tried the same with a external service provider configured with OAuth2 token and observed same result.

**Closed** 2020-08-25 04:50 UTC
