### ISSUE TITLE
No confirmation pop-up when deleting SAML2 or OAuth2 configuration from the service provider UI

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4797] opened 2019-03-24 12:22 UTC
There are no confirmation pop-ups for delete buttons under SAML2 or OAuth2 configurations in SP UI.

Similar validation required for Revoke & Regenerate options under OAuth2 configuration.

**Comment by ashensw** [comment] 2019-04-11 09:28
Reducing the severity as this is a request for improvement.

**Comment by madurangasiriwardena** [comment] 2020-03-03 06:58
Duplicate of https://github.com/wso2/product-is/issues/1975

**Closed by madurangasiriwardena** 2020-03-03 06:58 UTC
Labels: Affected/5.8.0-Alpha2, Complexity/Medium, Component/Auth Framework, Priority/High, Severity/Major, Type/Improvement
