### ISSUE TITLE
No prompt shown to enter Email OTP

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#13779] opened 2022-05-31 05:23 UTC
**Describe the issue:**
When an SP is configured with Email OTP, at the login after submitting the username and password instead of presenting the screen to enter the OTP, the browser is redirected to `<IS_SERVER>:<PORT>/carbon/admin/login.jsp`. After logging in with credentials again, `Error 405 - Method Not Allowed` is shown.

<img width="704" alt="Screenshot 2022-05-31 at 10 45 19" src="https://user-images.githubusercontent.com/28347418/171097880-0a7feb16-6991-40f6-96ae-e878ac69c0cb.png">

**How to reproduce:**
1. Enable email sending module and configure the Email OTP identity provider.
2. Deploy saml2-web-app-pickup-dispatch sample webapp and configure it as a service provider.
3. Configure Local & Outbound Authentication Configuration --> Advanced Configuration of the SP as follows.
<img width="1242" alt="Screenshot 2022-05-31 at 10 37 36" src="https://user-images.githubusercontent.com/28347418/171097317-c4913f50-4e02-4f48-91bd-8b476365c5d4.png">

4. Create user and edit profile to include the email address.

5. Login to saml2-web-app-pickup-dispatch.

**Expected behavior:**
After submitting the username and the password, the screen to enter the OTP should be loaded.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: Oracle 12c
 - Userstore: JDBC

**Comment by asha15** [comment] 2022-06-07 06:06
Thank you for reporting this issue. 

Tested this on `IS 6.0.0-m1` pack. Here the issue is EmailOTP authentication Endpoint URL is incorrect. The URL should be `https://localhost:9443/authenticationendpoint/email_otp.do`. 

I sent a PR to update the sample configuration in the documentation: https://github.com/wso2/docs-is/pull/3019

**Comment by rksk** [comment] 2022-08-08 08:35
The PR was sent to the incorrect branch. In 5.11.0, the email otp endpoint is a separate webapp. This change should be pushed to master only.

**Comment by piraveena** [comment] 2022-08-12 06:38
@asha15 send the doc PR to 6.0.0

**Comment by piraveena** [comment] 2022-08-12 06:41
@asha15 Please close this issue once you send the doc PR for 6.0.0 and revert from 5.11.0

**Comment by asha15** [comment] 2022-08-12 09:13
@rksk Thank you for pointing out.  I reverted the changes [1] and 6.0.0 doc was updated with the correct email endpoint[2].

[1] https://github.com/wso2/docs-is/pull/3246
[2] https://github.com/wso2/docs-is/blob/master/en/docs/guides/mfa/2fa-email-otp.md

**Closed by asha15** 2022-08-12 09:13 UTC
Labels: Priority/Highest, Severity/Critical, bug, Component/Email OTP, Affected-6.0.0, IS-6.0.0-Test-Hackathon
