### ISSUE TITLE
Application Branding is enable 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21512] opened 2024-10-28 06:10 UTC
**Describe the issue:**
Application branding feature  should be disable from IS, but its enable with browser, Firefox 123.0. This is not reproducible with the Chrome. 

![image](https://github.com/user-attachments/assets/006abcd3-4de1-4c2b-8d4f-b470842f992a)

**How to reproduce:**
1. Login to console
2. Create application (ex: SPA)
3. Navigate to Application edit -> General tab
4. Validate the application branding  configurations are there

**Expected behavior:**
Application branding configuration should be disable. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-M4
 - OS: Ubunti 22.04
 - Database: H2
 - Userstore: 
 - Browser : Firefox 123.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment] 2024-10-29 06:46
Please note that this is not reproducible in the following environment setup

Product Version: wso2is-7.1.0-M4
OS: MacOS Sonoma 14.6.1
Database: H2
Userstore: Primary
Browser: Firefox Product Version: wso2is-7.1.0-M4
OS: Ubuntu 22.04
Database: H2
Userstore: [
Browser: Firefox 131.0.3/Chrome 130.0.6723.70

**Comment by ThaminduR** [comment] 2024-12-16 06:34
Since this feature is now fully integrated into IS, the expected behavior is for application branding to be enabled. Therefore, closing the issue.

<img width="863" alt="Image" src="https://github.com/user-attachments/assets/19da1159-a0de-4295-aae4-fbd05b7e42e3" />

**Closed by ThaminduR** 2024-12-16 06:34 UTC
Labels: Priority/High, Severity/Critical, Type/Bug, QA-Reported, Team/Authentication & registration, Team/Identity Server Core, Affected/7.1.0-m4, Browser/Firefox
