### ISSUE TITLE
Edits to the Cookie Policy 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#5758] opened 2019-06-13 09:54 UTC
The cookie policy of WSO2 Identity Server 5.7.0 is mentioning the 5.5.0 version. Please fix in 5.7.0 and other applicable versions.

**Comment by hauntingEcho** [comment] 2019-06-13 14:41
possibly a duplicate of https://github.com/wso2/carbon-identity-framework/issues/1842

**Comment by darshanasbg** [comment] 2019-07-04 04:05
@dewniMW Lets fix this for master. Additionally, we have to come up with a way to avoid updating version in each product release as it doesn't scale.

**Comment by madurangasiriwardena** [comment] 2019-07-05 03:48
@YvonneW, thanks for reporting the issue and @hauntingEcho thanks for pointing out that this is a duplicate.
We are closing this since this is a duplicate of https://github.com/wso2/carbon-identity-framework/issues/1842.

**Comment by madurangasiriwardena** [comment] 2019-07-05 03:52
@YvonneW thanks for reporting the issue.
@hauntingEcho Thanks for pointing out that the issue is duplicate.

We are closing this issue since this is a duplicate of https://github.com/wso2/product-is/issues/3570

**Closed by madurangasiriwardena** 2019-07-05 03:52 UTC
Labels: Affected/5.7.0, Complexity/Low, Priority/High, Severity/Major, Type/Improvement
