### ISSUE TITLE
Cannot create new tenants with a DB2 database

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#13247] opened 2022-03-14 07:41 UTC
**Describe the issue:**
Getting the following error when trying to create new tenants in a DB2 environment.

```
[2022-03-14 12:59:00,239] [46e682e5-3e8b-4098-b042-471516f7900b] ERROR {org.wso2.carbon.tenant.mgt.core.TenantPersistor} - Error in adding tenant with domain: abc.com org.wso2.carbon.user.core.UserStoreException: Error in adding tenant with tenant domain: abc.com.
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.addTenant(JDBCTenantManager.java:174)
	at org.wso2.carbon.tenant.mgt.core.TenantPersistor.addTenant(TenantPersistor.java:202)
	at org.wso2.carbon.tenant.mgt.core.TenantPersistor.persistTenantInUserStore(TenantPersistor.java:111)
	at org.wso2.carbon.tenant.mgt.core.TenantPersistor.persistTenant(TenantPersistor.java:76)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtAdminService.addTenant(TenantMgtAdminService.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
Caused by: org.wso2.carbon.user.core.UserStoreException: Error while loading tenant from DB: Database driver could not be identified or not supported.
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.checkUniqueIdColumnInTable(JDBCTenantManager.java:1279)
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.isTenantUniqueIdColumnAvailable(JDBCTenantManager.java:1252)
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.addTenant(JDBCTenantManager.java:126)
	... 85 more
```

**Environment information** **:**
 - Product Version: IS 5.12.0 alpha 15, IS 5.11.0
 - Database: DB2
- Userstore: JDBC

**Comment by nilasini** [comment] 2022-03-28 06:22
Checked with alpha-16 pack with db2 environment. The issue is not reproducible hence closing the issue. 

@ashendes according to the error log 
`Caused by: org.wso2.carbon.user.core.UserStoreException: Error while loading tenant from DB: Database driver could not be identified or not supported.`
There is an issue with JDBC driver, please verify the driver name and connector is added properly.

**Closed by nilasini** 2022-03-28 06:22 UTC
Labels: Severity/Blocker, bug, 5.12.0-bug-fixing
