### ISSUE TITLE
Access Token not delivered as JWT when reusing it.

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#6819] opened 2019-11-07 15:31 UTC
Steps to reproduce -
1. Call authorization endpoint and obtain an access token (JWT) via implicit flow.
2. Call authorization endpoint again (after cache expires) a GUID is returned.

A JWT is not generated when fetching the access token from the database and the access token identifier from the database is returned instead. 

Suggested labels: wso2is-km-5.5.0
Type: Bug

**Comment by mefarazath** [comment] 2019-11-07 17:58
I suspect this could be due to the custom token issuer written in the IS as a KM pack.
Can you check whether this is reproducible with an IS 5.5.0 pack?

**Comment by mefarazath** [comment] 2019-11-07 17:59
or you can switch to IS default JWT token issuer using the steps https://docs.wso2.com/display/IS550/Self-contained+Access+Tokens

**Comment by mefarazath** [comment] 2019-11-07 18:00
Could be related to https://github.com/wso2/product-apim/issues/6654

**Comment by Manukam** [comment] 2019-11-13 05:58
Hi @mefarazath,
As I noticed, the issue was only reproducible in IS-KM

**Comment by pamodaaw** [comment] 2020-01-23 03:40
This issue is fixed in 5.5.0 with the PR https://github.com/wso2-support/identity-inbound-auth-oauth/pull/547. 
This is already fixed in the master with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/868 and https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/865

**Closed by pamodaaw** 2020-01-23 03:40 UTC
Labels: Type/Bug
