### ISSUE TITLE
Errors when trying to add the STS connector to IS

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#14858] opened 2022-09-07 10:44 UTC
**Describe the issue:**
The following errors are thrown when trying to run the IS after adding the STS connector.
```
 Unresolved requirement: Import-Package: org.apache.ws.security.components.crypto; version="[1.5.11,2.0.0)"
    -> Export-Package: org.apache.ws.security.components.crypto; bundle-symbolic-name="wss4j"; bundle-version="1.5.11.wso2v21"; version="1.5.11.wso2v21"; uses:="org.apache.ws.security.util,javax.security.auth.x500,org.apache.xml.security.utils,org.apache.ws.security,org.apache.commons.logging"
       wss4j [560]
         Unresolved requirement: Import-Package: javax.xml.rpc; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.rpc.handler; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.rpc.handler.soap; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.soap; version="[1.0.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.axis; version="[1.4.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.axis.components.logger; version="[1.4.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.axis.message; version="[1.4.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.axis.utils; version="[1.4.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.security; version="[1.4.2,2.0.0)"
```

**How to reproduce:**
1. Download the [STS connector](https://store.wso2.com/store/assets/isconnector/details/417e7ef2-76fb-424f-92b3-d5eb58e2efe6)
2. Add and extract the connector at the <IS_HOME>
3. Run the following commands at the home of the connector.
  chmod u+r+x setup_sts.sh
  ./setup_sts.sh 
4. Delete the added connector directory.
5. Run the IS

**Expected behavior:**
Identity Server should start without running into errors. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 and IS 6.0.0

---

**Comment by asha15** [comment] 2022-11-15 08:13
Duplicate of https://github.com/wso2/product-is/issues/14847

**Closed by asha15** 2022-11-15 08:13 UTC
Labels: bug, Component/Connectors
