### ISSUE TITLE
Need to define permissions for OAuth2 Scope Endpoint

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7771] opened 2020-02-26 10:37 UTC
**Description:**
Current OAuth2 Scope Endpoint has no permission specified. [identity.xml](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L1190)
User with internal/everyone role can use REST API Delete method to delete scopes.

**Related Issues:**
https://github.com/wso2/product-is/issues/5762

**Comment by janakamarasena** [comment] 2020-02-26 10:44
closing as duplicate of #5762

**Closed by janakamarasena** 2020-02-26 10:44 UTC
