### ISSUE TITLE
user-portal is returning 404 status code for /login endpoint

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10801] opened 2020-12-17 12:49 UTC
**Describe the issue:**
`/user-portal/login` is returning a 404 status code even though the flow is working fine. This is causing issues when the proxy/LB is trying to override the error page when it receives the 404 status code.

**How to reproduce:**
Login and logout to/from user-portal
404 responses can be seen for the following two requests

- https://localhost:9443/user-portal/login?code=xxx&session_state=xxx
- https://localhost:9443/user-portal/login?sp=User+Portal&tenantDomain=carbon.super

**Expected behavior:**
This endpoint return 200 status code along with the HTML payload

**Environment information** 
 - Product Version: IS 5.10.0, IS 5.11.0

**Comment by ashensw** [comment] 2020-12-17 13:08
Need to fix 5.11.0 as well,
```
https://localhost:9443/myaccount/login
https://localhost:9443/console/login
```

**Comment by Thumimku** [comment] 2021-01-13 05:03
This issue is not reproducible in 5.12 - m5, Hence we close this issue.

**Comment by jcgarciaa** [comment] 2022-08-17 13:49
This has not been fixed on IS-5.11.0 yet :
```
https://localhost:9443/myaccount/login
https://localhost:9443/console/login
```

**Comment by Shaaali** [comment] 2022-08-24 17:11
This issue is not reproducible in IS 6.0.0

**Comment by isharak** [comment] 2024-11-06 05:51
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 05:51 UTC
Labels: Type/Bug, WUM, IceBox
