### ISSUE TITLE
No error message for unsupported prompt parameter value select_account in authorize request.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#13983] opened 2022-06-21 07:18 UTC
**Describe the issue:**
When an unsupported prompt value such as `select_account` is added to the authorize request, the WSO2 Identity Server does a redirection to `https://localhost:9443/oauth2/`(blank page) with 401 response.

**How to reproduce:**
- Start the Identity Server.
- Execute the following request (containing the `prompt=select_account` parameter) by changing the client ID and the callback URL (Look at the network trace). 
```
https://localhost:9443/oauth2/authorize?response_type=code%20id_token&client_id=7UdmqM8jKaXdsXay90N2QMhRJh4a&redirect_uri=https%3A%2F%2Flocalhost&scope=openid&nonce=xyz&prompt=select_account&state=abc&response_mode=form_post
```
- Login as admin.
- You will be redirected to `https://localhost:9443/oauth2/` (blank page) with 401 status.

**Expected behavior:**
Either the WSO2 Identity Server should support the select_account [1] (section 3.1.2.1.) parameter value or a descriptive error message should be shown.

[1] - https://openid.net/specs/openid-connect-core-1_0.html

**Environment information**
 - Product Version: IS 5.11.0
 - OS: Ubuntu 20.04
 - Database: H2
 - Userstore: LDAP

---

**Comment by janakamarasena** [comment] 2022-07-19 07:09
closing as duplicate of https://github.com/wso2/product-is/issues/6372

**Closed by janakamarasena** 2022-07-19 07:09 UTC
Labels: bug
