### ISSUE TITLE
Configurations in Working with ACR and AMR doc is not templated

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6854] opened 2019-11-13 08:52 UTC
Following configurations in the `identity.xml` file in the `<IS_HOME>/repository/conf/identity` directory is not available by default. Need to template them to add to the identity.xml via deployment.toml

		```
		<AuthenticationContext>
		        <MethodRefs>
		            <MethodRef uri="pwd" method="BasicAuthenticator"  />
		            <MethodRef uri="fpt" method="DemoFingerprintAuthenticator"  />
		            <MethodRef uri="user" method="DemoFaceIdAuthenticator"  />
		            <MethodRef uri="hwk" method="DemoHardwareKeyAuthenticator"  />
		            <MethodRef method="AuthenticatorToBeHiddenFromAMR" xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
		        </MethodRefs>
		</AuthenticationContext>
		```

Once this is fixed, need to update the docs-is page as in https://github.com/wso2/docs-is/issues/807

Confluence reference: https://docs.wso2.com/display/IS580/Working+with+ACR+and+AMR

**Comment by piraveena** [comment] 2022-03-11 12:25
duplicate of https://github.com/wso2/product-is/issues/13225

**Comment by isharak** [comment] 2024-11-06 00:08
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 00:08 UTC
Labels: config, Affected/5.9.0, IceBox
