### ISSUE TITLE
Missing j2 templates for "IsAnalytics-Publisher-wso2event-AuthenticationData.xml" and "IsAnalytics-Publisher-wso2event-SessionData.xml"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6456] opened 2019-09-18 08:31 UTC
Purpose: Configure Event Publishers

So here it required, Configure the login analytics and session analytics using the following files.

Login analytics: <IS_HOME>/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-AuthenticationData.xml
Session analytics: <IS_HOME>/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-SessionData.xml 

Those files don't have j2 templates.

Ref: https://is.docs.wso2.com/en/5.9.0/learn/prerequisites-to-publish-statistics/

**Comment by janakamarasena** [comment] 2019-09-19 15:10
Duplicate of https://github.com/wso2/product-is/issues/6443

**Closed by janakamarasena** 2019-09-19 15:10 UTC
Labels: Priority/High, config
