### ISSUE TITLE
Custom proxy context path is missing from some URLs in user_profile/gadget.xml

### ISSUE THREAD

**Issue by SaubhagyaW** [wso2/product-is#4410] opened 2019-02-05 10:03 UTC
When a custom proxy context path is added in the carbon.xml, below use case in IS Dashboard fails.
1. Select _View Details_ from _My Profile_.
2. Check _Enable TOTP_ option and _Update_.

This will display an "Error while updating Profile" error.

This is because some URLs configured in <IS_HOME>/repository/deployment/server/jaggeryapps/portal/gadgets/user_profile/gadget.xml are missing PROXY_CONTEXT_PATH prefix which will cause them to redirect to the default URL without the proxy context path. Since there's no session cookie previously created for that path, above error will occur.

**Comment by IsurangaPerera** [comment] 2019-03-05 06:39
**Fixed with wso2/product-is#4434**
When adding a custom proxy context path to the carbon.xml update following files as well.

- <IS_HOME>repository/deployment/server/jaggeryapps/portal/conf/site.json

- <IS_HOME>/repository/deployment/server/jaggeryapps/dashboard/conf/site.json

**Comment by malithie** [comment] 2019-03-11 08:39
Resolving as the issue is addressed

**Closed by malithie** 2019-03-11 08:39 UTC
Labels: Affected/5.7.0, Component/Dashboard, Priority/Normal, Severity/Major, Type/Bug
