### ISSUE TITLE
SCIM issue- PATCH/ Remove Group Member does not work as expected

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7040] opened 2019-12-09 14:15 UTC
Affected - wso2is 5.10 m9
Severity: Medium
Priority: Medium
**Description** 
Even response return 200, user still has the removed role.

curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"remove","path":"members[display eq kim,value eq 81ffe274-19a9-46aa-acfe-469a09cdd25a]"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/1b91c4ef-9834-4278-82e3-ed810a94403b

WARN log- 
WARN {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - There is no updated field in the group: PRIMARY/manager. Therefore ignoring the provisioning.

**Comment by mefarazath** [comment] 2019-12-18 07:46
@NilukaSripalim Was this request obtained from our docs?

**Comment by senthalan** [comment] 2019-12-20 11:23
@mefarazath 

Yes, I can find it here, 
https://is.docs.wso2.com/en/next/develop/using-the-scim-2.0-rest-apis/#patch-remove-group-member

**Comment by mefarazath** [comment] 2019-12-20 11:26
@senthalan Let's fix the docs then since we only support simple filters.

**Comment by aaujayasena** [comment] 2020-02-05 08:38
Reopening this issue because  issue is observe in  product version 5.10.-alpha 3. [1]

[1] https://github.com/wso2/product-is/releases/download/v5.10.0-alpha3/wso2is-5.10.0-alpha3.zip

**Comment by IsuraD** [comment] 2020-02-05 16:20
Tried with the 5.10.0-Aplha3. Could not reproduce the issue with uniqueIdJDBC and UniqueIDReadWriteLdap user stores. 

I am resolving the issue. Please reopen if you still face the issue. Please provide the steps to recreate the issue.

**Comment by aaujayasena** [comment] 2020-02-06 05:07
Issue reopen since it reproduce in product version [1]. SCIM2 document [2]

[1] https://github.com/wso2/product-is/releases/download/v5.10.0-alpha3/wso2is-5.10.0-alpha3.zip
[2] https://is.docs.wso2.com/en/next/develop/using-the-scim-2.0-rest-apis/#patch-remove-group-member

**Steps:**

**01. Create user:** 

request:

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

response: 

`{"emails":[{"type":"work","value":"kim_j@wso2.com"},{"type":"home","value":"kim.jackson@gmail.com"}],"meta":{"created":"2020-02-05T17:57:38.128Z","location":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b","lastModified":"2020-02-05T17:57:38.128Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"}],"name":{"givenName":"kim","familyName":"jackson"},"id":"59116eda-24fd-4305-af5a-e7835187a53b","userName":"kim"}
`

**02. Create group:** 

request:

`curl -v -k --user admin:admin --data '{"displayName":"manager"}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups`

response:

`{"displayName":"PRIMARY/manager","meta":{"created":"2020-02-05T17:58:37.832Z","location":"https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d","lastModified":"2020-02-05T17:58:37.832Z","resourceType":"Group"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:Group"],"id":"4c498c36-ebc6-4dcd-b3ac-4e338551396d"}`

**03. Add member to the group**
 
request:

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"members":[{"display": "kim","$ref":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b","value": "59116eda-24fd-4305-af5a-e7835187a53b"}]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d`

response:

`{"displayName":"manager","meta":{"created":"2020-02-05T17:58:37.832Z","location":"https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d","lastModified":"2020-02-05T17:58:37.832Z"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:Group"],"members":[{"display":"kim","value":"59116eda-24fd-4305-af5a-e7835187a53b","$ref":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b"}],"id":"4c498c36-ebc6-4dcd-b3ac-4e338551396d"}`

**04. Get user detail:** (to verify user is add to the group)

request: 

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b'`

response:

`{"emails":[{"type":"work","value":"kim_j@wso2.com"},{"type":"home","value":"kim.jackson@gmail.com"}],"meta":{"created":"2020-02-05T17:57:38.128Z","location":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b","lastModified":"2020-02-05T17:57:38.128Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"manager,Internal/everyone"}],"name":{"givenName":"kim","familyName":"jackson"},"groups":[{"display":"manager","value":"4c498c36-ebc6-4dcd-b3ac-4e338551396d","$ref":"https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d"}],"id":"59116eda-24fd-4305-af5a-e7835187a53b","userName":"kim"}`

**05. Remove user:** 

request:

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"remove","path":"members[display eq kim,value eq 59116eda-24fd-4305-af5a-e7835187a53b]"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d`

response:

`{"displayName":"PRIMARY/manager","meta":{"created":"2020-02-05T17:58:37.832Z","location":"https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d","lastModified":"2020-02-05T17:58:37.832Z"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:Group"],"members":[{"display":"kim","value":"59116eda-24fd-4305-af5a-e7835187a53b","$ref":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b"}],"id":"4c498c36-ebc6-4dcd-b3ac-4e338551396d"}`

**06. Get user detail:** (to verify user is remove from the group)

request: 

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b'`

response: 

`{"emails":[{"type":"work","value":"kim_j@wso2.com"},{"type":"home","value":"kim.jackson@gmail.com"}],"meta":{"created":"2020-02-05T17:57:38.128Z","location":"https://localhost:9443/scim2/Users/59116eda-24fd-4305-af5a-e7835187a53b","lastModified":"2020-02-05T17:57:38.128Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"manager,Internal/everyone"}],"name":{"givenName":"kim","familyName":"jackson"},"groups":[{"display":"manager","value":"4c498c36-ebc6-4dcd-b3ac-4e338551396d","$ref":"https://localhost:9443/scim2/Groups/4c498c36-ebc6-4dcd-b3ac-4e338551396d"}],"id":"59116eda-24fd-4305-af5a-e7835187a53b","userName":"kim"}`

User is still assign to the removed group. 

Check the console as well
![image](https://user-images.githubusercontent.com/39077751/73907427-3ea8ce80-48cc-11ea-9d22-283a3e5714e9.png)

**Comment by aaujayasena** [comment] 2020-02-06 06:08
Issue is fixed but need to update the document as well. Therefore close the issue and open a document issue [1] 

[1] https://github.com/wso2/docs-is/issues/1118

**Closed by aaujayasena** 2020-02-06 06:08 UTC
Labels: Affected/5.10.0-Alpha3, Component/SCIM, Priority/Highest, Severity/Critical, WUM

**Comment by abhishekkandi** [comment] 2021-07-05 15:17
@aaujayasena @IsuraD We're using v5.10.0, We're still facing the same issue. 

Can you confirm if this issue is fixed in any version of 5.10.0 or 5.11.0
