### ISSUE TITLE
SCIM2 Listing Users does not List the users created under a secondary user store JDBC Mysql 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5144] opened 2019-04-25 16:49 UTC
**Suggested Labels**
Affected/IS5.8.0-Beta4-snapshot
Severity: Major
Priority: High
Component: SCIM2
Type-Bug

**Environment**
Secondary userstore > JDBC Mysql 5.7

**Steps to Reproduce**
1. Configure a secondary user store with JDBC Mysql 5.7 as in [1]
2. Register it as a secondary user store in WSO2 IS
3. Enable SCIM for the created user store 
Enabling SCIM: expand Advanced section, tick against the “Enable SCIM” and press on “Update”
4. Add a user for the created secondary user store
5. List the user with below command

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?'`

Behaviour

Will not list the users created under secondary user store when jdbc mysql is used. It will list only the users created under the default primary user store.

[1]. https://medium.com/@madumalt/wso2-identity-server-setting-up-a-secondary-mysql-jdbc-user-store-in-windows-and-linux-50a66afe79d5

**Comment by IshikaGodage** [comment] 2019-04-30 08:09
Cannot reproduce using wso2is-5.8.0-beta5-SNAPSHOT.

**Comment by malithie** [comment] 2019-04-30 12:04
@ShanikaWickramasinghe , Can you check this with beta5 and confirm

**Comment by ShanikaWickramasinghe** [comment] 2019-05-01 08:43
@malithie @IshikaGodage 
Tested this against wso2is-5.8.0-beta5-SNAPSHOT and does not reproduce against wso2is-5.8.0-beta5-SNAPSHOT. As the issue is fixed in this version we can close the issue.

**Comment by malithie** [comment] 2019-05-01 16:42
Resolving as per comment above

**Closed by malithie** 2019-05-01 16:42 UTC
Labels: Affected/5.8.0-Beta3, Component/SCIM, Priority/Highest, Severity/Major, Type/Bug
