### ISSUE TITLE
Can't save an OAuth config without providing a value for "AllowedOrigins" in the console

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#9918] opened 2020-10-16 12:48 UTC
### Description
Can't save an OAuth config without providing a value for "AllowedOrigins"

### Reproduced On
5.11-beta

**Comment by pulasthi7** [comment] 2020-10-23 08:36
Closing as duplicate of #9933

**Comment by NipuniBhagya** [comment] 2020-11-09 14:50
Reopening issue to track the UI changes that need to be made along with the fix https://github.com/wso2/carbon-identity-framework/pull/3228

**Closed** 2020-11-11 23:11 UTC
Labels: Component/Identity Apps, Priority/High, UI Component/Application Management, console, ux
