### ISSUE TITLE
Console homepage has no icons or banners

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#17461] opened 2023-10-31 17:56 UTC
**Describe the issue:**
After login to the console, user redirects a page with almost white screen.
<img width="1436" alt="Screenshot 2023-10-31 at 11 22 21 PM" src="https://github.com/wso2/product-is/assets/51480027/6d16a1e2-75fc-4a1a-b481-7d9cf7341bfc">

**How to reproduce:**
Login to console with new user

**Comment by madurangasiriwardena** [comment] 2023-11-13 09:58
This user does not have any permission, right? If so the expectation is that the user should not be able to login to the console application.

**Comment by brionmario** [comment] 2023-11-15 08:18
> This user does not have any permission, right? If so the expectation is that the user should not be able to login to the console application.

Ideally this should happen at the login level without hitting the application. If not we need to show an unauthorized page. (Using RBAC)

**Comment by NipuniBhagya** [comment] 2023-11-15 08:22
Duplicate of https://github.com/wso2/product-is/issues/17644

**Closed by NipuniBhagya** 2023-11-15 08:22 UTC
Labels: bug, Affected/7.0.0-Alpha
