### ISSUE TITLE
Config missing in carbon.xml.j2 in IS 5.10.0

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#15764] opened 2023-04-21 18:39 UTC
**Describe the issue:**
In PR[1] we have backported the validateUsername to the IS 5.10.0 and in PR[2] we have backported adding util method to disable email username validation. But the below configuration is missing in the carbon.xml.j2 file, therefore we cannot disable email username validation in the IS. This config has not been added with the PRs. 

{% if tenant_mgt.disable_email_domain_validation is defined %}
<DisableEmailUserNameValidation>{{tenant_mgt.disable_email_domain_validation}}</DisableEmailUserNameValidation>
{% endif %}

[1] https://github.com/wso2-support/carbon-identity-framework/pull/2577
[2] https://github.com/wso2/carbon-identity-framework/pull/3582

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0

---

**Comment by rksk** [comment] 2023-04-25 05:49
duplicate of https://github.com/wso2/product-is/issues/15678

**Closed by rksk** 2023-04-25 05:49 UTC
Labels: bug
