### ISSUE TITLE
[Console Settings] - on clicking the administrator, the page crashes to Something went wrong error message

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18308] opened 2023-12-02 07:24 UTC
**Describe the issue:**

**How to reproduce:**
Pack produced: https://wso2.org/jenkins/job/products/job/product-is/4957/

1. Login to the console
2. Click on Console Settings
3. Click on the Administrator

**Actual behavior:**
The user is redirected to the page: 
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/20d9181a-f10e-4ca9-8aeb-73da81f19761">

Error in Stack trace: 
![Uploading image.png…]()

The stack trace produced show

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] - IS 7.0 RC1 SNAPSHOT
 - OS: [e.g., Windows, Linux, Mac] - MAC
 - Database: [e.g., MySQL, H2] - ANY 
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment] 2023-12-02 07:29
Duplicate of https://github.com/wso2/product-is/issues/18288

**Closed** 2023-12-02 07:30 UTC
Labels: Priority/Highest, Resolution/Duplicate, Severity/Blocker, bug, Affected/7.0.0-beta2
