### ISSUE TITLE
java.nio.channels.AsynchronousCloseException while stopping the identity server instance

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#16469] opened 2023-08-16 10:05 UTC
**Describe the issue:**
An error is being thrown while stopping the Identity server instance.
```
[2023-08-16 15:20:20,731] [] ERROR {org.apache.tomcat.util.net.Acceptor} - Socket accept failed java.nio.channels.AsynchronousCloseException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:269)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:288)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:548)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.base/java.lang.Thread.run(Thread.java:829)

``` 

**How to reproduce:**
1. Get a latest identity server pack
2. Start the server with the relevant script command
3. If the server started successfully, execute the command to stop it.
4. The above mentioned error will be visible in the terminal logs.

**Expected behavior:**
No errors should be visible in the terminal logs.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0-alpha4-SNAPSHOT
 - Java versions: jdk11 & jdk17

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dhaura** [comment] 2023-08-28 06:14
### Analysis

- Recreated the issue for the following setup. (Note: Once in a while, the issue is not reproducing.)

  - IS Version: `6.2.0 alpha 5 SNAPSHOT`
  - OS: `macos Ventura 13.5`
  - Database: `Default`

- Furthermore, the exception is thrown by the `shutdown` method of `EclipseStarter`[1] which is called by the `CarbonServerManager`[2].

[1] - https://help.eclipse.org/latest/nftopic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/runtime/adaptor/EclipseStarter.html
[2] - https://github.com/wso2/carbon-kernel/blob/2aa7489f5800f5a4a3f96f62e3c4250bce4075d1/core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/init/CarbonServerManager.java#L865

**Comment by chamathns** [comment] 2023-08-29 04:31
hi @dhaura 
thanks for the thorough analysis. Need to verify if this is an OS-specific issue or not. Can you add your findings with the linux testing you've done?
@melanisilva can you please help with testing this on a windows setup?

**Comment by dhaura** [comment] 2023-08-29 04:49
### Analysis Ctd
- The error is thrown from here [1] and logged from here [2].
- Error is `NOT` reproducible in IS `6.1.0`, `6.2.0-alpha3`. **(on mac)**
- Error reproducible in IS `6.2.0-alpha4`, `6.2.0-alpha5-SNAPSHOT`. **(on mac)**
- An `extra log` can be seen at the startup (compared to “issue not reproducible pack” startups):
```
[2023-08-28 17:11:54,567] []  INFO {org.apache.tomcat.util.net.NioEndpoint.certificate} - Connector [https-jsse-nio-9443], TLS virtual host [_default_], certificate type [UNDEFINED] configured from [/Users/dhaurapathirana/Documents/WSO2-IS/wso2is-6.2.0-alpha5-SNAPSHOT-Aug-28/repository/resources/security/wso2carbon.jks] using alias [wso2carbon] and with trust store [/Users/dhaurapathirana/Documents/WSO2-IS/wso2is-6.2.0-alpha5-SNAPSHOT-Aug-28/repository/resources/security/client-truststore.jks] 
```

### Probable Causes
- Inside the shutdown method [3], the error is thrown while calling `framework.waitForStop(0)`. Therefore, maybe `framework.getState()` is not updated in time.
- Might be a fault due to **OS**: https://stackoverflow.com/a/956954: `Tried several times on a linux machine and the issue is NOT reproducible`.

[1] - https://github.com/apache/tomcat/blob/79900c9eef9aac2e892af73f23d9b16337deac27/java/org/apache/tomcat/util/net/Acceptor.java#L129
[2] - https://github.com/apache/tomcat/blob/79900c9eef9aac2e892af73f23d9b16337deac27/java/org/apache/tomcat/util/net/Acceptor.java#L171 
[3] - https://help.eclipse.org/latest/nftopic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/runtime/adaptor/EclipseStarter.html

**Comment by melanisilva** [comment] 2023-08-29 04:54
> hi @dhaura thanks for the thorough analysis. Need to verify if this is an OS-specific issue or not. Can you add your findings with the linux testing you've done? @melanisilva can you please help with testing this on a windows setup?

Sure , Will check.

**Comment by dhaura** [comment] 2023-08-29 05:27
> An extra log can be seen at the startup (compared to “issue not reproducible pack” startups)

The `logCertificate` [1] method is hit by `Error Reproducible IS packs` but NOT by other Error Not Reproducible IS packs

[1] - https://github.com/apache/tomcat/blob/497f18240318e623ae608f8d4bdcbb366e2eab54/java/org/apache/tomcat/util/net/AbstractEndpoint.java#L375

**Comment by dhaura** [comment] 2023-08-29 06:43
### Analysis Ctd
- A Tomcat version bump [1] for was carried out from `v9.0.58.wso2v1` to `v9.0.74.wso2v1` in IS and with that, this error is introduced. 
- Root cause for this is that a socket where Tomcat Acceptor is waiting [2], is getting closed by some other process. Thus, the `AsynchronousCloseException` is thrown. 
- Furthermore, this error happens `intermittently`.

[1] - https://github.com/wso2/carbon-kernel/pull/3611
[2] - https://github.com/apache/tomcat/blob/79900c9eef9aac2e892af73f23d9b16337deac27/java/org/apache/tomcat/util/net/Acceptor.java#L129

**Comment by chamathns** [comment] 2023-08-29 11:12
I'm putting this issue on hold since this is not a blocking issue for the release. Reducing the priority as well.

**Comment by chamathns** [comment] 2023-11-22 08:46
This was not reproducible on Linux. Currently only reproducible on MacOS. Hence it is likely to be an OS issue.

**Comment by isharak** [comment] 2024-11-07 05:55
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 05:55 UTC
Labels: Resolution/Won’t Fix, Priority/Normal, Type/Bug, IceBox
