### ISSUE TITLE
Support more powerful hashing algorithms

### ISSUE THREAD

**Issue by mohamednizar** [wso2/product-is#7003] opened 2019-12-03 11:22 UTC
WSO2 IS currently supports MessageDigest only.Is it possible to support more encryption  like  Cipher Algorithms `bcrypt`.

**Comment by ayomawdb** [comment] 2020-03-11 17:29
Isn't this a duplicate of #3912?

**Comment by malithie** [comment] 2020-09-22 13:49
Resolving this issue as this is tracked with #3912

**Closed by malithie** 2020-09-22 13:49 UTC
Labels: improvement
