### ISSUE TITLE
Userstore Password Automatically Resets When Updating Other Properties.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17053] opened 2023-10-19 05:46 UTC
**Describe the issue:**
When updating another property of the user store, such as modifying Immutable Attributes in advanced properties, if the user store password is also updated simultaneously, it results in an error.

Note: This issue was identified intermittently.
<img width="1511" alt="Screenshot 2023-10-18 at 18 06 19" src="https://github.com/wso2/product-is/assets/41188245/3702696b-521e-41b4-b8b8-33cd6d8d551c">

<img width="1511" alt="Screenshot 2023-10-19 at 11 20 13" src="https://github.com/wso2/product-is/assets/41188245/96a880f2-1889-4e6f-88cf-f8d1f933e4d6">

**How to reproduce:**

1. Configure an Active Directory/ LDAP 
2. Set it up as a secondary userstore
3. From your Mangement console 
4. Redirect to Userstore -> Select the Userstore -> Edit -> Advanced 
5. Change `Immutable Attributes` property value
6. Update the changes.

**Expected behavior:**
The Password Should not be updated unless it is actually changed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ImalshaG** [comment] 2023-10-27 09:53
This is not reproducible in the latest pack. 

Tried configuring an AD and changing properties through management console and react console. But the password did not get reset and the above error was not reproduced. Therefore closing this issue since it might be fixed with the latest changes.

**Closed by ImalshaG** 2023-10-27 09:53 UTC
Labels: Priority/High, Severity/Critical, bug, backend

**Comment by aaujayasena** [comment] 2023-11-16 12:41
Can not reporduce in IS side.Hence closing the issue.
