### ISSUE TITLE
Cannot Retrieve access token with saml2 bearer grant against MSSQL 2017 and unique id jdbc primary Userstore

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7704] opened 2020-02-19 10:31 UTC
**Environment**
MSSQL 2017
Primary User Store > uniqueid jdbc userstoremanager

Steps to Reproduce

1. Follow doc [1] in setting up saml2bearer grant type.
2. Access http://wso2is.local:8080/travelocity.com
3. Login as admin
4. Click on Request OAuth2 Access Token
5. Access token won't be retrieved 

**Observation**

This scenario worked on H2 default pack without any issues and was able to retrieve the access token as below against H2. Observing this issue on Mssql 2017 against uniqueid jdbc user store manager as primary user store.

![saml2bearer2](https://user-images.githubusercontent.com/31848014/74825831-96195680-5330-11ea-881f-e361651a7aac.png)

[1]. https://is.docs.wso2.com/en/next/learn/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/

**Comment by DinikaSen** [comment] 2020-11-05 06:01
Cannot reproduce in 5.11.0-Beta3.

**Comment by DinikaSen** [comment] 2020-11-05 06:16
Closing since this issue can no longer be reproduced in the following environment.
**DB** : MSSQL 2017
**Primary User Store** : uniqueid jdbc userstore

**Closed by DinikaSen** 2020-11-05 06:16 UTC
Labels: Affected/5.10.0-Beta2, Priority/Highest, Severity/Critical, bug
