### ISSUE TITLE
[Improvement]Invite set of external users to register into the organization at once

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#16720] opened 2023-09-19 17:32 UTC
**Describe the improvement**

The console currently sends user invitations to a single user to register with the organization.  However, the Console doesn't have the option to invite a set of users at once by providing their emails. Choreo has such a capability.
 
How multiple invitations work in Choreo.
The admin can enter a few emails, and assign a set of roles when sending invitations.
![image](https://github.com/wso2/product-is/assets/1498339/918311d2-5080-46d4-b6b7-e9bf4e0efd06)

After completing this epic:
- The console has an option to invite a set of users by providing their emails.
- While inviting the set of users, the admin can assign a set of roles also
- This invitation option will be available in primary organizations and sub-organizations as well

**Comment by AnuradhaSK** [comment] 2023-11-03 07:55
Duplicate of https://github.com/wso2/product-is/issues/17426

**Closed by AnuradhaSK** 2023-11-03 07:55 UTC
Labels: improvement
