### ISSUE TITLE
org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt unresolved requirement 

### ISSUE THREAD

**Issue by GeertsP** [wso2/product-is#12849] opened 2021-12-07 16:26 UTC
**Describe the issue:**

Hi I think this a replay of earlier bug report. Problem is that following up on a tutorial for IS 5.11.0 in the wso2 documentation set 
the uploaded jar file doesn't start because of  unresolved (dependency) problems.   
**How to reproduce:**

Follow the steps listed on 
https://is.docs.wso2.com/en/latest/learn/private-key-jwt-client-authentication-for-oidc/#private-key-jwt-client-authentication-for-oidc
After done all the steps and starting the server you can see in the console that the component doesn't start.  First it complains about a dependency for nimbus-jose-jwt-5.8.0 which I have been able to find(and resolve). Now it complains about :
Unresolved requirement: Import-Package: net.minidev.json; version="[1.3.0,2.0.0)" and I have no idea where to get this one from 
and if further dependencies that might lie behind this one further down the road. 

**Expected behavior:**

I should see in the console that the uploaded clientauth.jwt jar is in the ACTIVE state 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0]
 - OS: [ Windows]
 - Database: [product default(s)]
 - Userstore: [e.g., product default(s) ]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment] 2022-03-25 08:04
Couldn't reproduce this server startup issue in 5.12.0-alpha17 pack and 5.11 U2 updated pack with the latest connector in the store 2.2.8 https://maven.wso2.org/nexus/content/repositories/releases/org/wso2/carbon/extension/identity/oauth/addons/org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt/2.2.8/org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-2.2.8.jar

Hence closing this issue

**Closed by piraveena** 2022-03-25 08:04 UTC
Labels: Priority/High, Severity/Critical, bug
