### ISSUE TITLE
OIDC flow consent screen shows with no requested claims (please see attached image)

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4743] opened 2019-03-24 03:45 UTC
In the ODIC configuration, email is a requested claim.

![Screen Shot 2019-03-23 at 8 43 46 PM](https://user-images.githubusercontent.com/1422563/54874635-86099780-4dac-11e9-9b0f-189ed580c478.png)

**Comment by malithie** [comment] 2019-04-02 02:20
@nilasini , This should be due to pre-consented requested claims. Can you confirm.

**Comment by nilasini** [comment] 2019-04-02 03:54
@malithie Yes this issue is due to pre-consented requested claims. According to our current implementation, this is expected behavior.
Please refer [1] for more details on this.

[1] #2985 (comment)

**Comment by nilasini** [comment] 2019-04-09 04:49
This issue will be tracked with the doc issue \[1] hence closing the issue.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Closed by nilasini** 2019-04-09 04:49 UTC
Labels: Affected/5.8.0-Alpha2, Complexity/Medium, Component/OIDC, Priority/High, Severity/Critical, Type/Bug
