### ISSUE TITLE
Adaptive Templates are not visible for old and new apps after running adaptive.sh

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14275] opened 2022-07-18 07:42 UTC
**How to reproduce:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4155/
2. Set up oracle jdk 17.0.3.1
3. Start the server try out a application creation flow
4. Run adaptive.sh 
5. Re start the server
6. Access management console and check whether the adaptive scripts templates visible for the created app in step 3
7. Adaptive scripts visible via management console
8. Access console and check whether the adaptive scripts templates visible for the created app in step 3

Adaptive scripts are not visible via console for old apps and for newly created apps

https://user-images.githubusercontent.com/31848014/179465612-c215c839-b844-499b-8bf8-7f244a5ac011.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 Ubuntu 20
Oracle JDK 17.0.3.1
H2 Default
pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4155/

**Comment by Kanapriya** [comment] 2022-07-18 09:56
Checked this behavior with default configuration (with existing deployment.toml) and with oracle JDK 11/17, and it's working as expected. BTW, tried this with MySQL database as well. No issues were identified.
<img width="1440" alt="Screenshot 2022-07-18 at 3 26 19 PM" src="https://user-images.githubusercontent.com/13362482/179488094-10fa9dd4-b332-48a0-9d25-1b6e56e46357.png">

**Comment by ShanikaWickramasinghe** [comment] 2022-07-18 11:02
Rechecked the issue with a fresh pack. In the fresh pack issue didn't got reproduced. Attaching a reference video as below and reducing the priority of the issue due to this behavior. Keeping the issue opened as need to investigate whether this is a intermittent issue or some other flow that I tried before caused this problem in the earlier pack. Will get the issue updated if I could reproduce this again

**Comment by piraveena** [comment] 2022-08-02 07:31
closing this issue since this is not reproducible in the latest pack. Please reopen the issue if this is reproducible again

**Closed by piraveena** 2022-08-02 07:31 UTC
Labels: Priority/High, Severity/Major, bug, console, Affected-6.0.0, QA-Reported, JDK-17
