### ISSUE TITLE
Login with username doesn't work when multi attribute login is enabled with the username claim

### ISSUE THREAD

**Issue by wx-yz** [wso2/product-is#14915] opened 2022-09-21 17:00 UTC
**Describe the issue:**
When multi attribute login is enabled, username cannot be used to login. In my multi attribute login case, I have 3 claims listed with commas,

http://wso2.org/claims/username,http://wso2.org/claims/emailaddress,http://wso2.org/claims/mobile

![image](https://user-images.githubusercontent.com/57770159/191565636-5d9f5863-ecde-4317-8e5a-fee393caae8a.png)

When I have this, I cannot use the username to login. I either have to remove username from the multi attribute login and use a different claim or I have to disable multi attribute login altogether.

**How to reproduce:**
1. Download IS 6.0.0 and update through WUM
2. Start IS with JDK 11
3. Enable multi attribute login and add following to claim list - http://wso2.org/claims/username,http://wso2.org/claims/emailaddress,http://wso2.org/claims/mobile
4. Add a user
5. Navigate to https://localhost:9443/myaccount
6. Try login with the username

**Expected behavior:**
A successful login to the SP app

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - OS: Linux
 - Database: inbuilt, no external RDBMS
 - Userstore: inbuilt, no external userstore

**Comment by AnuradhaSK** [comment] 2022-09-22 09:20
- I could reproduce the same issue when IS-6.0.0 is configured according to the documentation https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/#add-regular-expressions-for-allowed-claims
-  We found that the username regex given in the documentation is invalid for the configured usernames. Therefore, user authentication fails since the login identifier doesn't match with any of the configured claim regexes
- If you change the regex pattern of username claim to a valid one (let's say `^[a-zA-Z0–9._-]{3,}$`), authentication successful with username and password 

doc issue: https://github.com/wso2/product-is/issues/14923

**Comment by AnuradhaSK** [comment] 2022-09-28 08:47
closing the issue since doc issue https://github.com/wso2/product-is/issues/14923 is fixed. Please reopen the issue if the above-mentioned fix didn't work.

**Closed by AnuradhaSK** 2022-09-28 08:47 UTC
Labels: bug
