### ISSUE TITLE
Changing the Default Datasource for BPS to PostgreSQL not work.

### ISSUE THREAD

**Issue by yuniet87** [wso2/product-is#9497] opened 2020-09-18 19:57 UTC
**Describe the issue:**
I am using PostgreSQL 11.7 because in 12.2 there is an error loading the script to create the database related to the "ABSTIME" data type. I used the configuration that comes here [1]. When I load the script to create the DB everything works correctly and when the IS starts everything also without problems but when I add the "Workflow Definition" I get this:
`[2020-08-23 23:55:01,884] [] ERROR {org.wso2.carbon.bpel.deployer.BPELDeployer} - Error deploying BPEL package: User_Approval_WF.zip org.apache.ode.bpel.iapi.ContextException: DbError
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.exec(ProcessStoreImpl.java:793)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.getDeploymentUnitDAO(ProcessStoreImpl.java:303)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.loadExistingBPELPackage(TenantProcessStoreImpl.java:819)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.reloadExistingVersionsOfBPELPackage(TenantProcessStoreImpl.java:672)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deployBPELPackageInODE(TenantProcessStoreImpl.java:728)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:296)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`
`Caused by: java.util.concurrent.ExecutionException: <openjpa-2.2.0-wso2v1-r128166:129108 fatal general error> org.apache.openjpa.persistence.PersistenceException: Cannot change transaction isolation level in the middle of a transaction.`
`FailedObject: User_Approval_WF-1 [org.apache.openjpa.util.StringId] [java.lang.String]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.exec(ProcessStoreImpl.java:791)
	... 22 more`

**PostgreSQL JDBC Driver 42.2.14**
**PostgresSQL: 11.7**

[1] https://is.docs.wso2.com/en/latest/setup/changing-datasource-bpsds/

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: **IS 5.10.0**
 - OS: **Docker 19.03**
 - Database: **PostgreSQL 11.7**
 - Userstore: **JDBC**

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by yuniet87** [comment] 2020-09-18 20:02
I forgot, when I try to eliminate the workflow I get this:
![{EAA4BBC2-5D5B-40DA-AFAB-97FEF720291E}](https://user-images.githubusercontent.com/50919882/93640222-3bc89d00-f9c8-11ea-90d2-e8a727da0db4.png)
![{A3941B58-0607-4E8E-AEAD-B50E49A4DA47}](https://user-images.githubusercontent.com/50919882/93640251-42efab00-f9c8-11ea-8e28-a535cc59f386.png)

**Comment by ruwanta** [comment] 2020-09-18 23:46
This may be not due to database, but related to file permissions or any issue at the directory "<IS_HOME>/repository/deployment". The reason is that the error log says a "deployment" or :un-deployment" error. Currently the BPEL artefacts are stored in file system. It is recommended to use a shared volume on a container or cluster for these artefacts. 
Worth to check that aspect.

**Comment by yuniet87** [comment] 2020-09-21 13:28
Double checked. The following folders were mounted
  as shared volumes:

> <IS_HOME> / repository / deployment / server / bpel
<IS_HOME> / repository / deployment / server / humantasks
<IS_HOME> / repository / bpel
<IS_HOME> / repository / humantasks /

Same problem!
However, when I put them in the local DB it shows no problems.

**Comment by pulasthi7** [comment] 2020-11-10 16:02
Hi,

This is a possible duplicate of https://github.com/wso2/product-is/issues/10032

Please see the comment on that ticket to get this fixed.

**Closed by pulasthi7** 2020-11-10 16:02 UTC
Labels: bug
