### ISSUE TITLE
Add Documentation for Google One Tap Authenticator

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15287] opened 2022-12-16 10:04 UTC
Add documentation needed for the Google One Tap Authenticator introduced to the product IS by https://github.com/wso2/product-is/issues/14407.

**Comment by nilminiwso2** [comment] 2022-12-22 10:11
Duplicate of https://github.com/wso2/product-is/issues/15241

**Closed by nilminiwso2** 2022-12-22 10:11 UTC
Labels: Resolution/Duplicate, docs
