### ISSUE TITLE
During role creation permissions do not get loaded for the role with the application audience from the "User Management > Role" view.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#18525] opened 2023-12-09 18:00 UTC
**Describe the issue:**
During role creation permissions do not get loaded for the role with the application audience from the "User Management > Role" view. This is reproducible in the alpha3 pack.

**How to reproduce:**

<img width="1043" alt="Screenshot 2023-12-09 at 23 26 55" src="https://github.com/wso2/product-is/assets/1498339/e48f25ac-cbd5-4e18-a384-e0dd5df44ebe">

**Comment by brionmario** [comment] 2023-12-10 03:13
Regression from: https://github.com/wso2/identity-apps/pull/4974/files#diff-ebf68f31002705c90865ac40952a319601be2d6094f01823de280c3b6a3cebbcR512

Reverting to the previous fixes the issue.

```tsx
                        options={ allAPIResourcesDropdownOptions
                            .sort((a: DropdownItemProps, b: DropdownItemProps) =>
                                -b?.type?.localeCompare(a?.type)) }
```

But need to address the original issue related to consistency: https://github.com/wso2/product-is/issues/18339

**Comment by dasuni-30** [comment] 2023-12-13 06:22
This error occurred because the `type` was not retrieved from the `authorized-apis API`. An ongoing backend improvement [1] is underway to add the `type` to the `authorized-apis AP`I. We'll implement the necessary filtering as soon as this improvement is completed.

[1] - https://github.com/wso2/product-is/issues/18276

**Comment by dasuni-30** [comment] 2023-12-14 10:54
### Fixed in the new pack

<img width="1158" alt="Screenshot 2023-12-14 at 16 23 57" src="https://github.com/wso2/product-is/assets/27746285/21969186-05bc-434f-ba58-e5e4bb1a902f">

**Closed by dasuni-30** 2023-12-14 10:54 UTC
Labels: Priority/High, Severity/Critical, bug, frontend, pr-sent

**Comment by aaujayasena** [comment] 2023-12-18 10:41
Please add the verified build number https://github.com/wso2/product-is/issues/18525#issuecomment-1855626716
