### ISSUE TITLE
Ask for user confirmation when deleting an Inbound Authentication Config

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5517] opened 2019-06-09 14:38 UTC
Moved from: https://wso2.org/jira/browse/IDENTITY-7121

The users can accidentally click on this button, So it's better to get user confirmation before deleting.

![Screenshot from 2017-12-11 14-32-54](https://user-images.githubusercontent.com/12288369/59160338-5be58d00-8af2-11e9-95ce-a03b14b7581e.png)

**Comment by madurangasiriwardena** [comment] 2020-03-03 06:59
Duplicate of https://github.com/wso2/product-is/issues/1975

**Closed by madurangasiriwardena** 2020-03-03 06:59 UTC
