### ISSUE TITLE
Indicate parent organization users' shadow accounts by special labels in user listing view in below organizationz

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17583] opened 2023-11-06 04:56 UTC
**Describe the issue:**
- Create organization  from console
- Go to  organization and invite users from parent and accept the invite
- The user list in below organization shows the parent organization users' shadown accounts 
- Need to indicate them using a label
<img width="1632" alt="Screenshot 2023-11-06 at 10 21 45" src="https://github.com/wso2/product-is/assets/25483865/373a399c-92f7-4841-b790-58413356fc82">

**Comment by dewniMW** [comment] 2023-11-06 06:28
Duplicate of https://github.com/wso2/product-is/issues/17402

**Closed** 2023-11-17 08:18 UTC
Labels: ui, Priority/High, bug, backend, frontend, Affected/7.0.0-Alpha, Component/B2B
