### ISSUE TITLE
[ConsoleApp][Windows] User Roles not getting updated after the edit

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10039] opened 2020-10-23 07:33 UTC
**Describe the issue:**
User roles did not get updated once its edit and update with new roles in console App. Check the network calls and seems its not calling any endpoint with update or patch method. 

**How to reproduce:**

1. Login to Console App
2. Create a User by adding user details, Assign group and roles.
3. Save the created user
4. Go to the created user and go to Roles section
5. Edit the user role and update the existing user role by remove or add roles
6. Click Save

**Expected behaviour:**
Existing User roles should be updated with given user roles.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 Beta3 Snapshot
 - OS: Windows 10
 - Database: JDK-11.0.9

**Comment by thivi** [comment] 2020-11-06 20:35
I wasn't able to reproduce this issue on 5.11.0-Beta5-SNAPSHOT

**Comment by jeradrutnam** [comment] 2020-11-09 11:22
Tested with wso2is-5.11.0-beta5 pack on Windows 10. Couldn't reproduce. Hence closing. And we'll re-open if can reproduce.

**Closed by jeradrutnam** 2020-11-09 11:22 UTC
Labels: Priority/High, Severity/Critical, bug, console, reviewed_511, ux
