### ISSUE TITLE
SAML related cookie not clearing when a User's session is timedout

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6845] opened 2019-11-12 04:38 UTC
When using a saml app after a user's session timed out the user will have to re-login at that time the old samlssoTokenId is assigned instead of a new one.

**Comment by piraveena** [comment] 2021-01-05 10:01
This issue still exists in IS.

**Steps to reproduce:**
1. Create 2 SAML apps (appA, appB).
2. Configure session idle timeout as 2min.
3. User A logs in to appA.
4. Check the samlssoTokenId cookie value (Let's consider it as samlssoTokenId=xxxy).
5. User A stays idle longer than the session idle timeout or logs out (more than 2min).
6. User B accesses the AppB in the same browser session.
7. Since the SSO session of userA is expired, the User B will be prompted with login page.
8. Login with userB.
9. Check the samlssoTokenId cookie value in the browser. The same cookie will be there for user B also (samlssoTokenId=xxxy).

We need to analyse what are the impacts of this and fix the issue

**Comment by IsuraD** [comment] 2021-02-05 03:59
@minolih

**Comment by piraveena** [comment] 2022-08-02 10:00
Fixed with https://github.com/wso2-support/identity-inbound-auth-saml/pull/224

**Closed by piraveena** 2022-08-02 10:00 UTC
Labels: Priority/Highest, Component/SAML, bug, 6.0.0-bug-fixing
