### ISSUE TITLE
[Legacy mode] Getting 403 Forbidden error while viewing  Groups.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18372] opened 2023-12-03 09:12 UTC
**Describe the issue:**

When trying to view an existing group, Getting a 403 error.
![Screenshot 2023-12-03 at 14 23 58](https://github.com/wso2/product-is/assets/41188245/3832a9fb-5453-4c8e-8675-29c3a14fd08d)
![Screenshot 2023-12-03 at 14 31 37](https://github.com/wso2/product-is/assets/41188245/120a7075-f10f-4912-b5dd-006f7e26cb20)

**How to reproduce:**

1. Navigate to Groups page 
2. select admin group

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Legacy pack
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nipunsampath** [comment] 2023-12-19 11:45
Closing the issue since this is not reproducible in the latest `wso2is-7.0.0-beta4-SNAPSHOT` running on legacy mode.

**Closed by nipunsampath** 2023-12-19 11:45 UTC
Labels: ui, Priority/Highest, Severity/Blocker, bug, backend, Component/B2B, Affected/7.0.0-beta2, is-7-legacy
