### ISSUE TITLE
Implement UI based Integration Tests for Developer Portal Identity Provider Component

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#8693] opened 2020-06-25 05:48 UTC
### Description

Implement UI based Integration Tests to validate the behaviour of each UI element for Developer Portal Identity Provider Component. Automation test will be implemented using cypress.io Test Automation Framework

**Comment by brionmario** [comment] 2020-10-23 07:19
Duplicate of https://github.com/wso2/product-is/issues/9828

**Closed by brionmario** 2020-10-23 07:19 UTC
Labels: console, dev-exp, task
