### ISSUE TITLE
Console app is not properly loading for the super admin user 

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17898] opened 2023-11-18 06:04 UTC
**Describe the issue:**

$subject
<img width="1512" alt="Screenshot 2023-11-18 at 11 30 26" src="https://github.com/wso2/product-is/assets/41533942/f8caad87-7e2c-446d-a885-22d7f951405c">

**How to reproduce:**

1. Get the latest changes (as of 18th Nov 2023) and build IS from source.
2. Try to access console as the super admin user
3. Observe that many features are hidden

**Expected behavior:**

Console app should be loading properly for super admins
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by shanggeeth** [comment] 2023-11-18 09:09
Got the latest changes and build from the source at 14:33 (GMT+5:30).

When, accessing the console as super admin, no features are hidden.

https://github.com/wso2/product-is/assets/59327626/b6b720f3-48ff-48c7-a023-4e7cccd7ff3f

**Comment by sadilchamishka** [comment] 2023-11-18 12:55
Yes, couldn't reproduced. Hence close the issue.

**Closed by sadilchamishka** 2023-11-18 12:55 UTC
Labels: Resolution/Cannot Reproduce, Severity/Blocker, Severity/Critical, bug, backend, Affected/7.0.0-Alpha, Component/B2B
