### ISSUE TITLE
[IS 6.0.0] Duplicate Service Provider names listed when having multiple inbound authenticators configured with pagination activated

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#15964] opened 2023-05-31 14:16 UTC
**Describe the issue:**
After creating the service provider with multiple inbound authentication configurations(SAML, OAuth/OpenID , PassiveSTS) the service provider will be shown multiple times when the user tries to list the service providers. But, this listing is not visible when the user tries to search the service provider in the search field.
There is already a fix for this has been provided in[1] but the error can be reproduced if PostgreSQL or H2 is used for the IDENTITY_DB and SHARED_DB.
Furthermore, this is only visible when you create a number of service providers (create SPs till pagination activates).

**How to reproduce:**
1. Go to Management Console → Service Providers
2. Create a new service provider and setup SAML and OAuth/OIDC inbound authentications for the SP.
3. When you go and list the service providers you will be able to see duplicate entries. (You need to have pagination activated with the SP list for this - To activate pagination you can create multiple SPs)

**Expected behavior:**
One SP entry should be visible in the UI even it has multiple inbound authentication configurations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 (6.0.0.68 / 6.0.0.77)
 - OS: Mac
 - Database: PostgreSQL / H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**
1. [https://github.com/wso2/product-is/issues/14950](https://github.com/wso2/product-is/issues/14950)

**Comment by mifrazmurthaja** [comment] 2023-06-01 03:50
duplicate of #14950

**Closed by mifrazmurthaja** 2023-06-01 03:50 UTC
Labels: bug
