### ISSUE TITLE
The default image logo in branding is not displayed in the app login UI

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16740] opened 2023-09-21 04:51 UTC
**Describe the issue:**

The image logos configured in branding are not displayed in console app
<img width="1512" alt="Screenshot 2023-09-21 at 09 31 28" src="https://github.com/wso2/product-is/assets/40081059/ac700781-2cb4-4875-8a2f-402c9785b15b">

1.Login in to the console
2.Go to customization - > branding
3.Go to images ->Add logo
4.Save and publish changes

**How to reproduce:**

**Expected behavior:**

The image should be displayed as shown in the preview section

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., 7.0.0 M2 - https://github.com/wso2/product-is/releases/tag/v7.0.0-m2]
 - OS: [ Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-09-21 07:07
This is not reproducible. Could you please check whether the image URL you used is valid and accessible?

![Screenshot 2023-09-21 at 12 31 29](https://github.com/wso2/product-is/assets/41533942/491115dd-feb3-44bd-9f80-4541b6a0d366)

**Comment by asekawa** [comment] 2023-09-21 07:11
@pavinduLakshan can u please check on the default image

**Comment by pavinduLakshan** [comment] 2023-09-21 07:15
> @pavinduLakshan can u please check on the default image

The issue here is not that configured images are not displayed, but the default image logo is not displayed. This has happened because the default logo is not present in the configured theme.

**Comment by chamathns** [comment] 2023-10-10 05:59
@pavinduLakshan can you please verify and close this issue?

**Comment by pavinduLakshan** [comment] 2023-10-11 14:45
Verified the fix in the latest build, hence closing the issue.

![Screenshot 2023-10-11 at 20 14 13](https://github.com/wso2/product-is/assets/41533942/52668b67-596c-4772-ac75-b8f25739c4d9)

**Closed by pavinduLakshan** 2023-10-11 14:45 UTC
Labels: Priority/Highest, Severity/Critical, bug
