### ISSUE TITLE
[Migration] IS-5.3.0 to IS-5.11.0 migration fails due to the symmetric key encryption introduced in IS-5.11.0 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11267] opened 2021-02-13 13:59 UTC
**Describe the issue:**
IS-5.3.0 to IS-5.11.0 migration fails due to the symmetric key encryption introduced in IS-5.11.0.

**How to reproduce:**

- Do a test migration from IS-5.3.0 to IS-5.11.0[1].

The following error is observed.

```
TID: [-1234] [] [2021-02-13 19:27:46,756] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.MigrationClientException: Error while checking whether the passwords are encrypted with new encryption algorithm.
	at org.wso2.carbon.is.migration.service.v550.migrator.BPSProfileDataMigrator.migrateBPSProfilePassword(BPSProfileDataMigrator.java:81)
	at org.wso2.carbon.is.migration.service.v550.migrator.BPSProfileDataMigrator.migrate(BPSProfileDataMigrator.java:50)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:367)
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:447)
	at org.wso2.carbon.is.migration.service.v550.migrator.BPSProfileDataMigrator.transformPasswordFromOldToNewEncryption(BPSProfileDataMigrator.java:94)
	at org.wso2.carbon.is.migration.service.v550.migrator.BPSProfileDataMigrator.migrateBPSProfilePassword(BPSProfileDataMigrator.java:71)
	... 31 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: An error occurred while decrypting using the algorithm : 'RSA'
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:152)
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132)
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:361)
	... 34 more
Caused by: java.security.InvalidKeyException: unknown key type passed to RSA
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1189)
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:139)
	... 36 more
```

[1]https://is.docs.wso2.com/en/5.11.0/setup/migrating-to-5110/

 - Database: [MySQL]
 - Related: https://github.com/wso2/product-is/issues/9455

**Comment by ashendes** [comment] 2022-06-17 14:15
Duplicate of https://github.com/wso2/product-is/issues/12777

**Closed by ashendes** 2022-06-17 14:15 UTC
Labels: bug
