### ISSUE TITLE
Input Field Placeholders Misaligned with Identity Server  in Branding in Links Section

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17104] opened 2023-10-21 19:20 UTC
**Describe the issue:**
In the brand page link section, the input field placeholders are misaligned with Identity Server  and are directed based on "Asgardeo".

**How to reproduce:**
Log in to the  console.
Navigate to the branding customization section.
Observe the placeholders within the input fields in the branding page "Links" section.

<img width="853" alt="Screenshot 2023-10-22 at 00 40 28" src="https://github.com/wso2/product-is/assets/39120228/593ca679-a04e-4c5b-b9f9-cf1065715b6f">

**Comment by pavinduLakshan** [comment] 2023-10-23 06:31
Duplicate of https://github.com/wso2/product-is/issues/17001

**Closed by pavinduLakshan** 2023-10-23 06:31 UTC
Labels: ui, Priority/High, Resolution/Duplicate, Severity/Major, bug, QA-Reported, affected - 7.0.0 m4
