### ISSUE TITLE
Error while retrieving Remote Fetch Configurations in 5.11-beta3 with Oracle

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#10121] opened 2020-10-27 13:47 UTC
**Describe the issue:**
Error while retrieving Remote Fetch Configurations after migrating 5.10 to 5.11-beta3 with Oracle 12c.

**How to reproduce:**
Populate data for 5.10 using Oracle
Migrate to 5.11-beta3
Open console with super tenant admin.

**Expected behavior:**
No errors

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta3
 - OS: Ubuntu 18.04 LTS
 - Database: Oracle 12c
 - Userstore: database_unique_id

*stacktrace*
ERROR {org.wso2.carbon.identity.api.server.fetch.remote.v1.core.ServerRemoteFetchConfigManagementService} - errorCode: RFE-65001 | message: Server encountered an error while listing remote fetch configurations. org.wso2.carbon.identity.remotefetch.common.exceptions.RemoteFetchServerException: Error while retrieving Remote Fetch Configurations.
at org.wso2.carbon.identity.remotefetch.core.util.RemoteFetchConfigurationUtils.handleServerException(RemoteFetchConfigurationUtils.java:201)
at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.getBasicRemoteFetchConfigurationsByTenant(RemoteFetchConfigurationDAOImpl.java:312)
at org.wso2.carbon.identity.remotefetch.core.RemoteFetchConfigurationServiceImpl.getBasicRemoteFetchConfigurationList(RemoteFetchConfigurationServiceImpl.java:145)
at org.wso2.carbon.identity.api.server.fetch.remote.v1.core.ServerRemoteFetchConfigManagementService.getRemoteFetchConfigs(ServerRemoteFetchConfigManagementService.java:95)
at org.wso2.carbon.identity.api.server.fetch.remote.v1.impl.RemoteFetchApiServiceImpl.getRemoteFetchConfigs(RemoteFetchApiServiceImpl.java:66)
at org.wso2.carbon.identity.api.server.fetch.remote.v1.RemoteFetchApi.getRemoteFetchConfigs(RemoteFetchApi.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.TransactionException: Could not commit the transaction.
at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:105)
at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.getBasicRemoteFetchConfigurationsByTenant(RemoteFetchConfigurationDAOImpl.java:267)
... 58 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, IS_ENABLED, REPO_MANAGER_TYPE, ACTION_LISTENER_TYPE, CONFIG_DEPLOYER_TYPE ,REMOTE_FETCH_NAME, DEPLOYED, ERROR_DEPLOYING , DEPLOYED_DATE FROM (SELECT IDN_REMOTE_FETCH_CONFIG.ID, IDN_REMOTE_FETCH_CONFIG.IS_ENABLED, IDN_REMOTE_FETCH_CONFIG.REPO_MANAGER_TYPE, IDN_REMOTE_FETCH_CONFIG.ACTION_LISTENER_TYPE, IDN_REMOTE_FETCH_CONFIG.CONFIG_DEPLOYER_TYPE ,IDN_REMOTE_FETCH_CONFIG.REMOTE_FETCH_NAME, (SELECT COUNT(IDN_REMOTE_FETCH_REVISIONS.ID) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID AND IDN_REMOTE_FETCH_REVISIONS.DEPLOYMENT_STATUS = 'SUCCESS') AS DEPLOYED, (SELECT COUNT(IDN_REMOTE_FETCH_REVISIONS.ID) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID AND IDN_REMOTE_FETCH_REVISIONS.DEPLOYMENT_STATUS = 'FAIL') AS ERROR_DEPLOYING , (SELECT MAX(IDN_REMOTE_FETCH_REVISIONS.DEPLOYED_DATE) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID) AS DEPLOYED_DATE, ROWNUM AS rnum FROM IDN_REMOTE_FETCH_CONFIG WHERE IDN_REMOTE_FETCH_CONFIG.TENANT_ID = ? AND ROWNUM <= ?) WHERE rnum > ?
at org.wso2.carbon.database.utils.jdbc.Template.executeQuery(Template.java:152)
at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.lambda$getBasicRemoteFetchConfigurationsByTenant$21(RemoteFetchConfigurationDAOImpl.java:268)
at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:83)
... 59 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
at com.sun.proxy.$Proxy54.executeQuery(Unknown Source)
at org.wso2.carbon.database.utils.jdbc.Template.executeQuery(Template.java:140)
... 61 more

**Comment by Buddhimah** [comment] 2020-10-28 18:46
[2020-10-28 23:40:20,294] [0fb94023-a56c-495a-83a6-150a32687d89] ERROR {org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService} - errorCode: APP-15001 | message: Server Encountered an error while retrieving applications. org.wso2.carbon.identity.application.common.IdentityApplicationManagementServerException: Error while getting application basic information for discoverable applications in tenantDomain: carbon.super
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4917)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4759)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getDiscoverableApplicationBasicInfo(CacheBackedApplicationDAO.java:400)
	at org.wso2.carbon.identity.application.mgt.internal.impl.DiscoverableApplicationManagerImpl.getDiscoverableApplicationBasicInfo(DiscoverableApplicationManagerImpl.java:38)
	at org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService.getApplications(ApplicationService.java:106)
	at org.wso2.carbon.identity.rest.api.user.application.v1.impl.MeApiServiceImpl.getApplications(MeApiServiceImpl.java:44)
	at org.wso2.carbon.identity.rest.api.user.application.v1.MeApi.getApplications(MeApi.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10145][10844][4.9.78] Invalid parameter 2: Parameter index is out of range. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.fd.a(fd.java:676)
	at com.ibm.db2.jcc.am.fd.a(fd.java:60)
	at com.ibm.db2.jcc.am.fd.a(fd.java:103)
	at com.ibm.db2.jcc.am.fn.e(fn.java:5021)
	at com.ibm.db2.jcc.am.fn.d(fn.java:5014)
	at com.ibm.db2.jcc.am.fn.c(fn.java:933)
	at com.ibm.db2.jcc.am.fn.setInt(fn.java:926)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy55.setInt(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.setInt(NamedPreparedStatement.java:127)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4907)
	... 60 more

[2020-10-28 23:40:33,960] [7971f73a-bf0b-493d-9777-53330944d86c] ERROR {org.wso2.carbon.identity.api.server.fetch.remote.v1.core.ServerRemoteFetchConfigManagementService} - errorCode: RFE-65001 | message: Server encountered an error while listing remote fetch configurations. org.wso2.carbon.identity.remotefetch.common.exceptions.RemoteFetchServerException: Error while retrieving Remote Fetch Configurations.
	at org.wso2.carbon.identity.remotefetch.core.util.RemoteFetchConfigurationUtils.handleServerException(RemoteFetchConfigurationUtils.java:201)
	at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.getBasicRemoteFetchConfigurationsByTenant(RemoteFetchConfigurationDAOImpl.java:312)
	at org.wso2.carbon.identity.remotefetch.core.RemoteFetchConfigurationServiceImpl.getBasicRemoteFetchConfigurationList(RemoteFetchConfigurationServiceImpl.java:145)
	at org.wso2.carbon.identity.api.server.fetch.remote.v1.core.ServerRemoteFetchConfigManagementService.getRemoteFetchConfigs(ServerRemoteFetchConfigManagementService.java:95)
	at org.wso2.carbon.identity.api.server.fetch.remote.v1.impl.RemoteFetchApiServiceImpl.getRemoteFetchConfigs(RemoteFetchApiServiceImpl.java:66)
	at org.wso2.carbon.identity.api.server.fetch.remote.v1.RemoteFetchApi.getRemoteFetchConfigs(RemoteFetchApi.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.TransactionException: Could not commit the transaction.
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:105)
	at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.getBasicRemoteFetchConfigurationsByTenant(RemoteFetchConfigurationDAOImpl.java:292)
	... 58 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT IDN_REMOTE_FETCH_CONFIG.ID, IDN_REMOTE_FETCH_CONFIG.IS_ENABLED, IDN_REMOTE_FETCH_CONFIG.REPO_MANAGER_TYPE, IDN_REMOTE_FETCH_CONFIG.ACTION_LISTENER_TYPE, IDN_REMOTE_FETCH_CONFIG.CONFIG_DEPLOYER_TYPE ,IDN_REMOTE_FETCH_CONFIG.REMOTE_FETCH_NAME, (SELECT COUNT(IDN_REMOTE_FETCH_REVISIONS.ID) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID AND IDN_REMOTE_FETCH_REVISIONS.DEPLOYMENT_STATUS = 'SUCCESS'), (SELECT COUNT(IDN_REMOTE_FETCH_REVISIONS.ID) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID AND IDN_REMOTE_FETCH_REVISIONS.DEPLOYMENT_STATUS = 'FAIL'), (SELECT MAX(IDN_REMOTE_FETCH_REVISIONS.DEPLOYED_DATE) FROM IDN_REMOTE_FETCH_REVISIONS WHERE IDN_REMOTE_FETCH_REVISIONS.CONFIG_ID = IDN_REMOTE_FETCH_CONFIG.ID) FROM IDN_REMOTE_FETCH_CONFIG WHERE IDN_REMOTE_FETCH_CONFIG.TENANT_ID = ? LIMIT ? OFFSET ?
	at org.wso2.carbon.database.utils.jdbc.Template.executeQuery(Template.java:152)
	at org.wso2.carbon.identity.remotefetch.core.dao.impl.RemoteFetchConfigurationDAOImpl.lambda$getBasicRemoteFetchConfigurationsByTenant$27(RemoteFetchConfigurationDAOImpl.java:293)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:83)
	... 59 more
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=DB2INST1.IDN_REMOTE_FETCH_CONFIG, DRIVER=4.9.78
	at com.ibm.db2.jcc.am.fd.a(fd.java:676)
	at com.ibm.db2.jcc.am.fd.a(fd.java:60)
	at com.ibm.db2.jcc.am.fd.a(fd.java:127)
	at com.ibm.db2.jcc.am.en.c(en.java:2553)
	at com.ibm.db2.jcc.am.en.d(en.java:2541)
	at com.ibm.db2.jcc.am.en.a(en.java:2017)
	at com.ibm.db2.jcc.t4.cb.g(cb.java:140)
	at com.ibm.db2.jcc.t4.cb.a(cb.java:40)
	at com.ibm.db2.jcc.t4.q.a(q.java:32)
	at com.ibm.db2.jcc.t4.rb.i(rb.java:135)
	at com.ibm.db2.jcc.am.en.ib(en.java:1988)
	at com.ibm.db2.jcc.am.fn.rc(fn.java:3016)
	at com.ibm.db2.jcc.am.fn.b(fn.java:3791)
	at com.ibm.db2.jcc.am.fn.dc(fn.java:697)
	at com.ibm.db2.jcc.am.fn.executeQuery(fn.java:667)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy55.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.Template.executeQuery(Template.java:140)
	... 61 more

[2020-10-28 23:48:16,991] [5642de39-0b90-4a4e-bd3b-d215c72fdbbd]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'admin@carbon.super [-1234]' logged in at [2020-10-28 23:48:16,989+0530]


This issue also reproduces in DB2 11.5

**Comment by NilukaSripalim** [comment] 2020-10-29 08:28
the same issue identified with DB2: while configuring as Primary user store

**Comment by Buddhimah** [comment] 2020-10-30 04:38
This issue was reproduced in Oracle and DB2 after migration since the tables does not exsists they were added to the migration client by https://github.com/wso2-extensions/identity-migration-resources/pull/156

**Comment by Buddhimah** [comment] 2020-10-30 04:44
@NilukaSripalim Can you create a seperate issue with the stacktrace if this reproduced in the Beta 4 Snapshot Pack

**Comment by Buddhimah** [comment] 2020-11-06 07:43
Closing as per https://github.com/wso2/product-is/issues/10121#issuecomment-719166572

**Closed by Buddhimah** 2020-11-06 07:43 UTC
Labels: Affected/5.11.0-Beta, bug
