### ISSUE TITLE
Should have confirmation box when deleting SAML/OIDC application

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#6907] opened 2019-11-21 11:53 UTC
Currently there is no any confirmation while deleting SAML/OIDC applications in the service provider.

<img width="944" alt="Screen Shot 2019-11-21 at 11 50 51" src="https://user-images.githubusercontent.com/8766778/69335863-80bf5e00-0c55-11ea-89ee-368f69685e70.png">

<img width="943" alt="Screen Shot 2019-11-21 at 11 51 13" src="https://user-images.githubusercontent.com/8766778/69335883-887f0280-0c55-11ea-82ea-fa9b9a20cf4d.png">

**Comment by madurangasiriwardena** [comment] 2020-03-03 06:59
Duplicate of https://github.com/wso2/product-is/issues/1975

**Closed by madurangasiriwardena** 2020-03-03 06:59 UTC
Labels: Priority/Normal, Type/Improvement
