### ISSUE TITLE
Get Unauthorized while trying the UMA flow

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#3716] opened 2018-09-11 08:44 UTC
Followed the steps here: https://medium.com/@dewni.matheesha/uma-2-0-features-in-wso2-identity-server-9f86fdfbb644

Get Unauthorized error in step 6. Use admin/admin to get the PAT.

**Comment by dewniMW** [comment] 2018-09-11 11:34
Issue is not reproducible.

**Comment by JKAUSHALYA** [comment] 2018-09-11 11:35
Closing since not reproducible.

**Closed by JKAUSHALYA** 2018-09-11 11:35 UTC
Labels: Affected/5.7.0-RC1
