### ISSUE TITLE
Mention UsernameWithEmailJavaScriptRegEx property in Email as Username doc

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#9750] opened 2020-10-10 19:28 UTC
When using email as a username we need to mention in the doc [1] that we need to add the **UsernameWithEmailJavaScriptRegEx** property to the UserStore config. This is only mentioned at [2]

[1] - https://docs.wso2.com/display/IS570/Using+Email+Address+as+the+Username
[2] - https://docs.wso2.com/display/ADMIN44x/Working+with+Properties+of+User+Stores

**Comment by rksk** [comment] 2022-02-07 06:56
Duplicate of https://github.com/wso2/product-is/issues/13079

**Closed by rksk** 2022-02-07 06:56 UTC
Labels: docs
