### ISSUE TITLE
Filter claims and pass to the service provider without being JIT provisioned in the primary userstore

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-is#2947] opened 2018-03-14 09:57 UTC
**Description:**
When an external federated IDP is created and enabled JIT provisioning to the primary userstore, the current implementation doesn't support for filtering out claims and just passing them to the service provider without being JIT provisioned in the primary userstore.

**Suggested Labels:**

Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**
IS 5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by emswbandara** [comment] 2018-03-14 10:01
can you provide more description on this including the steps to reproduce?

**Comment by isharak** [comment] 2021-04-09 11:43
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 11:43 UTC
Labels: Affected/5.3.0, improvement
