### ISSUE TITLE
Getting an Exception & unable to access user profile info(user portal) with "LDAP/AD" user store

### ISSUE THREAD

**Issue by denizzzzp** [wso2/product-is#8294] opened 2020-05-05 20:44 UTC
Step to reproduce:
WSO2IS5.10 (docker images docker.wso2.com/wso2is:5.10.0.1588181330216 and docker.wso2.com/wso2is:latest)

Set Primary user store as JDBC
[user_store]
type = "org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager"
[user_store.properties]
SCIMEnabled= true

Server up & try to login to user portal
https://localhost:9443/user-portal

Login with admin credentials
admin:admin

Navigate to "Personal Info"
Issue:
![WSO2IS](https://user-images.githubusercontent.com/30050758/81114090-fed4a000-8f29-11ea-86a6-66212a3e9c8f.png)
wso2is_1   | [2020-05-05 23:40:20,788] [ee4f034a-72a1-4566-92ef-83915151f95b] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/scim2].[SCIM2Servlet]} - Servlet.service() for servlet [SCIM2Servlet] in context with path [/scim2] threw exception java.lang.NullPointerException
wso2is_1   |    at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUser(SCIMUserManager.java:2798)
wso2is_1   |    at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getMe(SCIMUserManager.java:1776)
wso2is_1   |    at org.wso2.charon3.core.protocol.endpoints.MeResourceManager.get(MeResourceManager.java:71)
wso2is_1   |    at org.wso2.carbon.identity.scim2.provider.resources.MeResource.getUser(MeResource.java:67)
wso2is_1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wso2is_1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
wso2is_1   |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
wso2is_1   |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
wso2is_1   |    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
wso2is_1   |    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
wso2is_1   |    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
wso2is_1   |    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
wso2is_1   |    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
wso2is_1   |    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
wso2is_1   |    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
wso2is_1   |    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
wso2is_1   |    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
wso2is_1   |    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
wso2is_1   |    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
wso2is_1   |    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
wso2is_1   |    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
wso2is_1   |    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
wso2is_1   |    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
wso2is_1   |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
wso2is_1   |    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
wso2is_1   |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
wso2is_1   |    at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
wso2is_1   |    at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
wso2is_1   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
wso2is_1   |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
wso2is_1   |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
wso2is_1   |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
wso2is_1   |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
wso2is_1   |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
wso2is_1   |    at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
wso2is_1   |    at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
wso2is_1   |    at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:94)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
wso2is_1   |    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
wso2is_1   |    at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
wso2is_1   |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
wso2is_1   |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
wso2is_1   |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
wso2is_1   |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
wso2is_1   |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
wso2is_1   |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
wso2is_1   |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
wso2is_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
wso2is_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
wso2is_1   |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
wso2is_1   |    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by darshanasbg** [comment] 2020-05-13 09:18
@denizzzzp I have checked the possibility of having the NPE at SCIMUserManager.java:2798 but couldn't see a possible culprit.. Will have to check further by try to reproducing the same. @Thumimku Will you be able to try as above and check on this?

Also @denizzzzp, can you confirm whats the user user store you are using exactly? Is it a JDBC user store or a ReadOnlyLDAPUserStoreManager?

**Comment by senthalan** [comment] 2020-05-13 09:47
I found a related issue https://github.com/wso2/product-is/issues/8309

**Comment by darshanasbg** [comment] 2020-05-13 11:19
Thanks for the input @senthalan.. Probably this occurred due to similar reason.. Lets verify and decide the resolution.

**Comment by Thumimku** [comment] 2020-05-14 06:58
Fixed with the commit
wso2-extensions/identity-inbound-provisioning-scim2#261

Fix will be available after the identity-inbound-provisioning-scim2 library update on the product.

**Comment by isharak** [comment] 2024-11-06 03:11
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 03:11 UTC
Labels: Type/Bug, IceBox
