### ISSUE TITLE
Cannot see the role view in sub organizations

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#19115] opened 2024-01-23 04:46 UTC
**Describe the issue:**
$subject

<img width="721" alt="Screenshot 2024-01-23 at 10 13 51 AM" src="https://github.com/wso2/product-is/assets/4951983/29879007-673e-4a51-814b-eb9ae68f2746">

**How to reproduce:**

1. Create an organization and switch to that org
2. Note that role view is missing 

**Expected behavior:**
Role view should be available.
It's from the role view users get assigned to roles set for the app

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment] 2024-01-23 05:01
Duplicate of https://github.com/wso2/product-is/issues/19058. Hence closing the issue

**Closed by dewniMW** 2024-01-23 05:01 UTC
Labels: Severity/Blocker, bug, Affected/7.0.0-beta6, IS-7-demo
