### ISSUE TITLE
Cannot create an application role assigning scopes of org wise claim management API

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18916] opened 2024-01-13 17:43 UTC
**Describe the issue:**

https://github.com/wso2/product-is/assets/4951983/f121c45f-07ea-4cdb-b751-886836ad3fc9

**How to reproduce:**
1. Create an app
2. Authorize claim management API at organization level
3. Try to create a role assigning scopes of claim management api
4. Similar to what's shown above cannot list the scopes associated with this API. And when this is the API last added, the 'create' button is disabled

**Expected behavior:**
Should be able to pick specific scopes or all scopes of this API and create the role assigning those permissions to the role

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by SujanSanjula96** [comment] 2024-01-16 05:19
Can't reproduce the issue related to not showing the scopes. This might be due to not authorizing the scopes of the API. The issue related to create button getting disabled can be reprodued when no authorized scopes for the API and it should be fixed.

**Comment by dewniMW** [comment] 2024-01-16 06:52
I too cannot reproduce the issue with scopes not being shown for the claim management API (given that one or more scopes have been selected for the claim management API when authorizing an API for the application).

Regarding the issue with create button getting disabled when scopes are not selected for an API, that validation logic has been added with https://github.com/wso2/identity-apps/pull/5032 (`Validation error message will be displayed on the scopes dropdown if the user touches the dropdown, but doesn't set a value.`). This has been added to address https://github.com/wso2/product-is/issues/18523 to resolve an issue with the create button being unresponsive. However, IMO since we allow to create API resources without scopes, we should allow to create roles without any scopes also as the API during this role creation only considers the permissions bound to the selected API (where the permissions are optional)

``` "permissions": [
        {
            "value": "internal_org_session_view"
        },
        {
            "value": "internal_org_session_delete"
        }
    ]
```

**Comment by PasinduYeshan** [comment] 2024-01-18 04:31
This issue is fixed from following PR
- https://github.com/wso2/identity-apps/pull/5226

**Closed by PasinduYeshan** 2024-01-18 04:31 UTC
Labels: Severity/Critical, bug, frontend, Component/B2B, Application Roles, Affected/7.0.0 beta5
