### ISSUE TITLE
Password recovery not working when redirects from login page with multiple scopes

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-is#6674] opened 2019-10-17 09:33 UTC
1. Go to with multiple scope
    https://localhost:9443/oauth2/authorize?response_type=code&client_id=<>&redirect_uri=<>&scope=openid test test1
 2. Click on sign up and fill the data
 3. Error observed

[2019-10-15 13:15:02,675] ERROR - [jsp] Servlet.service() for servlet [jsp] threw exception
java.net.URISyntaxException: Illegal character in query at index 279: https://localhost:9443/authenticationendpoint/login.do?client_id=btGqE2uFjIbNq6E7w_DiFeEpLq0a&commonAuthCallerPath=/oauth2/authorize&forceAuth=false&passiveAuth=false&redirect_uri=https://localhost:9443/devportal/services/auth/callback/login&response_type=code&scope=apim:api_key apim:app_manage apim:app_update apim:dedicated_gateway apim:self-signup apim:store_settings apim:sub_alert_manage apim:sub_manage apim:subscribe openid&state=/apis?tenant=new.com&tenantDomain=carbon.super&sessionDataKey=2bd2dbeb-d14e-454e-b4c1-da0dff2998f8&relyingParty=btGqE2uFjIbNq6E7w_DiFeEpLq0a&type=oidc&sp=admin_admin_store&isSaaSApp=true&authenticators=BasicAuthenticator:LOCAL
at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_211]
at java.net.URI$Parser.checkChars(URI.java:3021) ~[?:1.8.0_211]
at java.net.URI$Parser.parseHierarchical(URI.java:3111) ~[?:1.8.0_211]
at java.net.URI$Parser.parse(URI.java:3053) ~[?:1.8.0_211]
at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_211]
at org.wso2.carbon.identity.mgt.endpoint.IdentityManagementEndpointUtil.getURLEncodedCallback(IdentityManagementEndpointUtil.java:467) ~[classes/:?]

**Comment by piraveena** [comment] 2020-11-09 05:52
Could not reproduce this issue with the latest 5.11.0-beta5-snapshot pack. This issue should have fixed with https://github.com/wso2-extensions/identity-governance/pull/315. Hence closing the issue

**Closed by piraveena** 2020-11-09 05:52 UTC
Labels: Priority/High, Severity/Critical, bug
