### ISSUE TITLE
Getting 500 in saml2 web app pickup dispatch sample when saml2 artifact binding is enabled

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#15235] opened 2022-11-29 19:40 UTC
**Describe the issue:**
SAML2 web app pick app dispatch gives 500 Internal Server error when SAML inbound auth config >> Artifact binding is enabled
**How to reproduce:**
1. Get wso2 IS 6.0.0 GA pack
2. Get sample (saml2-web-app-pickup-dispatch.com.war) from https://github.com/wso2/samples-is/releases/tag/v4.5.2
3. Register a SAML SP and enable SAML2 Artifact binding from UI
4. Access http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/
![Screenshot from 2022-11-30 01-05-15](https://user-images.githubusercontent.com/31848014/204631008-20ee2d5c-edf6-4037-8b67-1160664efc9a.png)
![Screenshot from 2022-11-30 01-05-54](https://user-images.githubusercontent.com/31848014/204631053-2ee537e0-fcec-4fa0-b289-d2d191547d5b.png)

Getting 500 error from sample app
No error printed in IS backend
![Screenshot from 2022-11-30 01-06-42](https://user-images.githubusercontent.com/31848014/204631136-575c1151-f84e-4abb-977f-5320815eec2e.png)

Disable the enabled SAML2 Artifact binding config and access http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/. Was able to successfully login to the sample without enabling this config

Attaching screen recording
[screen-capture.webm](https://user-images.githubusercontent.com/31848014/204631589-346c0a5a-3f67-4993-b0a5-ea8ab68c6b45.webm)

**Env**
IS 6.0.0 GA
Tomcat 9.0.1
openjdk version "11.0.17" 2022-10-18
Ubuntu 22.04

**Comment by UdeshAthukorala** [comment] 2024-01-18 03:21
Duplicate of https://github.com/wso2/product-is/issues/18873

**Comment by isharak** [comment] 2024-11-07 05:12
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-07 05:12 UTC
Labels: Priority/High, Severity/Critical, Type/Bug, QA-Reported, IceBox
