### ISSUE TITLE
SCIM User pagination doesn't function correctly

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9957] opened 2020-10-19 14:37 UTC
**Describe the issue:**
SCIM user pagination doesn't function as expected.

**How to reproduce:**

1. Create 7 new users. There will be 8 total users in the user store including admin.
2. paginate the users such that one page gets 3 users.
3. REQUEST: `{{base_url}}/scim2/Users?count={count}&startIndex={startIndex}&attributes=username`

**startIndex = 1, count = 3 --> return user 1, 2 ,3**

![page1](https://user-images.githubusercontent.com/25483865/96464862-f5c05c80-1245-11eb-9f2e-ae8cb0a80033.png)

**startIndex = 4, count = 3 --> return user 2, 3, 4**

![page2](https://user-images.githubusercontent.com/25483865/96464878-f822b680-1245-11eb-9d22-290deaa50a1d.png)

**startIndex = 7, count = 3 --> return user 5, 6, 7**

![oage3](https://user-images.githubusercontent.com/25483865/96464965-0e307700-1246-11eb-844c-3fa19d8bb610.png)

**startIndex = 10, count = 3 --> return user 8**

![page4](https://user-images.githubusercontent.com/25483865/96465065-2b654580-1246-11eb-90e2-ca147861d9e8.png)

**Expected behavior:**
**startIndex = 1, count = 3 --> return user 1, 2, 3**
**startIndex = 4, count = 3 --> return user 4, 5, 6**
**startIndex = 1, count = 3 --> return user 7, 8**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta 3 snapshot
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Comment by nilasini** [comment] 2020-11-06 05:01
The issue is not reproducible with 5.11.0-beta5 pack hence closing the issue.
![4](https://user-images.githubusercontent.com/20336761/98328182-1f85cb80-201b-11eb-9718-d06453c98706.png)
![3](https://user-images.githubusercontent.com/20336761/98328189-214f8f00-201b-11eb-8536-97aea3726d31.png)
![2](https://user-images.githubusercontent.com/20336761/98328193-2280bc00-201b-11eb-9711-d5201d3fc17e.png)
![1](https://user-images.githubusercontent.com/20336761/98328196-23195280-201b-11eb-9ba6-6afad4ab4262.png)

**Closed by nilasini** 2020-11-06 05:01 UTC
Labels: Priority/High, Severity/Critical, bug
