### ISSUE TITLE
User claims not returned with ID token for a user in the suborganization

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17725] opened 2023-11-10 03:19 UTC
**Describe the issue:**

An ID token retrieved through the Authorization Code grant type for a suborganization user does not contain the requested user claims.

**How to reproduce:**

1. Create a suborganization.
2. Create a user in the suborganization. Set first name, last name and email.
3. Switch to the primary organization.
4. Create a standard-based application and share it with the suborganization.
5. Change the access token type to JWT.
6. Mark first name, last name, email as requested attributes in the user attributes section. 
7. Invoke the authorization code flow with scopes `openid profile email` and retrieve the ID token for the suborganization user.
8. Decode the ID token and verify whether the requested user claims are returned.

**Expected behavior:**

The ID token should contain the requested user claims if they have been set for the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Kanapriya** [comment] 2023-11-17 13:07
The requested user attributes are resolved and added to the id-token. Here the issue is the user is not prompted with the consent page even the consent page are not skipped. 
This issue will be fixed with this PR - https://github.com/wso2-extensions/identity-organization-management/pull/298

**Closed** 2023-11-18 04:53 UTC
Labels: bug, Affected/7.0.0-Alpha, Component/B2B
