### ISSUE TITLE
Error adding sub-organization at Sub-Org Level

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19111] opened 2024-01-23 03:28 UTC
**Describe the issue:**

An error occurs when adding a sub-organization at the sub-organization level.

```
[2024-01-23 08:45:03,908] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} - Tenant 4 is not initialized correctly. Hence initializing the tenant registry
[2024-01-23 08:45:03,923] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at configregistry in 0ms
[2024-01-23 08:45:03,923] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at govregistry in 1ms
[2024-01-23 08:45:03,938] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at configregistry in 0ms
[2024-01-23 08:45:03,938] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at govregistry in 1ms
[2024-01-23 08:45:05,575] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0]  INFO {org.wso2.carbon.tenant.mgt.services.TenantMgtImpl} - Added the tenant '9a0e0877-880f-49ca-8b50-a5724c132064 [4]' by 'admin'
[2024-01-23 08:45:05,652] [2ac52dd9-dd93-4df0-ad3b-47a389c10ac0] ERROR {org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService} - errorCode: ORG-65090 | message: null org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Error while firing the events
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:162)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.preDeleteOrganization(OrganizationManagerListenerImpl.java:88)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.deleteOrganization(OrganizationManagerImpl.java:352)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.addOrganization(OrganizationManagerImpl.java:177)
	at org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService.addOrganization(OrganizationManagementService.java:237)
	at org.wso2.carbon.identity.api.server.organization.management.v1.impl.OrganizationsApiServiceImpl.organizationPost(OrganizationsApiServiceImpl.java:119)
	at org.wso2.carbon.identity.api.server.organization.management.v1.OrganizationsApi.organizationPost(OrganizationsApi.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:173)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.wso2.carbon.identity.event.IdentityEventException: An error occurred while retrieving main applications of fragment applications configured for organization with ID: 9a0e0877-880f-49ca-8b50-a5724c132064
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:89)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:156)
	... 62 more
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while getting applications from DB with filter: *
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationBasicInfo(ApplicationDAOImpl.java:3778)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getApplicationBasicInfo(CacheBackedApplicationDAO.java:256)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationBasicInfo(ApplicationManagementServiceImpl.java:338)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getAllApplicationBasicInfo(ApplicationManagementServiceImpl.java:302)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleMainApplicationUpdateForPreDeleteOrganization(OrganizationCreationHandler.java:178)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:87)
	... 64 more
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:507)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy6/jdk.proxy6.$Proxy54.executeQuery(Unknown Source)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationBasicInfo(ApplicationDAOImpl.java:3768)
	... 69 more
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 179
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:507)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy6/jdk.proxy6.$Proxy54.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeQuery(NamedPreparedStatement.java:260)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.fetchSingleRecord(NamedJdbcTemplate.java:192)
	at org.wso2.carbon.identity.organization.management.application.dao.impl.OrgApplicationMgtDAOImpl.getSharedApplication(OrgApplicationMgtDAOImpl.java:116)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.addSharedApplicationsToOrganization(OrganizationCreationHandler.java:120)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:76)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:156)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.postAddOrganization(OrganizationManagerListenerImpl.java:59)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.addOrganization(OrganizationManagerImpl.java:174)
	... 59 more

```

**How to reproduce:**
1. Log in to the console using the root organization credentials.
2. Create a sub-organization and switch to it.
3. Within the sub-organization, create another sub-organization at that level.

**Expected behavior:**
No error should be appear and sub organization should be created. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment] 2024-01-23 04:01
Duplicate of https://github.com/wso2/product-is/issues/19096. hence closing this issue

**Closed by dewniMW** 2024-01-23 04:01 UTC
Labels: Priority/Highest, Severity/Critical, bug, QA-Reported, Component/B2B, DB/postgres, Affected/7.0.0-beta6
