### ISSUE TITLE
Error occurred when navigating to permissions tab of shared roles in organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18289] opened 2023-12-01 18:36 UTC
**Describe the issue:**
1. Log in to console
2. Create an application
3. Share it with organizations
4. Create some roles with permissions and associate them with the application
5. Create an organization
6. Switch to the organization and go to roles section
7. Click on a role
8. Go to permissions tab

`https://localhost:9443/t/carbon.super/o/api/server/v1/api-resources` API call will fail with following response:
```
{
  "traceId": "4574ca98-0f33-4730-8548-a1b75319800b",
  "code": 403,
  "description": "Operation is not permitted. You do not have permissions to make this request.",
  "message": "Forbidden"
}
```

https://github.com/wso2/product-is/assets/25483865/ea900ee6-316d-434a-a1af-a3b26fbdb4c3

We don't need to invoke this API in the organization level, because APIs are not shared to organizations.
Because the APIs are not shared, permissions are not shown in API wise categorized view

**Comment by dewniMW** [comment] 2023-12-02 01:48
Duplicate of https://github.com/wso2/product-is/issues/18235

**Closed by dewniMW** 2023-12-02 01:48 UTC
Labels: Severity/Critical, bug, frontend, Application Roles, Affected/7.0.0-beta2
