### ISSUE TITLE
Cannot gracefully logout when "opbs" cookie is not available.

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-is#5325] opened 2019-05-23 10:52 UTC
The application sends OIDC logout request to the IS, during the user logout. If the user is already logged out from one application, he will get an error saying "opbs" cookie is not available, while trying to log out from the next application. Tested this in the latest WSO2 IS 5.7.0 WUM pack (1558540486178). 

Also, enable below property in <IS_HOME>/repository/conf/identity/identity.xml
<OAuth>
<HandleAlreadyLoggedOutSessionsGracefully>true</HandleAlreadyLoggedOutSessionsGracefully>
</OAuth>

**Comment by mefarazath** [comment] 2019-05-23 20:25
Duplicate of https://github.com/wso2/product-is/issues/4118

**Comment by madurangasiriwardena** [comment] 2019-09-06 11:52
Closing since this is a duplicate.

**Closed by madurangasiriwardena** 2019-09-06 11:52 UTC
Labels: WUM
