### ISSUE TITLE
[DOC] claim configurations for OAuth Scopes are outdated

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#5234] opened 2019-05-09 21:58 UTC
In the [Service provider configuration](https://docs.wso2.com/display/IS570/Adding+and+Configuring+a+Service+Provider#AddingandConfiguringaServiceProvider-Addingaserviceprovider) document, under "Click here for details on how to configure claims", under "Click to view vital information when configuring claims for an OpenID Connect Service Provider" it still points to registry resource, whereas latest (5.7.0) has it under a different wizard.

![oidc-scope](https://user-images.githubusercontent.com/5061791/57489581-4d922000-726b-11e9-9580-2304ec8ab56f.png)

**Comment by rksk** [comment] 2019-06-03 18:06
Duplicate of https://github.com/wso2/product-is/issues/4204

**Comment by sherenewso2** [comment] 2019-06-04 08:29
Fixed the steps in 5.7.0 and 5.8.0 [1] 
[1] - https://docs.wso2.com/display/IS570/Configuring+Claims+for+a+Service+Provider

**Closed by sherenewso2** 2019-06-04 08:29 UTC
Labels: Affected/5.7.0, Priority/Highest, Severity/Major, Type/Docs
