### ISSUE TITLE
UI inconsistency in Email and SMS Config

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18196] opened 2023-11-30 04:35 UTC
**Describe the issue:**

UI inconsistency in Email & SMS Config

- When you click Email & SMS only SMS configs are there. 
- Also the config card looks different than other places. 
- Also better to remove custom part from the label as well. 

<img width="1103" alt="Screenshot 2023-11-30 at 09 52 10" src="https://github.com/wso2/product-is/assets/13478571/7c757ad4-ebf3-484a-8863-5fa82480bccc">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment] 2023-11-30 04:53
Duplicate of https://github.com/wso2/product-is/issues/18146 and https://github.com/wso2/product-is/issues/17805

**Closed by pavinduLakshan** 2023-11-30 04:53 UTC
Labels: ui, Priority/Highest, Resolution/Duplicate, Severity/Critical, bug, ux, Affected/7.0.0-beta2
