### ISSUE TITLE
Unable to proceed Federation Flow when JIT Provisioning enabled with "Prompt for password and consent" option or "Prompt for consent" option

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17408] opened 2023-10-30 11:24 UTC
**Describe the issue:**

When attempting to proceed with the Federation flow with Just-in-Time (JIT) provisioning enabled, specifically with the options "Prompt for password and consent" and "Prompt for consent," users are encountering an error: "invalid user name. Please pick a valid username." This error prevents users from successfully completing the Federation flow.

<img width="1728" alt="Screenshot 2023-10-30 at 16 56 25" src="https://github.com/wso2/product-is/assets/39120228/85bd3b3a-1643-4bc8-99ce-b8d41fed99ef">

**How to reproduce:**
Initiate the Federation flow with JIT provisioning enabled.
Select the options "Prompt for password and consent" or "Prompt for consent."

Ex: setup Google / Federated Authentication with Asgardeo

**Expected behavior:**
Users should be able to complete the Federation flow seamlessly, even with JIT provisioning 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
* Product Version: wso2is-7.0.0-alpha-SNAPSHOT
* OS: Mac -
* Database: Mysql - 8.1.0
* Userstore: JDBC
* Browse - Safari, Firefox

---

[jitissue.webm](https://github.com/wso2/product-is/assets/39120228/84f76ecb-3296-421a-850e-57dd5ba240ce)

**Comment by UdeshAthukorala** [comment] 2023-11-06 04:02
This is not reproducible with Google. This issue is only reproducible with Federated Authentication with Asgardeo.

**Comment by UdeshAthukorala** [comment] 2023-11-07 06:39
**Analysis**

When the Jit provisioning was enabled with the options "Prompt for password and consent" or "Prompt for consent" options, after the user was authenticated from the federated IDP, user was redirected to user creation page[1] to get the user consent.In this user creation page we are doing the username validation[2]. When we using asgardeo as a federated IDP, Unique identifier is returned as subject identifier(UUID) for a federated user during JIT provisioning. For federated users. if the username is not specified, we are using subject identifier as the default username for federated users[3]. So we have a UUID as the username of this federated user and username validation was failed at the user creation page since uuid is not match with our username regex pattern.

But we have configured the silent JIT provisioning we didn't encounter this issue and user provisioning happened successfully. This provisioned user even also has a UUID as the username. The reason for this behaviour is when the silent JIT provisioning was enabled user was, not redirected to the user creation page and hence the FE username validation not happened. And also when the user was creating, we are skipping the username validation for JIT provisioned users here.[4] We have done this improvement[5] purposefully for fix a similar issue occured in the jit provisioning. More details on this can be find out from here[6].



[1] https://github.com/wso2/carbon-identity-framework/blob/b2c108308182f3ba21bc2bd401da99f32e105fea/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/JITProvisioningPostAuthenticationHandler.java#L343-L352
[2] https://github.com/wso2/identity-apps/blob/344986b75d91404040d8c3c91c3a3e0abf58c7f9/identity-apps-core/apps/recovery-portal/src/main/webapp/self-registration-process.jsp#L170
[3] https://github.com/wso2/carbon-identity-framework/blob/622bf35b46c3ccf972dcb71ba558ecd2155255a3/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/step/impl/DefaultStepHandler.java#L754-L758
[4] https://github.com/wso2/carbon-identity-framework/blob/8bbdd740f4d035ab7fd6ced3523bc775eca7ce52/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java#L239
[5] https://github.com/wso2/carbon-identity-framework/pull/4011
[6] `Jit Provisioning Username Regex Validation`

**Comment by UdeshAthukorala** [comment] 2023-11-20 09:53
After having a discussion with @madurangasiriwardena decided to provide a documentation improvement to mandate username claim mapping for this scenario. Exact solution is not yet finalyzed.

**Comment by Thisara-Welmilla** [comment] 2023-12-15 02:16
Doc issue: https://github.com/wso2/product-is/issues/18594

**Comment by NilukaSripalim** [comment] 2024-02-26 09:43
This issue is reopened , can be reproduced RC5 pack as well 
Followed same steps.

[JITIssue.webm](https://github.com/wso2/product-is/assets/39120228/0246eeaa-b827-40d9-869b-415d11a26f5a)

**Comment by mpmadhavig** [comment] 2024-09-12 04:27
Closing the issue as this is not reproducible in latest IS pack.

**Closed by mpmadhavig** 2024-09-12 04:27 UTC
Labels: Priority/Highest, Severity/Critical, Type/Bug, backend, QA-Reported, Affected/7.0.0-Alpha, Provisioning, Fixed/7.0.0
