### ISSUE TITLE
Users page timeout Issue: While Retrieving Users from Configured Userstore.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17065] opened 2023-10-19 09:35 UTC
**Describe the issue:**
Encountering a timeout issue during userstore data retrieval, where the delay exceeds the short 1-minute timeout period. This results in a 'Something Went Wrong' error, impacting user experience as the system doesn't wait for the request to complete successfully.

<img width="1511" alt="Screenshot 2023-10-19 at 13 25 09" src="https://github.com/wso2/product-is/assets/41188245/cf9eaf4c-6ec1-46a4-b5e7-994702807dde">

https://github.com/wso2/product-is/assets/41188245/cd85ffb3-c86a-449e-8199-b47542c9beea

**How to reproduce:**

1. Configure a userstore with users.
2. Configure it as a secondary user store 
3. Redirect to the Users Page
4. will get a something went wrong page if the get users list request gets a longer time than 1 minute.

**Expected behavior:**
Should be handled from the UI to improve the user experience.  

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: Active Directory.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment] 2023-11-23 05:45
Ideally user listing should not take more than 1 minute. However, as I can see, UI seems to be retrieving unnecessary details like the roles while listing the users. This will add unnecessary calls to the user store which will not be used by the UI.

**Comment by ashanthamara** [comment] 2023-12-02 06:13
This issue is now not reproducing since we are not allowing to search users through all databases from the UI. Also, with this PR (https://github.com/wso2/identity-apps/pull/4804) it has excluded `roles` and `groups` attributes from the get all users API call. 

Hence closing the issue since it is not reproducing in current tested console version `2.9.36`


https://github.com/wso2/product-is/assets/75057725/55aebc4d-a32a-41f4-bd7f-610099b9f681

**Closed by ashanthamara** 2023-12-02 06:13 UTC
Labels: Priority/Low, Severity/Critical, bug
