### ISSUE TITLE
Inconsistent behavior for subject claim in JWT tokens for different grant types

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-is#9313] opened 2020-08-26 09:33 UTC
**Describe the issue:**
When the "useTenantDomainInLocalSubjectIdentifier" property is not set for the SP, the sub claim of JWT token for client credential grant will in the format of username@tenantDomain. But for the other grants (ex: password/auth code grant), the sub claim will be just the username, without the tenant domain. 

Can we get this fixed, so that even when the authenticated subject identifier is not present, instead of adding the fully qualified name with tenant domain by default, add the value at least based on the property, useTenantDomainInLocalSubjectIdentifier?

**How to reproduce:**
1. Get a JWT token for client cred grant and password grant for an oauth app belog to a tenant user.
2. Compare the sub claim

**Expected behavior:**
It is expected for both grants to issue JWT tokens with sub claim in the same format (with or without tenant domain)

**Environment information** 
IS 5.10.0
---

**Comment by rksk** [comment] 2021-12-21 12:03
This seems to be addressed with https://github.com/wso2/product-is/issues/12341

**Comment by nilasini** [comment] 2022-03-31 07:22
Couldn't reproduce the issue with wso2is-5.12.0-alpha17 pack hence closing the issue

**Closed by nilasini** 2022-03-31 07:22 UTC
Labels: bug, WUM
