### ISSUE TITLE
The user info downloaded for tenants does not have consent information

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2950] opened 2018-03-14 14:14 UTC
The user info downloaded for tenants does not have consent information. Following is a sample user info. This user has given consent to share the username.

`{"basic" : {"http://wso2.org/claims/role" : "Internal/everyone,admin", "http://wso2.org/claims/emailaddress" : "peter@abc.com", "http://wso2.org/claims/lastname" : "g", "http://wso2.org/claims/givenname" : "peter"}}`

**Comment by emswbandara** [comment] 2018-03-14 17:34
Couldn't reproduce this issue. 

Steps followed:

1. Configure travelocity for SSO with consent management in tenant domain - test.com.
2. Authenticate using tenant user giving consent to share the username.
3. user info exported via dashboard for the corresponding tenant user contains the correct consent information as shown below.

`{"consents" : [{"version" : "KI-CR-v1.1.0", "jurisdiction" : "NONE", "consentTimestamp" : 1.521047069E12, "collectionMethod" : "Web Form - Sign-in", "consentReceiptID" : "4e2ad2b5-2d65-41c4-9452-72391d7cb8ee", "publicKey" : "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs65yVJH5Lo/ntjEz9319M2AjYzrVv+pboEh0mqcFgp5HX+DITt+0U3B1gazqLzG36bBDx6PaBc4PEAzHp5kdbw82aLLRu0GdqPmx3gUx6Rd8EoiSGdKbMK+a+ubx4l0Ppffe4n9LJF4AEFemilGdQODjjDv1YskvUaI2xfdEmFR8dyI3uaxAezQmgkUc1SiSnA7EV9tcMW/agOEzLcWKThJ3p68xyuB8P7vlPDuLXwig7gOGoiCd3jMfH0YvGuT1UcGtBQSiWwxHfFTcdSgql7xLO12+jPUm7kKWm5tcvhXqADl8POWmQi16GMAcVhcy95BFAKhnAOYhKCck2JliwQIDAQAB", "language" : "us_EN", "piiPrincipalId" : "admin", "tenantDomain" : "test.com", "state" : "ACTIVE", "piiControllers" : [{"piiController" : "change-me", "contact" : "change-me", "address" : {"addressCountry" : "change-me", "addressLocality" : "change-me", "addressRegion" : "change-me", "postOfficeBoxNumber" : "change-me", "postalCode" : "change-me", "streetAddress" : "change-me"}, "email" : "change-me", "phone" : "change-me", "onBehalf" : false, "piiControllerUrl" : "change-me"}], "policyUrl" : "NONE", "services" : [{"service" : "travelocity", "tenantDomain" : "test.com", "purposes" : [{"purpose" : "DEFAULT", "purposeCategory" : ["DEFAULT"], "consentType" : "EXPLICIT", "piiCategory" : [{"piiCategory" : "http://wso2.org/claims/username", "validity" : "VALID_UNTIL:INDEFINITE"}], "primaryPurpose" : true, "termination" : "VALID_UNTIL:INDEFINITE", "thirdPartyDisclosure" : false, "thirdPartyName" : null}]}], "sensitive" : false, "spiCat" : null}], "basic" : {"http://wso2.org/claims/username" : "admin", "http://wso2.org/claims/userid" : "259e58ac-9a7f-4608-9467-841446eeeebf", "http://wso2.org/claims/created" : "2018-03-14T12:49:41Z", "http://wso2.org/claims/role" : "Internal/everyone,admin,Application/travelocity", "http://wso2.org/claims/fullname" : "admin", "http://wso2.org/claims/modified" : "2018-03-14T12:49:41", "http://wso2.org/claims/emailaddress" : "admin@wso2.com", "http://wso2.org/claims/lastname" : "test", "http://wso2.org/claims/givenname" : "test"}}`

**Comment by emswbandara** [comment] 2018-03-14 19:39
Reducing priority since this issue cannot be reproduced in the normal flow.

**Comment by dilinisg** [comment] 2018-03-15 04:49
@emswbandara - I could reproduce the same in RC2 pack as well.
**Steps to reproduce**
1. Create a tenant
2. Login to the dashboard from the tenant
3. Download user info

User info downloaded is as follows
`{"basic" : {"http://wso2.org/claims/organization" : "wso2", "http://wso2.org/claims/role" : "Internal/everyone,admin", "http://wso2.org/claims/country" : "sl", "http://wso2.org/claims/emailaddress" : "sam@ksks.com", "http://wso2.org/claims/lastname" : "k", "http://wso2.org/claims/givenname" : "sam"}}
`

If I follow the same steps for a user in the super admin domain, I get the following information.
`{"consents" : [{"version" : "KI-CR-v1.1.0", "jurisdiction" : "NONE", "consentTimestamp" : 1.521089073E12, "collectionMethod" : "Web Form - Sign-in", "consentReceiptID" : "12cd47fb-89dc-400d-99bf-f17e29f38706", "publicKey" : "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAluZFdW1ynitztkWLC6xKegbRWxky+5P0p4ShYEOkHs30QI2VCuR6Qo4Bz5rTgLBrky03W1GAVrZxuvKRGj9V9+PmjdGtau4CTXu9pLLcqnruaczoSdvBYA3lS9a7zgFU0+s6kMl2EhB+rk7gXluEep7lIOenzfl2f6IoTKa2fVgVd3YKiSGsyL4tztS70vmmX121qm0sTJdKWP4HxXyqK9neolXI9fYyHOYILVNZ69z/73OOVhkh/mvTmWZLM7GM6sApmyLX6OXUp8z0pkY+vT/9+zRxxQs7GurC4/C1nK3rI/0ySUgGEafO1atNjYmlFN+M3tZX6nEcA6g94IavyQIDAQAB", "language" : "us_EN", "piiPrincipalId" : "test", "tenantDomain" : "carbon.super", "state" : "ACTIVE", "piiControllers" : [{"piiController" : "change-me", "contact" : "change-me", "address" : {"addressCountry" : "change-me", "addressLocality" : "change-me", "addressRegion" : "change-me", "postOfficeBoxNumber" : "change-me", "postalCode" : "change-me", "streetAddress" : "change-me"}, "email" : "change-me", "phone" : "change-me", "onBehalf" : false, "piiControllerUrl" : "change-me"}], "policyUrl" : "NONE", "services" : [{"service" : "wso2_sp_dashboard", "tenantDomain" : "carbon.super", "purposes" : [{"purpose" : "DEFAULT", "purposeCategory" : ["DEFAULT"], "consentType" : "EXPLICIT", "piiCategory" : [{"piiCategory" : "http://wso2.org/claims/username", "validity" : "VALID_UNTIL:INDEFINITE"}], "primaryPurpose" : true, "termination" : "VALID_UNTIL:INDEFINITE", "thirdPartyDisclosure" : false, "thirdPartyName" : null}]}], "sensitive" : false, "spiCat" : null}], "basic" : {"http://wso2.org/claims/organization" : "wso2", "http://wso2.org/claims/role" : "Internal/everyone,admin", "http://wso2.org/claims/country" : "uk", "http://wso2.org/claims/emailaddress" : "test@gmail.com", "http://wso2.org/claims/lastname" : "test", "http://wso2.org/claims/givenname" : "test"}}`

**Note**: I haven't done any SSO related scenarios with these users.

Can you please try again with the steps provided and check again? Sorry for not providing the steps earlier.

**Comment by isharak** [comment] 2021-04-09 11:42
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 11:42 UTC
Labels: Affected/5.5.0-RC1, Priority/Normal, bug
