### ISSUE TITLE
The Visual Editor tab cannot be accessed via the application Sign in methods.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17692] opened 2023-11-09 05:42 UTC
**Describe the issue:**
From application sign-in method editor cannot navigate to the visual Editor tab and keeps being redirected to the classic editor.

https://github.com/wso2/product-is/assets/41188245/fd4f2c3f-a607-4643-84af-4ef382739bdc

**How to reproduce:**

1. Log in to the console.
2. create an application.
3. Navigate to the `Sign-in Method` tab 
4. try to navigate to the visual editor tab.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment] 2023-11-09 05:49
Duplicate of https://github.com/wso2/product-is/issues/17643

**Closed** 2023-11-09 05:51 UTC
Labels: ui, Priority/Highest, Severity/Critical, bug, Affected/7.0.0-Alpha
