### ISSUE TITLE
SCIM2 User Listing with Primary UniqueIDJDBC Userstore for a non existing domain will list users under Primary domain

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7387] opened 2020-01-27 08:56 UTC
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to uniqueidjdbc userstore
[user_store]
type = "database_unique_id"
[user_store.properties]
SCIMEnabled= true
2. Add a User as kim for the primary userstore

3. Try to list users with a non existing domain in the system.

curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?domain=tyuiji'

**Response**
`{"totalResults":2,"startIndex":1,"itemsPerPage":2,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"work","value":"kim_j@wso2222288.com"},{"type":"home","value":"kim.jackkkkkkkmmm@gmail.com"}],"meta":{"location":"https://localhost:9443/scim2/Users/1988ceb0-9461-4d3c-afe4-351275173670","lastModified":"2020-01-27T06:54:34.440Z","resourceType":"User"},"name":{"givenName":"kim","familyName":"jackson"},"id":"1988ceb0-9461-4d3c-afe4-351275173670","userName":"admin"},{"emails":[{"type":"work","value":"kim_j@wso2.com"},{"type":"home","value":"kim.jackson@gmail.com"}],"meta":{"created":"2020-01-27T08:25:13.921Z","location":"https://localhost:9443/scim2/Users/4926e283-3a18-4c62-bb58-eb47980e4e65","lastModified":"2020-01-27T08:25:13.921Z","resourceType":"User"},"name":{"givenName":"kim","familyName":"jackson"},"id":"4926e283-3a18-4c62-bb58-eb47980e4e65","userName":"kim"}]}
`
The domain sent in the request is a non existing domain. But it will list all the users under Primary domain 
This is working properly as expected in Unique ID Read Only Ldap

**Comment by ShanikaWickramasinghe** [comment] 2020-02-03 06:38
Observing the same behaviour when try to list the users in a non existing domain in the tenant flow

`curl -v -k --user admin@wso2.com:admin 'https://localhost:9443/t/wso2.com/scim2/Users?domain=huji' -i `

**Response**

`{"totalResults":2,"startIndex":1,"itemsPerPage":2,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":["shanikanishadhi1992@gmail.com"],"meta":{"created":"2020-02-03T05:00:50.859Z","location":"https://localhost:9443/t/wso2.com/scim2/Users/fd511b4b-befb-461f-8f14-7478f812fb4b","lastModified":"2020-02-03T05:00:50.860Z","resourceType":"User"},"name":{"givenName":"shanika","familyName":"nishadhi"},"id":"fd511b4b-befb-461f-8f14-7478f812fb4b","userName":"admin"},{"meta":{"created":"2020-02-03T06:02:20.247Z","location":"https://localhost:9443/t/wso2.com/scim2/Users/44a63aab-9245-4069-b5dd-7e2a9b789a96","lastModified":"2020-02-03T06:02:20.247Z","resourceType":"User"},"id":"44a63aab-9245-4069-b5dd-7e2a9b789a96","userName":"kimtenant"}]}`

**Comment by IsuraD** [comment] 2020-09-10 23:37
Duplicate of https://github.com/wso2/product-is/issues/7408

**Closed by IsuraD** 2020-09-10 23:37 UTC
Labels: Priority/Highest, Severity/Critical
