### ISSUE TITLE
Service Provider (SaaS) doesn't work across tenants

### ISSUE THREAD

**Issue by giovanni-depalma** [wso2/product-is#10440] opened 2020-11-10 15:01 UTC
Service Provider created with checkbox (Saas) inside "carbon.super" doesn't work across tenants (with versione 5.11-beta5). Instead it works correctly with IS 5.10

**How to reproduce:**
- Login as "carbon.super" admin
- Create Service Provider with Saas enabled (with OAuth2-OpenID Connect Single-Sign-On)
- Create Tenant t1
- Create Sample application to try Single-Sign-on

**Expected behavior:**
Ability to log in with user of "carbon.super" and of tenant t1.
Instead it is not possible to log in with user of tenant (I get error 401)

**Environment information** 
 - Product Version: IS 5.11.0-beta5
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [JDBC]

---

### Optional Fields

**Suggested labels:**
Affected/5.11.0-beta

**Comment by janakamarasena** [comment] 2020-11-11 14:20
I was able to login successfully when using the tenant qualified username.

**Comment by janakamarasena** [comment] 2020-11-11 14:20
Closing the issue as cannot reproduce. Please reopen if needed.

**Comment by giannaccio** [comment] 2020-11-12 07:24
I'm sorry for for inaccurate steps to reproduce.

How to reproduce:
- Login as "carbon.super" admin
- Create Service Provider with Saas enabled (with OAuth2-OpenID Connect Single-Sign-On), and choose as Token Issuer the option JWT
![image](https://user-images.githubusercontent.com/24352928/98908161-4bdc9480-24c0-11eb-9146-ec9f2e2fa71f.png)
- Create Tenant t1
- Create Sample application to try Single-Sign-on

**Comment by giannaccio** [comment] 2020-11-12 08:37
@janakamarasena I don't have the permissions to reopen the bug (I don't know if it's better open another issue)

**Comment by janakamarasena** [comment] 2020-11-13 05:30
Are you trying to SSO or generate a token from a saas app?

**Comment by giannaccio** [comment] 2020-11-13 07:38
I'm using Spring Coud Gateway and after login process (with tenant user) I have this log:

2020-11-13 07:35:14.584 DEBUG 53 --- [or-http-epoll-4] o.s.w.r.f.client.ExchangeFunctions       : [42e504bb] HTTP GET https://dev-local:443/oauth2/userinfo
2020-11-13 07:35:14.599 DEBUG 53 --- [or-http-epoll-4] o.s.w.r.f.client.ExchangeFunctions       : [42e504bb] Response 401 UNAUTHORIZED

**Comment by janakamarasena** [comment] 2020-11-13 09:05
I am not familiar with the Spring Cloud Gateway. But with logs you have added it looks like you are trying ti access the userinfo endpoint of the super.tenant. 
Since your user is in a tenant(t1) the userinfo endpoint that is called should also be the tenants (t1) userinfo endpoint (https://dev-local:443/t/t1/oauth2/userinfo) 
I tested in that way and it works.

Adding the tenants userinfo enpoint should work. If this doesn't work for you can you attach the whole DEBUG log related to the login process from the gateway and also the [har log](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) related to your browser interactions so its possible to get a better understanding on what's happening.

If your trying to have single userinfo endpoint for all tenants, OOTB this is not possible AFAIK (@mefarazath please correct me if am wrong).
You could either do a customisation in the Identity Server to handle this internally. Or since your using JWTs you can get the user's tenant domain by extracting it from the sub claim of the jwt and the using it to construct the userinfo endpoint via an extension to the gateway if such extensions are possible at the gateway. 
To append the tenant domain to the sub claim you need to tick the "Use tenant domain in local subject identifier" checkbox under "Local & Outbound Authentication Configuration" inside the relevant saas SP configurations.

**Comment by giannaccio** [comment] 2020-11-13 10:17
I tried to use the tenants (t1) userinfo endpoint and the log the log has improved but the login process did not work.
I'll prepare a better scenario (whole DEBUG, har log and a github project of spring boot gateway to test)

I focus that single userinfo endpoint for all tenants works with 5.10, so appear me a breaking changes.
Moreover the reponse of url https://dev-local/t1/oauth2/token/.well-known/openid-configuration contains only the key "jwks_uri" tenant-based

end_session_endpoint: "https://dev-local:443/oidc/logout",
revocation_endpoint: "https://dev-local:443/oauth2/revoke",
userinfo_endpoint: "https://dev-local:443/oauth2/userinfo",
code_challenge_methods_supported: [
"S256",
"plain"
],
jwks_uri: "https://dev-local:443/t1/oauth2/jwks",

**Comment by giannaccio** [comment] 2020-11-15 16:14
Hi,
I created this project 
https://github.com/giannaccio/spring-gateway-wso2
where it's possibile trying spring-cloud-config integrated with wso2-is
(I hope README it's clear)

Debugging login process I understand the following points:
- With Token Issuer Default, it's possible login with
`
issuer-uri: ${provider.host}/oauth2/token
`
or
`
token-uri: ${provider.host}/oauth2/token
authorization-uri: ${provider.host}/oauth2/authorize
user-info-uri: ${provider.host}/oauth2/userinfo
jwk-set-uri: ${provider.host}/oauth2/jwks
`

Instead, with Token Issuer JWT, using 
`
token-uri: ${provider.host}/oauth2/token
authorization-uri: ${provider.host}/oauth2/authorize
user-info-uri: ${provider.host}/oauth2/userinfo
jwk-set-uri: ${provider.host}/oauth2/jwks
`

wso2is log this error

`
[2020-11-15 15:52:33,326] [a000f2e2-dcf6-43f3-8ae6-3659fbd84c32] DEBUG {org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint} - Error while building user info response. org.wso2.carbon.identity.oauth.user.UserInfoEndpointException: Access token validation failed
        at org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInfoISAccessTokenValidator.validateToken(UserInfoISAccessTokenValidator.java:63)
        at org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint.getUserClaims(OpenIDConnectUserEndpoint.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
`

Settings 

`
token-uri: ${provider.host}/oauth2/token
authorization-uri: ${provider.host}/oauth2/authorize
user-info-uri: ${provider.host}/t/test.com/oauth2/userinfo
jwk-set-uri: ${provider.host}/oauth2/jwks
user-name-attribute: sub
`

it's work but it's a strange configuration and different from wsois-5.10

**Comment by giannaccio** [comment] 2020-11-17 06:52
@janakamarasena @mefarazath  let me know if you need more details.

**Comment by giovanni-depalma** [comment] 2021-02-10 08:29
Please let me know if you need more details, or in generale the status of the issue.

**Comment by isharak** [comment] 2024-11-06 05:07
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Closed by isharak** 2024-11-06 05:07 UTC
Labels: Resolution/Cannot Reproduce, Type/Bug, IceBox
