### ISSUE TITLE
Unit tests fail for components with translation implementation

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10047] opened 2020-10-23 09:04 UTC
**Describe the issue:**
When writing unit tests for components which has `useTranslation` to have i18n compatibility, the unit tests fail.   

**How to reproduce:**
1. Write a unit test to test a component which consist a translation.
2. Run the unit test.

**Expected behavior:**
If no error in component implementation the test should pass

**Comment by jeradrutnam** [comment] 2020-11-16 09:06
Duplicate of: https://github.com/wso2/product-is/issues/10393

**Closed by jeradrutnam** 2020-11-16 09:06 UTC
Labels: bug, ux
