### ISSUE TITLE
Organization name is not populated properly in user onbording summary section for organization users

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18511] opened 2023-12-08 06:35 UTC
**Describe the issue:**
1. Login to console
2. Create an organization
3. Switch to the created organization
4. Try user creation by setting a password by admin. The shown summary will not have the organization name
<img width="767" alt="Screenshot 2023-12-08 at 11 53 55" src="https://github.com/wso2/product-is/assets/25483865/a6554ca2-d190-43df-95fe-282e43f58b49">

See the following image to see how it works in the super tenant. Seems we are showing the tenant domain here. Better to use the organization Display name, and if the display name is not set use the organization name.
<img width="771" alt="Screenshot 2023-12-08 at 11 52 49" src="https://github.com/wso2/product-is/assets/25483865/e1a33904-0820-4483-a50e-2284f9d8290c">

**Comment by NipuniBhagya** [comment] 2023-12-12 11:35
Verified the flow in the latest wso2is-7.0.0-beta4-SNAPSHOT pack and the issue is not reproducible.

<img width="1726" alt="image" src="https://github.com/wso2/product-is/assets/30111554/14d2595e-96e6-465a-a4d9-827f04b85c69">

**Comment by AnuradhaSK** [comment] 2023-12-13 05:47
Seems you have tested in another tenant.
The issue is reproduing in organizations

**Comment by dasuni-30** [comment] 2023-12-14 11:02
### Fixed in the new pack

<img width="610" alt="Screenshot 2023-12-14 at 16 31 38" src="https://github.com/wso2/product-is/assets/27746285/de1fc678-028c-4ed3-a755-df37ae74f264">

**Closed by dasuni-30** 2023-12-14 11:02 UTC
Labels: ui, Priority/High, Severity/Critical, bug, frontend, pr-sent, Affected/7.0.0-beta2
