### ISSUE TITLE
OIDC logout is not properly working with a federated IDP

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#4033] opened 2018-11-26 08:41 UTC
Follow documentation https://docs.wso2.com/display/IS570/Session+Management+with+Playground.
But instead of Local IDP, configure a federated IDP  for the both palyground2 and playground3 apps.
Then the OIDC logout is not happening as expected.

**Comment by hauntingEcho** [comment] 2019-07-25 19:57
possibly caused by #5958

**Comment by isharak** [comment] 2021-04-09 10:07
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 10:07 UTC
Labels: Affected/5.6.0
