### ISSUE TITLE
Unify the behaviour of OTP connectors 

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#15525] opened 2023-02-20 04:36 UTC
**Is your suggestion related to an experience ? Please describe.**

1. EmailOTP Authenticator returns generic error "authentication.fail.message" for expired OTPs except in case user account is locked whereas SMSOTP authenticator checks and returns "token.expired" for expired OTPs.

In this case it's better we can decide what is the correct error message that we need to display to the customer and proceed with that.

3. In case the user's account is locked, the SMSOTP authenticator prompts to enter the OTP and after the OTP is submitted only, the error message "User's account is locked. Please try again later" will be displayed, while the EmailOTP shows the error message "user account is locked. please try again later" without prompting to enter the OTP.

In this case we need to define what is the correct flow that we need to follow and proceed with that.

**Describe the improvement**
- Improve the error message with the common flows

**Comment by melanisilva** [comment] 2023-07-26 10:52
Closing this since the issue is fixed, Fell free to reopen if there are any concerns.

**Closed** 2023-07-26 10:52 UTC
Labels: improvement, Priority/Normal
