### ISSUE TITLE
New Application button missing in console after organization switch

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#17953] opened 2023-11-20 09:17 UTC
**Describe the issue:**
The "New Application" button is missing after switching to a sub-organization and returning to the super organization.

**How to reproduce:**
Switch to a sub-org and return to the super org.

**Environment information**
 - Product Version: IS 7.0 Alpha

**Comment by dewniMW** [comment] 2023-11-22 08:03
The issue is not reproducing in the latest pack. Hence closing this issue.

https://github.com/wso2/product-is/assets/24982871/603bc0c7-26a5-4073-8f62-28ce92c374fb

**Closed by dewniMW** 2023-11-22 08:03 UTC
Labels: bug, Affected/7.0.0-Alpha
