### ISSUE TITLE
'Share Application' only works with first immediate child/sub organization

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14438] opened 2022-07-28 11:36 UTC
**Describe the issue:**
Please refer to the screencast

https://user-images.githubusercontent.com/13362482/181495403-9185270e-615c-4bc2-976a-58d0cd92e1ff.mov

**How to reproduce:**

- Login to console as an admin user
- Create a sub-organization and create child organizations too
- Create an application and 'Share Application' among the created sub and its child organization
- Switch to the child organization and check whether the shared application (fragment) available in the child organization

**Expected behavior:**
Application sharing should work properly even for child organizations.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment] 2022-07-28 14:07
duplicate of https://github.com/wso2/product-is/issues/14196. hence closing the issue

**Closed by dewniMW** 2022-07-28 14:07 UTC
Labels: Priority/Highest, Severity/Critical, bug, QA-Reported, IS-6.0.0-Test-Hackathon, Organization Management
