### ISSUE TITLE
When creating a custom attribute it indicates no external mapping is done  , even though the SCIM mapping is created correctly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16955] opened 2023-10-14 05:14 UTC
**Describe the issue:**

When creating a custom attribute it indicates no external mapping is done, even though the mapping is created correctly. Due to this issue, the users can't enable attributes as mandatory because that option is disabled from the UI.

**Note: We dont get this issue when trying from the same flow from management console**

<img width="1222" alt="Screenshot 2023-10-14 at 10 07 13" src="https://github.com/wso2/product-is/assets/40081059/f4b07ebb-74d7-4bf2-b08c-ada38f4aff28">

**How to reproduce:**

1.Login into the console
2.Go to the attributes section
3.Create a new custom attribute

Here i have created a custom attribute  as below
<img width="1222" alt="Screenshot 2023-10-14 at 10 07 13" src="https://github.com/wso2/product-is/assets/40081059/f4c4ffe8-d94d-4673-b3d6-3e0cd21b3215">

when you go to the relevant SCIM mapping of this attribute we can see that its already created , even though its indicated that the external mapping isnt done properly.
<img width="1261" alt="Screenshot 2023-10-14 at 10 43 44" src="https://github.com/wso2/product-is/assets/40081059/072701bd-c149-4cfc-8585-619982657db2">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment] 2023-10-14 05:23
Duplicate of https://github.com/wso2/product-is/issues/16902

**Comment by asekawa** [comment] 2023-10-14 06:34
when we try to create the attribute via API also , it gives the same result 
curl -X 'POST' \
  'https://localhost:9443/t/carbon.super/api/server/v1/claim-dialects/local/claims' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "claimURI": "http://wso2.org/claims/username",
  "description": "Some description about the claim.",
  "displayOrder": 10,
  "displayName": "Username",
  "readOnly": true,
  "regEx": "^([a-zA-Z)$",
  "required": true,
  "supportedByDefault": true,
  "attributeMapping": [
    {
      "mappedAttribute": "username",
      "userstore": "SECONDARY"
    }
  ],
  "properties": [
    {
      "key": "string",
      "value": "string"
    }
  ]
}'

**Comment by madurangasiriwardena** [comment] 2023-11-22 08:47
This is resolved in the latest distribution. Verified with Beta.
<img width="723" alt="image" src="https://github.com/wso2/product-is/assets/1332991/6bf31c20-cff2-4ea0-ac95-4040c6c945b3">

**Closed by madurangasiriwardena** 2023-11-22 08:47 UTC
Labels: Priority/Highest, Severity/Blocker, bug, QA-Reported
