### ISSUE TITLE
Error when executing Identity Database Script against MySQL 8

### ISSUE THREAD

**Issue by darsham3** [wso2/product-is#9618] opened 2020-09-30 06:01 UTC
**Description:**

Following syntax error is thrown when executing identity database script against MySQL 8.

``` 
ERROR 1089 (HY000) at line 1059: Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
```

Error is thrown when executing following SQL (while creating the constraint):

```	
CREATE TABLE IF NOT EXISTS IDN_CONFIG_ATTRIBUTE (	
	    ID VARCHAR(255) NOT NULL,	
	    RESOURCE_ID VARCHAR(255) NOT NULL,	
	    ATTR_KEY VARCHAR(255) NOT NULL,	
	    ATTR_VALUE VARCHAR(1023) NULL,	
	    PRIMARY KEY (ID),	
	    CONSTRAINT RESOURCE_KEY_VAL_CONSTRAINT UNIQUE (RESOURCE_ID(64), ATTR_KEY(703))
	)ENGINE INNODB;
```

The issue is resolved if the script is modified as follows:

```
 CREATE TABLE IF NOT EXISTS IDN_CONFIG_ATTRIBUTE (	
	    ID VARCHAR(255) NOT NULL,	
	    RESOURCE_ID VARCHAR(255) NOT NULL,	
	    ATTR_KEY VARCHAR(255) NOT NULL,	
	    ATTR_VALUE VARCHAR(1023) NULL,	
	    PRIMARY KEY (ID),	
	    CONSTRAINT RESOURCE_KEY_VAL_CONSTRAINT UNIQUE (RESOURCE_ID, ATTR_KEY)
	)ENGINE INNODB;

```

What would be recommended way to resolve this issue? Appreciate any input on this.

**Affected Product Version:**
Wum time stamp = 1600491803101;
IS version = 5.10.0

**OS, DB, other environment details and versions:**    
MySQL8

**Steps to reproduce:**

- Create database with latin1 charset
- Execute the script resides in <IS-HOME>/dbscript/identity/mysql.sql

**Related Issues:**

**Comment by mefarazath** [comment] 2020-09-30 09:01
Duplicate of https://github.com/wso2/product-is/issues/9139

**Closed** 2020-09-30 09:06 UTC
