### ISSUE TITLE
"Enable Attribute Profile" doesn't seem to update when Import/Export Service provider

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#5233] opened 2019-05-09 20:46 UTC
Version: 5.7.0-WUM
Created a SP with "Enable Attribute Profile" enabled.
Exported and Imported to a different instance.
"Enable Attribute Profile" is not checked in the second.

**Comment by madurangasiriwardena** [comment] 2020-03-04 11:44
Duplicate of https://github.com/wso2/product-is/issues/4420

**Closed by madurangasiriwardena** 2020-03-04 11:44 UTC
Labels: Affected/5.7.0, Priority/Normal
