### ISSUE TITLE
New users are unable to login to the IDP

### ISSUE THREAD

**Issue by lathlk** [wso2/product-is#13018] opened 2022-01-22 08:04 UTC
**Describe the issue:**
When we configure an external IDP through IS-KM 5.10.0 for SSO purposes and enable the JIT provisioning[1], observed an issue when it comes to the new user login attempts where stuck in an authentication loop from ISKM to IDP as in the attached GIF(loop.gif).

![loop](https://user-images.githubusercontent.com/20392682/150630065-f94b5306-cf09-4289-8e51-7fa69a7b570e.gif)

This is observed after updating the IS-KM product to the latest.

**How to reproduce:**
1. Configuring External IDP through Identity Server for SSO[1].
2. Enable JIT provisioning.
3. Engage the **identityUserMetadataMgtHandler** event handler.
`[[event_handler]]
name= "identityUserMetadataMgtHandler" 
subscriptions =["POST_AUTHENTICATION", "POST_UPDATE_CREDENTIAL", "POST_UPDATE_CREDENTIAL_BY_ADMIN"] `
4. Try to log in as a non-provisioned user.

**Expected behavior:**
Non-provisioned users(new users) should be able to login

**Environment information:**
 - Product Version: IS-KM-5.10.0
 - OS: Windows, Linux, Mac
 - Database: MySQL, H2
 - Userstore: LDAP, JDBC

[1] [https://apim.docs.wso2.com/en/3.1.0/develop/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso/#configuring-external-idp-through-identity-server-for-sso](https://apim.docs.wso2.com/en/3.1.0/develop/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso/#configuring-external-idp-through-identity-server-for-sso)

**Suggested labels:**
is-km-5.10.0

**Comment by rajithacharith** [comment] 2022-01-28 04:20
The proposed solution is to backport these public fixes - https://github.com/wso2/carbon-identity-framework/pull/3598 , https://github.com/wso2/carbon-identity-framework/pull/3694

With the solution we identified the following behavior change in the login flow of account locked provisioned users. 

How to reproduce
* Configure a federated IdP with JIT provisioning.
* Log in to a service provider with a user non-existing in IS.
* Logout from the service provider.
* Go to the user's profile and make sure the user has been created.
* Lock the user account.
* Try to log in again to the service provider.

Before the above mentioned fix 
* Login attempt redirects to the home page of the service provider. 
* ![Dispatch Login](https://user-images.githubusercontent.com/32898873/151486635-208b8bff-1a9b-4453-a8f6-27d6613eae23.gif)

After the fix
* Login attempt will redirect to IS retry page (https://localhost:9443/authenticationendpoint/retry.do?sp=ddd&authFailure=true&authFailureMsg=error.user.account.disabled&errorCode=17004)
* ![Dispatch Login2](https://user-images.githubusercontent.com/32898873/151486722-47d76354-a1eb-4c46-a79a-3ad55bc62cdd.gif)

**Comment by nilasini** [comment] 2022-02-24 05:16
@rajithacharith Since the issue is already fixed in public can we close this issue? Is there any further fix needs to be done for public?

**Comment by rajithacharith** [comment] 2022-02-24 05:36
> @rajithacharith Since the issue is already fixed in public can we close this issue? Is there any further fix needs to be done for public?

Closed the issue, The fix is already in public and backported for 5.10

**Closed** 2022-02-24 05:36 UTC
Labels: bug, WUM
