### ISSUE TITLE
User creation through console application shows ask password option(email option) even if the feature is not enabled

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#9511] opened 2020-09-21 12:07 UTC
**Describe the issue:**
User creation through console application shows "ask password option"(email option) even if the feature is not enabled.

**Expected behavior:**
`[identity_mgt.user_onboarding]
ask_password_from_user= true`

if the above configuration is true we need to show the ask password option during the user creation. Otherwise only the user creation with password should be there.

**Comment by IsuraD** [comment] 2020-09-22 07:41
Duplicate of https://github.com/wso2/product-is/issues/9512

**Closed by IsuraD** 2020-09-22 07:41 UTC
Labels: Severity/Critical, bug, console, ux
