### ISSUE TITLE
Error - when try to "Recover Username"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7121] opened 2019-12-17 11:24 UTC
Affected version: is-5.10.0 m9
Priority: High
Severity: Critical
Type/ Bug

**Issue 1: Unable to recover username.**

Steps to Reproduce

Follow the doc [1] user name recovery with dashboard

Set the deployment.toml to send the email
Resident IDP > Account management policies > Account Recovery > Enable Username Recovery checkbox and the Enable Notification Internally Management

Add a user for a primary user store in **super tenant mode** and set a email in the users profile.

Go for user portal login page and click on Forgot User name

Fill the First name , Last name and email address without filling the tenant domain and click on submit.

**issue 2: There should be proper error message if it is an incorrect callback URL, error message should not display class name details.**

Screenshot attached: 

![image](https://user-images.githubusercontent.com/39120228/70991609-ce60a680-20ed-11ea-9f8b-bc9a8f328c03.png)

**Comment by AnuradhaSK** [comment] 2020-02-21 07:40
The issue can't be reproduced in is-5.10.0-Beta3

**Comment by IsuraD** [comment] 2020-02-25 12:09
Close the issue since it is not reproducible.

**Closed by IsuraD** 2020-02-25 12:09 UTC
Labels: Priority/High, Severity/Critical, Type/Bug
