### ISSUE TITLE
Redirect the user to the application  once email confirmation is completed 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#12804] opened 2021-11-22 13:00 UTC
**How to reproduce:**
- Enable self registration
- Add an access URL for a app
- Self-register 
- Click the confirmation link

**Expected behavior:**

- *Better to have an implementation to store the application Access URL against the confirmation code and retrieve it at the validation*

**Comment by ayshsandu** [comment] 2021-11-22 13:10
Note: we can remove the {{callback}} from the email placeholder.

**Comment by kayathiri4** [comment] 2021-11-25 06:21
Duplicate of https://github.com/wso2-enterprise/asgardeo-product/issues/8369

**Closed** 2021-11-26 17:46 UTC
Labels: improvement
