### ISSUE TITLE
Error when shutting down server

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#6364] opened 2019-09-05 12:23 UTC
```
[2019-09-05 17:48:59,507] [] ERROR {org.apache.catalina.loader.WebappClassLoaderBase} - The web application [shindig] created a ThreadLocal with key of type [org.apache.shindig.common.xml.XmlUtil$2] (value [org.apache.shindig.common.xml.XmlUtil$2@7dcd2859]) and a value of type [org.apache.xerces.jaxp.DocumentBuilderImpl] (value [org.apache.xerces.jaxp.DocumentBuilderImpl@7062131e]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```
The above error when shutting down the IS server

**Comment by JKAUSHALYA** [comment] 2019-09-16 14:59
Tested the alpha4 pack and the issue is not reproducible. Hence closing the issue.

**Closed by JKAUSHALYA** 2019-09-16 14:59 UTC
Labels: Affected/5.9.0-Alpha, Priority/High
