### ISSUE TITLE
After migrating from 5.8.0 to 5.11.0 tenant users can not login to the user-portal.

### ISSUE THREAD

**Issue by sudiptosarkar** [wso2/product-is#12836] opened 2021-12-01 14:48 UTC
**Describe the issue:**
After migrating from IS 5.8.0, which has multiple tenants and users added to it, to IS 5.11.0, tenant users are no longer able to login to the UI.

**How to reproduce:**

1.  Start a 5.8.0 pack and create several tenants.
1.   Do the migration as in docs.
1.  Now you will see the above error.
1.  Tenant users can not log in to the system

**Expected behavior:**
Tenant Users should be able to login after migration.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux
 - Database: MySQL 5.7 (`WSO2_SHARED_DB` & `WSO2_IDENTITY_DB`), H2 (`WSO2_CARBON_DB`)
 - Userstore: JDBC (MySQL 5.7)

---

### Optional Fields

**Related issues:**
There is a [similar issue](https://github.com/wso2/product-is/issues/10752) (although the same Error is not present in the logs in this case). The fix for that issue does not work in this case. There is no related (discernable) error in the logs either.

**Things to note**

When logging in with the carbon root admin, the tenants are showing up in the UI.

**Comment by sudiptosarkar** [comment] 2021-12-07 09:14
Is anyone looking into this?

**Comment by ashendes** [comment] 2022-01-18 05:03
Hi @sudiptosarkar, sorry about the delayed response.
You're trying to log into the MyAccount application, yes?
Are there any screenshots or error stacks available that you could post here for our reference?

**Comment by sudiptosarkar** [comment] 2022-01-18 08:39
> 

I was just trying to login to https://localhost:9443. Is the URL different for IS 5.11.0?

**Comment by ashendes** [comment] 2022-01-18 10:06
The base URL directs you the management console. Did the user you tried to login with have management console access permissions?

**Comment by sudiptosarkar** [comment] 2022-01-18 10:32
> The base URL directs you the management console. Did the user you tried to login with have management console access permissions?

Yes. It's the admin user for a different tenant I had setup with the admin user of the carbon.super tenant. I'm able to login with that user in the old IS version, but not after upgrade.

I can see the admin user for that tenant when logging in with carbon.super's admin user in the management console too, but I can't login with it.

Also, I just checked in /myaccount, I'm not able to login with that tenant's admin user there either.

**Comment by DMHP** [comment] 2023-08-28 08:35
Hi @sudiptosarkar 
We have tried the steps that you have provided, but could not reproduce the above case. Hence closing this issue.  If you still face this issue, please re-open the issue with the error stack you see in the console when starting up the migrated IS.

**Closed by DMHP** 2023-08-28 08:35 UTC
Labels: Priority/High, Severity/Major, bug, Component/Migration, 5.11-migration, 6.0.0-post-ga
