### ISSUE TITLE
[Social Authentication / Admin Login] - Social Federated user unable to access the Administrator access

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18316] opened 2023-12-02 09:44 UTC
**Describe the issue:**
When a social federated user logs in to the console, even with JIT provisioning the user's profile is not propagated with console. 

**How to reproduce:**
1. Login to IS Console as a tenant admin
2. Setup a google connector for the console settings login flow
3. Login to Console with a google user
4. Provide the provisioned user with administrator settings. 
5. Login again with the user and verify the access

**Actual behavior:**
1. The user only has the internal access and not the Administrator access

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/c0b30d97-ee86-4930-bc80-badceb90afa9

**Expected behavior:**
1. The user should have the administrator access

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by GoushiRam** [comment] 2023-12-02 09:53
Related to : https://github.com/wso2/product-is/issues/18283

**Comment by Thisara-Welmilla** [comment] 2023-12-05 11:11
Th root cause for this issue is, when retrieving roles list for the federated user it is only considering the IDP role mappings, the roles that assigned to the local account are not considered. Therefore, the scopes that comes with the administrator role does not get added to fed users. Hence, as required scopes for console are missing the above issue occurs.

Issue: https://github.com/wso2/product-is/issues/18313 may be due the same root cause.

**Comment by SujanSanjula96** [comment] 2023-12-19 08:04
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5303

**Closed by SujanSanjula96** 2023-12-19 08:04 UTC
Labels: Priority/Highest, Severity/Critical, bug, backend, Component/B2B
