### ISSUE TITLE
JIT Provisioning with option Prompt for username, password and consent is not working

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7889] opened 2020-03-16 07:16 UTC
**Environment**
IS 5.10.0 RC2
Embedded LDAP with H2

**Steps to Reproduce**
1. Create another IS as a secondary IDP
2. Create a user as a federated user in the secondary IDP created in step1
3. Enable JIT Provisioning with the option Prompt for username, password and consent
4. Try to login to the SP travelocity with the federated user created in secondary IDP.
5. Give a username on the UI to proceed with self-registering

**Observation**

Once the username is entered and click on proceed it will say as the tenant domain is invalid and cannot proceed to the self registration page

**Comment by janakamarasena** [comment] 2020-03-30 06:52
Reopening the issue as the master PR has been reverted with https://github.com/wso2/identity-apps/pull/634 due to a regression in the self-registration flow.

We will need to fix the place where tenantDomain param is set in the backend.
For JIT provisioning with username we use MultitenantConstants.TENANT_DOMAIN_HEADER_NAME[1] variable as the key to the tenant domain param. It resolves to "TenantDomain"[2]

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/JITProvisioningPostAuthenticationHandler.java#L527
[2] - https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/multitenancy/MultitenantConstants.java#L38

**Comment by Buddhimah** [comment] 2020-09-17 09:55
The issue cannot be reproduced with the given steps in IS-5.11 m35. Possibly fixed with https://github.com/wso2/identity-apps/pull/835

**Closed by Buddhimah** 2020-09-17 09:55 UTC
Labels: Affected/5.10.0-RC2, Priority/Highest, Severity/Blocker, bug
