### ISSUE TITLE
Same access token is returned for different grant types

### ISSUE THREAD

**Issue by npamudika** [wso2/product-is#3199] opened 2018-05-21 12:42 UTC
An application owner receives the same access token for two different token calls in two grant types.

Please consider following sample requests and responses.

**Password grant type with scope: openid**

curl -v -X POST -H "Authorization: Basic Xxxxxxxxx" -k -d "grant_type=password&username=admin&password=admin&scope=openid" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token

{"access_token":"326977ff21402f7d7c9b2770bed0f408","refresh_token":"227dc0895de100db9359cc135390e921","scope":"openid","id_token":"...","token_type":"Bearer","expires_in":1760}%                                 

**Client credentials grant with scope openid**

curl -v -X POST -H "Authorization: Basic Xxxxxxxxx" -k -d "grant_type=client_credentials&scope=openid" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token

{"access_token":"326977ff21402f7d7c9b2770bed0f408","scope":"openid","id_token":"...","token_type":"Bearer","expires_in":1753}

**Comment by dilin993** [comment] 2018-08-14 04:40
I tested with IS 5.7.0 - alpha2. The results for Password, Authorization Code and Client Credential grant types were as follows. 
**Password Grant Type**
{
    "access_token": "ed074839-7efc-3c07-a5a0-a06382eba5ac",
    "refresh_token": "faecb739-b065-305e-8233-fa2e9d94c10e",
    "scope": "openid",
    "id_token": ...,
    "token_type": "Bearer",
    "expires_in": 3212
}

**Client Credential Grant Type**
{
    "access_token": "c9deea6f-a440-35bf-8fac-e0a6043df2b1",
    "token_type": "Bearer",
    "expires_in": 2355
}

**Authorization Code Grant Type**
{
    "access_token": "ed074839-7efc-3c07-a5a0-a06382eba5ac",
    "refresh_token": "faecb739-b065-305e-8233-fa2e9d94c10e",
    "scope": "openid",
    "id_token": ...,
    "token_type": "Bearer",
    "expires_in": 3600
}

This shows acceptable behavior. Since we expect the same access token for user specific grant types it is acceptable to get the same access token for authorization code and password grant types. We get a different access token for client credential grant type. Therefore there is no issue.

**Comment by nuwandiw** [comment] 2018-08-14 04:53
Closing according to above comment

**Comment by janakamarasena** [comment] 2019-01-11 09:56
The issue still exists. I think it was not observed because the "openid" scope was used. As you can see in the above [comment](https://github.com/wso2/product-is/issues/3199#issuecomment-412752690) the client credentials grant type response doesn't have a scope in it and the other two has the openid scope. I observed the same when using the openid scope for password grant type and client credentials grant type. 

I tried using a different scope (ex: test_scope) and was able to reproduce the issue.
Tested in IS570 and IS master.

**Comment by Buddhimah** [comment] 2019-03-14 14:43
When "openid" scope is used with the client credentials grant the scope is neglected unless we make the <IdTokenAllowed>true</IdTokenAllowed> in the <GrantTypeName>client_credentials</GrantTypeName> in Identity.xml

**Comment by isharak** [comment] 2021-04-09 11:32
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Closed by isharak** 2021-04-09 11:32 UTC
Labels: Affected/5.7.0, Complexity/High, Component/OAuth, Priority/Normal, Severity/Major, bug
