### ISSUE TITLE
Inconsistent UI in Organization Administrators Page When No Admins are Present

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17682] opened 2023-11-08 12:47 UTC
**Describe the issue:**
Add a proper UI when Organization Administrators Page has not admins.
<img width="1507" alt="Screenshot 2023-11-08 at 18 08 30" src="https://github.com/wso2/product-is/assets/41188245/ad734623-7148-40cb-8337-1dc2eea1c132">

**How to reproduce:**
Delete all the Organization Administrators.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment] 2023-11-14 06:18
This is not an expected behaviour as the super admin is read only and is fixed now. Hence, couldn't reproduce this.

<img width="1315" alt="Screenshot 2023-11-14 at 10 56 49" src="https://github.com/wso2/product-is/assets/67315176/185bf768-0323-49d6-bc6d-d1bcdb9cbdc5">

In tenanted path

<img width="1320" alt="Screenshot 2023-11-14 at 11 47 42" src="https://github.com/wso2/product-is/assets/67315176/a2b1a515-3cdc-4b9d-ad66-488b83cdd372">

**Closed by savindi7** 2023-11-14 06:18 UTC
Labels: ui, Priority/Normal, Severity/Minor, bug, Affected/7.0.0-Alpha
