### ISSUE TITLE
Something went wrong on Analytic  

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17801] opened 2023-11-15 08:12 UTC
**Describe the issue:**
Something went wrong on accessing  Analytic.

<img width="1327" alt="Screenshot 2023-11-15 at 12 39 44" src="https://github.com/wso2/product-is/assets/39077751/7562e73b-dbb3-48ec-bdc9-8fd31910be7f">
Pakc: Build #4926

**How to reproduce:**
1. Login to console
2. Navigate to Analytic page

**Expected behavior:**
Should be able to access the page. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashanthamara** [comment] 2023-11-16 05:07
Closing since the issue is not reproducing
Console Version `2.6.6`
MyAccount Version `2.2.16`

https://github.com/wso2/product-is/assets/75057725/8963d4e4-cd0a-49b3-a3c4-896bd9ef08e3

**Closed by ashanthamara** 2023-11-16 05:07 UTC
Labels: Severity/Blocker, bug, Affected/7.0.0-Alpha
