### ISSUE TITLE
Console Continue Button in sign in page is different from earlier view

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14590] opened 2022-08-07 07:15 UTC
**Describe the issue:**
1. Get Pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Access console login

Did we purposely changed the continue button to a lengthy Button covering the form space from the short centered button we had previously.

Short centered button looks more good for me

![Screenshot from 2022-08-07 12-34-10](https://user-images.githubusercontent.com/31848014/183279692-1006c518-2be0-404b-aa96-4f824e3ed9a4.png)

**Comment by hwupathum** [comment] 2022-08-07 08:26
This was due to a change done in https://github.com/wso2/identity-apps/pull/3222

**Comment by ShanikaWickramasinghe** [comment] 2022-08-07 08:35
@thivi Is this change intentional. Any Idea

**Comment by thivi** [comment] 2022-08-07 08:37
@ShanikaWickramasinghe AFAIK, no. I will sort this out.

**Comment by hwupathum** [comment] 2022-08-07 08:45
Someone has added fluid class to buttons and changed the order of the 2 buttons

**Comment by brionmario** [comment] 2022-08-08 07:15
This was intentional.
cc:/ @indeewari

**Comment by indeewari** [comment] 2022-08-08 08:14
These changes were suggested for Google One Tap integration. Since Google One Tap is reverted from this release, it should not be here. 
Reverted PR [Reverted 3222](https://github.com/wso2/identity-apps/pull/3296/commits/9f40415c9c862ce4ba5806708878f98722d4694b) 

I will check the latest product-is on this matter.

**Comment by indeewari** [comment] 2022-08-08 09:28
As per the discussion had with @jeradrutnam , @thivi  we agreed to keep the fluid styles as it is. The social authenticator button sizes will be adjusted according to this.

**Comment by jeradrutnam** [comment] 2022-08-08 09:43
Yes, this is intetional

**Comment by indeewari** [comment] 2022-08-08 12:30
PR for social authenticator styles https://github.com/wso2/identity-apps/pull/3315

**Comment by brionmario** [comment] 2022-08-08 15:09
Closing this hence this is the expected behavior.

**Closed by brionmario** 2022-08-08 15:09 UTC
Labels: ui, Priority/High, Severity/Major, bug, console, Affected-6.0.0, QA-Reported, 6.0.0-rc-testing
